#!/usr/bin/env python3
"""
OpenClaw Security Guard - Report Generator
Generate security reports in various formats.
"""

import json
from datetime import datetime
from typing import Dict, List, Optional

from utils import (
    Colors, get_score_rating, load_i18n
)
from audit import run_audit
from scanner import scan_secrets


def generate_report(
    format: str = "table",
    deep: bool = False,
    include_secrets: bool = True
) -> Dict:
    """
    Generate comprehensive security report.

    Args:
        format: Output format (table, json, md)
        deep: Include deep scan
        include_secrets: Include secret scan results

    Returns:
        Dict with report data
    """
    # Run audits
    audit_results = run_audit(deep=deep)

    report = {
        "version": "1.0.0",
        "timestamp": datetime.now().isoformat(),
        "score": audit_results["score"],
        "rating": audit_results["rating"],
        "summary": audit_results["summary"],
        "audit_findings": audit_results["findings"],
    }

    # Include secrets scan
    if include_secrets:
        secrets_results = scan_secrets(deep=deep)
        report["secrets_findings"] = secrets_results["findings"]
        report["secrets_summary"] = secrets_results["summary"]

        # Adjust score based on secrets
        for finding in secrets_results["findings"]:
            severity = finding["severity"]
            if severity == "critical":
                report["score"] -= 25
            elif severity == "high":
                report["score"] -= 15
            elif severity == "medium":
                report["score"] -= 8
            elif severity == "low":
                report["score"] -= 3

        report["score"] = max(0, min(100, report["score"]))
        rating, emoji = get_score_rating(report["score"])
        report["rating"] = rating
        report["emoji"] = emoji

    return report


def format_json(report: Dict) -> str:
    """Format report as JSON."""
    return json.dumps(report, indent=2, ensure_ascii=False)


def format_markdown(report: Dict) -> str:
    """Format report as Markdown."""
    lines = []

    lines.append("# OpenClaw Security Report")
    lines.append("")
    lines.append(f"**Generated**: {report['timestamp']}")
    lines.append(f"**Score**: {report['score']}/100 {report.get('emoji', '')}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")

    summary = report["summary"]
    lines.append(f"| 🔴 Critical | {summary.get('critical', 0)} |")
    lines.append(f"| 🟠 High | {summary.get('high', 0)} |")
    lines.append(f"| 🟡 Medium | {summary.get('medium', 0)} |")
    lines.append(f"| 🟢 Low | {summary.get('low', 0)} |")
    lines.append(f"| ℹ️ Info | {summary.get('info', 0)} |")
    lines.append("")

    # Audit Findings
    lines.append("## Configuration Findings")
    lines.append("")

    for finding in report.get("audit_findings", []):
        if finding["severity"] == "info":
            continue

        severity_emoji = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🟢"
        }.get(finding["severity"], "⚪")

        lines.append(f"### {severity_emoji} {finding['title']}")
        lines.append("")
        lines.append(f"- **ID**: {finding['id']}")
        lines.append(f"- **Category**: {finding['category']}")
        lines.append(f"- **Description**: {finding['description']}")
        lines.append(f"- **Recommendation**: {finding['recommendation']}")
        lines.append("")

    # Secrets Findings
    if report.get("secrets_findings"):
        lines.append("## Secret Scan Findings")
        lines.append("")

        secrets_summary = report.get("secrets_summary", {})
        lines.append(f"- Critical: {secrets_summary.get('critical', 0)}")
        lines.append(f"- High: {secrets_summary.get('high', 0)}")
        lines.append(f"- Medium: {secrets_summary.get('medium', 0)}")
        lines.append(f"- Low: {secrets_summary.get('low', 0)}")
        lines.append("")

        for finding in report["secrets_findings"]:
            lines.append(f"- `{finding['file']}:{finding['line']}` - {finding['name']}")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by OpenClaw Security Guard*")

    return "\n".join(lines)


def print_table_report(report: Dict, i18n: Dict):
    """Print report in table format."""
    print()
    print(f"{Colors.BOLD}{Colors.CYAN}🔐 OpenClaw Security Guard v1.0.0{Colors.RESET}")
    print(f"{Colors.WHITE}{'━' * 50}{Colors.RESET}")
    print()

    # Score
    score = report["score"]
    if score >= 75:
        score_color = Colors.GREEN
    elif score >= 50:
        score_color = Colors.YELLOW
    else:
        score_color = Colors.RED

    print(f"{Colors.BOLD}📊 Security Score: {score_color}{score}/100{Colors.RESET} {report.get('emoji', '')}")
    print(f"   Generated: {report['timestamp']}")
    print()

    # Summary
    summary = report["summary"]
    print(f"{Colors.BOLD}📈 Summary{Colors.RESET}")
    print(f"   🔴 Critical: {summary.get('critical', 0)}")
    print(f"   🟠 High: {summary.get('high', 0)}")
    print(f"   🟡 Medium: {summary.get('medium', 0)}")
    print(f"   🟢 Low: {summary.get('low', 0)}")
    print(f"   ℹ️  Info: {summary.get('info', 0)}")
    print()

    # Critical/High findings
    important = [f for f in report.get("audit_findings", []) if f["severity"] in ["critical", "high"]]
    if important:
        print(f"{Colors.BOLD}⚠️ Important Findings{Colors.RESET}")
        for f in important:
            color = Colors.RED if f["severity"] == "critical" else Colors.YELLOW
            print(f"  {color}• {f['title']}{Colors.RESET}")
            print(f"    {f['recommendation']}")
            print()

    # Secrets summary
    if report.get("secrets_findings"):
        secrets_summary = report.get("secrets_summary", {})
        total = sum(secrets_summary.values())
        print(f"{Colors.BOLD}🔐 Secrets Scan: {total} finding(s){Colors.RESET}")
        print(f"   🔴 Critical: {secrets_summary.get('critical', 0)}")
        print(f"   🟠 High: {secrets_summary.get('high', 0)}")
        print()


if __name__ == "__main__":
    report = generate_report(deep=True)
    print(format_markdown(report))