#!/usr/bin/env bash
set -euo pipefail

# Writing Coach Pro — Export Report
# Generates a writing analysis summary from session history

SKILL_DIR="${HOME}/.openclaw/skills/writing-coach-pro"
DATA_DIR="${SKILL_DIR}/data"
REPORTS_DIR="${SKILL_DIR}/reports"
LEARNING_LOG="${DATA_DIR}/learning-log.json"

usage() {
    echo "Usage: export-report.sh [--format md|pdf] [--last N]"
    echo ""
    echo "Options:"
    echo "  --format md|pdf   Output format (default: md)"
    echo "  --last N          Include only the last N sessions (default: all)"
    echo ""
    echo "Generates a writing progress report from your session history."
    exit 0
}

FORMAT="md"
LAST_N=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --format)
            FORMAT="${2:-md}"
            if [[ "${FORMAT}" != "md" && "${FORMAT}" != "pdf" ]]; then
                echo "Error: Format must be 'md' or 'pdf'"
                exit 1
            fi
            shift 2
            ;;
        --last)
            LAST_N="${2:-}"
            if ! [[ "${LAST_N}" =~ ^[0-9]+$ ]]; then
                echo "Error: --last requires a positive number"
                exit 1
            fi
            shift 2
            ;;
        --help|-h)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

# Verify data exists
if [ ! -f "${LEARNING_LOG}" ]; then
    echo "Error: No learning log found at ${LEARNING_LOG}"
    echo "Have you run any writing reviews yet?"
    echo "Run setup.sh first if you haven't: bash scripts/setup.sh"
    exit 1
fi

# Check for jq
if ! command -v jq &>/dev/null; then
    echo "Error: jq is required for report generation"
    echo "Install it: brew install jq (macOS) or apt install jq (Linux)"
    exit 1
fi

mkdir -p "${REPORTS_DIR}"

TIMESTAMP=$(date +"%Y-%m-%d_%H%M%S")
REPORT_FILE="${REPORTS_DIR}/writing-report-${TIMESTAMP}.md"

echo "Generating writing report..."

# Extract stats from learning log
TOTAL_SESSIONS=$(jq '.sessions | length' "${LEARNING_LOG}")
TOTAL_SUGGESTIONS=$(jq '.suggestions | length' "${LEARNING_LOG}")

if [ "${TOTAL_SESSIONS}" -eq 0 ]; then
    echo "No sessions found in learning log. Use Writing Coach Pro a few times first."
    exit 0
fi

# Apply --last filter
if [ -n "${LAST_N}" ]; then
    SESSIONS_FILTER="(.sessions | sort_by(.date) | .[-${LAST_N}:])"
    SCOPE_NOTE="Last ${LAST_N} sessions"
else
    SESSIONS_FILTER="(.sessions)"
    SCOPE_NOTE="All ${TOTAL_SESSIONS} sessions"
fi

TOTAL_WORDS=$(jq "${SESSIONS_FILTER} | map(.wordCount) | add // 0" "${LEARNING_LOG}")
AVG_ISSUES=$(jq "${SESSIONS_FILTER} | map(.issuesFound) | if length > 0 then (add / length | . * 10 | round / 10) else 0 end" "${LEARNING_LOG}")
ACCEPTED=$(jq '.suggestions | map(select(.accepted == true)) | length' "${LEARNING_LOG}")
REJECTED=$(jq '.suggestions | map(select(.accepted == false)) | length' "${LEARNING_LOG}")

if [ "${TOTAL_SUGGESTIONS}" -gt 0 ]; then
    ACCEPT_RATE=$(echo "scale=1; ${ACCEPTED} * 100 / ${TOTAL_SUGGESTIONS}" | bc 2>/dev/null || echo "N/A")
else
    ACCEPT_RATE="N/A"
fi

# Build the report
cat > "${REPORT_FILE}" << EOF
# Writing Coach Pro — Progress Report

**Generated:** $(date +"%B %d, %Y at %I:%M %p")
**Scope:** ${SCOPE_NOTE}

---

## Summary

- **Total sessions:** ${TOTAL_SESSIONS}
- **Total words reviewed:** ${TOTAL_WORDS}
- **Average issues per session:** ${AVG_ISSUES}
- **Suggestions accepted:** ${ACCEPTED}
- **Suggestions rejected:** ${REJECTED}
- **Acceptance rate:** ${ACCEPT_RATE}%

## Session Breakdown

| Date | Mode | Words | Issues Found | Issues Accepted | Readability |
|------|------|-------|-------------|----------------|-------------|
EOF

# Add session rows
jq -r "${SESSIONS_FILTER} | sort_by(.date) | reverse | .[] | \"| \(.date) | \(.mode) | \(.wordCount) | \(.issuesFound) | \(.issuesAccepted) | \(.readabilityScore) |\"" "${LEARNING_LOG}" >> "${REPORT_FILE}"

cat >> "${REPORT_FILE}" << 'EOF'

## Top Suggestion Categories

EOF

# Count suggestions by type
jq -r '.suggestions | group_by(.type) | map({type: .[0].type, count: length}) | sort_by(-.count) | .[] | "- **\(.type)**: \(.count) suggestions"' "${LEARNING_LOG}" >> "${REPORT_FILE}"

cat >> "${REPORT_FILE}" << 'EOF'

---

*Report generated by Writing Coach Pro for NormieClaw*
EOF

echo "Report saved to: ${REPORT_FILE}"

# Convert to PDF if requested
if [ "${FORMAT}" = "pdf" ]; then
    PDF_FILE="${REPORTS_DIR}/writing-report-${TIMESTAMP}.pdf"
    if command -v pandoc &>/dev/null; then
        pandoc "${REPORT_FILE}" -o "${PDF_FILE}" --pdf-engine=wkhtmltopdf 2>/dev/null || \
        pandoc "${REPORT_FILE}" -o "${PDF_FILE}" 2>/dev/null || {
            echo "PDF conversion failed. Markdown report is still available at: ${REPORT_FILE}"
            exit 0
        }
        echo "PDF saved to: ${PDF_FILE}"
    else
        echo "pandoc not found — PDF conversion skipped."
        echo "Install pandoc for PDF export: brew install pandoc (macOS) or apt install pandoc (Linux)"
        echo "Markdown report is available at: ${REPORT_FILE}"
    fi
fi
