STALE_THRESHOLD_SECONDS = 10
INDICATOR_WINDOW_SIZE = 50
DEFAULT_INTELLIGENCE_TTL = 1800
EXPIRED_PLACEHOLDER = "[EXPIRED] Analyst report is outdated."

NAMESPACE_MARKET_STATE = "market_state"
NAMESPACE_INDICATORS = "indicators"
NAMESPACE_INTELLIGENCE = "intelligence"
NAMESPACE_RISK_AUDIT = "risk_audit"

VALID_NAMESPACES = frozenset({
    NAMESPACE_MARKET_STATE,
    NAMESPACE_INDICATORS,
    NAMESPACE_INTELLIGENCE,
    NAMESPACE_RISK_AUDIT,
})

WRITE_PERMISSIONS: dict[str, str] = {
    NAMESPACE_MARKET_STATE: "Default_Orchestrator",
    NAMESPACE_INDICATORS: "Default_Orchestrator",
    NAMESPACE_INTELLIGENCE: "Analyst_Officer",
    NAMESPACE_RISK_AUDIT: "Guard_Agent",
}

RISK_AUDIT_KEY = "global_state"
