#!/usr/bin/env python3
"""
peer_config.py — Interactive peer agent configuration generator.

Run this script to generate a peer-config.md file with all the
necessary connection details for two OpenClaw agents to communicate
via Tailscale VPN.

Usage:
    python3 scripts/peer_config.py

Prompts for:
    - Your machine name / agent name
    - Your Tailscale IP
    - Your OpenClaw gateway URL and port
    - Your gateway token
    - Your peer's details (name, Tailscale IP, gateway URL, token)
    - Your agentId
"""

import os
import sys
import json


def get_tailscale_ip():
    """Try to read the local Tailscale IP automatically."""
    if os.path.exists("/usr/local/bin/tailscale") or os.path.exists("/usr/bin/tailscale"):
        import subprocess
        try:
            result = subprocess.run(
                ["tailscale", "ip", "-4"],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.returncode == 0:
                return result.stdout.strip()
        except Exception:
            pass
    # Try Windows path
    try:
        import subprocess
        result = subprocess.run(
            ["tailscale", "ip", "-4"],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return None


def get_gateway_info():
    """Try to read OpenClaw gateway config for URL/port."""
    config_paths = [
        os.path.expanduser("~/.openclaw/config.json"),
        os.path.expanduser("~/.openclaw/gateway/config.json"),
        os.path.join(os.getcwd(), ".openclaw", "config.json"),
    ]
    for path in config_paths:
        if os.path.exists(path):
            try:
                with open(path) as f:
                    config = json.load(f)
                gateway = config.get("gateway", {})
                bind = gateway.get("bind", "localhost")
                port = gateway.get("port", 8080)
                if bind == "0.0.0.0" or bind == "localhost":
                    # Can't determine external IP automatically — return placeholder
                    return bind, port, None
                return bind, port, f"http://{bind}:{port}"
            except Exception:
                pass
    return "0.0.0.0", 8080, None


def main():
    print("=" * 50)
    print("  OpenClaw Peer Agent — Config Generator")
    print("=" * 50)
    print()
    print("This script generates a peer-agent/peer-config.md file")
    print("with connection details for your peer agent setup.")
    print()

    # Auto-detect what we can
    auto_tailscale_ip = get_tailscale_ip()
    auto_bind, auto_port, auto_gateway_url = get_gateway_info()

    # Gather your info
    print("--- YOUR DETAILS ---")
    my_name = input("Your name / agent name: ").strip()
    my_machine = input("Your machine name: ").strip()

    if auto_tailscale_ip:
        use_auto = input(f"Your Tailscale IP [{auto_tailscale_ip}]: ").strip()
        my_tailscale_ip = use_auto or auto_tailscale_ip
    else:
        my_tailscale_ip = input("Your Tailscale IP (run 'tailscale ip -4'): ").strip()

    my_gateway_port = input(f"Gateway port [{auto_port}]: ").strip()
    my_gateway_port = int(my_gateway_port) if my_gateway_port else auto_port

    my_gateway_bind = input(f"Gateway bind address [{auto_bind}]: ").strip()
    my_gateway_bind = my_gateway_bind or auto_bind

    if auto_gateway_url:
        use_url = input(f"Full gateway URL (leave blank for auto-detect) [{auto_gateway_url}]: ").strip()
        my_gateway_url = use_url or auto_gateway_url
    else:
        my_gateway_url = input(f"Full gateway URL (e.g. http://100.x.x.x:{my_gateway_port}): ").strip()
        if not my_gateway_url:
            my_gateway_url = f"http://{my_tailscale_ip}:{my_gateway_port}"

    my_token = input("Your gateway token (see openclaw gateway status): ").strip()
    my_agent_id = input("Your agentId (leave blank to auto-detect from config): ").strip()

    print()
    print("--- YOUR PEER'S DETAILS ---")
    peer_name = input("Peer's name / agent name: ").strip()
    peer_machine = input("Peer's machine name: ").strip()
    peer_tailscale_ip = input("Peer's Tailscale IP (they run 'tailscale ip -4'): ").strip()
    peer_gateway_url = input(f"Peer's gateway URL (e.g. http://100.x.x.x:{my_gateway_port}): ").strip()
    peer_token = input("Peer's gateway token: ").strip()
    peer_agent_id = input("Peer's agentId: ").strip()

    print()
    print("Generating peer-config.md...")

    # Build the config content
    config_content = f"""# Peer Agent Configuration
# Generated by peer_config.py
# Update these values when network details change.

---

## My Details

**Name:** {my_name}
**Machine:** {my_machine}
**Agent ID:** {my_agent_id or '<not set>'}
**Tailscale IP:** {my_tailscale_ip}
**Gateway URL:** {my_gateway_url}
**Gateway Token:** {my_token}

---

## My Peer

**Name:** {peer_name}
**Machine:** {peer_machine}
**Agent ID:** {peer_agent_id or '<not set>'}
**Tailscale IP:** {peer_tailscale_ip}
**Gateway URL:** {peer_gateway_url}
**Gateway Token:** {peer_token}

---

## Quick Reference

### Test my gateway is reachable from peer machine:
```bash
curl http://{my_tailscale_ip}:{my_gateway_port}/health --connect-timeout 5
```

### Test peer's gateway from my machine:
```bash
curl http://{peer_tailscale_ip}:{my_gateway_port}/health --connect-timeout 5
```

### Send a message to peer:
```json
sessions_send(
  sessionKey="<session-key>",
  agentId="{peer_agent_id or '<peers-agent-id>'}",
  message="Hello from {my_name}!",
  gatewayUrl="{peer_gateway_url}",
  gatewayToken="{peer_token}"
)
```

---

## Shared Collaboration Log

Create this file alongside peer-config.md:
`peer-agent/shared-log.md`

Format:
```markdown
# Peer Collaboration Log

## YYYY-MM-DD
**[Project Name]**
- [Insight] → [Topic] [description]
- [Review Request] → [Task] [outcome]
- [Milestone] 🎉 → [what happened]
```
"""

    # Write the file
    os.makedirs("peer-agent", exist_ok=True)
    output_path = os.path.join("peer-agent", "peer-config.md")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(config_content)

    print(f"✅ Written to: {output_path}")
    print()
    print("Next steps:")
    print(f"1. Review {output_path}")
    print("2. Share the 'My Details' section with your peer")
    print("3. Ask your peer to share their details so you can fill in the 'My Peer' section")
    print("4. Test connectivity: curl http://<peer-ip>:8080/health")
    print("5. Start collaborating!")


if __name__ == "__main__":
    main()
