#!/usr/bin/env python3
"""
Phase 3.5: Pack Tasks — bundle each candidate into a self-contained task file.

Reads candidates.json + crawled snippets → writes data/v9/tasks/{content_slug}.json.
Each task file contains everything needed for an isolated content-generation agent:
  - candidate metadata (topic, angle, reason)
  - writer prompt
  - source material (crawled snippets)
  - API config (endpoint, topicSlug)

The content_slug is generated by the LLM during candidate selection and serves
as both the task filename and the final content slug POSTed to the API.

Usage:
  python3 -m pipeline.pack_tasks
  python3 -m pipeline.pack_tasks --dry-run
"""

import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

from .config import (
    CANDIDATES_FILE, SNIPPETS_DIR, V9_DIR, DIRECTIVES_FILE,
    ensure_dirs, load_json, get_api_url, get_api_key,
)
from .eir_config import SKILL_DIR

TASKS_DIR = V9_DIR / "tasks"
WRITER_PROMPT_PATH = SKILL_DIR / "references" / "writer-prompt-eir.md"
WRITER_PROMPT_STANDALONE_PATH = SKILL_DIR / "references" / "writer-prompt-standalone.md"
MIN_CONTENT_LEN = 500


def _report_misses(misses):
    """Report missed topic slugs to POST /oc/curation/miss.
    
    Args:
        misses: list of {slug, reason} dicts, or list of slug strings (legacy)
    """
    if not misses:
        return
    # Normalize to [{slug, reason}]
    normalized = []
    for m in misses:
        if isinstance(m, str):
            normalized.append({"slug": m, "reason": "no usable content"})
        else:
            normalized.append({"slug": m.get("slug", ""), "reason": m.get("reason", "no usable content")})
    normalized = [m for m in normalized if m["slug"]]
    if not normalized:
        return
    try:
        import urllib.request
        api_url = get_api_url()
        api_key = get_api_key()
        payload = json.dumps({
            "slugs": [m["slug"] for m in normalized],
            "details": normalized,
        }).encode()
        req = urllib.request.Request(
            "%s/api/oc/curation/miss" % api_url,
            data=payload,
            headers={
                "Authorization": "Bearer %s" % api_key,
                "Content-Type": "application/json",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
        slugs_str = ", ".join(m["slug"] for m in normalized)
        print("  📡 Reported %d missed topics: %s" % (len(normalized), slugs_str))
    except Exception as e:
        print("  ⚠️ Failed to report misses: %s" % e)


def extract_article_body(text, max_len=4000):
    """Extract the article body from crawled content, skipping nav/boilerplate.

    Strategy:
    - Skip image links, markdown link lists, short fragments, nav-like lines.
    - Find the first substantial paragraph (40+ chars of real text).
    - Return up to max_len chars of the article body.
    """
    if not text:
        return ""

    lines = text.split("\n")
    body_start = 0

    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            continue
        # Skip image-only lines: ![...](...)  or plain URLs
        if stripped.startswith("![") or stripped.startswith("http"):
            continue
        # Skip markdown link lists: * [...], - [...], * [![
        if re.match(r'^[\*\-]\s*\[', stripped):
            continue
        # Skip lines that are mostly links/markdown formatting
        plain = re.sub(r'\[([^\]]*?)\]\([^)]*\)', r'\1', stripped)
        plain = re.sub(r'[!\[\]()#*_`>\-]', '', plain).strip()
        if len(plain) < 40:
            continue
        # Found a substantial line — this is likely the article start
        body_start = i
        break

    # Include the heading before if present
    if body_start > 0 and lines[body_start - 1].strip().startswith("#"):
        body_start -= 1

    body = "\n".join(lines[body_start:])
    return body[:max_len]


def snippet_path_for_url(url):
    url_hash = hashlib.md5(url.encode()).hexdigest()[:12]
    return SNIPPETS_DIR / ("%s.json" % url_hash)


def _get_title_for_url(candidate, url):
    titles = candidate.get("source_titles", [])
    urls = candidate.get("source_urls", [])
    if isinstance(titles, dict):
        return titles.get(url, "")
    if isinstance(titles, list) and isinstance(urls, list):
        try:
            idx = urls.index(url)
            return titles[idx] if idx < len(titles) else ""
        except ValueError:
            return ""
    return ""


def load_candidate_sources(candidate):
    """Load crawled content for a candidate's source URLs."""
    from .crawl import is_error_page
    sources = []
    # Get source_dates from candidate (written by crawl.py freshness gate)
    source_dates = candidate.get("source_dates", {})
    for url in candidate.get("crawled_sources", candidate.get("source_urls", [])):
        path = snippet_path_for_url(url)
        if not path.exists():
            continue
        snippet = load_json(path)
        content = snippet.get("content", "")
        if len(content) < MIN_CONTENT_LEN or is_error_page(content):
            continue
        # Get publishedDate: snippet first, then fallback to source_dates
        pub_date = snippet.get("publishedDate")
        if not pub_date and url in source_dates:
            pub_date = source_dates[url].get("publishedDate")
        sources.append({
            "url": url,
            "title": _get_title_for_url(candidate, url),
            "name": urlparse(url).netloc.replace("www.", ""),
            "content": content[:6000],
            "publishedDate": pub_date,
        })
    return sources


def load_writer_prompt():
    """Load writer prompt based on mode (eir or standalone)."""
    settings = load_json(SKILL_DIR / "config" / "settings.json", {})
    mode = settings.get("mode", "standalone")
    if mode == "eir" and WRITER_PROMPT_PATH.exists():
        return WRITER_PROMPT_PATH.read_text()
    if WRITER_PROMPT_STANDALONE_PATH.exists():
        return WRITER_PROMPT_STANDALONE_PATH.read_text()
    if WRITER_PROMPT_PATH.exists():
        return WRITER_PROMPT_PATH.read_text()
    return "Generate a structured content summary from the sources below."


def _get_user_md_path():
    """Resolve USER.md path from settings or default workspace."""
    settings = load_json(SKILL_DIR / "config" / "settings.json", {})
    path = settings.get("user_md_path", "")
    if path:
        return Path(path)
    # Default: OPENCLAW_WORKSPACE env or ~/.openclaw/workspace-content
    ws = os.environ.get("OPENCLAW_WORKSPACE", str(Path.home() / ".openclaw" / "workspace-content"))
    return Path(ws) / "USER.md"


def _load_reader_context():
    """Load reader context from USER.md.
    
    USER.md contains the user's profile, interests, and current focus.
    Used to personalize l2.context and eir_take.
    """
    p = _get_user_md_path()
    if p.exists():
        return p.read_text().strip()
    return ""
    return "Generate content for Eir. Output JSON only."


def sanitize_slug(slug):
    """Sanitize a content slug for use as filename."""
    slug = slug.lower().strip()
    slug = re.sub(r'[^a-z0-9-]', '-', slug)
    slug = re.sub(r'-+', '-', slug).strip('-')
    return slug[:80]  # reasonable max length


def pack_single_task(candidate, sources, writer_prompt, directives_map):
    """Build a self-contained task bundle for one candidate."""
    topic_slug = candidate["matched_topic_slug"]
    content_slug = candidate.get("content_slug", "")
    if not content_slug:
        # Fallback: use topic_slug + angle hash
        angle = candidate.get("suggested_angle", "")
        angle_hash = hashlib.md5(angle.encode()).hexdigest()[:6]
        content_slug = "%s_%s" % (topic_slug, angle_hash)

    content_slug = sanitize_slug(content_slug)
    directive = directives_map.get(topic_slug, {})

    # Build source material text for the prompt
    source_text = ""
    source_meta = []
    for i, s in enumerate(sources):
        source_text += "\n--- Source %d: %s (%s) ---\n%s\n" % (
            i + 1, s["title"], s["name"], extract_article_body(s["content"], 4000))
        source_meta.append({
            "url": s["url"],
            "title": s["title"],
            "name": s["name"],
            "publishedDate": s.get("publishedDate"),
        })

    task = {
        "task_version": 1,
        "content_slug": content_slug,
        "topic_slug": topic_slug,
        "topic_name": directive.get("label") or directive.get("topic", topic_slug),
        "suggested_angle": candidate.get("suggested_angle", ""),
        "reason": candidate.get("reason", ""),
        "priority": candidate.get("priority", "medium"),
        "reader_context": _load_reader_context(),
        "source_meta": source_meta,
        "source_text": source_text,
        "writer_prompt": writer_prompt,
        "has_fresh_source": candidate.get("has_fresh_source", True),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    return task


def _tokenize_for_dedup(text):
    """Extract meaningful tokens from a slug or title for dedup.
    Handles both English (space/hyphen split) and CJK (character bigrams)."""
    import re
    text = text.lower()
    tokens = set()
    
    # English tokens: split on non-alnum, keep 3+ chars
    en_tokens = set(re.findall(r'[a-z]{3,}', text))
    stop = {'the','and','for','with','from','new','that','this','are','was',
            'has','have','been','will','can','not','but','its','more',
            'than','into','how','what','why','who','about','after',
            'big','tech','race','boom','wave','shift','impact','risk',
            'reality','check','debate','crisis'}
    tokens |= en_tokens - stop
    
    # CJK character bigrams
    cjk_chars = re.findall(r'[\u4e00-\u9fff]', text)
    for i in range(len(cjk_chars) - 1):
        tokens.add(cjk_chars[i] + cjk_chars[i+1])
    
    return tokens


def _event_similarity(slug_a, title_a, slug_b, title_b):
    """Compute event similarity. Uses token overlap count (not Jaccard)
    because events are identified by shared key entities, not overall similarity."""
    # Combine slug + title tokens for each side
    a_tokens = _tokenize_for_dedup(slug_a) | _tokenize_for_dedup(title_a)
    b_tokens = _tokenize_for_dedup(slug_b) | _tokenize_for_dedup(title_b)
    
    if not a_tokens or not b_tokens:
        return 0.0
    
    shared = a_tokens & b_tokens
    # Score: shared count normalized by the SMALLER set (asymmetric — 
    # if a short slug matches most of a longer one, it's a dup)
    min_size = min(len(a_tokens), len(b_tokens))
    return len(shared) / min_size if min_size > 0 else 0.0


def _find_duplicate_event(content_slug, title, topic, recent_events):
    """Check if this candidate covers an event already in recent_events.
    Returns the slug of the duplicate, or None.
    Only compares within same topic (different topics = different events)."""
    THRESHOLD = 0.35  # tuned: catches 'ai-drug-discovery-*' variants
    for ev in recent_events:
        if ev.get("topic") != topic:
            continue
        sim = _event_similarity(content_slug, title,
                                ev.get("slug", ""), ev.get("title", ""))
        if sim >= THRESHOLD:
            return ev.get("slug", "?")
    return None


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Pack Tasks")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    ensure_dirs()
    TASKS_DIR.mkdir(parents=True, exist_ok=True)

    # Clean old task files before packing new ones
    for old_task in TASKS_DIR.glob("*.json"):
        if old_task.stem != "manifest":
            old_task.unlink()

    print("📦 Pack Tasks")

    # Load candidates
    candidates = load_json(CANDIDATES_FILE, {})
    candidate_list = candidates.get("candidates", [])
    if not candidate_list:
        print("  ❌ No candidates in candidates.json")
        sys.exit(1)

    # Load directives
    directives_data = load_json(DIRECTIVES_FILE, {})
    all_directives = directives_data.get("directives", []) + directives_data.get("tracked", [])
    directives_map = {d["slug"]: d for d in all_directives}

    # Load writer prompt once
    writer_prompt = load_writer_prompt()
    print("  Writer prompt: %d chars" % len(writer_prompt))

    # Load used URLs and posted content slugs for dedup
    try:
        from .run_state import get_all_used_urls, get_posted_content_slugs, get_recent_posted_events
        used_urls = get_all_used_urls()
        posted_slugs = get_posted_content_slugs()
        recent_events = get_recent_posted_events(days=3)
    except Exception:
        used_urls = set()
        posted_slugs = set()
        recent_events = []

    # Build event fingerprints for semantic dedup
    packed_events = []  # track within this run too

    # Pack each candidate into a task
    packed = 0
    skipped = 0
    for c in candidate_list:
        topic = c.get("matched_topic_slug", "")
        content_slug = c.get("content_slug", "")

        # Skip if no content
        if not c.get("has_content", False):
            print("  ⏭️  %s: no crawled content" % topic)
            skipped += 1
            continue

        # Skip if freshness gate failed (strict check, default to False)
        # has_fresh_source is set by crawl.py, must be True to proceed
        if c.get("has_fresh_source") is not True:
            print("  ⏭️  %s: no fresh source (freshness gate failed or missing)" % topic)
            skipped += 1
            continue

        # Skip if this exact content_slug was already posted
        if content_slug and sanitize_slug(content_slug) in posted_slugs:
            print("  ⏭️  %s: content_slug already posted" % content_slug)
            skipped += 1
            continue

        # Event-level semantic dedup: skip if same event already covered recently
        candidate_title = c.get("title", "") or c.get("suggested_angle", "")
        dup_of = _find_duplicate_event(content_slug, candidate_title, topic,
                                       recent_events + packed_events)
        if dup_of:
            print("  ⏭️  %s: duplicate event (similar to '%s')" % (content_slug, dup_of))
            skipped += 1
            continue

        # Remove individual used URLs (not skip entire candidate)
        source_urls = c.get("source_urls", [])
        fresh_urls = [u for u in source_urls if u not in used_urls]
        removed_count = len(source_urls) - len(fresh_urls)
        if removed_count > 0:
            print("  🔗 %s: removed %d used URL(s), %d remaining" % (content_slug, removed_count, len(fresh_urls)))
            c["source_urls"] = fresh_urls
        if source_urls and not fresh_urls:
            print("  ⏭️  %s: all source URLs already used" % topic)
            skipped += 1
            continue

        # Load sources
        sources = load_candidate_sources(c)
        if not sources:
            print("  ⏭️  %s: no usable sources after crawl" % topic)
            skipped += 1
            continue

        # Build task
        task = pack_single_task(c, sources, writer_prompt, directives_map)
        slug = task["content_slug"]

        if args.dry_run:
            print("  [dry-run] Would pack: %s.json (%d sources, %d chars)" % (
                slug, len(sources), len(task["source_text"])))
            packed += 1
            packed_events.append({"slug": content_slug, "title": candidate_title, "topic": topic})
            continue

        # Write task file
        task_path = TASKS_DIR / ("%s.json" % slug)
        task_path.write_text(json.dumps(task, indent=2, ensure_ascii=False))
        print("  ✅ %s.json (%d sources, angle: %s)" % (
            slug, len(sources), task["suggested_angle"][:50]))
        packed += 1
        packed_events.append({"slug": content_slug, "title": candidate_title, "topic": topic})

    print("\n📦 Packed %d tasks, skipped %d" % (packed, skipped))

    # Report missed topics to API (lowers their future priority)
    if not args.dry_run:
        misses = []
        seen_slugs = set()
        # 1. Topics skipped at candidate_selector stage (search results too low quality)
        candidates_data = load_json(CANDIDATES_FILE, {})
        for st in candidates_data.get("skipped_topics", []):
            slug = st.get("slug", "")
            if slug and slug not in seen_slugs:
                misses.append({"slug": slug, "reason": st.get("reason", "skipped at selection")})
                seen_slugs.add(slug)
        # 2. Candidates that failed crawl/freshness
        for c in candidate_list:
            topic = c.get("matched_topic_slug", "")
            if not topic:
                continue
            if not c.get("has_content", False) or c.get("has_fresh_source") is not True:
                if topic not in seen_slugs:
                    reason = "no fresh source" if c.get("has_content") else "crawl failed"
                    misses.append({"slug": topic, "reason": reason})
                    seen_slugs.add(topic)
        # 3. Topics skipped by event dedup
        # (already printed during pack, not critical to report)
        if misses:
            _report_misses(misses)

    if packed > 0 and not args.dry_run:
        # Write manifest
        manifest = {
            "packed_at": datetime.now(timezone.utc).isoformat(),
            "task_count": packed,
            "skipped": skipped,
            "tasks": sorted([f.stem for f in TASKS_DIR.glob("*.json") if f.stem != "manifest"]),
        }
        (TASKS_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2))
        print("  Manifest: %s" % (TASKS_DIR / "manifest.json"))


if __name__ == "__main__":
    main()
