#!/bin/bash

# Video Summary - Configuration Update Script
# Called by OpenClaw during conversational setup
# Usage: config-update.sh <step> <value>

set -e

CONFIG_DIR="$HOME/.config/video-summary"
CONFIG_FILE="$CONFIG_DIR/config.sh"
STATE_FILE="$CONFIG_DIR/setup-state.json"

# Ensure directory exists
mkdir -p "$CONFIG_DIR"

# Initialize state file if missing
if [[ ! -f "$STATE_FILE" ]]; then
    cat > "$STATE_FILE" << 'EOF'
{
  "status": "pending",
  "current_step": "api_provider",
  "steps": {
    "api_provider": { "status": "pending" },
    "api_key": { "status": "pending" },
    "whisper_model": { "status": "pending" },
    "cookies": { "status": "pending" }
  },
  "answers": {}
}
EOF
fi

# Parse arguments
STEP="$1"
VALUE="$2"

if [[ -z "$STEP" || -z "$VALUE" ]]; then
    echo '{"error": "Usage: config-update.sh <step> <value>"}'
    exit 1
fi

# Read current state
STATE=$(cat "$STATE_FILE")

# Update state based on step
case "$STEP" in
    api_provider)
        # Map provider name to base URL
        case "$VALUE" in
            openai|OpenAI|1)
                PROVIDER="openai"
                BASE_URL="https://api.openai.com/v1"
                ;;
            zhipu|智谱|GLM|2)
                PROVIDER="zhipu"
                BASE_URL="https://open.bigmodel.cn/api/paas/v4"
                ;;
            deepseek|DeepSeek|3)
                PROVIDER="deepseek"
                BASE_URL="https://api.deepseek.com/v1"
                ;;
            moonshot|Moonshot|Kimi|4)
                PROVIDER="moonshot"
                BASE_URL="https://api.moonshot.cn/v1"
                ;;
            *)
                PROVIDER="custom"
                BASE_URL="$VALUE"
                ;;
        esac
        
        STATE=$(echo "$STATE" | jq --arg provider "$PROVIDER" --arg base "$BASE_URL" '
            .steps.api_provider.status = "done" |
            .answers.provider = $provider |
            .answers.base_url = $base |
            .current_step = "api_key"
        ')
        ;;
        
    api_key)
        STATE=$(echo "$STATE" | jq --arg key "$VALUE" '
            .steps.api_key.status = "done" |
            .answers.api_key = $key |
            .current_step = "whisper_model"
        ')
        ;;
        
    whisper_model)
        # Map model choice to name
        case "$VALUE" in
            1|tiny) MODEL="tiny" ;;
            2|base) MODEL="base" ;;
            3|small) MODEL="small" ;;
            4|medium) MODEL="medium" ;;
            5|large) MODEL="large" ;;
            *) MODEL="base" ;;
        esac
        
        STATE=$(echo "$STATE" | jq --arg model "$MODEL" '
            .steps.whisper_model.status = "done" |
            .answers.whisper_model = $model |
            .current_step = "cookies"
        ')
        ;;
        
    cookies_skip)
        STATE=$(echo "$STATE" | jq '.steps.cookies.status = "done" | .current_step = "complete"')
        ;;
        
    cookies)
        # VALUE should be JSON with platform:cookie pairs
        STATE=$(echo "$STATE" | jq --argjson cookies "$VALUE" '
            .steps.cookies.status = "done" |
            .answers.cookies = $cookies |
            .current_step = "complete"
        ')
        ;;
        
    *)
        echo '{"error": "Unknown step"}'
        exit 1
        ;;
esac

# Check if all steps done
ALL_DONE=$(echo "$STATE" | jq '[.steps | .[] | .status] | all(. == "done")')
if [[ "$ALL_DONE" == "true" ]]; then
    STATE=$(echo "$STATE" | jq '.status = "complete"')
    
    # Generate config file
    PROVIDER=$(echo "$STATE" | jq -r '.answers.provider')
    API_KEY=$(echo "$STATE" | jq -r '.answers.api_key')
    BASE_URL=$(echo "$STATE" | jq -r '.answers.base_url')
    WHISPER_MODEL=$(echo "$STATE" | jq -r '.answers.whisper_model')
    
    cat > "$CONFIG_FILE" << EOF
# Video Summary Configuration
# Generated by conversational setup
# Generated at: $(date)

export OPENAI_API_KEY="${API_KEY}"
export OPENAI_API_BASE="${BASE_URL}"
export VIDEO_SUMMARY_WHISPER_MODEL="${WHISPER_MODEL}"
EOF
    
    # Add cookies if configured
    COOKIES=$(echo "$STATE" | jq -r '.answers.cookies // empty')
    if [[ -n "$COOKIES" && "$COOKIES" != "null" ]]; then
        XHS=$(echo "$COOKIES" | jq -r '.xiaohongshu // empty')
        DOUYIN=$(echo "$COOKIES" | jq -r '.douyin // empty')
        BILI=$(echo "$COOKIES" | jq -r '.bilibili // empty')
        
        [[ -n "$XHS" ]] && echo "export VIDEO_SUMMARY_XHS_COOKIE=\"${XHS}\"" >> "$CONFIG_FILE"
        [[ -n "$DOUYIN" ]] && echo "export VIDEO_SUMMARY_DOUYIN_COOKIE=\"${DOUYIN}\"" >> "$CONFIG_FILE"
        [[ -n "$BILI" ]] && echo "export VIDEO_SUMMARY_BILI_COOKIE=\"${BILI}\"" >> "$CONFIG_FILE"
    fi
    
    chmod 600 "$CONFIG_FILE"
fi

# Save state
echo "$STATE" > "$STATE_FILE"

# Output current state for OpenClaw
echo "$STATE"
