#!/bin/bash
#
# 通用项目初始化脚本
# 用法: bash scripts/init-project.sh <项目目录> <应用名称>

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

info() { echo -e "${BLUE}ℹ️${NC}  $1"; }
success() { echo -e "${GREEN}✅${NC} $1"; }
warn() { echo -e "${YELLOW}⚠️${NC}  $1"; }
error() { echo -e "${RED}❌${NC} $1"; }
step() { echo -e "${CYAN}▶ $1${NC}"; }

# 参数检查
PROJECT_DIR="${1:-}"
APP_NAME="${2:-}"

if [ -z "$PROJECT_DIR" ] || [ -z "$APP_NAME" ]; then
    echo "用法: bash scripts/init-project.sh <项目目录> <应用名称>"
    echo "示例: bash scripts/init-project.sh ./MyApp UserManager"
    exit 1
fi

# 创建目录结构
step "创建项目目录结构..."

mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

mkdir -p docs/{prd,api}
mkdir -p src/{models,services,pages,viewmodels,common/{utils,constants,components}}
mkdir -p test/{unittest,e2e}
mkdir -p scripts
mkdir -p templates
mkdir -p references
mkdir -p versions

# 创建PROJECT.md
cat > PROJECT.md << EOF
# $APP_NAME 项目配置

## 项目概述
- **应用名称**: $APP_NAME
- **创建日期**: $(date +%Y-%m-%d)
- **目标平台**: HarmonyOS 6.0+

## 功能模块
- [ ] 核心功能模块
- [ ] 用户管理模块
- [ ] 数据管理模块

## 检查点
- [ ] 数据模型定义
- [ ] 核心服务实现
- [ ] DevEco编译通过
- [ ] 单元测试覆盖>60%
- [ ] 规范检查通过>90分

## 进度追踪
| 阶段 | 状态 | 完成度 | 预计/实际耗时 |
|-----|------|--------|--------------|
| 产品设计 | ⏳ | 0% | -/- |
| 规划 | ⏳ | 0% | -/- |
| 生成 | ⏳ | 0% | -/- |
| 实现 | ⏳ | 0% | -/- |
| 验证 | ⏳ | 0% | -/- |
| 集成 | ⏳ | 0% | -/- |

## 风险标记
| 风险项 | 等级 | 应对策略 |
|-------|------|---------|
| 技术复杂度 | 🟡 中 | 分阶段实现 |
| 外部依赖 | 🟡 中 | Mock数据备用 |
EOF

# 创建version.json
cat > version.json << EOF
{
  "name": "$APP_NAME",
  "version": "1.0.0",
  "stage": "development",
  "createdAt": "$(date -Iseconds)",
  "lastUpdated": "$(date -Iseconds)",
  "milestones": []
}
EOF

# 创建.gitignore
cat > .gitignore << 'EOF'
# IDE
.idea/
*.iml

# Build
build/
*.hap

# Dependencies
node_modules/

# Generated
.generated/

# Local
.local/
*.local.json

# Backup
*.bak
.backups/

# OS
.DS_Store
Thumbs.db
EOF

# 复制工作流脚本
step "复制工作流脚本..."

# 获取脚本源目录
SCRIPT_SOURCE="${SCRIPT_SOURCE:-$(dirname "$0")}"

if [ -f "$SCRIPT_SOURCE/prd.sh" ]; then
    cp "$SCRIPT_SOURCE/prd.sh" scripts/
    cp "$SCRIPT_SOURCE/generate.sh" scripts/
    cp "$SCRIPT_SOURCE/tdd.sh" scripts/
    cp "$SCRIPT_SOURCE/fill-logic.sh" scripts/
    cp "$SCRIPT_SOURCE/update-logic.sh" scripts/
    cp "$SCRIPT_SOURCE/debug.sh" scripts/
    cp "$SCRIPT_SOURCE/build-check.sh" scripts/
    cp "$SCRIPT_SOURCE/lint.sh" scripts/
    cp "$SCRIPT_SOURCE/test.sh" scripts/
    cp "$SCRIPT_SOURCE/demo-prep.sh" scripts/
    cp "$SCRIPT_SOURCE/update.sh" scripts/
    cp "$SCRIPT_SOURCE/daily-check.sh" scripts/
fi

chmod +x scripts/*.sh 2>/dev/null || true

# 复制模板
step "复制代码模板..."

TEMPLATE_SOURCE="${TEMPLATE_SOURCE:-$SCRIPT_SOURCE/../templates}"

if [ -d "$TEMPLATE_SOURCE" ]; then
    cp "$TEMPLATE_SOURCE/model.hbs.txt" templates/ 2>/dev/null || true
    cp "$TEMPLATE_SOURCE/service.hbs.txt" templates/ 2>/dev/null || true
    cp "$TEMPLATE_SOURCE/page.hbs.txt" templates/ 2>/dev/null || true
    cp "$TEMPLATE_SOURCE/viewmodel.hbs.txt" templates/ 2>/dev/null || true
    cp "$TEMPLATE_SOURCE/test.hbs.txt" templates/ 2>/dev/null || true
    cp "$TEMPLATE_SOURCE/prd.md.hbs.txt" templates/ 2>/dev/null || true
    cp "$TEMPLATE_SOURCE/user-story.md.hbs.txt" templates/ 2>/dev/null || true
    cp "$TEMPLATE_SOURCE/feature-priority.md.hbs.txt" templates/ 2>/dev/null || true
fi

# 创建README
cat > README.md << EOF
# $APP_NAME

基于 AppDev Skill 创建的 HarmonyOS 应用项目。

## 快速开始

\`\`\`bash
# 1. 产品功能设计
bash scripts/prd.sh init '核心功能'

# 2. 生成代码
bash scripts/generate.sh model User
bash scripts/generate.sh service UserService

# 3. TDD开发
bash scripts/tdd.sh start UserService getUserInfo
bash scripts/tdd.sh run

# 4. 编译验证
bash scripts/build-check.sh

# 5. 版本归档
./scripts/update.sh minor "完成核心功能"
\`\`\`

## 项目结构

\`\`\`
src/
├── models/          # 数据模型
├── services/        # 业务服务
├── pages/           # 页面组件
├── viewmodels/      # 状态管理
└── common/          # 公共工具
\`\`\`

## 文档

- [开发流程](./docs/workflow.md)
- [PRD模板](./docs/prd/)
- [API文档](./docs/api/)

## 版本

当前版本: 1.0.0

---
Generated by AppDev Skill v1.0
EOF

echo ""
success "项目初始化完成！"
echo ""
echo "项目目录: $(pwd)"
echo ""
echo "下一步:"
echo "  1. cd $PROJECT_DIR"
echo "  2. bash scripts/prd.sh init '核心功能'"
echo "  3. bash scripts/generate.sh model User"
echo ""
