#!/usr/bin/env python3
"""
analyze.py — 扫描 memory/*.md，提取用户发言，分析个人风格，生成 persona/$user.json
用法:
  python3 analyze.py --user <昵称> --memory-dir <memory目录> [--persona-dir <输出目录>] [--min-messages 10]
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path


def find_memory_files(memory_dir: str) -> list[Path]:
    """找到所有 memory/YYYY-MM-DD.md 文件，按日期排序"""
    p = Path(memory_dir)
    if not p.exists():
        return []
    files = sorted(p.glob("*.md"))
    return files


def extract_user_messages(memory_files: list[Path], exclude_patterns: list[str] = None) -> list[str]:
    """
    从 memory 文件中提取用户发言。
    策略 B：提取所有非 AI/bot 发言，过滤掉明显的指令性内容。
    识别用户发言的标记：
      - 行以 "**用户:**" / "**User:**" / "> " / "eliqiao:" / "[用户]" 等开头
      - 或 markdown 引用块 (> ...)
      - 或对话记录格式 "发言者: 内容"
    """
    exclude_patterns = exclude_patterns or []
    messages = []

    # 匹配常见对话格式中用户发言
    user_prefixes = re.compile(
        r'^(?:\*\*)?(?:用户|User|Human|eliqiao|我|sender)(?:\*\*)?[：:]\s*(.+)',
        re.IGNORECASE
    )
    # 引用块（> 内容）也视作用户发言候选
    quote_block = re.compile(r'^>\s+(.+)')

    # 跳过明显的指令/任务行
    skip_patterns = re.compile(
        r'(已完成|待办|TODO|DONE|\[x\]|\[ \]|进度|下一步|Next Step|任务|cron job|创建了|更新了|安装了|重启|配置)',
        re.IGNORECASE
    )

    for f in memory_files:
        try:
            content = f.read_text(encoding='utf-8')
        except Exception:
            continue

        for line in content.splitlines():
            line = line.strip()
            if not line:
                continue

            # 匹配用户发言格式
            m = user_prefixes.match(line) or quote_block.match(line)
            if m:
                msg = m.group(1).strip()
                # 过滤太短（<5字）的内容
                if len(msg) < 5:
                    continue
                # 过滤指令性内容
                if skip_patterns.search(msg):
                    continue
                messages.append(msg)

    return messages


def build_analysis_prompt(messages: list[str], user_name: str) -> str:
    """构建给 LLM 的分析提示"""
    sample = "\n".join(f"{i+1}. {m}" for i, m in enumerate(messages[:60]))
    return f"""你是一位语言风格分析专家。以下是用户「{user_name}」的历史发言样本（共 {len(messages)} 条），请仔细分析其说话风格。

【发言样本】
{sample}

请严格按以下 JSON 格式输出分析结果，不要输出任何额外文字：

{{
  "tone": {{
    "overall": "一句话描述整体语气",
    "formality_level": 0.0到1.0之间的数字（0=极随意，1=极正式）,
    "enthusiasm_level": 0.0到1.0之间的数字（0=冷淡，1=热情）,
    "description": "详细描述语气特征"
  }},
  "sentence_structure": {{
    "avg_length": 估计平均句子字数（整数）,
    "preference": "描述句式偏好（短句/长句/混合等）",
    "question_ratio": 0.0到1.0（提问句占比）,
    "uses_ellipsis": true或false（是否常用省略号）
  }},
  "emoji_usage": {{
    "frequency": "低/中/高",
    "favorites": ["最常用的emoji列表，最多8个"],
    "style": "描述emoji使用风格"
  }},
  "professionalism": {{
    "tech_density": 0.0到1.0（技术词汇密度）,
    "jargon_level": "描述专业术语使用程度",
    "domain_keywords": ["高频领域词汇，最多10个"]
  }},
  "humor": {{
    "level": 0.0到1.0（幽默程度）,
    "style": "描述幽默风格（冷幽默/调侃/无等）"
  }},
  "interactivity": {{
    "asking_questions": true或false（是否爱提问）,
    "follow_up_ratio": 0.0到1.0（追问比例）,
    "directive_style": true或false（是否习惯发指令/要求）
  }},
  "formatting": {{
    "loves_tables": true或false,
    "uses_lists": "不用/偶尔/频繁",
    "markdown_heavy": true或false,
    "uses_code_blocks": true或false
  }},
  "catchphrases": ["口头禅列表，最多10个，直接引用原文"],
  "common_phrases": ["常用短语列表，最多10个"],
  "topic_preferences": ["经常谈论的话题或领域，最多8个"],
  "communication_patterns": ["总结2-4个最显著的沟通模式特征"],
  "system_prompt_fragment": "写一段50-100字的系统提示，用第二人称描述这个人的风格，供AI模仿时使用"
}}"""


def call_llm_for_analysis(prompt: str) -> dict:
    """
    调用 LLM 进行风格分析。
    注意：此函数被 SKILL.md 中的 Agent 调用，实际 LLM 调用由 Agent 完成。
    此处输出 prompt 供 Agent 读取并调用模型。
    """
    # 将 prompt 写入临时文件，由 Agent (skill) 读取并调用 LLM
    prompt_file = Path("/tmp/persona_analysis_prompt.txt")
    prompt_file.write_text(prompt, encoding='utf-8')
    print(f"PROMPT_FILE:{prompt_file}")
    print("NEEDS_LLM_CALL:true")
    return {}


def save_persona(user_name: str, analysis: dict, messages: list[str],
                 memory_files: list[Path], persona_dir: str, template_path: str):
    """将分析结果写入 persona/$user.json"""
    persona_dir_p = Path(persona_dir)
    persona_dir_p.mkdir(parents=True, exist_ok=True)

    # 读取模板
    template = {}
    if Path(template_path).exists():
        with open(template_path, 'r', encoding='utf-8') as f:
            template = json.load(f)

    now = datetime.utcnow().isoformat() + "Z"
    date_range = []
    if memory_files:
        dates = [f.stem for f in memory_files if re.match(r'\d{4}-\d{2}-\d{2}', f.stem)]
        if dates:
            date_range = [min(dates), max(dates)]

    persona = {
        "_comment": f"Auto-generated by persona-creator. Do not edit manually.",
        "user_id": user_name,
        "display_name": user_name,
        "created_at": now,
        "updated_at": now,
        "version": 1,
        "statistics": {
            "analyzed_messages": len(messages),
            "date_range": date_range,
            "memory_files_scanned": [str(f.name) for f in memory_files]
        },
        "persona": analysis
    }

    output_path = persona_dir_p / f"{user_name}.json"
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(persona, f, ensure_ascii=False, indent=2)

    return str(output_path)


def main():
    parser = argparse.ArgumentParser(description='分析用户说话风格，生成数字人档案')
    parser.add_argument('--user', required=True, help='用户名/昵称（将作为 JSON 文件名）')
    parser.add_argument('--memory-dir', default='memory', help='memory 目录路径（默认: memory）')
    parser.add_argument('--persona-dir', default='persona', help='输出 persona 目录（默认: persona）')
    parser.add_argument('--min-messages', type=int, default=10, help='最少需要的消息数（默认: 10）')
    parser.add_argument('--template', default=None, help='模板 JSON 路径（默认自动查找 persona/yourself.json）')
    parser.add_argument('--dry-run', action='store_true', help='仅提取消息，不调用 LLM')
    args = parser.parse_args()

    # 查找 memory 文件
    memory_files = find_memory_files(args.memory_dir)
    if not memory_files:
        print(f"ERROR: 在 {args.memory_dir} 中未找到任何 .md 文件", file=sys.stderr)
        sys.exit(1)

    print(f"📂 找到 {len(memory_files)} 个 memory 文件")

    # 提取用户发言
    messages = extract_user_messages(memory_files)
    print(f"💬 提取到 {len(messages)} 条用户发言")

    if len(messages) < args.min_messages:
        print(f"ERROR: 发言数量不足（{len(messages)} < {args.min_messages}），无法生成可靠的风格分析", file=sys.stderr)
        print(f"HINT: 请确保 memory 目录中有足够的对话记录，或降低 --min-messages 阈值", file=sys.stderr)
        sys.exit(2)

    if args.dry_run:
        print(f"\n--- DRY RUN: 提取的发言样本 ---")
        for i, m in enumerate(messages[:20]):
            print(f"  {i+1}. {m}")
        print(f"--- 共 {len(messages)} 条 ---")
        sys.exit(0)

    # 查找模板
    script_dir = Path(__file__).parent.parent
    template_path = args.template or str(script_dir / "persona" / "yourself.json")

    # 生成分析 prompt（由 Agent 负责实际 LLM 调用）
    prompt = build_analysis_prompt(messages, args.user)

    # 输出 prompt 和元数据供 Agent 使用
    print(f"\nANALYSIS_PROMPT_START")
    print(prompt)
    print(f"ANALYSIS_PROMPT_END")
    print(f"\nMETA:user={args.user}")
    print(f"META:messages_count={len(messages)}")
    print(f"META:persona_dir={args.persona_dir}")
    print(f"META:template={template_path}")

    # 将元数据存入临时文件供后续 save 步骤使用
    meta = {
        "user": args.user,
        "messages": messages,
        "memory_files": [str(f) for f in memory_files],
        "persona_dir": args.persona_dir,
        "template_path": template_path
    }
    meta_path = Path("/tmp/persona_meta.json")
    meta_path.write_text(json.dumps(meta, ensure_ascii=False), encoding='utf-8')
    print(f"\nMETA_FILE:{meta_path}")


if __name__ == '__main__':
    main()
