#!/bin/bash
echo "=== claws-dream Diagnostic ==="
WORKSPACE="${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace}"
echo "Workspace: $WORKSPACE"
echo ""
echo "--- Memory Directory ---"
ls -la "$WORKSPACE/memory/" 2>/dev/null || echo "No memory dir"
echo ""
echo "--- index.json ---"
cat "$WORKSPACE/memory/index.json" 2>/dev/null || echo "Missing or empty"
echo ""
echo "--- Last 5 Dream Entries ---"
tail -30 "$WORKSPACE/memory/dream-log.md" 2>/dev/null | grep "^## " | head -5
echo ""
echo "--- Lock File ---"
ls -la "$WORKSPACE/logs/claws-dream.lock" 2>/dev/null || echo "No lock file"
echo ""
echo "--- MEMORY.md Size ---"
wc -l "$WORKSPACE/MEMORY.md" 2>/dev/null || echo "Missing"
echo ""
echo "--- Backup Files ---"
ls -la "$WORKSPACE/MEMORY.md.bak."* 2>/dev/null || echo "No backups"