#!/usr/bin/env python3
"""
bib_generator.py — Auto-generate BibTeX (.bib) from downloaded paper metadata
Feature 3: Auto Bibliography Management
No manual citation work — every downloaded paper becomes a ready BibTeX entry.
Usage:
  python3 bib_generator.py [metadata_json] [output_bib]
  python3 bib_generator.py papers_pdf/metadata.json references.bib
"""

import sys
import os
import json
import re
import time
import requests

SS_BASE = "https://api.semanticscholar.org/graph/v1"


def slugify_key(title, authors, year):
    """Generate a clean BibTeX key: FirstAuthorLastNameYearKeyword"""
    first_author = ""
    if authors:
        name = authors[0].strip()
        parts = name.split()
        first_author = parts[-1] if parts else "Unknown"
        # Remove non-alpha chars
        first_author = re.sub(r'[^a-zA-Z]', '', first_author)

    # First meaningful word from title (skip short words)
    stopwords = {'a','an','the','of','in','on','for','with','and','or','is','are','to','via','by','from'}
    title_words = [w for w in re.sub(r'[^a-zA-Z0-9 ]','',title).split()
                   if w.lower() not in stopwords and len(w) > 2]
    keyword = title_words[0].capitalize() if title_words else "Paper"

    return f"{first_author}{year or 'XXXX'}{keyword}"


def fetch_doi(arxiv_id):
    """Try to get DOI from Semantic Scholar."""
    clean_id = arxiv_id.split("v")[0].replace("_", "/")
    url = f"{SS_BASE}/paper/arXiv:{clean_id}?fields=externalIds,venue,publicationVenue"
    try:
        time.sleep(1.0)
        r = requests.get(url, timeout=10)
        if r.status_code == 200:
            data = r.json()
            ext = data.get("externalIds", {}) or {}
            doi = ext.get("DOI", "")
            venue = ""
            pv = data.get("publicationVenue") or {}
            venue = pv.get("name", "") or data.get("venue", "")
            return doi, venue
    except Exception:
        pass
    return "", ""


def make_bibtex_entry(paper, fetch_extra=False):
    """Convert paper metadata dict to a BibTeX entry string."""
    title   = paper.get("title", "Unknown Title")
    authors = paper.get("authors", [])
    year_raw = paper.get("published", "")[:4]
    year    = year_raw if year_raw.isdigit() else "2024"
    arxiv_id = paper.get("arxiv_id", "").replace("_", "/").split("v")[0]
    abstract = paper.get("abstract", "")[:300]

    key = slugify_key(title, authors, year)

    # Format author list: Last, First and Last, First
    author_str = " and ".join(authors[:8]) if authors else "Unknown"

    doi, venue = "", "arXiv"
    if fetch_extra and arxiv_id:
        doi, venue = fetch_doi(arxiv_id)

    url = f"https://arxiv.org/abs/{arxiv_id}" if arxiv_id else ""

    lines = [
        f"@article{{{key},",
        f"  title   = {{{{{title}}}}},",
        f"  author  = {{{author_str}}},",
        f"  year    = {{{year}}},",
        f"  journal = {{{venue or 'arXiv preprint'}}},",
    ]
    if arxiv_id:
        lines.append(f"  note    = {{arXiv:{arxiv_id}}},")
    if doi:
        lines.append(f"  doi     = {{{doi}}},")
    if url:
        lines.append(f"  url     = {{{url}}},")
    if abstract:
        lines.append(f"  abstract = {{{abstract}...}},")
    lines.append("}")

    return key, "\n".join(lines)


def generate_bib(metadata_path="papers_pdf/metadata.json",
                 output_bib="references.bib",
                 fetch_extra=True):
    if not os.path.exists(metadata_path):
        print(f"❌ {metadata_path} not found. Run arxiv_downloader.py first.")
        sys.exit(1)

    with open(metadata_path) as f:
        papers = json.load(f)

    print(f"📚 Generating BibTeX for {len(papers)} papers...")

    entries = []
    key_map = {}   # key → title (for collision detection)
    cite_map = []  # list of {original_title, bibtex_key} for reference

    for i, paper in enumerate(papers):
        title = paper.get("title", "")
        try:
            key, entry = make_bibtex_entry(paper, fetch_extra=(fetch_extra and i < 20))
        except Exception as e:
            print(f"  ⚠️  [{i+1}] Error for '{title[:40]}': {e}")
            continue

        # Handle duplicate keys
        if key in key_map:
            key = f"{key}_{i}"

        key_map[key] = title
        entries.append(entry)
        cite_map.append({"bibtex_key": key, "title": title})
        print(f"  ✅ [{i+1}/{len(papers)}] \\cite{{{key}}}  ←  {title[:55]}...")

    # Write .bib file
    with open(output_bib, "w") as f:
        f.write("% Auto-generated by EVE Research Supervisor\n")
        f.write(f"% Papers: {len(entries)}\n\n")
        f.write("\n\n".join(entries))
        f.write("\n")

    # Write cite_map.json for paper_writer.py to use
    with open("cite_map.json", "w") as f:
        json.dump(cite_map, f, indent=2)

    # Write human-readable cite cheatsheet
    with open("cite_cheatsheet.md", "w") as f:
        f.write("# Citation Cheatsheet\n\n")
        f.write("Use these keys in your LaTeX paper:\n\n")
        for item in cite_map:
            f.write(f"- `\\cite{{{item['bibtex_key']}}}` → {item['title'][:70]}\n")

    print(f"\n✅ BibTeX generated!")
    print(f"   {output_bib}         — include in LaTeX: \\bibliography{{references}}")
    print(f"   cite_map.json        — used by paper_writer.py automatically")
    print(f"   cite_cheatsheet.md   — your quick reference")
    print(f"\n   In your .tex file add:")
    print(f"   \\bibliographystyle{{plain}}")
    print(f"   \\bibliography{{{output_bib.replace('.bib','')}}}")
    return cite_map


if __name__ == "__main__":
    metadata = sys.argv[1] if len(sys.argv) > 1 else "papers_pdf/metadata.json"
    output   = sys.argv[2] if len(sys.argv) > 2 else "references.bib"
    generate_bib(metadata, output)
