/**
 * Context Composer - Assemble final context window
 */

import { truncateToTokens } from '../utils/tokenCounter.js';

export function composeContext({ goal, parsed, local, kb, web, maxTokens }) {
  const sections = [];
  
  // Header
  sections.push(`## 🎯 Context for: "${goal}"\n`);
  sections.push(`*Generated by SCG | Intents: ${parsed.intents.join(', ') || 'general'} | Langs: ${parsed.languages.join(', ') || 'any'}*\n`);
  
  // Security warning if high security
  if (parsed.securityLevel === 'high') {
    sections.push(`⚠️ **SECURITY-CRITICAL**: Exercise extra caution. Validate all inputs, follow OWASP guidelines.\n`);
  }

  // 📚 Knowledge Base (curated patterns)
  const pitfalls = kb.filter(i => i.category === 'common-pitfalls');
  const patterns = kb.filter(i => i.category === 'recommended-patterns');
  
  if (pitfalls.length) {
    sections.push(`### ⚠️ Common Pitfalls`);
    for (const p of pitfalls.slice(0, 4)) {
      sections.push(`\n**${p.title}**`);
      sections.push('```' + (p.languages?.includes('python') ? 'python' : 'javascript') + '\n' + p.content + '\n```');
    }
    sections.push('');
  }
  
  if (patterns.length) {
    sections.push(`### ✅ Recommended Patterns`);
    for (const p of patterns.slice(0, 4)) {
      sections.push(`\n**${p.title}**`);
      sections.push('```' + (p.languages?.includes('python') ? 'python' : 'javascript') + '\n' + p.content + '\n```');
    }
    sections.push('');
  }

  // 📂 Local Results
  if (local.length) {
    sections.push(`### 📂 From Your Project`);
    for (const l of local.slice(0, 3)) {
      const relevance = l.relevance === 'high' ? '🟢' : l.relevance === 'medium' ? '🟡' : '🔴';
      sections.push(`\n${relevance} **${l.source}:${l.line}**`);
      sections.push('```');
      sections.push(l.content.slice(0, 500));
      sections.push('```');
    }
    sections.push('');
  }

  // 🌐 Web Results (StackOverflow)
  if (web.length) {
    sections.push(`### 🌐 StackOverflow Solutions`);
    for (const w of web.slice(0, 3)) {
      const votes = w.score > 50 ? '🔥' : w.score > 10 ? '⭐' : '📗';
      const answered = w.isAnswered ? '✅' : '❓';
      sections.push(`\n${votes} ${answered} [${w.title}](${w.url})`);
      sections.push(`   Score: ${w.score} | Answers: ${w.answerCount} | Tags: ${w.tags?.slice(0, 3).join(', ')}`);
    }
    sections.push('');
  }

  // Footer
  sections.push(`\n---\n*Context truncated to ~${maxTokens} tokens*`);

  let context = sections.join('\n');
  
  // Truncate if needed
  const estimatedTokens = Math.ceil(context.length / 4);
  if (estimatedTokens > maxTokens) {
    context = truncateToTokens(context, maxTokens);
  }
  
  return context;
}