#!/usr/bin/env python3
"""
ingest.py — 摄取新资料到 Wiki

用法:
    python3 ingest.py /path/to/wiki raw/articles/article.md
"""

import sys
import json
import re
from pathlib import Path
from datetime import datetime


def extract_frontmatter(content: str) -> dict:
    """Extract frontmatter from markdown."""
    if not content.startswith("---"):
        return {}

    end = content.find("---", 3)
    if end == -1:
        return {}

    fm_text = content[4:end].strip()
    fm = {}
    for line in fm_text.split("\n"):
        if ":" in line:
            key, value = line.split(":", 1)
            fm[key.strip()] = value.strip()
    return fm


def extract_title(content: str) -> str:
    """Extract title from frontmatter or first heading."""
    fm = extract_frontmatter(content)
    if "title" in fm:
        return fm["title"].strip('"\'')

    match = re.search(r"^# (.+)$", content, re.MULTILINE)
    if match:
        return match.group(1).strip()

    return "Untitled"


def slugify(text: str) -> str:
    """Convert text to kebab-case slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s\u4e00-\u9fff-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    return text[:50]


def identify_concepts(content: str) -> list:
    """Identify potential concepts from content."""
    concepts = []

    headings = re.findall(r"^## (.+)$", content, re.MULTILINE)
    for h in headings[:10]:
        if len(h) < 50 and h not in ["Key takeaways", "Core claims", "Notable quotes"]:
            concepts.append(h.strip())

    return concepts[:5]


def create_summary_page(raw_content: str, slug: str, wiki_root: Path):
    """Create wiki/summaries/<slug>.md"""
    today = datetime.now().strftime("%Y-%m-%d")
    title = extract_title(raw_content)

    summary = f"""---
title: summaries/{slug}
type: summary
source_type: article
date: {today}
ingested: {today}
tags: []
---

# {title}

**Source**: <Unknown> · {today}

## Key takeaways
- <最关键洞察 1>
- <最关键洞察 2>
- <最关键洞察 3>

## Core claims
<主要论点的 2-4 句话摘要。>

## Notable quotes
> "<精确引用>"

## Concepts introduced / referenced
<概念和实体。>

---
*Generated by synapse-wiki ingest*
"""

    summaries_dir = wiki_root / "wiki" / "summaries"
    summaries_dir.mkdir(parents=True, exist_ok=True)

    summary_path = summaries_dir / f"{slug}.md"
    summary_path.write_text(summary, encoding="utf-8")

    return summary_path


def create_concept_page(concept: str, wiki_root: Path, sources: list):
    """Create wiki/concepts/<concept>.md if not exists."""
    today = datetime.now().strftime("%Y-%m-%d")
    slug = slugify(concept)

    concept_path = wiki_root / "wiki" / "concepts" / f"{slug}.md"

    if concept_path.exists():
        return None

    concept_content = f"""---
title: {concept}
type: concept
created: {today}
updated: {today}
sources: {sources}
tags: []
---

# {concept}

<一句话定义或核心思想。>

## What it is
<清晰解释。>

## How it works
<机制、过程或结构。>

## Key properties / tradeoffs
<重要特征。>

## Relationship to other concepts
<相关概念的 wikilinks。>

## Open questions
<Wiki 尚未解决的问题。>

---
*Generated by synapse-wiki ingest*
"""

    concept_path.write_text(concept_content, encoding="utf-8")
    return concept_path


def create_entity_page(entity: str, wiki_root: Path, sources: list):
    """Create wiki/entities/<entity>.md if not exists."""
    today = datetime.now().strftime("%Y-%m-%d")
    slug = slugify(entity)

    entity_path = wiki_root / "wiki" / "entities" / f"{slug}.md"

    if entity_path.exists():
        return None

    entity_content = f"""---
title: {entity}
type: entity
entity_type: tool
created: {today}
updated: {today}
sources: {sources}
tags: []
---

# {entity}

<一句话描述。>

## Key contributions / features
<主要贡献或特性。>

## Related concepts
<相关概念。>

---
*Generated by synapse-wiki ingest*
"""

    entity_path.write_text(entity_content, encoding="utf-8")
    return entity_path


def update_index(wiki_root: Path):
    """Update wiki/index.md with all pages."""
    today = datetime.now().strftime("%Y-%m-%d")

    concepts = []
    entities = []
    summaries = []

    for md_file in (wiki_root / "wiki" / "concepts").glob("*.md"):
        title = extract_title(md_file.read_text(encoding="utf-8"))
        concepts.append(f"- [[{title}]]")

    for md_file in (wiki_root / "wiki" / "entities").glob("*.md"):
        title = extract_title(md_file.read_text(encoding="utf-8"))
        entities.append(f"- [[{title}]]")

    for md_file in (wiki_root / "wiki" / "summaries").glob("*.md"):
        title = extract_title(md_file.read_text(encoding="utf-8"))
        summaries.append(f"- [[{title}]]")

    index_content = f"""# Index — Wiki Knowledge Base

> Master catalog of all wiki pages. Updated after every ingest.
> Last updated: {today}

## Concepts（概念）

{chr(10).join(concepts) if concepts else "*(none yet)*"}

## Entities（实体）

{chr(10).join(entities) if entities else "*(none yet)*"}

## Summaries（资料摘要）

{chr(10).join(summaries) if summaries else "*(none yet)*"}

## Outputs（探索产出）

*(none yet)*
"""

    (wiki_root / "wiki" / "index.md").write_text(index_content, encoding="utf-8")


def append_to_log(wiki_root: Path, op: str, description: str):
    """Append entry to log.md."""
    today = datetime.now().strftime("%Y-%m-%d")
    entry = f"## [{today}] {op} | {description}\n"

    log_path = wiki_root / "log.md"
    if log_path.exists():
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(entry)
    else:
        log_path.write_text(f"# Log\n\n{entry}", encoding="utf-8")


def ingest_source(wiki_root: Path, source_path: Path):
    """Ingest a source file into the wiki."""
    wiki_root = wiki_root.resolve()
    source_path = source_path.resolve()

    if not source_path.exists():
        print(f"Error: Source file not found: {source_path}")
        return False

    print(f"Ingesting: {source_path}")
    print("-" * 60)

    content = source_path.read_text(encoding="utf-8")
    slug = source_path.stem
    sources_list = [str(source_path.relative_to(wiki_root))]

    step1_path = create_summary_page(content, slug, wiki_root)
    print(f"  ✓ Created: {step1_path.relative_to(wiki_root)}")

    concepts = identify_concepts(content)
    created_concepts = []
    for concept in concepts:
        result = create_concept_page(concept, wiki_root, sources_list)
        if result:
            created_concepts.append(concept)
            print(f"  ✓ Created concept: {concept}")

    update_index(wiki_root)
    print(f"  ✓ Updated: wiki/index.md")

    append_to_log(wiki_root, "ingest", f"{slug} — {extract_title(content)}")
    print(f"  ✓ Appended to: log.md")

    print("-" * 60)
    print(f"Ingest complete: {len(concepts)} concepts identified")

    return True


def main():
    if len(sys.argv) < 3:
        print("Usage: python3 ingest.py /path/to/wiki <source-file>")
        sys.exit(1)

    wiki_root = Path(sys.argv[1])
    source_path = Path(sys.argv[2])

    success = ingest_source(wiki_root, source_path)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
