#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Tika Digital Key vehicle query script.
Tika 数字钥匙车辆查询脚本。
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Optional


BASE_URL = "https://openapi.nokeeu.com"
API_URL = f"{BASE_URL}/iot/v1/condition"
CACHE_FILE = Path.home() / ".skill_carkey_cache.json"
TOKEN_SEPARATOR = "####"
SUPPORTED_LANGS = ("zh", "en")
ENV_API_KEY = "TIKA_API_KEY"
ENV_VEHICLE_TOKEN = "TIKA_VEHICLE_TOKEN"
ENV_ACCESS_TOKEN = "TIKA_ACCESS_TOKEN"

MESSAGES = {
    "zh": {
        "auth_available": "认证信息可用",
        "api_key": "API Key",
        "address": "地址",
        "air_conditioner_state": "空调状态",
        "auth_format_error": "API Key 格式错误，请使用 App 生成的完整 API Key",
        "cache_file": "缓存文件",
        "cache_not_found": "未找到认证信息",
        "cache_path": "缓存文件路径",
        "cache_read_failed": "读取缓存文件失败",
        "cache_saved": "认证信息已写入缓存",
        "cache_write_failed": "写入缓存文件失败",
        "cache_invalid": "缓存文件格式错误",
        "cache_cleared": "认证缓存已删除",
        "cache_already_missing": "认证缓存不存在，无需删除",
        "check_auth_conflict": "--check-auth 不能与查询参数或 token 参数一起使用",
        "clear_auth_conflict": "--clear-auth 不能与查询参数或 token 参数一起使用",
        "condition_only": "仅查询车况信息（车门、车锁、车窗、空调等）",
        "data_incomplete": "认证信息不完整，请提供完整的 API Key",
        "detail_help": "输出完整详细状态，而不是摘要简报",
        "door_state": "车门状态",
        "driver_side_temp": "左侧温度",
        "front_left_door": "左前门",
        "front_left_lock": "左前锁",
        "front_left_window": "左前窗",
        "front_right_door": "右前门",
        "front_right_lock": "右前锁",
        "front_right_window": "右前窗",
        "gear": "档位",
        "http_error": "HTTP 错误",
        "json_parse_failed": "响应 JSON 解析失败",
        "lang_help": "输出语言：zh 或 en",
        "left_rear_door": "左后门",
        "left_rear_lock": "左后锁",
        "left_rear_window": "左后窗",
        "location_info": "位置信息",
        "lock_state": "车锁状态",
        "lock_summary": "车锁",
        "network_error": "网络错误",
        "no_data": "暂无数据",
        "position_only": "仅查询车辆位置信息",
        "position_update_time": "更新时间",
        "power": "电源",
        "query_failed": "请求失败",
        "query_success": "查询成功",
        "summary_title": "车辆状态简报",
        "summary_hint": "提示",
        "summary_car_started": "你的车子已经启动啦，等待你的驾驶。",
        "summary_car_secure": "你的车子稳稳停着呢，门窗都关好了，不用担心。",
        "summary_car_unlocked": "车辆目前是解锁状态，离车前记得确认车锁。",
        "summary_door_open": "有车门还没完全关闭，建议先检查一下。",
        "summary_trunk_open": "后备箱还开着，记得确认一下是否需要关闭。",
        "summary_window_open": "有车窗没有完全关闭，建议及时确认。",
        "summary_attention": "车辆状态正常，但仍建议离车前再确认一次门锁和车况。",
        "summary_all_locked": "全车上锁",
        "summary_not_fully_locked": "存在未上锁车门",
        "summary_all_closed": "全部关闭",
        "summary_not_fully_closed": "存在未关闭部件",
        "rear_trunk": "后备箱",
        "right_rear_door": "右后门",
        "right_rear_lock": "右后锁",
        "right_rear_window": "右后窗",
        "env_available": "已从环境变量读取认证信息",
        "env_api_key": "环境变量 TIKA_API_KEY",
        "save_apikey_only_conflict": "使用 --save-token-only 时必须同时提供 --apikey",
        "save_apikey_only_help": "仅保存 API Key 到缓存，不发起车辆查询",
        "skylight": "天窗",
        "sn": "SN",
        "status_unknown": "未知",
        "status_unknown_value": "未知({value})",
        "apikey_help": "直接提供 App 生成的完整 API Key；提供后会写入缓存文件",
        "token_status_check_help": "仅检查当前缓存中的认证信息是否存在且格式完整",
        "trunk": "后备箱",
        "vehicle_status": "车辆状态",
        "vin": "VIN",
        "window_state": "车窗状态",
        "coordinates": "经纬度",
        "json_help": "输出 JSON 数据",
        "api_error": "API 错误",
        "token_expired_hint": "提示: access_token 可能已过期，请重新获取认证信息",
    },
    "en": {
        "auth_available": "Authentication info is available",
        "api_key": "API Key",
        "address": "Address",
        "air_conditioner_state": "A/C State",
        "auth_format_error": "Invalid API key format. Use the full API key generated by the App",
        "cache_file": "Cache file",
        "cache_not_found": "Authentication info not found",
        "cache_path": "Cache file path",
        "cache_read_failed": "Failed to read cache file",
        "cache_saved": "Authentication info saved to cache",
        "cache_write_failed": "Failed to write cache file",
        "cache_invalid": "Invalid cache file format",
        "cache_cleared": "Authentication cache deleted",
        "cache_already_missing": "Authentication cache does not exist",
        "check_auth_conflict": "--check-auth cannot be used with query or token arguments",
        "clear_auth_conflict": "--clear-auth cannot be used with query or token arguments",
        "condition_only": "Query vehicle condition only",
        "data_incomplete": "Authentication info is incomplete. Provide the full API key",
        "detail_help": "Show full detailed status instead of summary view",
        "door_state": "Door State",
        "driver_side_temp": "Left Temperature",
        "front_left_door": "Front Left Door",
        "front_left_lock": "Front Left Lock",
        "front_left_window": "Front Left Window",
        "front_right_door": "Front Right Door",
        "front_right_lock": "Front Right Lock",
        "front_right_window": "Front Right Window",
        "gear": "Gear",
        "http_error": "HTTP error",
        "json_parse_failed": "Failed to parse response JSON",
        "lang_help": "Output language: zh or en",
        "left_rear_door": "Rear Left Door",
        "left_rear_lock": "Rear Left Lock",
        "left_rear_window": "Rear Left Window",
        "location_info": "Location",
        "lock_state": "Lock State",
        "lock_summary": "Lock",
        "network_error": "Network error",
        "no_data": "No data",
        "position_only": "Query vehicle position only",
        "position_update_time": "Updated At",
        "power": "Power",
        "query_failed": "Request failed",
        "query_success": "Query succeeded",
        "summary_title": "Vehicle Status Summary",
        "summary_hint": "Note",
        "summary_car_started": "Your car is started and ready for your drive.",
        "summary_car_secure": "Your car is parked safely. Doors and windows are closed.",
        "summary_car_unlocked": "The vehicle is currently unlocked. Check the locks before leaving.",
        "summary_door_open": "At least one door is not fully closed. Please check it.",
        "summary_trunk_open": "The trunk is still open. Please make sure that is intentional.",
        "summary_window_open": "At least one window is not fully closed. Please verify it.",
        "summary_attention": "The vehicle looks normal, but it is still worth rechecking the locks and status before leaving.",
        "summary_all_locked": "All locked",
        "summary_not_fully_locked": "Not fully locked",
        "summary_all_closed": "All closed",
        "summary_not_fully_closed": "Something is open",
        "rear_trunk": "Trunk",
        "right_rear_door": "Rear Right Door",
        "right_rear_lock": "Rear Right Lock",
        "right_rear_window": "Rear Right Window",
        "env_available": "Authentication info loaded from environment variables",
        "env_api_key": "Environment variable TIKA_API_KEY",
        "save_apikey_only_conflict": "--save-token-only requires --apikey",
        "save_apikey_only_help": "Save API key to cache only, do not query the vehicle",
        "skylight": "Sunroof",
        "sn": "SN",
        "status_unknown": "Unknown",
        "status_unknown_value": "Unknown({value})",
        "apikey_help": "Provide the full API key generated by the App; it will be saved to cache",
        "token_status_check_help": "Check whether cached authentication info exists and is complete",
        "trunk": "Trunk",
        "vehicle_status": "Vehicle Status",
        "vin": "VIN",
        "window_state": "Window State",
        "coordinates": "Coordinates",
        "json_help": "Output JSON data",
        "api_error": "API error",
        "token_expired_hint": "Hint: access_token may have expired. Please refresh it.",
    },
}

STATUS_TEXT = {
    "power": {
        0: {"zh": "熄火", "en": "Off"},
        1: {"zh": "ACC", "en": "ACC"},
        2: {"zh": "ON", "en": "ON"},
        3: {"zh": "START", "en": "START"},
    },
    "gear": {
        0: {"zh": "P档", "en": "P"},
        1: {"zh": "P档", "en": "P"},
        2: {"zh": "N档", "en": "N"},
        3: {"zh": "D档", "en": "D"},
        4: {"zh": "R档", "en": "R"},
        5: {"zh": "S档", "en": "S"},
    },
    "door": {
        0: {"zh": "关闭", "en": "Closed"},
        1: {"zh": "开启", "en": "Open"},
    },
    "lock": {
        0: {"zh": "解锁", "en": "Unlocked"},
        1: {"zh": "上锁", "en": "Locked"},
    },
    "window": {
        0: {"zh": "关闭", "en": "Closed"},
        1: {"zh": "开启", "en": "Open"},
    },
    "trunk": {
        0: {"zh": "关闭", "en": "Closed"},
        1: {"zh": "开启", "en": "Open"},
    },
}

DOOR_FIELDS = [
    ("frontLeft", "fl", "front_left_door"),
    ("frontRight", "fr", "front_right_door"),
    ("rearLeft", "rl", "left_rear_door"),
    ("rearRight", "rr", "right_rear_door"),
]

LOCK_FIELDS = [
    ("frontLeft", "fl", "front_left_lock"),
    ("frontRight", "fr", "front_right_lock"),
    ("rearLeft", "rl", "left_rear_lock"),
    ("rearRight", "rr", "right_rear_lock"),
]

WINDOW_FIELDS = [
    ("frontLeft", "fl", "front_left_window"),
    ("frontRight", "fr", "front_right_window"),
    ("rearLeft", "rl", "left_rear_window"),
    ("rearRight", "rr", "right_rear_window"),
    ("skylight", "skylight", "skylight"),
]

AC_FIELDS = [
    ("acLeftTemp", "driverTemperature", "driver_side_temp"),
    ("acRightTemp", "passengerTemperature", "passenger_side_temp"),
]

MESSAGES["zh"]["passenger_side_temp"] = "右侧温度"
MESSAGES["en"]["passenger_side_temp"] = "Right Temperature"


def t(key: str, lang: str, **kwargs):
    template = MESSAGES[lang][key]
    if kwargs:
        return template.format(**kwargs)
    return template


def fail(message: str, exit_code: int = 1):
    print(message, file=sys.stderr)
    sys.exit(exit_code)


def parse_combined_token(token: str, lang: str):
    parts = token.split(TOKEN_SEPARATOR, 1)
    if len(parts) != 2 or not parts[0] or not parts[1]:
        fail(t("auth_format_error", lang))
    return parts[0], parts[1]


def save_cache(vehicle_token: str, access_token: str, lang: str):
    api_key = "{0}{1}{2}".format(vehicle_token, TOKEN_SEPARATOR, access_token)
    cache = {
        "apiKey": api_key,
    }
    try:
        CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
        fd = os.open(str(CACHE_FILE), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as file_obj:
            file_obj.write(json.dumps(cache, ensure_ascii=False, indent=2) + "\n")
        os.chmod(CACHE_FILE, 0o600)
    except OSError as exc:
        fail("{0}: {1}".format(t("cache_write_failed", lang), exc))


def mask_token(token: str, prefix: int = 6, suffix: int = 4):
    if len(token) <= prefix + suffix:
        return "*" * len(token)
    return "{0}...{1}".format(token[:prefix], token[-suffix:])


def load_cache(lang: str):
    if not CACHE_FILE.exists():
        fail(
            "{0}\n{1}\n{2}: {3}".format(
                t("cache_not_found", lang),
                t("data_incomplete", lang),
                t("cache_path", lang),
                CACHE_FILE,
            )
        )

    try:
        cache = json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        fail(t("cache_invalid", lang))
    except OSError as exc:
        fail("{0}: {1}".format(t("cache_read_failed", lang), exc))

    api_key = cache.get("apiKey", "").strip()
    if api_key:
        vehicle_token, access_token = parse_combined_token(api_key, lang)
        return access_token, vehicle_token

    access_token = cache.get("accessToken", "")
    vehicle_token = cache.get("vehicleToken", "")
    if not access_token or not vehicle_token:
        fail(t("data_incomplete", lang))
    return access_token, vehicle_token


def load_env_credentials(lang: str):
    api_key = os.environ.get(ENV_API_KEY, "").strip()
    if api_key:
        vehicle_token, access_token = parse_combined_token(api_key, lang)
        return access_token, vehicle_token

    access_token = os.environ.get(ENV_ACCESS_TOKEN, "").strip()
    vehicle_token = os.environ.get(ENV_VEHICLE_TOKEN, "").strip()
    if not access_token and not vehicle_token:
        return None
    if not access_token or not vehicle_token:
        fail(
            "{0}: {1}".format(t("data_incomplete", lang), t("env_api_key", lang))
        )
    return access_token, vehicle_token


def check_auth_status(lang: str):
    env_credentials = load_env_credentials(lang)
    if env_credentials:
        access_token, vehicle_token = env_credentials
        print(t("env_available", lang))
        if os.environ.get(ENV_API_KEY, "").strip():
            print("{0}: {1}".format(t("env_api_key", lang), ENV_API_KEY))
    else:
        access_token, vehicle_token = load_cache(lang)
        print(t("auth_available", lang))
    print("{0}: {1}".format(t("cache_file", lang), CACHE_FILE))
    print("{0}: {1}".format(t("api_key", lang), mask_token("{0}{1}{2}".format(vehicle_token, TOKEN_SEPARATOR, access_token), prefix=10, suffix=8)))


def clear_auth_cache(lang: str):
    if not CACHE_FILE.exists():
        print("{0}: {1}".format(t("cache_already_missing", lang), CACHE_FILE))
        return
    try:
        CACHE_FILE.unlink()
    except OSError as exc:
        fail("{0}: {1}".format(t("cache_write_failed", lang), exc))
    print("{0}: {1}".format(t("cache_cleared", lang), CACHE_FILE))


def call_api(access_token: str, vehicle_token: str, lang: str):
    headers = {
        "Authorization": "Bearer {0}".format(access_token),
        "Content-Type": "application/json",
    }
    payload = json.dumps({"vehicleToken": vehicle_token}).encode("utf-8")
    request = urllib.request.Request(API_URL, data=payload, headers=headers, method="POST")

    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        fail(build_http_error_message(exc, lang))
    except urllib.error.URLError as exc:
        fail("{0}: {1}".format(t("network_error", lang), exc.reason))
    except json.JSONDecodeError as exc:
        fail("{0}: {1}".format(t("json_parse_failed", lang), exc))
    except Exception as exc:
        fail("{0}: {1}".format(t("query_failed", lang), exc))


def check_response(response: dict, lang: str):
    if response.get("code") == 0:
        return
    error_msg = response.get("message", t("status_unknown", lang))
    error_code = response.get("code", "")
    message = "{0} [{1}]: {2}".format(t("api_error", lang), error_code, error_msg)
    if error_code == 360004:
        message = "{0}\n{1}".format(message, t("token_expired_hint", lang))
    fail(message)


def extract_error_message(body_text: str):
    if not body_text:
        return None
    try:
        payload = json.loads(body_text)
    except json.JSONDecodeError:
        return None

    if isinstance(payload, dict):
        for key in ("message", "msg", "error_description", "error"):
            value = payload.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
    return None


def build_http_error_message(exc: urllib.error.HTTPError, lang: str):
    body_text = exc.read().decode("utf-8", errors="replace").strip()
    message = "{0}: {1}".format(t("http_error", lang), exc.code)
    error_text = extract_error_message(body_text)
    if error_text:
        message = "{0}\n{1}".format(message, error_text)
    return message


def format_timestamp(timestamp_ms):
    if not timestamp_ms:
        return None
    try:
        return datetime.fromtimestamp(timestamp_ms / 1000).strftime("%Y-%m-%d %H:%M:%S")
    except (TypeError, ValueError, OSError):
        return str(timestamp_ms)


def read_alias_value(source: dict, primary_key: str, legacy_key: str):
    for key in (primary_key, legacy_key):
        if key in source:
            return source[key]
    return None


def translate_status(group: str, value, lang: str):
    if value is None:
        return t("status_unknown", lang)
    if value in STATUS_TEXT[group]:
        return STATUS_TEXT[group][value][lang]
    return t("status_unknown_value", lang, value=value)


def parse_named_section(source: dict, field_specs, group: str, lang: str):
    parsed = []
    for primary_key, legacy_key, label_key in field_specs:
        value = read_alias_value(source, primary_key, legacy_key)
        if value is None:
            continue
        parsed.append({
            "label": t(label_key, lang),
            "value": value,
            "display": translate_status(group, value, lang),
        })
    return parsed


def parse_ac_section(source: dict, lang: str):
    parsed = []
    for primary_key, legacy_key, label_key in AC_FIELDS:
        value = read_alias_value(source, primary_key, legacy_key)
        if value is None:
            continue
        parsed.append({
            "label": t(label_key, lang),
            "value": value,
            "display": "{0}°C".format(value),
        })
    return parsed


def normalize_data(data: dict, lang: str):
    position = data.get("vehiclePosition", {})
    condition = data.get("vehicleCondition", {})
    return {
        "sn": data.get("sn"),
        "vin": data.get("vin"),
        "vehiclePosition": {
            "address": position.get("address"),
            "longitude": position.get("longitude"),
            "latitude": position.get("latitude"),
            "positionUpdateTimeText": format_timestamp(position.get("positionUpdateTime")),
        },
        "vehicleCondition": {
            "power": translate_status("power", condition.get("power"), lang),
            "gear": translate_status("gear", condition.get("gear"), lang),
            "trunk": translate_status("trunk", condition.get("trunk"), lang),
            "door": parse_named_section(condition.get("door", {}), DOOR_FIELDS, "door", lang),
            "lock": parse_named_section(condition.get("lock", {}), LOCK_FIELDS, "lock", lang),
            "window": parse_named_section(condition.get("window", {}), WINDOW_FIELDS, "window", lang),
            "airConditionerState": parse_ac_section(condition.get("airConditionerState", {}), lang),
        },
    }


def all_section_values_match(rows, expected_display: str):
    return bool(rows) and all(row["display"] == expected_display for row in rows)


def build_summary(normalized: dict, lang: str):
    position = normalized.get("vehiclePosition", {})
    condition = normalized.get("vehicleCondition", {})
    door_rows = condition.get("door", [])
    lock_rows = condition.get("lock", [])
    window_rows = condition.get("window", [])
    trunk_display = condition.get("trunk", t("status_unknown", lang))

    all_locked = all_section_values_match(lock_rows, translate_status("lock", 1, lang))
    all_doors_closed = all_section_values_match(door_rows, translate_status("door", 0, lang))
    all_windows_closed = all_section_values_match(window_rows, translate_status("window", 0, lang))
    trunk_closed = trunk_display == translate_status("trunk", 0, lang)
    power_display = condition.get("power", t("status_unknown", lang))
    started = power_display == translate_status("power", 3, lang)

    if started:
        hint = t("summary_car_started", lang)
    elif not all_locked:
        hint = t("summary_car_unlocked", lang)
    elif not all_doors_closed:
        hint = t("summary_door_open", lang)
    elif not trunk_closed:
        hint = t("summary_trunk_open", lang)
    elif not all_windows_closed:
        hint = t("summary_window_open", lang)
    elif all_locked and all_doors_closed and all_windows_closed and trunk_closed:
        hint = t("summary_car_secure", lang)
    else:
        hint = t("summary_attention", lang)

    return {
        "address": position.get("address") or t("no_data", lang),
        "power": power_display,
        "gear": condition.get("gear", t("status_unknown", lang)),
        "lock": t("summary_all_locked", lang) if all_locked else t("summary_not_fully_locked", lang),
        "door": t("summary_all_closed", lang) if all_doors_closed else t("summary_not_fully_closed", lang),
        "trunk": trunk_display,
        "window": t("summary_all_closed", lang) if all_windows_closed else t("summary_not_fully_closed", lang),
        "air_rows": condition.get("airConditionerState", []),
        "updated_at": position.get("positionUpdateTimeText") or t("no_data", lang),
        "hint": hint,
    }


def print_basic_info(normalized: dict, lang: str):
    print("{0}: {1}".format(t("sn", lang), normalized.get("sn") or t("status_unknown", lang)))
    print("{0}: {1}".format(t("vin", lang), normalized.get("vin") or t("status_unknown", lang)))


def print_section(title_key: str, rows, lang: str):
    print("\n{0}:".format(t(title_key, lang)))
    if not rows:
        print("  {0}".format(t("no_data", lang)))
        return
    for row in rows:
        print("  {0}: {1}".format(row["label"], row["display"]))


def print_position(normalized: dict, lang: str):
    position = normalized.get("vehiclePosition", {})
    if not any(position.get(key) for key in ("address", "longitude", "latitude", "positionUpdateTimeText")):
        print("\n{0}: {1}".format(t("location_info", lang), t("no_data", lang)))
        return

    print("\n{0}:".format(t("location_info", lang)))
    if position.get("address"):
        print("  {0}: {1}".format(t("address", lang), position["address"]))
    if position.get("longitude") is not None and position.get("latitude") is not None:
        print("  {0}: {1}, {2}".format(t("coordinates", lang), position["longitude"], position["latitude"]))
    if position.get("positionUpdateTimeText"):
        print("  {0}: {1}".format(t("position_update_time", lang), position["positionUpdateTimeText"]))


def print_condition(normalized: dict, lang: str):
    condition = normalized.get("vehicleCondition", {})
    print("\n{0}:".format(t("vehicle_status", lang)))
    print("  {0}: {1}".format(t("power", lang), condition["power"]))
    print("  {0}: {1}".format(t("gear", lang), condition["gear"]))
    print("  {0}: {1}".format(t("trunk", lang), condition["trunk"]))
    print_section("door_state", condition.get("door", []), lang)
    print_section("lock_state", condition.get("lock", []), lang)
    print_section("window_state", condition.get("window", []), lang)
    print_section("air_conditioner_state", condition.get("airConditionerState", []), lang)


def print_summary(normalized: dict, lang: str):
    summary = build_summary(normalized, lang)
    print("{0}\n".format(t("summary_title", lang)))
    print("=" * 50)
    print_basic_info(normalized, lang)
    print("\n{0}: {1}".format(t("location_info", lang), summary["address"]))
    print("{0}: {1}".format(t("power", lang), summary["power"]))
    print("{0}: {1}".format(t("gear", lang), summary["gear"]))
    print("{0}: {1}".format(t("lock_summary", lang), summary["lock"]))
    print("{0}: {1}".format(t("door_state", lang), summary["door"]))
    print("{0}: {1}".format(t("trunk", lang), summary["trunk"]))
    print("{0}: {1}".format(t("window_state", lang), summary["window"]))
    if summary["air_rows"]:
        temps = " / ".join(row["display"] for row in summary["air_rows"])
        print("{0}: {1}".format(t("air_conditioner_state", lang), temps))
    print("{0}: {1}".format(t("position_update_time", lang), summary["updated_at"]))
    print("\n{0}: {1}".format(t("summary_hint", lang), summary["hint"]))
    print("\n" + "=" * 50)


def display_text(normalized: dict, mode: str, lang: str, detail: bool):
    if mode == "all" and not detail:
        print_summary(normalized, lang)
        return
    print("{0}\n".format(t("query_success", lang)))
    print("=" * 50)
    print_basic_info(normalized, lang)
    if mode in ("all", "position"):
        print_position(normalized, lang)
    if mode in ("all", "condition"):
        print_condition(normalized, lang)
    print("\n" + "=" * 50)


def select_output_data(data: dict, mode: str):
    if mode == "position":
        return data.get("vehiclePosition", {})
    if mode == "condition":
        return data.get("vehicleCondition", {})
    return data


def output_json(data: dict, mode: str):
    print(json.dumps(select_output_data(data, mode), ensure_ascii=False, indent=2))


def parse_args():
    parser = argparse.ArgumentParser(
        description="Vehicle query script / 车辆查询脚本",
    )
    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument(
        "-p",
        "--position",
        action="store_true",
        help="Query vehicle position only / 仅查询车辆位置信息",
    )
    mode_group.add_argument(
        "-c",
        "--condition",
        action="store_true",
        help="Query vehicle condition only / 仅查询车辆车况信息",
    )
    parser.add_argument("--json", action="store_true", help="Output JSON data / 输出 JSON 数据")
    parser.add_argument(
        "--detail",
        action="store_true",
        help="Show full detailed status instead of summary / 输出完整详细状态而不是摘要",
    )
    parser.add_argument(
        "--lang",
        choices=SUPPORTED_LANGS,
        default="zh",
        help="Output language: zh or en / 输出语言：zh 或 en",
    )
    parser.add_argument(
        "--apikey",
        help="Provide the full API key and save it to cache / 提供完整 API Key 并写入缓存",
    )
    parser.add_argument(
        "--save-token-only",
        action="store_true",
        help="Save API key only, do not query / 仅保存 API Key，不发起查询",
    )
    parser.add_argument(
        "--check-auth",
        action="store_true",
        help="Check cached auth status only / 仅检查缓存认证状态",
    )
    parser.add_argument(
        "--clear-auth",
        action="store_true",
        help="Delete cached auth info / 删除本地认证缓存",
    )
    return parser.parse_args()


def resolve_mode(args) -> str:
    if args.position:
        return "position"
    if args.condition:
        return "condition"
    return "all"


def validate_args(args):
    if args.save_token_only and not args.apikey:
        fail(t("save_apikey_only_conflict", args.lang))
    if args.check_auth:
        if args.apikey or args.save_token_only or args.position or args.condition or args.json or args.detail:
            fail(t("check_auth_conflict", args.lang))
    if args.clear_auth:
        if (
            args.apikey
            or args.save_token_only
            or args.position
            or args.condition
            or args.json
            or args.detail
            or args.check_auth
        ):
            fail(t("clear_auth_conflict", args.lang))


def resolve_credentials(apikey: Optional[str], lang: str):
    if apikey:
        vehicle_token, access_token = parse_combined_token(apikey, lang)
        save_cache(vehicle_token, access_token, lang)
        return access_token, vehicle_token
    env_credentials = load_env_credentials(lang)
    if env_credentials:
        return env_credentials
    return load_cache(lang)


def fetch_vehicle_data(access_token: str, vehicle_token: str, lang: str):
    response = call_api(access_token, vehicle_token, lang)
    check_response(response, lang)
    return response.get("data", {})


def render_output(data: dict, mode: str, json_output: bool, lang: str, detail: bool):
    if json_output:
        output_json(data, mode)
        return
    display_text(normalize_data(data, lang), mode, lang, detail)


def run_query(
    mode: str,
    json_output: bool,
    lang: str,
    apikey: Optional[str],
    save_token_only: bool,
    check_auth: bool,
    clear_auth: bool,
    detail: bool,
):
    if clear_auth:
        clear_auth_cache(lang)
        return
    if check_auth:
        check_auth_status(lang)
        return
    access_token, vehicle_token = resolve_credentials(apikey, lang)
    if save_token_only:
        print("{0}: {1}".format(t("cache_saved", lang), CACHE_FILE))
        return
    data = fetch_vehicle_data(access_token, vehicle_token, lang)
    render_output(data, mode, json_output, lang, detail)


def main():
    args = parse_args()
    validate_args(args)
    run_query(
        resolve_mode(args),
        args.json,
        args.lang,
        args.apikey,
        args.save_token_only,
        args.check_auth,
        args.clear_auth,
        args.detail,
    )


if __name__ == "__main__":
    main()
