#!/bin/bash

echo "🚀 Setting up AI Content Generator Pro Skill"
echo "=========================================="

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is required but not installed. Please install Node.js 18+"
    exit 1
fi

echo "✅ Node.js found: $(node --version)"

# Install dependencies
echo "📦 Installing dependencies..."
npm install

# Create necessary directories
echo "📁 Creating directories..."
mkdir -p content data exports

# Create default configuration
echo "⚙️  Creating default configuration..."
cat > config/config.json << EOF
{
  "openai": {
    "apiKey": "",
    "model": "gpt-4"
  },
  "anthropic": {
    "apiKey": "",
    "model": "claude-3-opus"
  },
  "xai": {
    "apiKey": "",
    "model": "grok-beta"
  },
  "defaultModel": "openai",
  "tone": "professional",
  "seo": {
    "enabled": true,
    "keywords": []
  },
  "brandVoice": {
    "enabled": false,
    "samples": []
  }
}
EOF

# Create sample content
echo "📝 Creating sample content..."
mkdir -p content/samples
cat > content/samples/sample-blog.md << EOF
# Welcome to AI Content Generator Pro

This is a sample blog post generated by the AI Content Generator Pro skill.

## Features

- **Multi-model support**: Use OpenAI, Claude, and Grok
- **SEO optimization**: Improve search engine rankings
- **Tone adjustment**: Match your brand voice
- **Content calendar**: Plan and schedule content
- **Export options**: Multiple format support

## Getting Started

1. Configure your API keys
2. Choose your content type
3. Generate high-quality content
4. Optimize and export

## Support

For help, contact support@jaceal.com
EOF

# Set permissions
echo "🔒 Setting permissions..."
chmod +x index.js
chmod +x scripts/*.sh

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "1. Add your API keys to config/config.json"
echo "2. Run: npm test (to verify installation)"
echo "3. Try: node index.js generate blog 'Future of AI'"
echo ""
echo "For OpenClaw integration:"
echo "1. Move this folder to your OpenClaw skills directory"
echo "2. Run: openclaw skill install ./ai-content-generator-pro"
echo ""
echo "🎉 Enjoy your premium content generation skill!"