#!/usr/bin/env python3
"""
Sync a workspace HEARTBEAT.md file for say-hi-to-me.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import yaml

HEARTBEAT_INTERVALS = {
    "low": "6h",
    "mid": "2h",
    "high": "30m",
}


def read_yaml(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    return loaded if isinstance(loaded, dict) else {}


def read_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def resolve_openclaw_home(explicit_home: Optional[Path] = None) -> Path:
    if explicit_home:
        return explicit_home.expanduser()
    if os.environ.get("OPENCLAW_HOME"):
        return Path(os.environ["OPENCLAW_HOME"]).expanduser()
    return Path.home() / ".openclaw"


def resolve_workspace(
    openclaw_home: Path,
    explicit_workspace: Optional[Path] = None,
    explicit_workspace_name: Optional[str] = None,
    agent_id: Optional[str] = None,
) -> Tuple[Path, str]:
    if explicit_workspace:
        return explicit_workspace.expanduser(), "explicit-workspace"

    if explicit_workspace_name:
        return openclaw_home / explicit_workspace_name, "explicit-workspace-name"

    env_workspace = os.environ.get("OPENCLAW_WORKSPACE")
    if env_workspace:
        return Path(env_workspace).expanduser(), "env-workspace"

    env_workspace_name = os.environ.get("OPENCLAW_WORKSPACE_NAME")
    if env_workspace_name:
        return openclaw_home / env_workspace_name, "env-workspace-name"

    config = read_json(openclaw_home / "openclaw.json")
    requested_agent_id = agent_id or os.environ.get("OPENCLAW_AGENT_ID")
    if requested_agent_id:
        agents = config.get("agents", {}).get("list", [])
        for item in agents:
            if not isinstance(item, dict):
                continue
            if item.get("id") == requested_agent_id and item.get("workspace"):
                return Path(item["workspace"]).expanduser(), f"config-agent:{requested_agent_id}"

    default_workspace = config.get("agents", {}).get("defaults", {}).get("workspace")
    if default_workspace:
        return Path(default_workspace).expanduser(), "config-default"

    return openclaw_home / "workspace", "fallback-default"


def load_active_role_name(skill_root: Path, session: Dict[str, Any]) -> Optional[str]:
    active_rel = session.get("role", {}).get("active")
    if not active_rel:
        return None
    active_path = (skill_root / active_rel).resolve()
    role = read_yaml(active_path)
    return role.get("meta", {}).get("display_name")


def select_task_interval(session: Dict[str, Any]) -> str:
    proactive = session.get("proactive", {})
    if not proactive.get("enabled", False):
        return HEARTBEAT_INTERVALS["low"]
    return HEARTBEAT_INTERVALS.get(proactive.get("frequency", "mid"), HEARTBEAT_INTERVALS["mid"])


def render_heartbeat_md(skill_root: Path, workspace_root: Path, session: Dict[str, Any]) -> str:
    proactive = session.get("proactive", {})
    active_role = load_active_role_name(skill_root, session) or "none"
    interval = select_task_interval(session)
    quiet_hours = proactive.get("quiet_hours") or "none"
    pause_until = proactive.get("pause_until") or "none"
    freshness = session.get("context", {}).get("freshness_hours", 72)
    enabled = str(bool(proactive.get("enabled", False))).lower()

    return (
        "# Generated by say-hi-to-me\n\n"
        "tasks:\n"
        "- name: say-hi-to-me-proactive-checkin\n"
        f"  interval: {interval}\n"
        "  prompt: |\n"
        "    Use the say-hi-to-me skill for a proactive companionship check.\n"
        f"    Skill root: {skill_root}\n"
        f"    Workspace root: {workspace_root}\n"
        f"    Read {skill_root / 'state' / 'session.yaml'} for current runtime state.\n"
        f"    Run `python3 {skill_root / 'scripts' / 'heartbeat_bridge.py'} --skill-root {skill_root} --json --mark-sent`.\n"
        "    If the returned `response_text` is `HEARTBEAT_OK`, do not send a greeting.\n"
        "    Otherwise send exactly that one short greeting and nothing extra.\n"
        "    Respect quiet hours, pause windows, cooldowns, consent gates, and safety boundaries.\n\n"
        "## Runtime Snapshot\n\n"
        f"- Workspace name: {workspace_root.name}\n"
        f"- Skill root: {skill_root}\n"
        f"- Proactive enabled: {enabled}\n"
        f"- Frequency: {proactive.get('frequency', 'mid')}\n"
        f"- Quiet hours: {quiet_hours}\n"
        f"- Pause until: {pause_until}\n"
        f"- Freshness window: {freshness}h\n"
        f"- Active role: {active_role}\n"
    )


def sync_heartbeat_md(
    skill_root: Path,
    session: Optional[Dict[str, Any]] = None,
    workspace: Optional[Path] = None,
    workspace_name: Optional[str] = None,
    agent_id: Optional[str] = None,
    openclaw_home: Optional[Path] = None,
) -> Dict[str, Any]:
    root = skill_root.resolve()
    session_data = session if session is not None else read_yaml(root / "state" / "session.yaml")
    home = resolve_openclaw_home(openclaw_home)
    workspace_root, source = resolve_workspace(
        openclaw_home=home,
        explicit_workspace=workspace,
        explicit_workspace_name=workspace_name,
        agent_id=agent_id,
    )

    heartbeat_path = workspace_root / "HEARTBEAT.md"
    try:
        workspace_root.mkdir(parents=True, exist_ok=True)
        heartbeat_path.write_text(render_heartbeat_md(root, workspace_root, session_data), encoding="utf-8")
        return {
            "synced": True,
            "path": str(heartbeat_path),
            "workspace": str(workspace_root),
            "workspace_source": source,
            "task_interval": select_task_interval(session_data),
        }
    except PermissionError as e:
        return {
            "synced": False,
            "error": "permission_denied",
            "message": f"Cannot write to {heartbeat_path}: {e}",
            "workspace": str(workspace_root),
            "workspace_source": source,
            "task_interval": select_task_interval(session_data),
        }
    except OSError as e:
        return {
            "synced": False,
            "error": "write_error",
            "message": f"Failed to write {heartbeat_path}: {e}",
            "workspace": str(workspace_root),
            "workspace_source": source,
            "task_interval": select_task_interval(session_data),
        }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sync workspace HEARTBEAT.md for say-hi-to-me")
    parser.add_argument("--skill-root", help="Skill root path; default is script parent folder")
    parser.add_argument("--workspace", help="Explicit OpenClaw workspace path")
    parser.add_argument("--workspace-name", help="Explicit workspace name under OPENCLAW_HOME")
    parser.add_argument("--agent-id", help="Resolve workspace from openclaw.json agents.list[].id")
    parser.add_argument("--openclaw-home", help="OpenClaw home path; default is ~/.openclaw or $OPENCLAW_HOME")
    parser.add_argument("--json", action="store_true", help="Print JSON result")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    skill_root = Path(args.skill_root).resolve() if args.skill_root else Path(__file__).resolve().parents[1]
    result = sync_heartbeat_md(
        skill_root=skill_root,
        workspace=Path(args.workspace).expanduser() if args.workspace else None,
        workspace_name=args.workspace_name,
        agent_id=args.agent_id,
        openclaw_home=Path(args.openclaw_home).expanduser() if args.openclaw_home else None,
    )
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(result["path"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
