#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""WeChat API Tool for OpenClaw Skill

Configuration sources (priority: CLI args > env vars > service_status.json > config.yaml > defaults):
  - WXAPI_BASE_URL or WXAPI_PORT: API server address
  - WXAPI_TOKEN: Authentication token
  - ~/.wxautox/service_status.json: Auto-generated by wxauto-restful-api
  - config.yaml in service directory

GitHub: https://github.com/cluic/wxauto-restful-api
"""

import argparse
import json
import os
import sys
import requests
import subprocess
from pathlib import Path

# Defaults
DEFAULT_PORT = 8000
DEFAULT_HOST = "localhost"
DEFAULT_TOKEN = "token"

# Resolved values
BASE_URL = None
TOKEN = None
SERVICE_DIR = None
SERVICE_STATUS_FILE = Path.home() / ".wxautox" / "service_status.json"

# Possible service directories to search
SERVICE_SEARCH_PATHS = [
    Path(__file__).parent.parent.parent / "wxauto-restful-api",  # sibling of skill dir
    Path(__file__).parent.parent / "wxauto-restful-api",  # nested in skill dir
    Path.home() / "wxauto-restful-api",  # in home directory
]

def find_service_dir():
    """Find the service directory."""
    # Check environment variable first
    env_dir = os.environ.get('WXAPI_SERVICE_DIR')
    if env_dir:
        env_path = Path(env_dir)
        if env_path.exists() and (env_path / "run.py").exists():
            return env_path
    
    # Check default search paths
    for path in SERVICE_SEARCH_PATHS:
        if path.exists() and (path / "run.py").exists():
            return path
    return None

def check_service_alive(base_url):
    """Check if service is responding."""
    try:
        resp = requests.get(f"{base_url}/", timeout=3)
        return resp.status_code == 200
    except Exception:
        return False

def start_service(service_dir):
    """Start the wxauto-restful-api service."""
    if not service_dir or not service_dir.exists():
        print(f"Error: Service directory not found")
        print(f"  Clone from: https://github.com/cluic/wxauto-restful-api")
        return False
    
    run_py = service_dir / "run.py"
    if not run_py.exists():
        print(f"Error: run.py not found in {service_dir}")
        return False
    
    print(f"Starting service from {service_dir}...")
    try:
        # Set environment for proper encoding
        env = os.environ.copy()
        env['PYTHONIOENCODING'] = 'utf-8'
        
        # Start service in background
        if sys.platform == "win32":
            subprocess.Popen(
                [sys.executable, "run.py"],
                cwd=str(service_dir),
                env=env,
                creationflags=subprocess.CREATE_NO_WINDOW | subprocess.DETACHED_PROCESS
            )
        else:
            subprocess.Popen(
                [sys.executable, "run.py"],
                cwd=str(service_dir),
                env=env,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                start_new_session=True
            )
        
        # Wait for service to start (up to 15 seconds)
        import time
        for i in range(15):
            time.sleep(1)
            # Re-read service_status.json
            if SERVICE_STATUS_FILE.exists():
                with open(SERVICE_STATUS_FILE, 'r', encoding='utf-8') as f:
                    status = json.load(f)
                    if status.get('status') == 'running':
                        port = status.get('port', DEFAULT_PORT)
                        host = '127.0.0.1' if status.get('host') == '0.0.0.0' else status.get('host', DEFAULT_HOST)
                        test_url = f"http://{host}:{port}"
                        if check_service_alive(test_url):
                            print(f"[OK] Service started on {test_url}")
                            return True
        
        print("Error: Service failed to start within 15 seconds")
        return False
    except Exception as e:
        print(f"Error starting service: {e}")
        return False

def resolve_config():
    """Resolve configuration from multiple sources."""
    global BASE_URL, TOKEN, SERVICE_DIR
    
    # Find service directory first
    SERVICE_DIR = find_service_dir()
    
    # 1. Try environment variables first
    base_url = os.environ.get('WXAPI_BASE_URL')
    token = os.environ.get('WXAPI_TOKEN')
    
    # 2. If no base_url, try WXAPI_PORT
    if not base_url:
        port = os.environ.get('WXAPI_PORT')
        host = os.environ.get('WXAPI_HOST', 'localhost')
        if port:
            base_url = f"http://{host}:{port}"
    
    # 3. Try service_status.json (auto-generated by wxauto-restful-api)
    service_was_started = False
    if not base_url:
        try:
            if SERVICE_STATUS_FILE.exists():
                with open(SERVICE_STATUS_FILE, 'r', encoding='utf-8') as f:
                    status = json.load(f)
                    
                    # Check if status says running
                    if status.get('status') == 'running':
                        port = status.get('port', DEFAULT_PORT)
                        host = '127.0.0.1' if status.get('host') == '0.0.0.0' else status.get('host', DEFAULT_HOST)
                        candidate_url = f"http://{host}:{port}"
                        
                        # Verify service is actually responding
                        if check_service_alive(candidate_url):
                            base_url = candidate_url
                        else:
                            # Status file says running but service not responding
                            # Try to start service
                            print(f"Service status file exists but service not responding")
                            if start_service(SERVICE_DIR):
                                service_was_started = True
                                # Re-read status file
                                if SERVICE_STATUS_FILE.exists():
                                    with open(SERVICE_STATUS_FILE, 'r', encoding='utf-8') as f:
                                        status = json.load(f)
                                        if status.get('status') == 'running':
                                            port = status.get('port', DEFAULT_PORT)
                                            host = '127.0.0.1' if status.get('host') == '0.0.0.0' else status.get('host', DEFAULT_HOST)
                                            base_url = f"http://{host}:{port}"
        except Exception as e:
            pass
    
    # 4. If still no base_url, try to start service
    if not base_url and SERVICE_DIR:
        print("No running service found")
        if start_service(SERVICE_DIR):
            service_was_started = True
            # Re-read status file
            try:
                if SERVICE_STATUS_FILE.exists():
                    with open(SERVICE_STATUS_FILE, 'r', encoding='utf-8') as f:
                        status = json.load(f)
                        if status.get('status') == 'running':
                            port = status.get('port', DEFAULT_PORT)
                            host = '127.0.0.1' if status.get('host') == '0.0.0.0' else status.get('host', DEFAULT_HOST)
                            base_url = f"http://{host}:{port}"
            except Exception:
                pass
    
    # 5. Try to load from config.yaml
    if not base_url or not token:
        try:
            import yaml
            
            config_paths = [
                SERVICE_DIR / "config.yaml" if SERVICE_DIR else None,
                Path(__file__).parent.parent / "wxauto-restful-api" / "config.yaml",
                os.environ.get('WXAPI_CONFIG', ''),
            ]
            
            for config_path in config_paths:
                if config_path and Path(config_path).exists():
                    with open(config_path, 'r', encoding='utf-8') as f:
                        config = yaml.safe_load(f)
                        if config:
                            if not base_url:
                                port = config.get('server', {}).get('port', DEFAULT_PORT)
                                host = config.get('server', {}).get('host', DEFAULT_HOST)
                                host = '127.0.0.1' if host == '0.0.0.0' else host
                                base_url = f"http://{host}:{port}"
                            if not token:
                                token = config.get('auth', {}).get('token', DEFAULT_TOKEN)
                        break
        except Exception:
            pass
    
    # 6. Apply defaults
    if not base_url:
        base_url = f"http://{DEFAULT_HOST}:{DEFAULT_PORT}"
    if not token:
        token = DEFAULT_TOKEN
    
    BASE_URL = base_url
    TOKEN = token

resolve_config()

def get_headers():
    return {
        "Authorization": f"Bearer {TOKEN}",
        "Content-Type": "application/json"
    }

def call_api(endpoint, data=None, method="POST"):
    """Call API endpoint."""
    url = f"{BASE_URL}{endpoint}"
    try:
        if method == "GET":
            resp = requests.get(url, headers=get_headers(), timeout=10)
        else:
            resp = requests.post(url, headers=get_headers(), json=data or {}, timeout=10)
        return resp.json()
    except requests.exceptions.ConnectionError:
        print("Error: Cannot connect to service. Start with: python run.py")
        return None
    except Exception as e:
        print(f"Error: {e}")
        return None

# ==================== WeChat Commands ====================

def cmd_send(args):
    """Send message via main window."""
    data = {"who": args.who, "msg": args.message}
    if args.exact:
        data["exact"] = True
    if args.at:
        data["at"] = args.at.split(",")
    
    result = call_api("/v1/wechat/send", data)
    if result and result.get('success'):
        print(f"[OK] Message sent to {args.who}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_send_chat(args):
    """Send message via sub-window."""
    data = {"who": args.who, "msg": args.message}
    if args.at:
        data["at"] = args.at.split(",")
    
    result = call_api("/v1/chat/send", data)
    if result and result.get('success'):
        print(f"[OK] Message sent to {args.who} (sub-window)")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_getmsg(args):
    """Get chat history from main window."""
    data = {"who": args.who}
    result = call_api("/v1/wechat/getallmessage", data)
    if result and result.get('success'):
        msg_data = result.get('data', {})
        messages = msg_data.get('messages', [])
        print(f"Chat with {args.who} ({len(messages)} messages):")
        for msg in messages[-10:]:
            content = msg.get('content', '')[:50]
            sender = msg.get('sender', '?')
            print(f"  [{sender}] {content}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_getmsg_chat(args):
    """Get chat history from sub-window."""
    data = {"who": args.who}
    result = call_api("/v1/chat/getallmessage", data)
    if result and result.get('success'):
        msg_data = result.get('data', {})
        messages = msg_data.get('messages', [])
        print(f"Sub-window chat with {args.who} ({len(messages)} messages):")
        for msg in messages[-10:]:
            content = msg.get('content', '')[:50]
            sender = msg.get('sender', '?')
            print(f"  [{sender}] {content}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_history(args):
    """Get history messages."""
    data = {"who": args.who, "n": args.count}
    result = call_api("/v1/wechat/gethistorymessage", data)
    if result and result.get('success'):
        msg_data = result.get('data', {})
        messages = msg_data.get('messages', [])
        print(f"History with {args.who} ({len(messages)} messages):")
        for msg in messages[-10:]:
            content = msg.get('content', '')[:50]
            sender = msg.get('sender', '?')
            print(f"  [{sender}] {content}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_listen(args):
    """Add listen chat."""
    data = {"who": args.who}
    result = call_api("/v1/wechat/addlistenchat", data)
    if result and result.get('success'):
        print(f"[OK] Listening to {args.who}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_newmsg(args):
    """Get next new message."""
    data = {"filter_mute": args.filter_mute}
    result = call_api("/v1/wechat/getnextnewmessage", data)
    if result and result.get('success'):
        msg_data = result.get('data', {})
        messages = msg_data.get('messages', [])
        if messages:
            for msg in messages:
                content = msg.get('content', '')
                sender = msg.get('sender', '?')
                who = msg.get('who', '?')
                print(f"[{who}] {sender}: {content}")
        else:
            print("No new messages")
    else:
        print("No new messages")

def cmd_newmsg_chat(args):
    """Get new message from sub-window."""
    data = {"who": args.who}
    result = call_api("/v1/chat/getnewmessage", data)
    if result and result.get('success'):
        msg_data = result.get('data', {})
        messages = msg_data.get('messages', [])
        if messages:
            for msg in messages:
                content = msg.get('content', '')
                sender = msg.get('sender', '?')
                print(f"  [{sender}] {content}")
        else:
            print("No new messages")
    else:
        print("No new messages")

def cmd_session(args):
    """Get session list."""
    result = call_api("/v1/wechat/getsession", {})
    if result and result.get('success'):
        data = result.get('data', {})
        items = data.get('items', [])
        print(f"Sessions ({len(items)} total):")
        for item in items[:20]:
            if isinstance(item, dict):
                name = item.get('name', '?')
            else:
                name = str(item)
            print(f"  - {name}")
        if len(items) > 20:
            print(f"  ... and {len(items) - 20} more")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_windows(args):
    """Get all sub-windows."""
    result = call_api("/v1/wechat/getallsubwindow", {})
    if result and result.get('success'):
        data = result.get('data', {})
        items = data.get('items', [])
        print(f"Sub-windows ({len(items)} total):")
        for item in items:
            name = item.get('name', '?')
            wtype = item.get('type', '?')
            print(f"  - [{wtype}] {name}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_chatwith(args):
    """Switch chat window."""
    data = {"who": args.who}
    if args.exact:
        data["exact"] = True
    result = call_api("/v1/wechat/chatwith", data)
    if result and result.get('success'):
        print(f"[OK] Switched to {args.who}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_friends(args):
    """Get friends list."""
    result = call_api("/v1/wechat/getfriends", {})
    if result and result.get('success'):
        data = result.get('data', {})
        items = data.get('items', [])
        print(f"Friends ({len(items)} total):")
        for item in items[:20]:
            name = item.get('name', '?') if isinstance(item, dict) else str(item)
            print(f"  - {name}")
        if len(items) > 20:
            print(f"  ... and {len(items) - 20} more")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_groups(args):
    """Get groups list."""
    result = call_api("/v1/wechat/getrecentgroups", {})
    if result and result.get('success'):
        data = result.get('data', {})
        items = data.get('items', [])
        print(f"Groups ({len(items)} total):")
        for item in items[:20]:
            if isinstance(item, list) and len(item) >= 1:
                name = item[0]
            elif isinstance(item, dict):
                name = item.get('name', '?')
            else:
                name = str(item)
            print(f"  - {name}")
        if len(items) > 20:
            print(f"  ... and {len(items) - 20} more")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_myinfo(args):
    """Get my info."""
    result = call_api("/v1/wechat/getmyinfo", {})
    if result and result.get('success'):
        data = result.get('data', {})
        item = data.get('item', {})
        name = item.get('display_name', item.get('name', '?'))
        wxid = item.get('id', item.get('wxid', '?'))
        print(f"Name: {name}")
        print(f"WeChat ID: {wxid}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_status(args):
    """Get service status."""
    result = call_api("/v1/wechat/status", method="GET")
    if result and result.get('success'):
        data = result.get('data', {})
        status = data.get('status', '?')
        clients = data.get('clients_count', 0)
        print(f"Status: {status}")
        print(f"Clients: {clients}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_initialize(args):
    """Initialize WeChat instance."""
    result = call_api("/v1/wechat/initialize", {})
    if result and result.get('success'):
        data = result.get('data', {})
        status = data.get('status', '?')
        clients = data.get('clients_count', 0)
        print(f"[OK] Initialized: {status}, {clients} client(s)")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_online(args):
    """Check if online."""
    result = call_api("/v1/wechat/isonline", {})
    if result and result.get('success'):
        data = result.get('data', {})
        item = data.get('item', {})
        online = item.get('online', False)
        status = "online" if online else "offline"
        print(f"Status: {status}")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_switch_chat(args):
    """Switch to chat page."""
    result = call_api("/v1/wechat/switch/chat", {})
    if result and result.get('success'):
        print("[OK] Switched to chat page")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def cmd_switch_contact(args):
    """Switch to contact page."""
    result = call_api("/v1/wechat/switch/contact", {})
    if result and result.get('success'):
        print("[OK] Switched to contact page")
    elif result:
        print(f"[FAIL] {result.get('message', 'Unknown error')}")
    else:
        print("[FAIL] API call failed")

def main():
    global BASE_URL, TOKEN
    
    # Build epilog with current config
    epilog = f"""
Current config:
  BASE_URL: {BASE_URL}
  TOKEN: {TOKEN}

Config sources (priority: CLI args > env vars > service_status.json > config.yaml > defaults):
  - WXAPI_BASE_URL or WXAPI_HOST/WXAPI_PORT: API server address
  - WXAPI_TOKEN: Authentication token
  - ~/.wxautox/service_status.json: Auto-detected from running service
  - WXAPI_CONFIG: Path to config.yaml
"""
    
    parser = argparse.ArgumentParser(description="WeChat API Tool", epilog=epilog)
    parser.add_argument("--base-url", help=f"API base URL (default: {BASE_URL})")
    parser.add_argument("--token", help=f"Auth token (default: {TOKEN})")
    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # WeChat commands
    p_init = subparsers.add_parser("init", help="Initialize WeChat instance")
    p_init.set_defaults(func=cmd_initialize)

    p_status = subparsers.add_parser("status", help="Get service status")
    p_status.set_defaults(func=cmd_status)

    p_online = subparsers.add_parser("online", help="Check if online")
    p_online.set_defaults(func=cmd_online)

    p_send = subparsers.add_parser("send", help="Send message (main window)")
    p_send.add_argument("who", help="Recipient")
    p_send.add_argument("message", help="Message content")
    p_send.add_argument("--exact", action="store_true", help="Exact match")
    p_send.add_argument("--at", help="@people, comma separated")
    p_send.set_defaults(func=cmd_send)

    p_send_chat = subparsers.add_parser("send-chat", help="Send message (sub-window)")
    p_send_chat.add_argument("who", help="Recipient")
    p_send_chat.add_argument("message", help="Message content")
    p_send_chat.add_argument("--at", help="@people, comma separated")
    p_send_chat.set_defaults(func=cmd_send_chat)

    p_getmsg = subparsers.add_parser("getmsg", help="Get chat history (main window)")
    p_getmsg.add_argument("who", help="Contact")
    p_getmsg.set_defaults(func=cmd_getmsg)

    p_getmsg_chat = subparsers.add_parser("getmsg-chat", help="Get chat history (sub-window)")
    p_getmsg_chat.add_argument("who", help="Contact")
    p_getmsg_chat.set_defaults(func=cmd_getmsg_chat)

    p_history = subparsers.add_parser("history", help="Get history messages")
    p_history.add_argument("who", help="Contact")
    p_history.add_argument("--count", "-n", type=int, default=50, help="Number of messages")
    p_history.set_defaults(func=cmd_history)

    p_listen = subparsers.add_parser("listen", help="Add listener")
    p_listen.add_argument("who", help="Contact to listen")
    p_listen.set_defaults(func=cmd_listen)

    p_newmsg = subparsers.add_parser("newmsg", help="Get next new message")
    p_newmsg.add_argument("--filter-mute", action="store_true", help="Filter muted")
    p_newmsg.set_defaults(func=cmd_newmsg)

    p_newmsg_chat = subparsers.add_parser("newmsg-chat", help="Get new message (sub-window)")
    p_newmsg_chat.add_argument("who", help="Contact")
    p_newmsg_chat.set_defaults(func=cmd_newmsg_chat)

    p_session = subparsers.add_parser("session", help="Get session list")
    p_session.set_defaults(func=cmd_session)

    p_windows = subparsers.add_parser("windows", help="Get sub-windows")
    p_windows.set_defaults(func=cmd_windows)

    p_chatwith = subparsers.add_parser("chatwith", help="Switch chat window")
    p_chatwith.add_argument("who", help="Contact")
    p_chatwith.add_argument("--exact", action="store_true", help="Exact match")
    p_chatwith.set_defaults(func=cmd_chatwith)

    p_friends = subparsers.add_parser("friends", help="Get friends list")
    p_friends.set_defaults(func=cmd_friends)

    p_groups = subparsers.add_parser("groups", help="Get groups list")
    p_groups.set_defaults(func=cmd_groups)

    p_myinfo = subparsers.add_parser("myinfo", help="Get my info")
    p_myinfo.set_defaults(func=cmd_myinfo)

    p_switch_chat = subparsers.add_parser("switch-chat", help="Switch to chat page")
    p_switch_chat.set_defaults(func=cmd_switch_chat)

    p_switch_contact = subparsers.add_parser("switch-contact", help="Switch to contact page")
    p_switch_contact.set_defaults(func=cmd_switch_contact)

    # Legacy aliases (for backward compatibility)
    p_contacts = subparsers.add_parser("contacts", help="[Legacy] Get friends list")
    p_contacts.set_defaults(func=cmd_friends)

    args = parser.parse_args()
    
    # Apply CLI overrides
    if args.base_url:
        BASE_URL = args.base_url
    if args.token:
        TOKEN = args.token
    
    if args.command is None:
        parser.print_help()
        return

    args.func(args)

if __name__ == "__main__":
    main()
