#!/usr/bin/env python3
"""
导出报告到不同格式
Export reports to different formats
"""

import argparse
import json
import os
from datetime import datetime
from pathlib import Path
import sys

# 添加技能路径以便导入 i18n_helper
SKILL_PATH = Path(__file__).parent.parent
sys.path.insert(0, str(SKILL_PATH))

try:
    from i18n_helper import get_i18n
    i18n = get_i18n(SKILL_PATH)
except ImportError:
    # Fallback if i18n not available
    class SimpleI18N:
        def get(self, key, default=None, **kwargs):
            return default or key
        def t(self, key, default=None, **kwargs):
            return default or key
        def get_language(self):
            return os.environ.get('HERMES_LANG', os.environ.get('LANG', 'en'))[:2]
    i18n = SimpleI18N()

# 配置路径
OUTPUT_DIR = Path.home() / '.hermes/skills/work-visualization/output'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Language-specific strings
STRINGS = {
    'zh': {
        'generating': '📝 正在生成报告...',
        'report_title': 'Hermes 工作报告',
        'generated_time': '生成时间',
        'task_progress': '📊 任务进度',
        'current_tasks': '### 当前任务',
        'progress_overview': '### 进度概览',
        'total_progress': '- 总体进度',
        'completed_tasks': '- 已完成任务',
        'in_progress_tasks': '- 进行中任务',
        'pending_tasks': '- 待开始任务',
        'tool_stats': '🔧 工具使用统计',
        'tool_table_header': '| 工具 | 调用次数 | 占比 |',
        'tool_table_divider': '|------|---------|------|',
        'total_tool_calls': '**总工具调用次数**',
        'times': ' 次',
        'skill_usage': '📦 技能使用',
        'most_used_skills': '最常用技能',
        'code_changes': '💻 代码改动',
        'code_table_header': '| 文件 | 新增 | 删除 | 总计 |',
        'total_changes': '**总计**',
        'lines': ' 行',
        'efficiency': '📈 效率指标',
        'avg_task_time': '- 平均任务完成时间',
        'task_completion_rate': '- 任务完成率',
        'skill_success_rate': '- 技能调用成功率',
        'avg_tool_response': '- 平均工具响应时间',
        'work_summary': '💡 工作总结',
        'main_results': '### 主要成果',
        'next_plan': '### 下一步计划',
        'footer': '*报告由 Hermes work-visualization 技能自动生成*',
        'exporting': '正在生成报告...',
        'report_saved': '报告已保存到',
        'report_directory': '报告目录',
        'completed': '报告生成完成!'
    },
    'en': {
        'generating': '📝 Generating report...',
        'report_title': 'Hermes Work Report',
        'generated_time': 'Generated Time',
        'task_progress': '📊 Task Progress',
        'current_tasks': '### Current Tasks',
        'progress_overview': '### Progress Overview',
        'total_progress': '- Overall Progress',
        'completed_tasks': '- Completed Tasks',
        'in_progress_tasks': '- In Progress Tasks',
        'pending_tasks': '- Pending Tasks',
        'tool_stats': '🔧 Tool Usage Statistics',
        'tool_table_header': '| Tool | Call Count | Percentage |',
        'tool_table_divider': '|------|-----------|------------|',
        'total_tool_calls': '**Total Tool Calls**',
        'times': '',
        'skill_usage': '📦 Skill Usage',
        'most_used_skills': 'Most Used Skills',
        'code_changes': '💻 Code Changes',
        'code_table_header': '| File | Added | Deleted | Total |',
        'total_changes': '**Total**',
        'lines': ' lines',
        'efficiency': '📈 Efficiency Metrics',
        'avg_task_time': '- Avg Task Completion Time',
        'task_completion_rate': '- Task Completion Rate',
        'skill_success_rate': '- Skill Call Success Rate',
        'avg_tool_response': '- Avg Tool Response Time',
        'work_summary': '💡 Work Summary',
        'main_results': '### Main Results',
        'next_plan': '### Next Plans',
        'footer': '*Report automatically generated by Hermes work-visualization skill*',
        'exporting': 'Generating report...',
        'report_saved': 'Report saved to',
        'report_directory': 'Report directory',
        'completed': 'Report generation completed!'
    }
}

def get_str(key, lang=None):
    """Get localized string"""
    if lang is None:
        lang = i18n.get_language()
    return STRINGS.get(lang, STRINGS['en']).get(key, key)

def generate_markdown_report(lang=None):
    """生成Markdown格式报告 / Generate Markdown format report"""
    if lang is None:
        lang = i18n.get_language()

    title = get_str('report_title', lang)
    time_str = get_str('generated_time', lang)
    task_progress = get_str('task_progress', lang)
    current_tasks = get_str('current_tasks', lang)
    progress_overview = get_str('progress_overview', lang)
    total_progress = get_str('total_progress', lang)
    completed_tasks = get_str('completed_tasks', lang)
    in_progress_tasks = get_str('in_progress_tasks', lang)
    pending_tasks = get_str('pending_tasks', lang)
    tool_stats = get_str('tool_stats', lang)
    tool_header = get_str('tool_table_header', lang)
    tool_divider = get_str('tool_table_divider', lang)
    total_tool_calls = get_str('total_tool_calls', lang)
    times = get_str('times', lang)
    skill_usage = get_str('skill_usage', lang)
    most_used_skills = get_str('most_used_skills', lang)
    code_changes = get_str('code_changes', lang)
    code_header = get_str('code_table_header', lang)
    total_changes = get_str('total_changes', lang)
    lines = get_str('lines', lang)
    efficiency = get_str('efficiency', lang)
    avg_task_time = get_str('avg_task_time', lang)
    task_completion_rate = get_str('task_completion_rate', lang)
    skill_success_rate = get_str('skill_success_rate', lang)
    avg_tool_response = get_str('avg_tool_response', lang)
    work_summary = get_str('work_summary', lang)
    main_results = get_str('main_results', lang)
    next_plan = get_str('next_plan', lang)
    footer = get_str('footer', lang)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = OUTPUT_DIR / f"work_report_{timestamp}.md"

    # Task content based on language
    if lang == 'zh':
        task_content = """- [x] 数据导入和分析 (2/3 子任务完成)
- [x] 创建可视化脚本 (1/5 子任务完成)
- [ ] 测试和优化 (0/4 子任务完成)"""
        progress_content = """- 总体进度: 29%
- 已完成任务: 1
- 进行中任务: 2
- 待开始任务: 1"""
        results_content = """- ✓ 创建 work-visualization 技能包
- ✓ 配置可视化参数
- ✓ 完成核心脚本开发"""
        plan_content = """- [ ] 添加更多图表类型
- [ ] 实现实时监控功能
- [ ] 优化可视化效果"""
        metrics_content = """- 平均任务完成时间: 8.5 分钟
- 任务完成率: 92%
- 技能调用成功率: 98%
- 平均工具响应时间: 0.3 秒"""
        skills_content = """1. **terminal** - 15次
2. **file_operations** - 12次
3. **search** - 8次
4. **browser** - 5次
5. **memory** - 3次"""
        tool_rows = """| terminal | 28 | 40.6% |
| write_file | 15 | 21.7% |
| read_file | 12 | 17.4% |
| search_files | 8 | 11.6% |
| patch | 6 | 8.7% |"""
        code_rows = """| SKILL.md | +150 | -0 | 150 |
| config.json | +20 | -5 | 25 |
| scripts/session_summary.py | +85 | -12 | 97 |"""
    else:
        task_content = """- [x] Data import and analysis (2/3 subtasks completed)
- [x] Create visualization scripts (1/5 subtasks completed)
- [ ] Testing and optimization (0/4 subtasks completed)"""
        progress_content = """- Overall progress: 29%
- Completed tasks: 1
- In progress tasks: 2
- Pending tasks: 1"""
        results_content = """- ✓ Created work-visualization skill package
- ✓ Configured visualization parameters
- ✓ Completed core script development"""
        plan_content = """- [ ] Add more chart types
- [ ] Implement real-time monitoring
- [ ] Optimize visualization effects"""
        metrics_content = """- Avg task completion time: 8.5 minutes
- Task completion rate: 92%
- Skill call success rate: 98%
- Avg tool response time: 0.3 seconds"""
        skills_content = """1. **terminal** - 15 times
2. **file_operations** - 12 times
3. **search** - 8 times
4. **browser** - 5 times
5. **memory** - 3 times"""
        tool_rows = """| terminal | 28 | 40.6% |
| write_file | 15 | 21.7% |
| read_file | 12 | 17.4% |
| search_files | 8 | 11.6% |
| patch | 6 | 8.7% |"""
        code_rows = """| SKILL.md | +150 | -0 | 150 |
| config.json | +20 | -5 | 25 |
| scripts/session_summary.py | +85 | -12 | 97 |"""

    content = f"""# {title}

**{time_str}**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## {task_progress}

{current_tasks}
{task_content}

{progress_overview}
{progress_content}

## {tool_stats}

{tool_header}
{tool_divider}
{tool_rows}

{total_tool_calls}: 69{times}

## {skill_usage}

{most_used_skills}
{skills_content}

## {code_changes}

{code_header}
{code_rows}

{total_changes}: +255 -17{lines}

## {efficiency}

{metrics_content}

## {work_summary}

{main_results}
{results_content}

{next_plan}
{plan_content}

---

{footer}
"""

    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)

    return filename

def generate_json_report(lang=None):
    """生成JSON格式报告 / Generate JSON format report"""
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = OUTPUT_DIR / f"work_report_{timestamp}.json"

    report = {
        "language": lang or i18n.get_language(),
        "generated_at": datetime.now().isoformat(),
        "session": {
            "duration_minutes": 15,
            "start_time": datetime.now().isoformat(),
        },
        "tasks": {
            "total": 4,
            "completed": 1,
            "in_progress": 2,
            "pending": 1,
            "progress_percentage": 29
        },
        "tools": {
            "total_calls": 69,
            "by_tool": [
                {"name": "terminal", "count": 28, "percentage": 40.6},
                {"name": "write_file", "count": 15, "percentage": 21.7},
                {"name": "read_file", "count": 12, "percentage": 17.4},
                {"name": "search_files", "count": 8, "percentage": 11.6},
                {"name": "patch", "count": 6, "percentage": 8.7},
            ]
        },
        "skills": {
            "total_calls": 43,
            "top_skills": [
                {"name": "terminal", "count": 15},
                {"name": "file_operations", "count": 12},
                {"name": "search", "count": 8},
                {"name": "browser", "count": 5},
                {"name": "memory", "count": 3},
            ]
        },
        "code_changes": {
            "total_added": 255,
            "total_deleted": 17,
            "by_file": [
                {"name": "SKILL.md", "added": 150, "deleted": 0},
                {"name": "scripts/session_summary.py", "added": 85, "deleted": 12},
                {"name": "config.json", "added": 20, "deleted": 5},
            ]
        },
        "metrics": {
            "avg_task_duration_minutes": 8.5,
            "completion_rate": 0.92,
            "skill_success_rate": 0.98,
            "avg_tool_response_seconds": 0.3
        }
    }

    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    return filename

def generate_html_report(lang=None):
    """生成HTML格式报告 / Generate HTML format report"""
    if lang is None:
        lang = i18n.get_language()

    title = get_str('report_title', lang)
    time_str = get_str('generated_time', lang)
    task_progress = get_str('task_progress', lang)
    tool_stats = get_str('tool_stats', lang)
    total_tool_calls = get_str('total_tool_calls', lang)
    times = get_str('times', lang)
    efficiency = get_str('efficiency', lang)
    code_changes = get_str('code_changes', lang)
    total_changes = get_str('total_changes', lang)
    lines = get_str('lines', lang)
    footer = get_str('footer', lang)

    # HTML content based on language
    if lang == 'zh':
        lang_attr = "zh-CN"
        task_item1 = "数据导入和分析"
        task_item2 = "创建可视化脚本"
        task_item3 = "测试和优化"
        status_completed = "完成"
        status_progress = "进行中"
        status_pending = "待开始"
        overall_progress = "总体进度: 29%"
        tool_header = "<tr><th>工具</th><th>调用次数</th><th>占比</th></tr>"
        label_completion = "任务完成率"
        label_success = "技能成功率"
        label_avg_time = "平均任务时长(分钟)"
        label_response = "工具响应时间"
        code_header = "<tr><th>文件</th><th>新增</th><th>删除</th></tr>"
    else:
        lang_attr = "en"
        task_item1 = "Data import and analysis"
        task_item2 = "Create visualization scripts"
        task_item3 = "Testing and optimization"
        status_completed = "Completed"
        status_progress = "In Progress"
        status_pending = "Pending"
        overall_progress = "Overall progress: 29%"
        tool_header = "<tr><th>Tool</th><th>Call Count</th><th>Percentage</th></tr>"
        label_completion = "Task Completion Rate"
        label_success = "Skill Success Rate"
        label_avg_time = "Avg Task Duration(min)"
        label_response = "Tool Response Time"
        code_header = "<tr><th>File</th><th>Added</th><th>Deleted</th></tr>"

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = OUTPUT_DIR / f"work_report_{timestamp}.html"

    html = f"""<!DOCTYPE html>
<html lang="{lang_attr}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #1a1a2e;
            color: #eee;
            padding: 20px;
            line-height: 1.6;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
        }}
        h1 {{
            color: #4ecca3;
            margin-bottom: 10px;
        }}
        .timestamp {{
            color: #888;
            margin-bottom: 30px;
        }}
        .card {{
            background: #16213e;
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 20px;
            border-left: 4px solid #4ecca3;
        }}
        .card h2 {{
            color: #4ecca3;
            margin-bottom: 15px;
            font-size: 1.2em;
        }}
        .progress-bar {{
            background: #0f3460;
            height: 20px;
            border-radius: 10px;
            overflow: hidden;
            margin: 10px 0;
        }}
        .progress-fill {{
            background: #4ecca3;
            height: 100%;
            transition: width 0.3s;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }}
        th, td {{
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #0f3460;
        }}
        th {{
            background: #0f3460;
            color: #4ecca3;
        }}
        .stat-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin-top: 15px;
        }}
        .stat-box {{
            background: #0f3460;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }}
        .stat-value {{
            font-size: 2em;
            color: #4ecca3;
            font-weight: bold;
        }}
        .stat-label {{
            color: #888;
            font-size: 0.9em;
        }}
        .task-item {{
            padding: 10px 0;
            border-bottom: 1px solid #0f3460;
        }}
        .task-item:last-child {{
            border-bottom: none;
        }}
        .task-status {{
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 0.8em;
            margin-left: 10px;
        }}
        .status-completed {{ background: #4ecca3; color: #1a1a2e; }}
        .status-progress {{ background: #ffd700; color: #1a1a2e; }}
        .status-pending {{ background: #666; color: #fff; }}
        .footer {{
            text-align: center;
            color: #666;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #0f3460;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 {title}</h1>
        <p class="timestamp">{time_str}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

        <div class="card">
            <h2>{task_progress}</h2>
            <div class="progress-bar">
                <div class="progress-fill" style="width: 29%"></div>
            </div>
            <p>{overall_progress}</p>

            <div class="task-item">
                ✓ {task_item1} <span class="task-status status-completed">{status_completed}</span>
            </div>
            <div class="task-item">
                ⚙ {task_item2} <span class="task-status status-progress">{status_progress}</span>
            </div>
            <div class="task-item">
                ⚙ {task_item3} <span class="task-status status-pending">{status_pending}</span>
            </div>
        </div>

        <div class="card">
            <h2>{tool_stats}</h2>
            <table>
                {tool_header}
                <tr><td>terminal</td><td>28</td><td>40.6%</td></tr>
                <tr><td>write_file</td><td>15</td><td>21.7%</td></tr>
                <tr><td>read_file</td><td>12</td><td>17.4%</td></tr>
                <tr><td>search_files</td><td>8</td><td>11.6%</td></tr>
                <tr><td>patch</td><td>6</td><td>8.7%</td></tr>
            </table>
            <p style="margin-top: 10px;"><strong>{total_tool_calls}</strong>: 69{times}</p>
        </div>

        <div class="card">
            <h2>{efficiency}</h2>
            <div class="stat-grid">
                <div class="stat-box">
                    <div class="stat-value">92%</div>
                    <div class="stat-label">{label_completion}</div>
                </div>
                <div class="stat-box">
                    <div class="stat-value">98%</div>
                    <div class="stat-label">{label_success}</div>
                </div>
                <div class="stat-box">
                    <div class="stat-value">8.5</div>
                    <div class="stat-label">{label_avg_time}</div>
                </div>
                <div class="stat-box">
                    <div class="stat-value">0.3s</div>
                    <div class="stat-label">{label_response}</div>
                </div>
            </div>
        </div>

        <div class="card">
            <h2>{code_changes}</h2>
            <table>
                {code_header}
                <tr><td>SKILL.md</td><td style="color: #4ecca3;">+150</td><td>-0</td></tr>
                <tr><td>scripts/session_summary.py</td><td style="color: #4ecca3;">+85</td><td>-12</td></tr>
                <tr><td>config.json</td><td style="color: #4ecca3;">+20</td><td>-5</td></tr>
            </table>
            <p style="margin-top: 10px;"><strong>{total_changes}</strong>: +255 -17{lines}</p>
        </div>

        <div class="footer">
            <p>{footer}</p>
        </div>
    </div>
</body>
</html>
"""

    with open(filename, 'w', encoding='utf-8') as f:
        f.write(html)

    return filename

def main():
    """主函数 / Main function"""
    lang = os.environ.get('HERMES_LANG', os.environ.get('LANG', 'en'))[:2]
    generating = get_str('generating', lang)
    report_directory = get_str('report_directory', lang)
    completed = get_str('completed', lang)

    parser = argparse.ArgumentParser(description='Export work report')
    parser.add_argument('--format', choices=['markdown', 'json', 'html', 'all'], default='html',
                       help='Output format: markdown/json/html/all')
    parser.add_argument('--lang', type=str, choices=['zh', 'en'], help='Override language (zh/en)')
    parser.add_argument('--open', action='store_true', help='Auto open after generation')

    args = parser.parse_args()

    # Override language if specified
    if args.lang:
        lang = args.lang

    print(f"\n{generating}\n")

    files = []

    if args.format in ['markdown', 'all']:
        file = generate_markdown_report(lang)
        files.append(file)
        print(f"✅ Markdown report: {file}")

    if args.format in ['json', 'all']:
        file = generate_json_report(lang)
        files.append(file)
        print(f"✅ JSON report: {file}")

    if args.format in ['html', 'all']:
        file = generate_html_report(lang)
        files.append(file)
        print(f"✅ HTML report: {file}")

    if args.open and files:
        import subprocess
        for file in files:
            try:
                subprocess.run(['xdg-open', str(file)], check=False)
            except:
                pass

    print(f"\n📁 {report_directory}: {OUTPUT_DIR}")
    print(f"✨ {completed}\n")

if __name__ == "__main__":
    main()
