#!/usr/bin/env python3
"""
generate_mcp_server.py — MCP Server Generator (M5)

Reads graph.json + embeddings/ from the output directory and writes a
fully self-contained MCP server (server.py) to that same directory.

The generated server exposes 8 tools:
  search            Semantic search over chunk content
  get_concept       Look up a concept and its related chunks
  get_related       Find related concepts via graph edges
  get_learning_path Shortest path between two concepts in the knowledge graph
  get_prerequisites List prerequisites for a concept
  get_examples      Find code examples for a concept
  list_concepts     List all indexed concepts (optionally filtered by tag)
  get_page          Return all chunks for a given page URL

Usage:
    python scripts/generate_mcp_server.py --input ./output/strudel-cc-mcp
    python scripts/generate_mcp_server.py --input ./output/strudel-cc-mcp \\
        --model all-MiniLM-L6-v2 --force
"""

import argparse
import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Introspect the output directory to derive config values
# ---------------------------------------------------------------------------

def _infer_config(input_dir: Path, model: str) -> dict:
    """Return a config dict derived from graph.json + the --model flag."""
    graph_path = input_dir / "graph.json"
    if not graph_path.exists():
        print(f"WARNING: graph.json not found — run build_graph.py first", file=sys.stderr)
        stats = {"pages": 0, "chunks": 0, "concepts": 0}
    else:
        meta = json.loads(graph_path.read_text()).get("meta", {})
        stats = meta.get("stats", {})

    # Derive a human-readable topic from the folder name
    # e.g. "strudel-cc-mcp" → "strudel-cc"
    slug = input_dir.name
    if slug.endswith("-mcp"):
        slug = slug[:-4]
    topic = slug.replace("-", " ").replace("_", " ").title()

    return {
        "topic":           topic,
        "slug":            slug,
        "embedding_model": model,
        "stats":           stats,
    }


# ---------------------------------------------------------------------------
# Server template
# ---------------------------------------------------------------------------

_SERVER_TEMPLATE = '''\
#!/usr/bin/env python3
"""
MCP Knowledge Server: {topic}

Auto-generated by GraphRAGBuilderSkill.

This server exposes the following tools:
  search            Semantic search over all indexed content
  get_concept       Look up a concept + its related chunks
  get_related       Find related concepts via graph edges
  get_learning_path Shortest concept path between two topics
  get_prerequisites List prerequisite concepts
  get_examples      Find code examples for a concept
  list_concepts     List all indexed concepts (optionally filtered)
  get_page          Return all chunks for a given page URL

Add to Claude Desktop config (~/Library/Application Support/Claude/claude_desktop_config.json):

  "mcpServers": {{
    "{slug}": {{
      "command": "python",
      "args": ["/absolute/path/to/{slug}-mcp/server.py"]
    }}
  }}

Run standalone:
  python server.py
"""

import asyncio
import json
import os
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration — paths are relative to this file\'s location
# ---------------------------------------------------------------------------

TOPIC = {topic!r}
EMBEDDING_MODEL = {embedding_model!r}
BASE_DIR = Path(__file__).parent.resolve()
GRAPH_JSON = BASE_DIR / "graph.json"
EMBEDDINGS_DIR = BASE_DIR / "embeddings"

# ---------------------------------------------------------------------------
# Dependency bootstrap
# ---------------------------------------------------------------------------

def _install(pkg):
    print(f"Installing {{pkg}}...", file=sys.stderr)
    os.system(f"pip install {{pkg}} --break-system-packages -q")

def _import_ok(mod):
    try:
        __import__(mod)
        return True
    except ImportError:
        return False

for mod, pkg in [("mcp", "mcp"), ("networkx", "networkx"),
                  ("numpy", "numpy"),
                  ("sentence_transformers", "sentence-transformers")]:
    if not _import_ok(mod):
        _install(pkg)

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp import types
import networkx as nx
import numpy as np
from sentence_transformers import SentenceTransformer

# ---------------------------------------------------------------------------
# Load resources at startup
# ---------------------------------------------------------------------------

def _load_graph() -> nx.MultiDiGraph:
    if not GRAPH_JSON.exists():
        print(f"WARNING: {{GRAPH_JSON}} not found — graph tools will be limited",
              file=sys.stderr)
        return nx.MultiDiGraph()
    data = json.loads(GRAPH_JSON.read_text())
    return nx.node_link_graph(data, edges="edges")


def _load_embeddings():
    """Load numpy embedding index. Returns (model, chunk_matrix, chunk_index,
    concept_matrix, concept_index) or (None, ...) if not available."""
    meta_path = EMBEDDINGS_DIR / "meta.json"
    if not EMBEDDINGS_DIR.exists() or not meta_path.exists():
        print(f"WARNING: {{EMBEDDINGS_DIR}} not found — run build_embeddings.py first",
              file=sys.stderr)
        return None, None, None, None, None
    try:
        model         = SentenceTransformer(EMBEDDING_MODEL)
        chunk_matrix  = np.load(EMBEDDINGS_DIR / "chunks.npy")
        chunk_index   = json.loads((EMBEDDINGS_DIR / "chunks.json").read_text())
        concept_matrix = np.load(EMBEDDINGS_DIR / "concepts.npy")
        concept_index  = json.loads((EMBEDDINGS_DIR / "concepts.json").read_text())
        return model, chunk_matrix, chunk_index, concept_matrix, concept_index
    except Exception as e:
        print(f"WARNING: Could not load embeddings: {{e}}", file=sys.stderr)
        return None, None, None, None, None


def _vec_search(query: str, model, matrix, index, n: int = 5) -> list[tuple]:
    """Cosine similarity search. Returns [(meta_dict, score), ...]."""
    qv = model.encode([query], convert_to_numpy=True).astype(np.float32)
    qv = qv / np.maximum(np.linalg.norm(qv), 1e-8)
    scores = matrix @ qv[0]
    top = np.argsort(scores)[::-1][:n]
    return [(index[i], float(scores[i])) for i in top]


print(f"Loading {{TOPIC}} knowledge graph...", file=sys.stderr)
G = _load_graph()
_emb_model, _chunk_mat, _chunk_idx, _concept_mat, _concept_idx = _load_embeddings()
print(
    f"Ready: {{G.number_of_nodes()}} nodes, {{G.number_of_edges()}} edges",
    file=sys.stderr,
)

# ---------------------------------------------------------------------------
# Concept node helpers
# ---------------------------------------------------------------------------

def _norm(name: str) -> str:
    name = name.strip()
    name = re.sub(r\'\\(\\s*\\)$\', \'\', name)
    name = name.lower()
    name = re.sub(r\'[ _\\-]+\', \' \', name)
    return re.sub(r\'\\s+\', \' \', name).strip().rstrip(\'.,;:\')


def _concept_id(name: str) -> str:
    return f"concept:{{_norm(name)}}"


def _concept_data(name: str) -> dict | None:
    cid = _concept_id(name)
    if G.has_node(cid):
        return dict(G.nodes[cid])
    # Semantic fallback: find closest concept by embedding
    if _emb_model is not None and _concept_mat is not None:
        hits = _vec_search(name, _emb_model, _concept_mat, _concept_idx, n=1)
        if hits and hits[0][1] > 0.7:
            norm = hits[0][0].get("norm_name", "")
            node_id = f"concept:{{norm}}"
            if G.has_node(node_id):
                return dict(G.nodes[node_id])
    return None


def _chunks_for_concept(concept_id: str) -> list[dict]:
    """Return chunk node dicts that MENTION this concept."""
    chunks = []
    for pred, _, d in G.in_edges(concept_id, data=True):
        if d.get("type") in ("MENTIONS", "REQUIRES") and G.nodes[pred].get("type") == "chunk":
            chunks.append(dict(G.nodes[pred]))
    return chunks


# ---------------------------------------------------------------------------
# Tool implementations
# ---------------------------------------------------------------------------

def _tool_search(query: str, n_results: int = 5) -> list[dict]:
    if _emb_model is None or _chunk_mat is None:
        return [{{"error": "Embedding index not available. Run build_embeddings.py first."}}]
    results = []
    for meta, score in _vec_search(query, _emb_model, _chunk_mat, _chunk_idx, n=n_results):
        # Retrieve full text from graph node if available
        chunk_node = G.nodes.get(meta.get("id", ""), {{}})
        text = chunk_node.get("text", "")
        results.append({{
            "score":      round(score, 3),
            "section":    meta.get("section", ""),
            "page_title": meta.get("page_title", ""),
            "url":        meta.get("url", ""),
            "tags":       meta.get("tags", ""),
            "has_code":   meta.get("has_code", False),
            "text":       text[:500] + ("..." if len(text) > 500 else ""),
        }})
    return results


def _tool_get_concept(name: str) -> dict:
    data = _concept_data(name)
    if not data:
        return {{"error": f"Concept {{name!r}} not found. Try list_concepts() to browse."}}
    cid = f"concept:{{_norm(name)}}"
    chunks = _chunks_for_concept(cid)
    return {{
        "name":          data.get("name", name),
        "description":   data.get("description", ""),
        "mention_count": data.get("mention_count", 0),
        "chunks": [
            {{
                "section":  c.get("section", ""),
                "url":      c.get("url", ""),
                "text":     c.get("text", "")[:400],
                "has_code": bool(c.get("code_examples")),
            }}
            for c in chunks[:5]
        ],
    }}


def _tool_get_related(concept: str, n: int = 5) -> list[dict]:
    cid = _concept_id(concept)
    if not G.has_node(cid):
        return [{{"error": f"Concept {{concept!r}} not found."}}]
    related = []
    # Outgoing RELATED edges (concept → other_concept)
    for _, tgt, d in G.out_edges(cid, data=True):
        if d.get("type") == "RELATED" and G.nodes[tgt]["type"] == "concept":
            tgt_data = G.nodes[tgt]
            related.append({{
                "name":        tgt_data.get("name", tgt),
                "description": tgt_data.get("description", ""),
                "relation":    d.get("relation", "related_to"),
                "direction":   "→",
            }})
    # Incoming RELATED edges (other_concept → concept)
    for src, _, d in G.in_edges(cid, data=True):
        if d.get("type") == "RELATED" and G.nodes[src]["type"] == "concept":
            src_data = G.nodes[src]
            related.append({{
                "name":        src_data.get("name", src),
                "description": src_data.get("description", ""),
                "relation":    d.get("relation", "related_to"),
                "direction":   "←",
            }})
    return related[:n]


def _tool_get_learning_path(start: str, goal: str) -> dict:
    start_id = _concept_id(start)
    goal_id  = _concept_id(goal)
    if not G.has_node(start_id):
        return {{"error": f"Start concept {{start!r}} not found."}}
    if not G.has_node(goal_id):
        return {{"error": f"Goal concept {{goal!r}} not found."}}
    try:
        path = nx.shortest_path(G, start_id, goal_id)
        return {{
            "path": [G.nodes[n].get("name", n) for n in path],
            "length": len(path) - 1,
        }}
    except nx.NetworkXNoPath:
        return {{"error": f"No path found from {{start!r}} to {{goal!r}}."}}
    except nx.NodeNotFound as e:
        return {{"error": str(e)}}


def _tool_get_prerequisites(concept: str) -> list[str]:
    cid = _concept_id(concept)
    if not G.has_node(cid):
        return [f"Concept {{concept!r}} not found."]
    prereqs = set()
    # Find chunks that REQUIRE this concept
    for src, _, d in G.in_edges(cid, data=True):
        if d.get("type") == "REQUIRES" and G.nodes[src]["type"] == "chunk":
            # Also look at what OTHER concepts are required by the same chunks
            for _, tgt2, d2 in G.out_edges(src, data=True):
                if (d2.get("type") == "REQUIRES"
                        and tgt2 != cid
                        and G.nodes[tgt2]["type"] == "concept"):
                    prereqs.add(G.nodes[tgt2].get("name", tgt2))
    return sorted(prereqs)


def _tool_get_examples(concept: str) -> list[dict]:
    chunks = _chunks_for_concept(_concept_id(concept))
    examples = []
    for chunk in chunks:
        for ex in chunk.get("code_examples", []):
            examples.append({{
                "code":        ex.get("code", ""),
                "description": ex.get("description", ""),
                "source":      chunk.get("section", ""),
                "url":         chunk.get("url", ""),
            }})
    return examples[:10]


def _tool_list_concepts(tag: str = "", limit: int = 20) -> list[dict]:
    results = []
    for nid, data in G.nodes(data=True):
        if data.get("type") != "concept":
            continue
        # Tag filter: check chunks that mention this concept
        if tag:
            chunk_tags = []
            for chunk_data in _chunks_for_concept(nid):
                raw = chunk_data.get("tags", [])
                if isinstance(raw, str):
                    chunk_tags += [t.strip() for t in raw.split(",")]
                else:
                    chunk_tags += raw
            if tag.lower() not in [t.lower() for t in chunk_tags]:
                continue
        results.append({{
            "name":          data.get("name", nid),
            "description":   data.get("description", "")[:120],
            "mention_count": data.get("mention_count", 0),
        }})
    results.sort(key=lambda x: -x["mention_count"])
    return results[:limit]


def _tool_get_page(url: str) -> dict:
    page_id = f"page:{{url}}"
    if not G.has_node(page_id):
        # Try prefix match
        matches = [n for n in G.nodes if n.startswith("page:") and url in n]
        if not matches:
            return {{"error": f"Page {{url!r}} not found."}}
        page_id = matches[0]
    page_data = dict(G.nodes[page_id])
    chunks = []
    for _, chunk_id, d in G.out_edges(page_id, data=True):
        if d.get("type") == "HAS_CHUNK":
            cdata = dict(G.nodes[chunk_id])
            chunks.append({{
                "section":       cdata.get("section", ""),
                "text":          cdata.get("text", "")[:600],
                "word_count":    cdata.get("word_count", 0),
                "tags":          cdata.get("tags", []),
                "has_code":      bool(cdata.get("code_examples")),
            }})
    return {{
        "url":    page_data.get("url", url),
        "title":  page_data.get("title", ""),
        "chunks": chunks,
    }}


# ---------------------------------------------------------------------------
# MCP server definition
# ---------------------------------------------------------------------------

server = Server(f"{{TOPIC.lower().replace(' ', '-')}}-knowledge")


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(
            name="search",
            description=(
                f"Semantic search over all {{TOPIC}} documentation and tutorials. "
                "Returns the most relevant content sections for a natural-language query."
            ),
            inputSchema={{
                "type": "object",
                "properties": {{
                    "query":     {{"type": "string",  "description": "What to search for"}},
                    "n_results": {{"type": "integer", "description": "Max results (default 5)", "default": 5}},
                }},
                "required": ["query"],
            }},
        ),
        types.Tool(
            name="get_concept",
            description=(
                f"Look up a {{TOPIC}} concept by name. Returns its description, "
                "mention count, and the content chunks where it appears."
            ),
            inputSchema={{
                "type": "object",
                "properties": {{
                    "name": {{"type": "string", "description": "Concept name to look up"}},
                }},
                "required": ["name"],
            }},
        ),
        types.Tool(
            name="get_related",
            description=(
                "Find concepts related to a given concept via the knowledge graph. "
                "Returns directed relationships extracted from the documentation."
            ),
            inputSchema={{
                "type": "object",
                "properties": {{
                    "concept": {{"type": "string"}},
                    "n":       {{"type": "integer", "default": 5}},
                }},
                "required": ["concept"],
            }},
        ),
        types.Tool(
            name="get_learning_path",
            description=(
                "Find the shortest conceptual path between two topics. "
                "Useful for planning what to learn in order to understand a target concept."
            ),
            inputSchema={{
                "type": "object",
                "properties": {{
                    "start": {{"type": "string", "description": "Starting concept"}},
                    "goal":  {{"type": "string", "description": "Target concept to reach"}},
                }},
                "required": ["start", "goal"],
            }},
        ),
        types.Tool(
            name="get_prerequisites",
            description="List concepts that are prerequisites for understanding a given concept.",
            inputSchema={{
                "type": "object",
                "properties": {{
                    "concept": {{"type": "string"}},
                }},
                "required": ["concept"],
            }},
        ),
        types.Tool(
            name="get_examples",
            description=(
                f"Find code examples related to a {{TOPIC}} concept. "
                "Returns runnable code snippets with descriptions."
            ),
            inputSchema={{
                "type": "object",
                "properties": {{
                    "concept": {{"type": "string"}},
                }},
                "required": ["concept"],
            }},
        ),
        types.Tool(
            name="list_concepts",
            description=(
                f"List all indexed {{TOPIC}} concepts, sorted by how often they appear "
                "in the documentation. Optionally filter by topic tag."
            ),
            inputSchema={{
                "type": "object",
                "properties": {{
                    "tag":   {{"type": "string",  "description": "Filter by tag (optional)"}},
                    "limit": {{"type": "integer", "description": "Max results (default 20)", "default": 20}},
                }},
            }},
        ),
        types.Tool(
            name="get_page",
            description=(
                f"Return all content chunks for a specific {{TOPIC}} documentation page, "
                "identified by URL."
            ),
            inputSchema={{
                "type": "object",
                "properties": {{
                    "url": {{"type": "string", "description": "Page URL"}},
                }},
                "required": ["url"],
            }},
        ),
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent]:
    result: object

    if name == "search":
        result = _tool_search(
            arguments["query"],
            int(arguments.get("n_results", 5)),
        )
    elif name == "get_concept":
        result = _tool_get_concept(arguments["name"])
    elif name == "get_related":
        result = _tool_get_related(
            arguments["concept"],
            int(arguments.get("n", 5)),
        )
    elif name == "get_learning_path":
        result = _tool_get_learning_path(arguments["start"], arguments["goal"])
    elif name == "get_prerequisites":
        result = _tool_get_prerequisites(arguments["concept"])
    elif name == "get_examples":
        result = _tool_get_examples(arguments["concept"])
    elif name == "list_concepts":
        result = _tool_list_concepts(
            arguments.get("tag", ""),
            int(arguments.get("limit", 20)),
        )
    elif name == "get_page":
        result = _tool_get_page(arguments["url"])
    else:
        result = {{"error": f"Unknown tool: {{name}}"}}

    return [types.TextContent(type="text", text=json.dumps(result, indent=2))]


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

async def _main():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options(),
        )


if __name__ == "__main__":
    asyncio.run(_main())
'''


# ---------------------------------------------------------------------------
# Claude Desktop config snippet
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
{{
  "mcpServers": {{
    "{slug}": {{
      "command": "{python_cmd}",
      "args": ["{server_path}"]
    }}
  }}
}}
"""


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------

def generate(input_dir: Path, model: str, force: bool = False):
    server_path = input_dir / "server.py"
    config_path = input_dir / "mcp_config.json"

    if server_path.exists() and not force:
        print(f"server.py already exists. Use --force to overwrite.")
        sys.exit(0)

    cfg = _infer_config(input_dir, model)

    # Fill template
    server_code = _SERVER_TEMPLATE.format(
        topic=cfg["topic"],
        slug=cfg["slug"],
        embedding_model=cfg["embedding_model"],
    )
    server_path.write_text(server_code)

    # Write config snippet — use sys.executable so the venv Python is baked in
    config_json = _CONFIG_TEMPLATE.format(
        slug=cfg["slug"],
        server_path=server_path.resolve(),
        python_cmd=sys.executable,
    )
    config_path.write_text(config_json)

    stats = cfg["stats"]
    print()
    print("━" * 62)
    print("  MCP server generated!")
    print(f"  Topic:   {cfg['topic']}")
    print(f"  Server:  {server_path}")
    print(f"  Config:  {config_path}")
    print()
    print(f"  Graph:   {stats.get('pages', '?')} pages, "
          f"{stats.get('chunks', '?')} chunks, "
          f"{stats.get('concepts', '?')} concepts")
    print()
    print("  Next steps:")
    print(f"  1. Add the contents of mcp_config.json to:")
    print(f"     ~/Library/Application Support/Claude/claude_desktop_config.json")
    print(f"  2. Restart Claude Desktop")
    print(f"  3. The '{cfg['slug']}' MCP server will appear in Claude's tool list")
    print("━" * 62)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate a self-contained MCP server from the graph + embeddings (M5)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--input", required=True, metavar="DIR",
                        help="MCP output dir (e.g. ./output/strudel-cc-mcp)")
    parser.add_argument("--model", default="all-MiniLM-L6-v2", metavar="MODEL",
                        help="Embedding model used in M4 (default: all-MiniLM-L6-v2)")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing server.py")
    args = parser.parse_args()

    input_dir = Path(args.input)
    if not input_dir.exists():
        print(f"ERROR: Input directory not found: {input_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Generating MCP server for: {input_dir.name}")
    generate(input_dir, model=args.model, force=args.force)


if __name__ == "__main__":
    main()
