/**
 * SAP Journal Auditor - Report Generator
 * Generates professional Markdown audit memos from findings.
 *
 * @author Daryoosh Dehestani (https://github.com/dda-oo)
 * @organization RadarRoster (https://radarroster.com)
 * @license CC-BY-4.0
 *
 * Features:
 *   - English and German output
 *   - Executive summary with risk assessment
 *   - Detailed findings table with recommendations
 *   - Professional formatting for management review
 */

"use strict";

const riskEmoji = { CRITICAL: "🔴", HIGH: "🟠", MEDIUM: "🟡", LOW: "🔵", CLEAN: "🟢" };
const riskLabel = {
  en: { CRITICAL: "CRITICAL", HIGH: "HIGH", MEDIUM: "MEDIUM", LOW: "LOW", CLEAN: "CLEAN" },
  de: { CRITICAL: "KRITISCH", HIGH: "HOCH", MEDIUM: "MITTEL", LOW: "NIEDRIG", CLEAN: "UNAUFFÄLLIG" },
};

function fmt(date) {
  if (!date) return "—";
  if (typeof date === "string") return date;
  return date.toISOString().slice(0, 10);
}

function fmtAmount(amount, currency) {
  if (amount === null || amount === undefined) return "—";
  return `${Number(amount).toLocaleString("de-DE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currency || "EUR"}`;
}

function generateMemo(auditResults, entries, options = {}) {
  const lang = options.language === "de" ? "de" : "en";
  const period = options.period || null;
  const now = new Date().toISOString().slice(0, 10);
  const { findings, overallRisk, checksSummary } = auditResults;

  const t = {
    en: {
      title: "SAP FI/CO Journal Entry Audit Report",
      subtitle: "Generated by SAP Journal Auditor (RadarRoster)",
      meta_date: "Audit Date",
      meta_period: "Period Analyzed",
      meta_entries: "Total Entries Analyzed",
      meta_findings: "Total Findings",
      meta_risk: "Overall Risk Level",
      sec_exec: "Executive Summary",
      sec_findings: "Audit Findings",
      sec_summary: "Findings by Check Category",
      sec_recs: "Recommendations",
      sec_footer: "Disclaimer",
      col_id: "ID",
      col_type: "Check Type",
      col_doc: "Document(s)",
      col_amount: "Amount",
      col_account: "Account",
      col_cc: "Cost Center",
      col_date: "Posting Date",
      col_user: "User",
      col_risk: "Risk",
      col_desc: "Description",
      no_findings: "✅ No anomalies detected. The journal entries appear to be within normal parameters.",
      footer_text:
        "This report was generated automatically by SAP Journal Auditor, an open-source OpenClaw skill by RadarRoster. " +
        "All flagged items require human review before any corrective action is taken. " +
        "This tool analyzes exported data only and does not access live SAP systems. " +
        "Consult your internal audit team or controller for HIGH and CRITICAL findings.",
      all_periods: "All periods in file",
      check_labels: {
        duplicates: "Duplicate Postings",
        roundAmounts: "Round Amount / Period-End",
        costCenterMismatch: "Unusual Cost Center Assignments",
        approvalBypass: "Approval Bypass / Missing Documentation",
        intercompany: "Intercompany / GR-IR Clearing",
        userPatterns: "User Pattern Anomalies",
      },
    },
    de: {
      title: "SAP FI/CO Buchungsbeleg-Prüfbericht",
      subtitle: "Erstellt durch SAP Journal Auditor (RadarRoster)",
      meta_date: "Prüfdatum",
      meta_period: "Analysierte Periode",
      meta_entries: "Analysierte Buchungszeilen",
      meta_findings: "Gesamtbefunde",
      meta_risk: "Gesamtrisiko",
      sec_exec: "Zusammenfassung",
      sec_findings: "Prüfungsbefunde",
      sec_summary: "Befunde nach Prüfkategorie",
      sec_recs: "Handlungsempfehlungen",
      sec_footer: "Hinweis",
      col_id: "Nr.",
      col_type: "Prüfart",
      col_doc: "Belegnummer(n)",
      col_amount: "Betrag",
      col_account: "Konto",
      col_cc: "Kostenstelle",
      col_date: "Buchungsdatum",
      col_user: "Benutzer",
      col_risk: "Risiko",
      col_desc: "Beschreibung",
      no_findings: "✅ Keine Auffälligkeiten festgestellt. Die Buchungsbelege liegen im normalen Bereich.",
      footer_text:
        "Dieser Bericht wurde automatisch durch SAP Journal Auditor erstellt, ein Open-Source-OpenClaw-Skill von RadarRoster. " +
        "Alle markierten Positionen bedürfen einer menschlichen Überprüfung vor einer Korrekturmaßnahme. " +
        "Das Tool analysiert ausschließlich exportierte Daten und hat keinen Zugriff auf Live-SAP-Systeme. " +
        "Bitte konsultieren Sie Ihre Interne Revision oder den zuständigen Controller bei HOCH- und KRITISCH-Befunden.",
      all_periods: "Alle Perioden in der Datei",
      check_labels: {
        duplicates: "Doppelbuchungen",
        roundAmounts: "Runde Beträge / Periodenende",
        costCenterMismatch: "Ungewöhnliche Kostenstellenzuordnungen",
        approvalBypass: "Freigabe-Umgehung / Fehlende Dokumentation",
        intercompany: "Konzernverrechnungen / WE/RE-Abstimmung",
        userPatterns: "Benutzer-Anomalien",
      },
    },
  }[lang];

  // ── Executive summary sentences ──────────────────────────────────────────
  const critical = findings.filter((f) => f.risk === "CRITICAL").length;
  const high = findings.filter((f) => f.risk === "HIGH").length;
  const medium = findings.filter((f) => f.risk === "MEDIUM").length;
  const low = findings.filter((f) => f.risk === "LOW").length;

  let execSummary;
  if (lang === "de") {
    execSummary =
      `Es wurden **${entries.length} Buchungszeilen** analysiert. ` +
      (findings.length === 0
        ? "Es wurden keine Auffälligkeiten festgestellt."
        : `Die Analyse ergab **${findings.length} Befunde** (${critical} kritisch, ${high} hoch, ${medium} mittel, ${low} niedrig). ` +
          `Das Gesamtrisiko wird als **${riskLabel.de[overallRisk]}** eingestuft. `) +
      (high + critical > 0
        ? `Befunde mit hohem oder kritischem Risiko erfordern unmittelbare Aufmerksamkeit des Controllers oder der Internen Revision.`
        : `Es werden keine unmittelbaren Maßnahmen für hoch- oder kritisch eingestufte Positionen benötigt.`);
  } else {
    execSummary =
      `A total of **${entries.length} journal lines** were analyzed. ` +
      (findings.length === 0
        ? "No anomalies were detected."
        : `The audit identified **${findings.length} findings** (${critical} critical, ${high} high, ${medium} medium, ${low} low). ` +
          `The overall risk level is rated **${riskLabel.en[overallRisk]}**. `) +
      (high + critical > 0
        ? `High and critical findings require immediate attention from the controller or internal audit team.`
        : `No immediate action is required for high or critical items.`);
  }

  // ── Recommendations ──────────────────────────────────────────────────────
  const topFindings = findings.filter((f) => ["CRITICAL", "HIGH"].includes(f.risk)).slice(0, 10);
  const recsSection =
    topFindings.length === 0
      ? lang === "de"
        ? "_Keine dringenden Maßnahmen erforderlich._"
        : "_No urgent actions required._"
      : topFindings.map((f, i) => `${i + 1}. **[${f.id}]** ${f.recommendation}`).join("\n");

  // ── Findings table ───────────────────────────────────────────────────────
  let findingsSection;
  if (findings.length === 0) {
    findingsSection = t.no_findings;
  } else {
    const header = `| ${t.col_id} | ${t.col_risk} | ${t.col_type} | ${t.col_doc} | ${t.col_amount} | ${t.col_account} | ${t.col_cc} | ${t.col_date} | ${t.col_user} |\n` +
      `|---|---|---|---|---|---|---|---|---|\n`;

    const rows = findings.map((f) =>
      `| ${f.id} | ${riskEmoji[f.risk]} ${riskLabel[lang][f.risk]} | ${f.checkType} | ${(f.docNumbers || []).slice(0, 2).join(", ")} | ${fmtAmount(f.amount, f.currency)} | ${f.account || "—"} | ${f.costCenter || "—"} | ${fmt(f.postingDate)} | ${f.user || "—"} |`
    ).join("\n");

    findingsSection = header + rows;

    // Detailed descriptions
    findingsSection += "\n\n### " + (lang === "de" ? "Detailbeschreibungen" : "Finding Details") + "\n\n";
    for (const f of findings) {
      findingsSection +=
        `**${f.id}** — ${riskEmoji[f.risk]} ${riskLabel[lang][f.risk]}: ${f.checkType}\n\n` +
        `> ${f.description}\n\n` +
        `_${lang === "de" ? "Empfehlung" : "Recommendation"}: ${f.recommendation}_\n\n---\n\n`;
    }
  }

  // ── Summary by category ──────────────────────────────────────────────────
  const summaryRows = Object.entries(checksSummary)
    .map(([key, count]) => `| ${t.check_labels[key] || key} | ${count} |`)
    .join("\n");

  const summaryTable =
    `| ${lang === "de" ? "Prüfkategorie" : "Check Category"} | ${lang === "de" ? "Befunde" : "Findings"} |\n` +
    `|---|---|\n` +
    summaryRows;

  // ── Assemble full memo ───────────────────────────────────────────────────
  return `# ${t.title}
_${t.subtitle}_

---

## ${lang === "de" ? "Metadaten" : "Metadata"}

| | |
|---|---|
| **${t.meta_date}** | ${now} |
| **${t.meta_period}** | ${period || t.all_periods} |
| **${t.meta_entries}** | ${entries.length} |
| **${t.meta_findings}** | ${findings.length} |
| **${t.meta_risk}** | ${riskEmoji[overallRisk]} ${riskLabel[lang][overallRisk]} |

---

## ${t.sec_exec}

${execSummary}

---

## ${t.sec_summary}

${summaryTable}

---

## ${t.sec_findings}

${findingsSection}

---

## ${t.sec_recs}

${recsSection}

---

## ${t.sec_footer}

_${t.footer_text}_

---
*SAP Journal Auditor v1.0.0 — [github.com/dda-oo/sap-journal-auditor](https://github.com/dda-oo/sap-journal-auditor) — Built by [RadarRoster](https://radarroster.com)*
`;
}

module.exports = { generateMemo };
