#!/usr/bin/env python3
"""Unified map-reference resolution for de-anonymization flows."""

from __future__ import annotations

from pathlib import Path
from typing import Optional, Tuple

from modeio_redact.workflow.file_workflow import extract_embedded_map_id, read_sidecar_map_reference
from modeio_redact.workflow.map_store import MapStoreError


def resolve_map_reference(
    *,
    explicit_map: Optional[str],
    input_type: str,
    input_path: Optional[str],
    input_content: str,
) -> Tuple[Optional[str], str]:
    """Resolve map reference using explicit, embedded, sidecar, then latest fallback."""
    if explicit_map:
        return explicit_map, "explicit-map"

    if input_type == "file" and input_path:
        embedded_map_id = extract_embedded_map_id(input_content)
        if embedded_map_id:
            return embedded_map_id, "embedded-mapid"

        try:
            sidecar_ref, _ = read_sidecar_map_reference(Path(input_path).expanduser())
        except ValueError as error:
            raise MapStoreError(str(error)) from error

        if sidecar_ref:
            return sidecar_ref, "sidecar"

        raise MapStoreError(
            "no map reference found for file input; provide --map or use file generated by anonymize"
        )

    return None, "latest-fallback"
