#!/usr/bin/env python3
"""
protein-struct-viz: Generate PyMOL scripts for highlighting specific protein residues.

Usage:
    python main.py --pdb <pdb_file_or_id> --residues <residue_list> [options]

Example:
    python main.py --pdb 1mbn --residues "A:64:HIS,A:93:VAL" --style sticks --output result.pml
"""

import argparse
import sys
from pathlib import Path
from typing import List, Tuple, Optional


class PyMOLScriptGenerator:
    """Generate PyMOL scripts for protein residue visualization."""
    
    # Predefined color schemes
    COLOR_SCHEMES = {
        "rainbow": "cmd.spectrum()",
        "chain": "cmd.color('chainbow', 'all')",
        "element": "util.cbc()",
        "secondary": "cmd.dss(); cmd.color('secondary', 'all')",
        "gray": "cmd.color('gray70', 'all')",
        "white": "cmd.color('white', 'all')",
        "blue_red": "cmd.spectrum('b', 'blue_red')",
    }
    
    # Standard residue colors for highlighting
    RESIDUE_COLORS = [
        "red", "blue", "green", "yellow", "magenta", "cyan",
        "orange", "salmon", "lime", "pink", "slate", "teal"
    ]
    
    def __init__(self, pdb_source: str, residues: List[str], style: str = "sticks",
                 color_scheme: str = "gray", highlight_colors: Optional[List[str]] = None,
                 output: str = "output.pml", ray_trace: bool = False):
        """
        Initialize the generator.
        
        Args:
            pdb_source: PDB file path or PDB ID
            residues: List of residue specifications (chain:resnum:resname)
            style: Visualization style for highlighted residues
            color_scheme: Global color scheme
            highlight_colors: Custom colors for highlighted residues
            output: Output script filename
            ray_trace: Include ray tracing commands for high-quality images
        """
        self.pdb_source = pdb_source
        self.residues = residues
        self.style = style
        self.color_scheme = color_scheme
        self.highlight_colors = highlight_colors or self.RESIDUE_COLORS
        self.output = output
        self.ray_trace = ray_trace
        
    def _parse_residue(self, residue_spec: str) -> Tuple[Optional[str], str, Optional[str]]:
        """
        Parse residue specification.
        
        Formats supported:
            - chain:resnum:resname (A:145:ASP)
            - chain:resnum (A:145)
            - resnum (145 - assumes chain A or first chain)
            
        Returns:
            Tuple of (chain, resnum, resname)
        """
        parts = residue_spec.split(":")
        
        if len(parts) == 3:
            return parts[0], parts[1], parts[2]
        elif len(parts) == 2:
            return parts[0], parts[1], None
        elif len(parts) == 1:
            return None, parts[0], None
        else:
            raise ValueError(f"Invalid residue specification: {residue_spec}")
    
    def _generate_selection_string(self, chain: Optional[str], resnum: str, 
                                   resname: Optional[str]) -> str:
        """Generate PyMOL selection string for a residue."""
        parts = []
        if chain:
            parts.append(f"chain {chain}")
        parts.append(f"resi {resnum}")
        if resname:
            parts.append(f"resn {resname}")
        return " and ".join(parts)
    
    def _get_load_command(self) -> str:
        """Generate structure loading command."""
        # Check if pdb_source is a PDB ID (4 characters, alphanumeric)
        if len(self.pdb_source) == 4 and self.pdb_source.isalnum():
            return f"fetch {self.pdb_source}, async=0"
        else:
            return f"load {self.pdb_source}"
    
    def generate_script(self) -> str:
        """Generate the complete PyMOL script."""
        lines = []
        
        # Header
        lines.append("# PyMOL script generated by protein-struct-viz")
        lines.append(f"# Target: {self.pdb_source}")
        lines.append(f"# Highlighted residues: {', '.join(self.residues)}")
        lines.append("")
        
        # Load structure
        lines.append("# Load structure")
        lines.append(self._get_load_command())
        lines.append("")
        
        # Basic settings
        lines.append("# Visualization settings")
        lines.append("bg_color white")
        lines.append("set antialias, 2")
        lines.append("set ray_shadows, 0")
        lines.append("")
        
        # Global representation
        lines.append("# Global representation")
        lines.append("hide everything")
        lines.append("show cartoon")
        lines.append("")
        
        # Apply color scheme
        lines.append("# Color scheme")
        if self.color_scheme in self.COLOR_SCHEMES:
            lines.append(self.COLOR_SCHEMES[self.color_scheme])
        else:
            lines.append(f"cmd.color('{self.color_scheme}', 'all')")
        lines.append("")
        
        # Highlight specific residues
        lines.append("# Highlight specified residues")
        for i, residue_spec in enumerate(self.residues):
            try:
                chain, resnum, resname = self._parse_residue(residue_spec)
                selection = self._generate_selection_string(chain, resnum, resname)
                sel_name = f"residue_{i+1}"
                color = self.highlight_colors[i % len(self.highlight_colors)]
                
                lines.append(f"# {residue_spec}")
                lines.append(f"select {sel_name}, {selection}")
                lines.append(f"show {self.style}, {sel_name}")
                lines.append(f"color {color}, {sel_name}")
                lines.append("")
            except ValueError as e:
                lines.append(f"# Error parsing {residue_spec}: {e}")
                lines.append("")
        
        # Center on highlighted residues
        if self.residues:
            lines.append("# Center view on highlighted residues")
            lines.append("center sele")
            lines.append("zoom sele, 10")
            lines.append("")
        
        # Ray tracing for high quality
        if self.ray_trace:
            lines.append("# High-quality rendering")
            lines.append("set ray_trace_mode, 1")
            lines.append("set ray_trace_gain, 0.01")
            lines.append("ray 2400, 2400")
            lines.append("")
        
        # Label residues option
        lines.append("# Optional: Label residues (uncomment to enable)")
        lines.append("# label sele and name CA, '%s-%s' % (resn, resi)")
        lines.append("")
        
        return "\n".join(lines)
    
    def save(self) -> str:
        """Generate and save the script to file."""
        script_content = self.generate_script()
        output_path = Path(self.output)
        output_path.write_text(script_content)
        return str(output_path.absolute())


def main():
    parser = argparse.ArgumentParser(
        description="Generate PyMOL scripts for protein residue visualization",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Highlight specific residues with sticks representation
  python main.py --pdb 1mbn --residues "A:64:HIS,A:93:VAL" --style sticks
  
  # Use PDB ID and custom color scheme
  python main.py --pdb 1abc --residues "B:23:LYS,B:45:ASP" --color_scheme chain
  
  # Generate high-quality image script
  python main.py --pdb protein.pdb --residues "156,202,245" --ray_trace --output hq.pml
        """
    )
    
    parser.add_argument("--pdb", required=True,
                        help="PDB file path or PDB ID (4-letter code)")
    parser.add_argument("--residues", required=True,
                        help="Comma-separated residue specs (e.g., 'A:64:HIS,A:93:VAL')")
    parser.add_argument("--style", default="sticks",
                        choices=["sticks", "spheres", "surface", "cartoon", "lines", "mesh"],
                        help="Representation style for highlighted residues (default: sticks)")
    parser.add_argument("--color_scheme", default="gray",
                        help="Global color scheme: rainbow, chain, element, secondary, gray, white, or color name")
    parser.add_argument("--output", default="output.pml",
                        help="Output script filename (default: output.pml)")
    parser.add_argument("--ray_trace", action="store_true",
                        help="Include ray tracing commands for high-quality images")
    
    args = parser.parse_args()
    
    # Parse residues
    residue_list = [r.strip() for r in args.residues.split(",")]
    
    # Create generator
    generator = PyMOLScriptGenerator(
        pdb_source=args.pdb,
        residues=residue_list,
        style=args.style,
        color_scheme=args.color_scheme,
        output=args.output,
        ray_trace=args.ray_trace
    )
    
    # Generate and save script
    try:
        output_path = generator.save()
        print(f"PyMOL script generated successfully: {output_path}")
        print(f"\nTo use:")
        print(f"  pymol {args.output}")
        print(f"  # or within PyMOL:")
        print(f"  @ {args.output}")
    except Exception as e:
        print(f"Error generating script: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
