"""GitHubPublisher - GitHub 자동 퍼블리싱"""

import logging
import subprocess
from pathlib import Path
from typing import Dict, Optional

logger = logging.getLogger('builder-agent.integration.github')


class GitHubPublisher:
    """gh CLI를 사용한 GitHub 자동 퍼블리싱"""

    def __init__(self, config=None):
        self.config = config
        self.private = config.github.private if config else False
        self.license = config.github.license if config else "MIT"

    def publish(self, project_path: Path, project_info: Dict) -> Dict:
        """프로젝트를 GitHub에 퍼블리싱

        Steps:
        1. git 초기화
        2. GitHub repo 생성
        3. commit & push
        4. release 생성
        """
        title = project_info.get('title', 'Untitled Project')
        repo_name = self._sanitize_repo_name(title)
        description = project_info.get('description', '')[:200]

        try:
            # 1. git 초기화
            self._init_git(project_path)

            # 2. repo 생성
            repo_url = self._create_repo(repo_name, description)

            # 3. remote 추가 & push
            self._push_to_github(project_path, repo_url)

            # 4. release 생성
            self._create_release(project_path, title, description)

            logger.info("Published: https://github.com/%s", repo_url.replace('git@github.com:', '').replace('.git', ''))

            return {
                'success': True,
                'repo_name': repo_name,
                'url': repo_url
            }

        except Exception as e:
            logger.warning("Publish failed: %s", e)
            return {
                'success': False,
                'error': str(e)
            }

    def _sanitize_repo_name(self, title: str) -> str:
        """제목을 GitHub repo 이름으로 변환"""
        name = title.lower()
        name = name.replace(':', '-')
        name = name.replace(' ', '-')
        name = name.replace('_', '-')
        # 알파벳, 숫자, 하이픈만 유지
        import re
        name = re.sub(r'[^a-z0-9-]', '', name)
        name = name.strip('-')
        return name or 'builder-project'

    def _init_git(self, project_path: Path):
        """git 초기화"""
        subprocess.run(['git', 'init'], cwd=str(project_path),
                      capture_output=True, check=True)
        subprocess.run(['git', 'add', '.'], cwd=str(project_path),
                      capture_output=True, check=True)
        subprocess.run(['git', 'commit', '-m', 'Initial commit'],
                      cwd=str(project_path), capture_output=True, check=True)

    def _create_repo(self, repo_name: str, description: str) -> str:
        """GitHub repo 생성"""
        args = ['gh', 'repo', 'create', repo_name,
                '--description', description]

        if self.private:
            args.append('--private')
        else:
            args.append('--public')

        # git remote로 추가할 수 있도록 --clone 옵션 대신 직접 처리
        result = subprocess.run(args, capture_output=True, text=True)

        if result.returncode != 0:
            raise RuntimeError(f"gh repo create failed: {result.stderr}")

        # repo URL 가져오기
        result = subprocess.run(
            ['gh', 'repo', 'view', repo_name, '--json', 'url', '-q', '.url'],
            capture_output=True, text=True
        )

        return result.stdout.strip()

    def _push_to_github(self, project_path: Path, repo_url: str):
        """GitHub로 push"""
        subprocess.run(['git', 'remote', 'add', 'origin', repo_url],
                      cwd=str(project_path), capture_output=True)
        subprocess.run(['git', 'push', '-u', 'origin', 'main'],
                      cwd=str(project_path), capture_output=True)

    def _create_release(self, project_path: Path, title: str, description: str):
        """GitHub release 생성"""
        notes = f"""Auto-generated by Builder Agent

{description}

---

Built with Builder Agent v4
"""

        subprocess.run([
            'gh', 'release', 'create', 'v1.0.0',
            '--title', f'{title} v1.0.0',
            '--notes', notes
        ], cwd=str(project_path), capture_output=True)
