#!/usr/bin/env python3
"""
Generate a ready-to-run Google Colab notebook for persona model fine-tuning.

The notebook uses Unsloth (fastest QLoRA on T4/A100) and is pre-filled with
your training data, model choice, and hyperparameters. Open it in Colab,
run all cells, then download adapter_weights.zip back to your machine to
continue with voice_test.py and export.py.

Usage:
    python scripts/generate_colab.py \\
        --slug alice \\
        --model google/gemma-4-E4B-it \\
        --training-dir ./training \\
        --epochs 3 \\
        --output colab_train_alice.ipynb

Colab workflow:
    1. Run this script locally → generates a .ipynb file
    2. Upload .ipynb to Google Colab (colab.research.google.com)
    3. Runtime > Change runtime type > T4 GPU
    4. Run All cells
    5. Download the adapter_weights.zip that appears in the last cell
    6. Unzip into models/{slug}/ and continue with pipeline.sh (voice_test + export)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def build_notebook(slug: str, model: str, lora_rank: int, lora_alpha: int,
                   lora_layers: int, warmup_ratio: float,
                   epochs: int, batch_size: int, learning_rate: float,
                   train_data: list[dict], eval_data: list[dict],
                   profile_text: str) -> dict:
    """Build a Jupyter notebook dict from the given parameters."""
    _reset_cell_counter()  # ensure IDs start at 0001 for every generated notebook

    # Inline training data as escaped JSON strings (avoids file upload step)
    train_json = json.dumps(train_data, ensure_ascii=False)
    eval_json  = json.dumps(eval_data,  ensure_ascii=False)
    # Use json.dumps for profile_text to correctly escape ALL special chars
    # (\n, \t, \r, \", \\, etc.) without a fragile manual replace chain.
    profile_json = json.dumps(profile_text, ensure_ascii=False)

    has_enable_thinking = any(
        part in model.lower() for part in ['gemma-4', 'gemma4', 'qwen3', 'qwen-3']
    )
    enable_thinking_code = (
        "extra_template_kwargs = {'enable_thinking': False}"
        if has_enable_thinking else
        "extra_template_kwargs = {}"
    )

    # Models that require HuggingFace auth (license gate on huggingface.co).
    # Mistral-7B and Qwen are public — do NOT add them here.
    GATED_PREFIXES = ('google/gemma', 'meta-llama/')
    is_gated = any(model.lower().startswith(p) for p in GATED_PREFIXES)

    cells = [
        # ── Cell 0: Title ──────────────────────────────────────────────────
        _md(f"""# Persona Fine-Tuning: `{slug}`

Auto-generated by `persona-model-trainer/scripts/generate_colab.py`.

**Model**: `{model}`  
**LoRA rank**: {lora_rank} | **Epochs**: {epochs} | **Batch size**: {batch_size}

## Steps
1. Run all cells (Runtime → Run all)
2. Wait for training to complete (~15–45 min on T4 depending on data size)
3. Download `adapter_weights_{slug}.zip` from the last cell
4. Unzip into `models/{slug}/export/` on your local machine
5. Continue locally: `bash scripts/pipeline.sh --slug {slug} --model {model} --source ./training --method skip-train`
"""),

        # ── Cell 1: Install ────────────────────────────────────────────────
        _code("""\
# Install dependencies (takes ~3 min on first run)
!pip install -q "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install -q trl transformers peft datasets accelerate
print("✅ Dependencies installed")
"""),

        # ── Cell 2: HuggingFace auth ───────────────────────────────────────
        _code(f"""\
# HuggingFace login — required for gated models (Gemma 4, Llama 3, etc.)
# Set your token via: Colab left sidebar → 🔑 Secrets → Add "HF_TOKEN"
# Or paste it directly below (not recommended for shared notebooks).
import os
from google.colab import userdata

try:
    hf_token = userdata.get("HF_TOKEN")
except Exception:
    hf_token = os.environ.get("HF_TOKEN", "")

if hf_token:
    from huggingface_hub import login
    login(token=hf_token, add_to_git_credential=False)
    print("✅ HuggingFace login OK")
else:
    # Only Gemma 4 / Llama 3 / similar gated models need a token.
    # Public models (Qwen, Mistral, Phi) can skip this cell.
    IS_GATED = {is_gated}  # auto-detected from model ID at notebook generation time
    if IS_GATED:
        raise RuntimeError(
            "HF_TOKEN not found but IS_GATED=True — this model requires a HuggingFace token.\\n"
            "Add your token via Colab Secrets (left sidebar → 🔑) with key 'HF_TOKEN'."
        )
    else:
        print("ℹ️  No HF_TOKEN — OK for public models. Add one via Colab Secrets if downloads fail.")
"""),

        # ── Cell 3: Check GPU ─────────────────────────────────────────────
        _code("""\
import torch
gpu = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU (no GPU!)"
vram = torch.cuda.get_device_properties(0).total_memory // (1024**3) if torch.cuda.is_available() else 0
print(f"GPU: {gpu}  |  VRAM: {vram} GB")
if not torch.cuda.is_available():
    raise RuntimeError("No GPU detected. Go to Runtime > Change runtime type > T4 GPU")
"""),

        # ── Cell 4: Config ─────────────────────────────────────────────────
        _code(f"""\
# ── Configuration (auto-generated — edit if needed) ──────────────────────
SLUG          = "{slug}"
MODEL_ID      = {json.dumps(model)}
LORA_RANK     = {lora_rank}
LORA_ALPHA    = {lora_alpha}   # default = rank (Gemma 4 recommendation: alpha == rank)
LORA_LAYERS   = {lora_layers}  # informational; Unsloth applies LoRA to all layers by default
WARMUP_RATIO  = {warmup_ratio}
EPOCHS        = {epochs}
BATCH_SIZE    = {batch_size}
LEARNING_RATE = {learning_rate}
MAX_SEQ_LEN   = 2048
OUTPUT_DIR    = f"/content/models/{{SLUG}}"

import os
os.makedirs(OUTPUT_DIR, exist_ok=True)
print(f"Output dir: {{OUTPUT_DIR}}")
"""),

        # ── Cell 5: Write training data ────────────────────────────────────
        _code(f"""\
# Write training data (inlined from local files — no upload needed)
import json, pathlib

train_data = {train_json}
eval_data  = {eval_json}
profile_text = {profile_json}

data_dir = pathlib.Path("/content/training_data")
data_dir.mkdir(exist_ok=True)

(data_dir / "train.jsonl").write_text("\\n".join(json.dumps(d, ensure_ascii=False) for d in train_data) + "\\n")
# Only write eval if non-empty — empty JSONL causes load_dataset to raise EmptyDatasetError
if eval_data:
    (data_dir / "eval.jsonl").write_text("\\n".join(json.dumps(d, ensure_ascii=False) for d in eval_data) + "\\n")
(data_dir / "profile.md").write_text(profile_text)

HAS_EVAL = bool(eval_data)
print(f"Training samples: {{len(train_data)}}")
print(f"Eval samples:     {{len(eval_data)}} ({{'' if HAS_EVAL else 'no eval — training without validation'}})")
print(f"Profile: {{len(profile_text)}} chars")
"""),

        # ── Cell 6: Load model ─────────────────────────────────────────────
        _code(f"""\
from unsloth import FastLanguageModel
import torch

print(f"Loading {{MODEL_ID}} with Unsloth…")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_ID,
    max_seq_length=MAX_SEQ_LEN,
    load_in_4bit=True,
    dtype=None,  # auto-detect bfloat16/float16
)
print("✅ Base model loaded")

model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_RANK,
    lora_alpha=LORA_ALPHA,
    lora_dropout=0.05,
    bias="none",
    use_gradient_checkpointing="unsloth",
    # target_modules omitted: PEFT auto-detects all linear layers
)
print(f"✅ LoRA adapter attached  (rank={{LORA_RANK}})")
"""),

        # ── Cell 7: Prepare formatting function ────────────────────────────
        _code(f"""\
# enable_thinking=False: suppress Gemma 4 / Qwen 3 thinking tokens
# so the model trains on clean persona responses only
{enable_thinking_code}

def _apply_template(msgs):
    try:
        return tokenizer.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=False,
            **extra_template_kwargs,
        )
    except TypeError:
        return tokenizer.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=False,
        )

def formatting_func(examples):
    return [_apply_template(msgs) for msgs in examples["messages"]]

print(f"Chat template extra kwargs: {{extra_template_kwargs}}")
print("✅ Formatting function ready")
"""),

        # ── Cell 8: Train ─────────────────────────────────────────────────
        _code("""\
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# HAS_EVAL is set in Cell 5; recompute here in case Cell 8 is re-run alone
HAS_EVAL = globals().get("HAS_EVAL", False) and (data_dir / "eval.jsonl").exists()

data_files = {"train": str(data_dir / "train.jsonl")}
if HAS_EVAL:
    data_files["eval"] = str(data_dir / "eval.jsonl")
dataset = load_dataset("json", data_files=data_files)

training_args = TrainingArguments(
    output_dir=f"{OUTPUT_DIR}/checkpoints",
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=4,
    learning_rate=LEARNING_RATE,
    lr_scheduler_type="cosine",
    warmup_ratio=WARMUP_RATIO,
    logging_steps=10,
    eval_strategy="epoch" if HAS_EVAL else "no",
    save_strategy="epoch",
    load_best_model_at_end=HAS_EVAL,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    fp16=True,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["eval"] if HAS_EVAL else None,
    tokenizer=tokenizer,
    formatting_func=formatting_func,
    max_seq_length=MAX_SEQ_LEN,
)

print(f"Starting training ({EPOCHS} epochs, eval={'yes' if HAS_EVAL else 'no'})…")
trainer.train()
print("\\n✅ Training complete!")
"""),

        # ── Cell 9: Save adapter + write training summary ─────────────────
        _code("""\
import json, math

adapter_path = f"{OUTPUT_DIR}/adapter_weights"
model.save_pretrained(adapter_path)
tokenizer.save_pretrained(adapter_path)
print(f"✅ Adapter saved → {adapter_path}")

# Extract eval_loss from training log history (populated when eval data exists)
eval_loss = next(
    (e["eval_loss"] for e in reversed(trainer.state.log_history) if "eval_loss" in e),
    None,
)

# Write training summary (compatible with pipeline.sh / pack-integration)
summary = {
    "base_model": MODEL_ID,
    "method": "unsloth-colab",
    "lora_rank": LORA_RANK,
    "lora_alpha": LORA_ALPHA,
    "epochs": EPOCHS,
    "train_samples": len(train_data),
    "eval_samples": len(eval_data),
    "device": "colab-t4",
    "adapter_path": adapter_path,
}
if eval_loss is not None:
    summary["evaluation"] = {
        "eval_loss":  round(eval_loss, 4),
        "perplexity": round(math.exp(eval_loss), 2),
    }
    print(f"   Perplexity: {summary['evaluation']['perplexity']:.2f}  (eval_loss={eval_loss:.4f})")

summary_path = f"{OUTPUT_DIR}/training_summary.json"
with open(summary_path, "w") as f:
    json.dump(summary, f, indent=2)
print(f"   Summary → {summary_path}")
"""),

        # ── Cell 10: Download ──────────────────────────────────────────────
        _code(f"""\
# Zip and download adapter_weights
import shutil, zipfile
from google.colab import files

zip_path = "/content/adapter_weights_{slug}"
shutil.make_archive(zip_path, "zip", OUTPUT_DIR, "adapter_weights")
zip_file = zip_path + ".zip"

# Also include training_summary.json in the zip
with zipfile.ZipFile(zip_file, "a") as zf:
    zf.write(f"{{OUTPUT_DIR}}/training_summary.json", "training_summary.json")

print(f"Packed: {{zip_file}}")
print("Downloading adapter_weights_{slug}.zip — check your browser downloads…")
files.download(zip_file)
print("\\n── Next steps (run locally) ──────────────────────────────────────")
print("  1. Unzip adapter into the export directory:")
print("     unzip adapter_weights_{slug}.zip -d models/{slug}/export/")
print("  2. Run voice test + export + archive in one command:")
print(f"     bash scripts/pipeline.sh --slug {slug} --model {{MODEL_ID}} --source ./training --method skip-train")
"""),
    ]

    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.0"},
            "accelerator": "GPU",
            "colab": {
                "provenance": [],
                "gpuType": "T4",
                "name": f"persona_train_{slug}.ipynb",
            },
        },
        "cells": cells,
    }


def _code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": _cell_id(),
        "metadata": {},
        "outputs": [],
        "source": source.rstrip(),
    }


def _md(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": _cell_id(),
        "metadata": {},
        "source": source.rstrip(),
    }


_cell_counter = 0

def _reset_cell_counter() -> None:
    global _cell_counter
    _cell_counter = 0

def _cell_id() -> str:
    global _cell_counter
    _cell_counter += 1
    return f"cell-{_cell_counter:04d}"


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    items = []
    for line in path.open():
        line = line.strip()
        if line:
            try:
                items.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return items


def main():
    parser = argparse.ArgumentParser(description="Generate a Colab notebook for persona fine-tuning")
    parser.add_argument("--slug",         required=True, help="Persona slug")
    parser.add_argument("--model",        required=True, help="HuggingFace model ID")
    parser.add_argument("--training-dir", required=True, help="Path to prepared training dir (output of prepare_data.py)")
    parser.add_argument("--epochs",       type=int,   default=3)
    parser.add_argument("--batch-size",   type=int,   default=2,
                        help="Per-device batch size (default 2 for T4 16 GB)")
    parser.add_argument("--lora-rank",    type=int,   default=16)
    parser.add_argument("--lora-alpha",   type=int,   default=None,
                        help="LoRA alpha (default: auto = lora-rank)")
    parser.add_argument("--lora-layers",  type=int,   default=16,
                        help="Transformer layers to apply LoRA (informational for Colab/Unsloth)")
    parser.add_argument("--warmup-ratio", type=float, default=0.05,
                        help="LR warmup ratio (default 0.05; gemma4 preset uses 0.1)")
    parser.add_argument("--learning-rate",type=float, default=2e-4)
    parser.add_argument("--output",       default=None,
                        help="Output .ipynb path (default: colab_train_{slug}.ipynb)")
    args = parser.parse_args()
    if args.lora_alpha is None:
        args.lora_alpha = args.lora_rank

    # Validate slug — must be safe for use in Python string literals, filenames, and paths.
    # OpenPersona slugs are lowercase alphanumeric + hyphens; reject anything else early.
    import re as _re
    if not _re.fullmatch(r'[a-zA-Z0-9][a-zA-Z0-9\-_]*', args.slug):
        print(f"❌ Invalid slug: {args.slug!r}")
        print("   Slug must be alphanumeric with hyphens/underscores (e.g. 'alice', 'my-persona').")
        sys.exit(1)

    training_dir = Path(args.training_dir)
    if not training_dir.exists():
        print(f"❌ Training dir not found: {training_dir}")
        print("   Run scripts/prepare_data.py first, then point --training-dir at its output.")
        sys.exit(1)

    train_data = load_jsonl(training_dir / "train.jsonl")
    eval_data  = load_jsonl(training_dir / "eval.jsonl")

    if not train_data:
        print(f"❌ No training data found in {training_dir}/train.jsonl")
        print("   Run scripts/prepare_data.py first.")
        sys.exit(1)

    profile_path = training_dir.parent / "profile.md"
    if not profile_path.exists():
        profile_path = training_dir / "profile.md"
    profile_text = profile_path.read_text() if profile_path.exists() else ""

    # Warn if dataset is large — inlining into notebook has size limits
    total_chars = sum(len(json.dumps(d)) for d in train_data + eval_data)
    if total_chars > 5_000_000:  # ~5 MB
        print(f"⚠️  Large dataset ({total_chars // 1024} KB) — notebook may be slow to open.")
        print("   Consider using --max-chars in prepare_data.py to reduce sample size.")

    nb = build_notebook(
        slug=args.slug,
        model=args.model,
        lora_rank=args.lora_rank,
        lora_alpha=args.lora_alpha,
        lora_layers=args.lora_layers,
        warmup_ratio=args.warmup_ratio,
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        train_data=train_data,
        eval_data=eval_data,
        profile_text=profile_text,
    )

    out_path = Path(args.output) if args.output else Path(f"colab_train_{args.slug}.ipynb")
    out_path.write_text(json.dumps(nb, indent=2, ensure_ascii=False) + "\n")

    print(f"✅ Notebook generated: {out_path}")
    print(f"   Training samples: {len(train_data)}  |  Eval: {len(eval_data)}")
    print(f"   Model: {args.model}  |  Epochs: {args.epochs}  |  LoRA rank: {args.lora_rank}")
    print()
    print("Next steps:")
    print(f"  1. Open {out_path} in Google Colab")
    print(f"     https://colab.research.google.com/  → File > Upload notebook")
    print(f"  2. Runtime > Change runtime type > T4 GPU")
    print(f"  3. Runtime > Run all  (approx 15–45 min)")
    print(f"  4. Download adapter_weights_{args.slug}.zip when it appears")
    print(f"  5. Unzip into models/{args.slug}/export/ then:")
    print(f"     bash scripts/pipeline.sh --slug {args.slug} --model {args.model} --source ./training --method skip-train")


if __name__ == "__main__":
    main()
