#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import sys
import unicodedata
from pathlib import Path
from typing import Any
from urllib import error, request

ALLOWED_LEVELS = {"critical", "high", "medium", "info"}
DEFAULT_SKILL_CONFIG = Path(__file__).resolve().parent.parent / "config.json"
DEFAULT_USER_AGENT = "ClawLockRank-Skill/1.1.0 (+https://github.com/g1at/ClawLock-Rank)"
UPLOADED_FIELDS = [
    "tool",
    "clawlock_version",
    "adapter",
    "adapter_version",
    "device_fingerprint",
    "evidence_hash",
    "score",
    "grade",
    "nickname",
    "findings[].scanner",
    "findings[].level",
    "findings[].title",
    "timestamp",
]
EXCLUDED_FIELDS = [
    "raw configuration files",
    "remediation text",
    "local file paths / location",
    "environment variables",
    "full raw scan report",
    "scan_history.json",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upload a sanitized ClawLockRank payload to the configured Worker.",
    )
    parser.add_argument("--input", required=True, help="Path to the payload JSON generated by run_scan.py.")
    parser.add_argument(
        "--api-base",
        default="",
        help="Optional Worker origin override. Defaults to CLAWLOCK_RANK_API_BASE or skill/config.json.",
    )
    parser.add_argument("--nickname", default="", help="Optional nickname override.")
    parser.add_argument("--timeout", type=int, default=15, help="Upload timeout in seconds.")
    parser.add_argument("--yes", action="store_true", help="Skip the interactive upload confirmation prompt.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    api_base = resolve_api_base(args.api_base)
    if not api_base:
        raise SystemExit("Missing Worker origin. Pass --api-base, set CLAWLOCK_RANK_API_BASE, or add skill/config.json.")

    payload_path = Path(args.input).expanduser().resolve()
    raw_payload = load_payload(payload_path)
    payload = sanitize_payload(raw_payload, nickname_override=args.nickname)

    if not args.yes:
        print(json.dumps(build_public_summary(payload), ensure_ascii=False, indent=2))
        print(
            "Only score, version, nickname, timestamp, device fingerprint, evidence hash, and finding titles/levels/scanners "
            "will be uploaded. Raw configs, remediation details, file paths, and local reports stay on this device.",
        )
        confirm = input(f"Upload score {payload['submission']['score']} for {payload['submission']['nickname']}? [y/N]: ")
        if confirm.strip().lower() not in {"y", "yes"}:
            print(json.dumps({"ok": False, "accepted": False, "message": "Upload cancelled."}, indent=2))
            return 0

    response = post_payload(payload, api_base=api_base, timeout=args.timeout)
    stream = sys.stdout if response["ok"] else sys.stderr
    print(json.dumps(response["body"], ensure_ascii=False, indent=2), file=stream)
    return 0 if response["ok"] else 1


def load_payload(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise SystemExit(f"Payload file not found: {path}")

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Input file is not valid JSON: {exc}") from exc

    if not isinstance(payload, dict) or not isinstance(payload.get("submission"), dict):
        raise SystemExit("Input file does not contain a valid submission payload.")
    return payload


def sanitize_payload(raw_payload: dict[str, Any], nickname_override: str = "") -> dict[str, Any]:
    submission = raw_payload.get("submission")
    if not isinstance(submission, dict):
        raise SystemExit("Payload is missing a submission object.")

    meta = raw_payload.get("meta")
    if not isinstance(meta, dict):
        meta = {}

    nickname = clean_text(nickname_override or submission.get("nickname"), 24) or "Anonymous"
    sanitized_submission = {
        "tool": clean_text(submission.get("tool"), 32) or "ClawLock",
        "clawlock_version": clean_text(submission.get("clawlock_version") or submission.get("version"), 32),
        "adapter": clean_text(submission.get("adapter"), 64),
        "adapter_version": clean_text(submission.get("adapter_version"), 32),
        "device_fingerprint": clean_text(submission.get("device_fingerprint") or submission.get("device"), 128),
        "evidence_hash": clean_hash(submission.get("evidence_hash")),
        "score": sanitize_score(submission.get("score")),
        "grade": sanitize_grade(submission.get("grade")),
        "nickname": nickname,
        "findings": sanitize_findings(submission.get("findings")),
        "timestamp": clean_text(submission.get("timestamp") or submission.get("time"), 64),
    }

    if not sanitized_submission["clawlock_version"]:
        raise SystemExit("Payload is missing submission.clawlock_version.")
    if not sanitized_submission["adapter"]:
        raise SystemExit("Payload is missing submission.adapter.")
    if not sanitized_submission["device_fingerprint"]:
        raise SystemExit("Payload is missing submission.device_fingerprint.")
    if not sanitized_submission["timestamp"]:
        raise SystemExit("Payload is missing submission.timestamp.")

    return {
        "submission": sanitized_submission,
        "meta": {
            "source": clean_text(meta.get("source"), 64) or "clawlock-rank-skill",
            "skill_version": clean_text(meta.get("skill_version"), 32) or "1.1.0",
        },
    }


def sanitize_findings(raw_findings: Any) -> list[dict[str, str]]:
    if not isinstance(raw_findings, list):
        return []

    findings: list[dict[str, str]] = []
    for item in raw_findings[:200]:
        if not isinstance(item, dict):
            continue
        level = clean_text(item.get("level"), 16).lower()
        if level == "warn":
            level = "medium"
        elif level == "low":
            level = "info"
        if level not in ALLOWED_LEVELS:
            continue

        scanner = clean_text(item.get("scanner"), 64)
        title = clean_text(item.get("title"), 160)
        if not scanner or not title:
            continue

        findings.append(
            {
                "scanner": scanner,
                "level": level,
                "title": title,
            }
        )
    return findings


def build_public_summary(payload: dict[str, Any]) -> dict[str, Any]:
    submission = payload["submission"]
    return {
        "tool": submission["tool"],
        "clawlock_version": submission["clawlock_version"],
        "score": submission["score"],
        "grade": submission["grade"],
        "adapter": submission["adapter"],
        "adapter_version": submission["adapter_version"],
        "nickname": submission["nickname"],
        "finding_count": len(submission["findings"]),
        "uploaded_fields": UPLOADED_FIELDS,
        "excluded_fields": EXCLUDED_FIELDS,
    }


def post_payload(payload: dict[str, Any], api_base: str, timeout: int) -> dict[str, Any]:
    endpoint = f"{api_base}/api/submit"
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    http_request = request.Request(
        endpoint,
        data=body,
        headers={
            "Content-Type": "application/json; charset=utf-8",
            "Accept": "application/json",
            "User-Agent": DEFAULT_USER_AGENT,
        },
        method="POST",
    )

    try:
        with request.urlopen(http_request, timeout=timeout) as response:
            raw = response.read().decode("utf-8")
            parsed = json.loads(raw) if raw else {}
            return {"ok": response.status < 400, "body": parsed}
    except error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        parsed = try_parse_json(raw)
        return {"ok": False, "body": parsed or {"ok": False, "error": raw or f"HTTP {exc.code}"}}
    except error.URLError as exc:
        raise SystemExit(f"Upload failed: {exc.reason}") from exc


def sanitize_score(value: Any) -> int:
    try:
        score = int(round(float(value)))
    except (TypeError, ValueError) as exc:
        raise SystemExit("Payload is missing a numeric submission.score.") from exc
    return max(0, min(100, score))


def sanitize_grade(value: Any) -> str:
    grade = clean_text(value, 2).upper()
    if grade not in {"S", "A", "B", "C", "D", "F"}:
        raise SystemExit("Payload is missing a valid submission.grade.")
    return grade


def normalize_api_base(value: str) -> str:
    return value.strip().rstrip("/")


def resolve_api_base(explicit: str) -> str:
    for candidate in (explicit, os.environ.get("CLAWLOCK_RANK_API_BASE", ""), read_skill_api_base()):
        normalized = normalize_api_base(candidate)
        if normalized:
            return normalized
    return ""


def read_skill_api_base() -> str:
    if not DEFAULT_SKILL_CONFIG.is_file():
        return ""
    try:
        raw = json.loads(DEFAULT_SKILL_CONFIG.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return ""
    if not isinstance(raw, dict):
        return ""
    value = raw.get("api_base")
    return value if isinstance(value, str) else ""


def clean_text(value: Any, max_length: int) -> str:
    if not isinstance(value, str):
        return ""
    normalized = unicodedata.normalize("NFC", value)
    collapsed = " ".join(normalized.strip().split())
    return collapsed[:max_length]


def clean_hash(value: Any) -> str:
    text = clean_text(value, 64).lower()
    if not text:
        return ""
    if len(text) != 64 or any(char not in "0123456789abcdef" for char in text):
        raise SystemExit("submission.evidence_hash must be a 64-character lowercase hex string.")
    return text


def try_parse_json(raw: str) -> dict[str, Any] | None:
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return None
    return parsed if isinstance(parsed, dict) else None


if __name__ == "__main__":
    sys.exit(main())
