package setup

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/maxtechera/admirarr/internal/config"
	"github.com/maxtechera/admirarr/internal/deploy"
	"github.com/maxtechera/admirarr/internal/recyclarr"
	"github.com/maxtechera/admirarr/internal/ui"
)

// arrServiceConfig holds what we need to generate a recyclarr config entry.
type arrServiceConfig struct {
	Name    string
	BaseURL string
	APIKey  string
	Type    string // "radarr", "sonarr", "lidarr"
}

// generateRecyclarrConfig builds a recyclarr.yml from the current setup state.
func generateRecyclarrConfig(state *SetupState) string {
	var b strings.Builder

	b.WriteString("# yaml-language-server: $schema=https://schemas.recyclarr.dev/latest/config-schema.json\n")
	b.WriteString("# Generated by Admirarr setup — https://github.com/maxtechera/admirarr\n")
	b.WriteString("# Re-run `admirarr setup` to regenerate.\n\n")

	profile := config.QualityProfile()
	if profile == "" {
		profile = "HD-1080p"
	}

	// Collect services
	var radarrServices []arrServiceConfig
	var sonarrServices []arrServiceConfig

	for _, name := range []string{"radarr"} {
		svc := state.Services[name]
		if svc == nil || !svc.Reachable || state.Keys[name] == "" {
			continue
		}
		radarrServices = append(radarrServices, arrServiceConfig{
			Name:    name,
			BaseURL: state.InternalURL(name),
			APIKey:  state.Keys[name],
			Type:    "radarr",
		})
	}
	for _, name := range []string{"sonarr"} {
		svc := state.Services[name]
		if svc == nil || !svc.Reachable || state.Keys[name] == "" {
			continue
		}
		sonarrServices = append(sonarrServices, arrServiceConfig{
			Name:    name,
			BaseURL: state.InternalURL(name),
			APIKey:  state.Keys[name],
			Type:    "sonarr",
		})
	}

	// Radarr section
	if len(radarrServices) > 0 {
		b.WriteString("radarr:\n")
		for _, svc := range radarrServices {
			b.WriteString(fmt.Sprintf("  %s:\n", svc.Name))
			b.WriteString(fmt.Sprintf("    base_url: %s\n", svc.BaseURL))
			b.WriteString(fmt.Sprintf("    api_key: %s\n", svc.APIKey))
			b.WriteString("\n")
			b.WriteString("    quality_definition:\n")
			b.WriteString("      type: movie\n")
			b.WriteString("\n")

			b.WriteString("    quality_profiles:\n")
			b.WriteString(fmt.Sprintf("      - name: %s\n", profile))
			b.WriteString("        reset_unmatched_scores:\n")
			b.WriteString("          enabled: true\n")
			b.WriteString("\n")

			// Custom formats: always include Repack/Proper + common unwanted
			b.WriteString("    custom_formats:\n")
			b.WriteString("      - trash_ids:\n")
			writeRadarrCustomFormats(&b)
			b.WriteString("        assign_scores_to:\n")
			b.WriteString(fmt.Sprintf("          - name: %s\n", profile))
			b.WriteString("\n")
		}
	}

	// Sonarr section
	if len(sonarrServices) > 0 {
		b.WriteString("sonarr:\n")
		for _, svc := range sonarrServices {
			b.WriteString(fmt.Sprintf("  %s:\n", svc.Name))
			b.WriteString(fmt.Sprintf("    base_url: %s\n", svc.BaseURL))
			b.WriteString(fmt.Sprintf("    api_key: %s\n", svc.APIKey))
			b.WriteString("\n")
			b.WriteString("    quality_definition:\n")
			b.WriteString("      type: series\n")
			b.WriteString("\n")

			b.WriteString("    quality_profiles:\n")
			b.WriteString(fmt.Sprintf("      - name: %s\n", profile))
			b.WriteString("        reset_unmatched_scores:\n")
			b.WriteString("          enabled: true\n")
			b.WriteString("\n")

			b.WriteString("    custom_formats:\n")
			b.WriteString("      - trash_ids:\n")
			writeSonarrCustomFormats(&b)
			b.WriteString("        assign_scores_to:\n")
			b.WriteString(fmt.Sprintf("          - name: %s\n", profile))
			b.WriteString("\n")
		}
	}

	return b.String()
}

// writeRadarrCustomFormats writes the standard set of TRaSH Guide custom format
// trash_ids for Radarr. These are the "must-have" formats recommended by TRaSH.
func writeRadarrCustomFormats(b *strings.Builder) {
	formats := []struct {
		id      string
		comment string
	}{
		{"e7718d7a3ce595f289bfee26adc178f5", "Repack/Proper"},
		{"ae43b294509409a6a13919dedd4764c4", "Repack2"},
		{"ed38b889b31be83fda192888e2286d83", "BR-DISK"},
		{"90a6f9a284dff5103f6346090e6280c8", "LQ"},
		{"dc98083864ea246d05a42df0d05f81cc", "x265 (HD)"},
		{"b8cd450cbfa689c0259571fc8aa856cb", "3D"},
		{"0a3f082873eb454bde444150b70253cc", "Extras"},
	}
	for _, f := range formats {
		b.WriteString(fmt.Sprintf("          - %s # %s\n", f.id, f.comment))
	}
}

// writeSonarrCustomFormats writes the standard set for Sonarr.
func writeSonarrCustomFormats(b *strings.Builder) {
	formats := []struct {
		id      string
		comment string
	}{
		{"ec8fa7296b64e8cd390a1600981f3923", "Repack/Proper"},
		{"eb3d5cc0a2be0db205fb823640db6a3c", "Repack2"},
		{"85c61753df5da1fb2aab6f2a47c2c0a4", "BR-DISK"},
		{"fbcb31d8f2bd40d3cfa1fc0c79df9462", "LQ"},
		{"47435ece6b99a0b477caf360e79ba0bb", "x265 (HD)"},
		{"32b367365729d530ca1c124a0b180c64", "Bad Dual Groups"},
		{"82d40da2bc6923f41e14394075dd4b03", "No-RlsGroup"},
		{"e1a997ddb54e3ecbfe06341ad323c458", "Obfuscated"},
		{"06d66ab109d4d2eddb2794d21526d140", "Retags"},
	}
	for _, f := range formats {
		b.WriteString(fmt.Sprintf("          - %s # %s\n", f.id, f.comment))
	}
}

// writeRecyclarrConfig writes the generated recyclarr config to the appropriate location.
// For Docker: writes into the container's config volume.
// For native: writes to ~/.config/recyclarr/recyclarr.yml.
func writeRecyclarrConfig(state *SetupState, content string) error {
	rt := recyclarr.Detect()

	switch rt.Method {
	case "docker":
		// Write into the Docker container
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, "docker", "exec", "-i", rt.Path, "sh", "-c",
			"cat > /config/recyclarr.yml")
		cmd.Stdin = strings.NewReader(content)
		return cmd.Run()

	case "native":
		// Write to native config path
		dir := filepath.Join(os.Getenv("HOME"), ".config", "recyclarr")
		os.MkdirAll(dir, 0755)
		return os.WriteFile(filepath.Join(dir, "recyclarr.yml"), []byte(content), 0644)

	default:
		// Try to write to compose config dir for when recyclarr gets deployed later
		composeDir := state.ComposeDir
		if composeDir == "" {
			composeDir = filepath.Join(os.Getenv("HOME"), "docker")
		}
		configDir := filepath.Join(composeDir, "config", "recyclarr")
		os.MkdirAll(configDir, 0755)
		return os.WriteFile(filepath.Join(configDir, "recyclarr.yml"), []byte(content), 0644)
	}
}

// ensureRecyclarr deploys recyclarr if it's not available and the user selected it.
func ensureRecyclarr(state *SetupState) recyclarr.Runtime {
	rt := recyclarr.Detect()
	if rt.Method != "none" {
		return rt
	}

	// Check if recyclarr was selected
	if !hasService(state, "recyclarr") {
		return rt
	}

	fmt.Printf("  %s Deploying Recyclarr…\n", ui.GoldText("⟳"))
	result := deploy.Service("recyclarr")
	if result.Error != nil {
		fmt.Printf("  %s Deploy failed: %v\n", ui.Err("✗"), result.Error)
		return rt
	}

	fmt.Printf("  %s Recyclarr deployed (container: %s)\n", ui.Ok("✓"), result.Container)

	// Wait for container to be ready
	time.Sleep(3 * time.Second)

	return recyclarr.Detect()
}
