#!/usr/bin/env bash
#
# ClawMobile Skill Setup Script
# This script helps set up ClawMobile Skill for use

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_ROOT="$(dirname "$SCRIPT_DIR")"

echo "=========================================="
echo "  ClawMobile Skill Setup"
echo "=========================================="
echo ""

# Function to print colored output
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check Python version
check_python() {
    print_info "Checking Python version..."

    if ! command -v python3 &> /dev/null; then
        print_error "Python 3 is not installed"
        echo "Please install Python 3.7 or higher"
        exit 1
    fi

    PYTHON_VERSION=$(python3 --version | awk '{print $2}')
    PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
    PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)

    if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 7 ]); then
        print_error "Python version $PYTHON_VERSION is not supported (requires 3.7+)"
        exit 1
    fi

    print_info "Python $PYTHON_VERSION found ✓"
}

# Check ADB
check_adb() {
    print_info "Checking ADB..."

    if ! command -v adb &> /dev/null; then
        print_warning "ADB not found in PATH"
        echo "Please install Android Platform Tools"
        echo "Download from: https://developer.android.com/studio/releases/platform-tools"
        read -p "Continue anyway? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    else
        print_info "ADB found ✓"
    fi
}

# Check dependencies
check_dependencies() {
    print_info "Checking Python dependencies..."

    if [ ! -f "$SKILL_ROOT/requirements.txt" ]; then
        print_warning "requirements.txt not found"
    else
        print_info "Installing dependencies..."
        pip3 install -q -r "$SKILL_ROOT/requirements.txt" || {
            print_error "Failed to install dependencies"
            exit 1
        }
        print_info "Dependencies installed ✓"
    fi
}

# Create config from template
create_config() {
    print_info "Creating configuration..."

    if [ -f "$SKILL_ROOT/config/settings.yaml" ]; then
        print_info "Configuration file already exists"
        read -p "Overwrite? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            return
        fi
    fi

    # Use existing config
    print_info "Configuration file ready ✓"
}

# Setup environment variables
setup_env() {
    print_info "Setting up environment variables..."

    ENV_FILE="$SKILL_ROOT/.env"

    if [ -f "$ENV_FILE" ]; then
        print_info ".env file already exists"
        read -p "Update .env file? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            return
        fi
    fi

    echo "# ClawMobile Environment Variables" > "$ENV_FILE"
    echo "# Generated by setup script on $(date)" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
    echo "# API Configuration" >> "$ENV_FILE"
    echo "CLAWMOBILE_API_URL=\"http://localhost:8765\"" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
    echo "# Authentication" >> "$ENV_FILE"
    echo "# Replace with your actual AutoX.js token" >> "$ENV_FILE"
    echo "CLAWMOBILE_API_TOKEN=\"your-autox-token-here\"" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
    echo "# Optional: Device ID" >> "$ENV_FILE"
    echo "# CLAWMOBILE_DEVICE_ID=\"\"" >> "$ENV_FILE"

    print_info ".env file created ✓"
    print_warning "Please edit .env and set your CLAWMOBILE_API_TOKEN"
}

# Create log directory
create_log_dir() {
    print_info "Creating log directory..."

    mkdir -p "$SKILL_ROOT/logs"
    print_info "Log directory created ✓"
}

# Validate skill structure
validate_skill() {
    print_info "Validating skill structure..."

    REQUIRED_FILES=(
        "SKILL.md"
        "skill/__init__.py"
        "skill/client.py"
        "skill/api_server.py"
        "skill/executor.py"
        "skill/models.py"
        "config/settings.yaml"
    )

    MISSING_FILES=()

    for file in "${REQUIRED_FILES[@]}"; do
        if [ ! -f "$SKILL_ROOT/$file" ]; then
            MISSING_FILES+=("$file")
        fi
    done

    if [ ${#MISSING_FILES[@]} -gt 0 ]; then
        print_error "Missing required files:"
        for file in "${MISSING_FILES[@]}"; do
            echo "  - $file"
        done
        exit 1
    fi

    print_info "Skill structure valid ✓"
}

# Print next steps
print_next_steps() {
    echo ""
    echo "=========================================="
    echo "  Setup Complete!"
    echo "=========================================="
    echo ""
    echo "Next steps:"
    echo ""
    echo "1. Connect your Android device:"
    echo "   adb devices"
    echo ""
    echo "2. Start AutoX.js HTTP server on your device (port 8765)"
    echo ""
    echo "3. Update your .env file:"
    echo "   nano $SKILL_ROOT/.env"
    echo "   Set CLAWMOBILE_API_TOKEN to your AutoX.js token"
    echo ""
    echo "4. Test the connection:"
    echo "   cd $SKILL_ROOT"
    echo "   bash scripts/validate.sh"
    echo ""
    echo "5. Run tests:"
    echo "   cd $SKILL_ROOT"
    echo "   python3 -m pytest tests/"
    echo ""
    echo "For more information, see:"
    echo "  - README.md"
    echo "  - SKILL.md"
    echo ""
}

# Main setup process
main() {
    print_info "Starting ClawMobile Skill setup..."
    echo ""

    check_python
    check_adb
    check_dependencies
    create_config
    setup_env
    create_log_dir
    validate_skill

    print_next_steps
}

# Run main function
main "$@"
