#!/usr/bin/env python3
import argparse
import os
import re
from pathlib import Path
from datetime import datetime

BASE = Path(__file__).resolve().parents[2]
OUT = BASE / 'skill-router' / 'references' / 'skill-index.md'
CHANGELOG = BASE / 'skill-router' / 'references' / 'change-log.md'

MANUAL = {
    'dropbox': ('A','A4','R1','write-remote,retrieve'),
    'claw-me-maybe': ('A','A1','R3','message-send,write-remote'),
    'telegram-compose': ('A','A1','R2','message-send,write-local'),
    'whatsapp-styler': ('A','A1','R1','message-send'),
    'wa-styler': ('A','A1','R1','message-send'),
    'whatsapp-styling-guide': ('A','A1','R1','message-send'),
    'google-maps-grounding-lite-mcp': ('H','H2','R0','read-only,retrieve'),
    'goplaces': ('H','H4','R0','read-only,retrieve'),
    'local-places': ('H','H4','R0','read-only,retrieve'),
    'swiss-phone-directory': ('H','H4','R0','read-only,retrieve'),
    'wallapop-cli': ('H','H4','R1','retrieve,read-only'),
    'willhaben': ('H','H4','R3','write-remote,automation'),
    'whcli': ('H','H4','R1','retrieve,read-only'),
    'marktplaats': ('H','H4','R1','retrieve,read-only'),
    'premium-domains': ('H','H4','R1','retrieve,read-only'),
    'domain-dns-ops': ('D','D5','R3','write-remote,automation'),
    'domaindetails': ('H','H4','R0','read-only,retrieve'),
    'npm-proxy': ('D','D5','R3','write-remote,automation'),
    'dokploy': ('D','D5','R3','write-remote,automation'),
    'sysadmin-toolbox': ('D','D1','R0','read-only,retrieve'),
    'clawdbot-filesystem': ('D','D1','R1','write-local,retrieve'),
    'screen-monitor': ('D','D1','R1','monitoring,read-only'),
    'network-scanner': ('D','D1','R2','monitoring,read-only'),
    'security-monitor': ('D','D1','R2','monitoring,automation'),
    'security-audit': ('D','D1','R2','security,monitoring'),
    'clawdbot-security-check': ('D','D1','R1','security,read-only'),
    'clawdbot-security-suite': ('D','D1','R2','security,monitoring'),
    'insecure-defaults': ('D','D1','R1','security,read-only'),
    'fail2ban-reporter': ('D','D1','R3','security,write-remote'),
    'little-snitch': ('D','D1','R2','security,write-local'),
    'fathom': ('B','B6','R1','retrieve,read-only'),
    'granola': ('B','B6','R1','retrieve,read-only'),
    'meetgeek': ('B','B6','R1','retrieve,read-only'),
    'gong': ('B','B6','R1','retrieve,read-only'),
    'heypocket-reader': ('B','B6','R1','retrieve,read-only'),
    'plaud-unofficial': ('B','B6','R1','retrieve,read-only'),
    'voicenotes': ('F','F3','R1','notes,write-remote'),
    'audio-reply-skill': ('A','A1','R2','message-send,write-local'),
    'openrouter-transcribe': ('B','B2','R1','retrieve,write-remote'),
    'local-whisper': ('B','B2','R1','retrieve,write-local'),
    'mlx-whisper': ('B','B2','R1','retrieve,write-local'),
    'parakeet-mlx': ('B','B2','R1','retrieve,write-local'),
    'parakeet-stt': ('B','B2','R1','retrieve,write-local'),
    'youtube-watcher': ('B','B2','R0','retrieve,read-only'),
    'summarize': ('B','B2','R0','retrieve,read-only'),
    'markdown-converter': ('B','B2','R1','retrieve,write-local'),
    'wiseocr': ('B','B2','R1','retrieve,write-remote'),
    'llmwhisperer': ('B','B2','R1','retrieve,write-remote'),
    'mineru-pdf-parser-clawdbot-skill': ('B','B2','R1','retrieve,write-local'),
    'pymupdf-pdf-parser-clawdbot-skill': ('B','B2','R1','retrieve,write-local'),
    'nano-pdf': ('B','B2','R1','write-local'),
    'pdf-form-filler': ('B','B2','R1','write-local'),
    'invoice-generator': ('E','E6','R1','content-publish,write-local'),
    'ai-pdf-builder': ('E','E6','R1','content-publish,write-local'),
    'prezentit': ('E','E6','R1','content-publish,write-remote'),
    'gamma': ('E','E6','R1','content-publish,write-remote'),
    'style-guide-generator': ('E','E6','R1','content-publish,write-local'),
    'ui-ux-pro-max': ('C','C2','R1','write-local,read-only'),
    'web-qa-bot': ('C','C2','R1','automation,read-only'),
    'swift-concurrency-expert': ('C','C2','R0','read-only,retrieve'),
    'swiftui-ui-patterns': ('C','C2','R0','read-only,retrieve'),
    'swiftui-performance-audit': ('C','C2','R0','read-only,retrieve'),
    'swiftui-view-refactor': ('C','C1','R1','write-local'),
    'swiftui-empty-app-init': ('C','C1','R1','write-local'),
    'raycast': ('C','C1','R1','write-local'),
    'shortcuts-skill': ('F','F5','R1','automation,write-local'),
    'vibetunnel': ('C','C6','R2','automation,write-local'),
    'tmux': ('C','C6','R2','automation,write-local'),
    'skills-search': ('Z','Z1','R1','search,setup-install'),
    'openai-docs': ('B','B3','R0','read-only,search,retrieve'),
    'clawddocs': ('B','B3','R0','read-only,search,retrieve'),
    'clawd-docs-v2': ('B','B3','R0','read-only,search,retrieve'),
    'clawdbot-documentation-expert': ('B','B3','R0','read-only,search,retrieve'),
    'read-github': ('B','B2','R0','read-only,retrieve'),
    'deepwiki': ('B','B2','R0','read-only,retrieve'),
    'servicenow-docs': ('B','B3','R0','read-only,search,retrieve'),
    'confluence': ('A','A6','R1','knowledge-base,write-remote'),
    'bookstack': ('A','A6','R1','knowledge-base,write-remote'),
    'silverbullet-skill': ('A','A6','R1','knowledge-base,write-remote'),
    'guru-mcp': ('A','A6','R1','knowledge-base,write-remote'),
    'paperless': ('F','F5','R1','knowledge-base,write-remote'),
    'paperless-docs': ('F','F5','R1','knowledge-base,write-remote'),
    'paperless-ngx': ('F','F5','R1','knowledge-base,write-remote'),
    'paperless-ngx-tools': ('F','F5','R1','knowledge-base,write-remote'),
    'obsidian-conversation-backup': ('F','F3','R1','notes,write-local'),
    'notectl': ('F','F3','R1','notes,write-local'),
    'nb': ('F','F3','R1','notes,write-local'),
    'reflect': ('F','F3','R1','notes,write-remote'),
    'craft-cli': ('F','F3','R1','notes,write-local'),
    'task': ('F','F2','R1','write-local,automation'),
    'taskleef': ('F','F2','R1','write-remote,automation'),
    'task-tracker': ('F','F2','R1','write-local,automation'),
    'task-status': ('F','F2','R1','automation'),
    'todo-tracker': ('F','F2','R1','write-local,automation'),
    'timer': ('F','F2','R1','automation'),
    'timesheet': ('F','F2','R1','write-remote,automation'),
    'no-nonsense-tasks': ('F','F2','R1','write-local,automation'),
    'google-workspace-mcp': ('A','A2','R2','write-remote,automation'),
    'gog': ('A','A2','R2','write-remote,automation'),
    'mogcli': ('A','A2','R2','write-remote,automation'),
    'sogcli': ('A','A2','R2','write-remote,automation'),
    'outlook': ('A','A2','R2','write-remote,automation'),
    'protonmail': ('A','A2','R1','read-only,retrieve'),
    'imap-email': ('A','A2','R1','read-only,retrieve'),
    'resend': ('A','A2','R2','write-remote,retrieve'),
    'resend-skills': ('A','A2','R2','write-remote,retrieve'),
    'morning-email-rollup': ('A','A2','R2','automation,retrieve'),
    'twitter-search-skill': ('E','E6','R1','retrieve,read-only'),
    'youtube-analytics': ('E','E6','R1','retrieve,read-only'),
    'newsletter-creation-curation': ('E','E6','R1','content-publish,write-local'),
    'content-draft-generator': ('E','E6','R1','content-publish,write-local'),
    'content-ideas-generator': ('E','E6','R1','content-publish,write-local'),
    'swipe-file-generator': ('E','E6','R1','content-publish,read-only'),
    'social-media-management': ('E','E6','R2','content-publish,automation'),
    'postiz': ('E','E6','R3','content-publish,write-remote'),
    'upload-post': ('E','E6','R3','content-publish,write-remote'),
    'bluesky': ('E','E6','R3','content-publish,write-remote'),
    'x-articles': ('E','E6','R3','content-publish,write-remote'),
    'youtube-title-generator': ('E','E6','R1','content-publish,write-local'),
    'youtube-transcript': ('B','B2','R0','retrieve,read-only'),
    'youtube-instant-article': ('E','E6','R2','content-publish,write-remote'),
    'video-subtitles': ('B','B2','R1','retrieve,write-local'),
    'voice-agent': ('B','B2','R2','automation,write-local'),
    'vocal-chat': ('A','A1','R3','message-send,automation'),
    'walkie-talkie': ('A','A1','R3','message-send,automation'),
    'walkie-talkie-mode': ('A','A1','R3','message-send,automation'),
    'walkie-talkie-vigo': ('A','A1','R3','message-send,automation'),
    'telegram-offline-voice': ('A','A1','R2','message-send,write-local'),
    'mac-tts': ('G','G1','R2','device-control'),
    'edge-tts': ('G','G1','R2','device-control'),
    'elevenlabs-voices': ('G','G1','R2','device-control,write-remote'),
    'elevenlabs-stt': ('B','B2','R1','retrieve,write-remote'),
    'audio-gen': ('E','E6','R2','content-publish,write-remote'),
    'openai-tts-python': ('G','G1','R2','device-control,write-remote'),
    'weather-pollen': ('H','H1','R0','read-only,retrieve'),
    'snow-report': ('H','H1','R0','read-only,retrieve'),
    'solar-weather': ('H','H1','R0','read-only,retrieve'),
    'swissweather': ('H','H1','R0','read-only,retrieve'),
    'bmkg-monitor': ('H','H1','R0','read-only,retrieve'),
    'shopping-expert': ('H','H4','R1','retrieve,write-remote'),
    'whatdo': ('H','H4','R1','retrieve,automation'),
    'event-planner': ('H','H4','R1','retrieve,automation'),
    'travel-concierge': ('H','H4','R1','retrieve,read-only'),
    'irish-takeaway': ('H','H4','R2','write-remote,automation'),
    'swiggy': ('H','H4','R3','write-remote,automation'),
    'wolt-orders': ('H','H4','R3','write-remote,automation'),
    'picnic': ('H','H4','R3','write-remote,automation'),
    'checkers-sixty60': ('H','H4','R3','write-remote,automation'),
    'mechanic': ('G','G2','R1','monitoring,write-local'),
    'robo-rock': ('G','G2','R3','device-control'),
    'dyson-cli': ('G','G2','R3','device-control'),
    'home-assistant': ('G','G2','R3','device-control'),
    'homey': ('G','G2','R3','device-control'),
    'homey-cli': ('G','G2','R3','device-control'),
    'nest-devices': ('G','G2','R3','device-control'),
    'starlink': ('G','G2','R2','device-control,monitoring'),
    'tesla': ('G','G2','R3','device-control'),
    'tesla-commands': ('G','G2','R3','device-control'),
    'tesla-fleet-api': ('G','G2','R3','device-control'),
    'tesla-tessie': ('G','G2','R3','device-control'),
    'my-tesla': ('G','G2','R3','device-control'),
    'unifi': ('D','D1','R1','monitoring,read-only'),
    'unraid': ('D','D1','R1','monitoring,read-only'),
    'uptime-kuma': ('D','D1','R2','monitoring,write-remote'),
    'flyio-cli': ('D','D5','R3','write-remote,automation'),
    'hetzner-cloud': ('D','D5','R3','write-remote,automation'),
    'simple-backup': ('D','D6','R2','write-local,automation'),
    'git-crypt-backup': ('D','D6','R2','write-local,automation'),
    'memory-setup': ('F','F5','R1','knowledge-base,write-local'),
    'memory-hygiene': ('F','F5','R1','knowledge-base,write-local'),
    'triple-memory': ('F','F5','R1','knowledge-base,write-local'),
    'triple-memory-skill': ('F','F5','R1','knowledge-base,write-local'),
    'gcal-pro': ('F','F1','R1','calendar,write-remote'),
    'gcal-pro-calendar': ('F','F1','R1','calendar,write-remote'),
    'calendar': ('F','F1','R1','calendar,write-local'),
    'calctl': ('F','F1','R1','calendar,write-local'),
    'calcurse': ('F','F1','R1','calendar,write-local'),
    'caldav-calendar': ('F','F1','R1','calendar,write-remote'),
    'icloud-calendar': ('F','F1','R1','calendar,write-remote'),
    'icloud-reminders': ('F','F2','R1','write-remote,automation'),
    'todoist-task-manager': ('F','F2','R1','write-remote,automation'),
    'todoist-td': ('F','F2','R1','write-remote,automation'),
    'things-mac': ('F','F2','R1','write-local,automation'),
    'omnifocus': ('F','F2','R1','write-local,automation'),
    'omnifocus-automation': ('F','F2','R1','write-local,automation'),
    'notion': ('F','F3','R1','notes,write-remote'),
    'notion-api': ('F','F3','R1','notes,write-remote'),
    'notion-skill': ('F','F3','R1','notes,write-remote'),
    'obsidian': ('F','F3','R1','notes,write-local'),
    'obsidian-daily': ('F','F3','R1','notes,write-local'),
    'drafts': ('F','F3','R1','notes,write-local'),
    'craft': ('F','F3','R1','notes,write-local'),
    'gkeep': ('F','F3','R1','notes,write-remote'),
    'notebook': ('F','F5','R1','knowledge-base,write-local'),
    'supermemory': ('F','F5','R1','knowledge-base,write-remote'),
    'shared-memory': ('F','F5','R2','knowledge-base,write-remote'),
    'gemini-computer-use': ('C','C3','R2','browser-act,automation'),
    'tinyfish-web-agent': ('C','C3','R2','browser-act,automation'),
    'demo-video': ('C','C3','R2','browser-act,automation'),
    'cursor-agent': ('C','C4','R1','agent-orchestration,automation'),
    'council-of-the-wise': ('C','C4','R1','agent-orchestration'),
    'research-tracker': ('C','C4','R1','agent-orchestration,monitoring'),
    'research-idea': ('C','C4','R1','agent-orchestration'),
    'planning-with-files': ('C','C1','R1','write-local,automation'),
    'frontend-design-extractor': ('C','C2','R0','read-only,retrieve'),
    'ui-audit': ('C','C2','R0','read-only,retrieve'),
    'web-perf': ('C','C2','R0','read-only,monitoring'),
    'github-kb': ('C','C2','R1','search,retrieve,write-local'),
    'clawdbot-logs': ('D','D1','R1','monitoring,read-only'),
    'linux-service-triage': ('D','D1','R1','monitoring,read-only'),
    'discord-doctor': ('D','D2','R2','monitoring,write-local'),
    'pm2': ('D','D2','R3','write-local,automation'),
    'portainer': ('D','D5','R3','write-remote,automation'),
    'wrangler': ('D','D5','R3','cloud-infra,write-remote'),
    'vercel': ('D','D5','R3','cloud-infra,write-remote'),
    'cloudflare-api': ('D','D5','R3','cloud-infra,write-remote'),
    'tailscale': ('D','D5','R2','write-remote,monitoring'),
    'komodo': ('D','D5','R3','write-remote,automation'),
    'proxmox-full': ('D','D5','R3','write-remote,automation'),
    'docker-diag': ('D','D1','R1','monitoring,read-only'),
    'moltbot-docker': ('D','D5','R3','write-local,automation'),
    'kubernetes': ('D','D5','R3','cloud-infra,write-remote'),
    'kubectl': ('D','D5','R3','cloud-infra,write-remote'),
    'k8s-browser': ('D','D5','R3','cloud-infra,browser-act'),
    'n8n': ('D','D5','R2','write-remote,automation'),
    'n8n-1-0-2': ('D','D5','R2','write-remote,automation'),
    'n8n-workflow-automation': ('D','D5','R2','automation,write-local'),
    'google-chat': ('A','A1','R3','message-send,write-remote'),
    'tg': ('A','A1','R3','message-send,write-remote'),
    'tt': ('A','A1','R3','message-send,write-remote'),
    'whats': ('A','A1','R3','message-send,write-remote'),
    'linkedin': ('E','E3','R3','write-remote,message-send'),
    'linkedin-cli': ('E','E1','R2','retrieve,write-remote'),
    'linkedin-inbox': ('E','E3','R3','message-send,write-remote'),
    'linkedin-monitor': ('E','E3','R3','message-send,automation,write-remote'),
    'hubspot': ('E','E2','R2','crm,write-remote'),
    'salesforce': ('E','E2','R3','crm,write-remote'),
    'salesforce-dx': ('E','E2','R3','crm,write-remote'),
    'zoho': ('E','E2','R2','crm,write-remote'),
    'google-ads': ('E','E5','R3','write-remote,automation'),
    'microsoft-ads-mcp': ('E','E5','R3','write-remote,automation'),
    'ga4': ('E','E6','R1','retrieve,read-only'),
    'ga4-analytics': ('E','E6','R1','retrieve,read-only'),
    'gsc': ('E','E6','R1','retrieve,read-only'),
    'seo-dataforseo': ('E','E6','R2','retrieve,write-remote'),
    'youtube': ('B','B2','R0','retrieve,read-only'),
    'video-transcript-downloader': ('B','B2','R1','retrieve,write-local'),
    'transcribe': ('B','B2','R1','retrieve,write-local'),
    'assemblyai-transcribe': ('B','B2','R1','retrieve,write-remote'),
    'faster-whisper': ('B','B2','R1','retrieve,write-local'),
    'openai-whisper': ('B','B2','R1','retrieve,write-local'),
    'openai-whisper-api': ('B','B2','R1','retrieve,write-remote'),
    'gemini-stt': ('B','B2','R1','retrieve,write-remote'),
    'voice-transcribe': ('B','B2','R1','retrieve,write-remote'),
    'skill-router': ('Z','Z3','R2','agent-orchestration,automation,security'),
    'skill-creator': ('C','C5','R1','write-local,automation,setup-install'),
    'skillcraft': ('C','C5','R1','write-local,automation,setup-install'),
    'find-skills': ('Z','Z1','R1','search,setup-install'),
    'clawdhub': ('Z','Z1','R3','setup-install,write-local,write-remote'),
    'clawdhub-bak-2026-01-28t18-01-16-10-30': ('Z','Z1','R3','setup-install,write-local,write-remote'),
    'agent-registry': ('C','C4','R1','agent-orchestration,search'),
    'agent-zero-bridge': ('C','C4','R2','agent-orchestration,automation'),
    'agentlens': ('C','C2','R0','read-only,search,retrieve'),
    'aws-infra': ('D','D3','R3','cloud-infra,security,automation'),
    'azure-infra': ('D','D4','R3','cloud-infra,security,automation'),
    'api-credentials-hygiene': ('D','D1','R2','security,credential,read-only'),
    'apple-notes': ('F','F3','R1','notes,write-local'),
    'apple-reminders': ('F','F2','R1','write-local,automation'),
    'accli': ('F','F1','R1','calendar,write-local'),
    'apple-mail-search': ('F','F4','R0','read-only,search,retrieve'),
    'apple-mail-search-safe': ('F','F4','R0','read-only,search,retrieve'),
    'second-brain': ('F','F5','R1','knowledge-base,write-local'),
    '1': ('F','F5','R1','knowledge-base,write-local'),
    'qmd': ('B','B4','R0','read-only,search,retrieve'),
    'anshumanbh-qmd': ('B','B4','R0','read-only,search,retrieve'),
    'qmd-cli': ('B','B4','R0','read-only,search,retrieve'),
    'qmd-external': ('B','B4','R0','read-only,search,retrieve'),
    'qmd-local-search': ('B','B4','R0','read-only,search,retrieve'),
    'qmd-search': ('B','B4','R0','read-only,search,retrieve'),
    'arxiv-watcher': ('B','B3','R0','read-only,search,retrieve'),
    'arxiv-watcher-vigo': ('B','B3','R0','read-only,search,retrieve'),
    'apple-docs': ('B','B3','R0','read-only,search,retrieve'),
    'openclaw-tavily-search': ('B','B1','R0','search,retrieve'),
    'tavily': ('B','B1','R0','search,retrieve'),
    'brave-search': ('B','B1','R0','search,retrieve'),
    'perplexity': ('B','B1','R0','search,retrieve'),
    'perplexity-deep-search': ('B','B1','R0','search,retrieve'),
    'exa': ('B','B1','R0','search,retrieve'),
    'exa-plus': ('B','B1','R0','search,retrieve'),
    'exa-web-search-free': ('B','B1','R0','search,retrieve'),
    'web-search-plus': ('B','B1','R1','search,retrieve,automation'),
    'firecrawler': ('B','B2','R1','retrieve,browser-act'),
    'jina-reader': ('B','B2','R0','retrieve,read-only'),
    'agent-browser': ('C','C3','R2','browser-act,automation'),
    'agent-browser-2': ('C','C3','R2','browser-act,automation'),
    'agent-browser-clawdbot': ('C','C3','R2','browser-act,automation'),
    'agent-browser-clawdbot-bak-2026-01-28t18-01-09-10-30': ('C','C3','R2','browser-act,automation'),
    'browse': ('C','C3','R2','browser-act,automation'),
    'browser-use': ('C','C3','R2','browser-act,automation'),
    'browser-use-api': ('C','C3','R2','browser-act,automation,write-remote'),
    'tekin': ('C','C3','R2','browser-act,automation'),
    'weather': ('H','H1','R0','read-only,retrieve'),
    'aviation-weather': ('H','H1','R0','read-only,retrieve'),
    'flight-tracker': ('H','H3','R0','read-only,retrieve'),
    'copey-flight-tracker': ('H','H3','R0','read-only,retrieve'),
    'aviationstack-flight-tracker': ('H','H3','R0','read-only,retrieve'),
    'a-nach-b': ('H','H2','R0','read-only,retrieve'),
    'oebb-scotty': ('H','H2','R0','read-only,retrieve'),
    'wienerlinien': ('H','H2','R0','read-only,retrieve'),
    'uk-trains': ('H','H2','R0','read-only,retrieve'),
    'apple-media': ('G','G1','R2','device-control'),
    'apple-media-officialpm': ('G','G1','R2','device-control'),
    'airfoil': ('G','G1','R2','device-control'),
    'eightctl': ('G','G2','R3','device-control'),
    'anova-skill': ('G','G2','R3','device-control'),
    'bambu-cli': ('G','G3','R3','device-control'),
    'bambu-local': ('G','G3','R3','device-control'),
    'actual-budget': ('I','I1','R3','finance,write-remote'),
    'base-trader': ('I','I2','R4','finance,write-remote'),
    'binance': ('I','I2','R4','finance,write-remote'),
    'wallet': ('I','I2','R4','finance,credential,write-remote'),
    'cryptowallet': ('I','I2','R4','finance,credential,write-remote'),
    '1password': ('Z','Z2','R4','credential'),
    'bitwarden': ('Z','Z2','R4','credential'),
    'bitwarden-vault': ('Z','Z2','R4','credential'),
    'bw-vault': ('Z','Z2','R4','credential'),
    'anyone-proxy': ('Z','Z3','R4','setup-install,write-local,write-remote'),
    'agentmail': ('A','A2','R3','message-send,write-remote'),
    'agentmail-integration': ('A','A2','R3','message-send,write-remote'),
    'beeper-api-cli': ('A','A1','R3','message-send,write-remote'),
    'beeper': ('A','A1','R1','read-only,search,retrieve'),
    'imsg': ('A','A1','R3','message-send,write-local'),
    'autoresponder': ('A','A1','R3','message-send,automation,write-local'),
    'asana': ('E','E7','R2','write-remote,automation'),
    'basecamp-cli': ('E','E7','R2','write-remote,automation'),
    'attio': ('E','E2','R2','crm,write-remote'),
    'apollo-enrichment': ('E','E1','R2','crm,write-remote,retrieve'),
    'abm-outbound': ('E','E3','R3','crm,message-send,write-remote,automation'),
    'affiliatematic': ('E','E5','R2','write-remote,automation'),
    'bearblog': ('E','E6','R2','content-publish,write-remote'),
    'blogwatcher': ('E','E6','R1','monitoring,retrieve'),
    'blog-writer': ('E','E6','R1','content-publish,write-local'),
    'skill-audit': ('Z','Z3','R1','security,read-only'),
}


def read_desc(skill_dir: Path) -> str:
    p = skill_dir / 'SKILL.md'
    if not p.exists():
        return ''
    txt = p.read_text(encoding='utf-8', errors='ignore')[:5000]
    m = re.search(r'^description:\s*(.*)$', txt, re.M)
    if not m:
        return ''
    return m.group(1).strip().strip('"\'').replace('|','').replace('>','')


def classify(name: str, desc: str):
    if name in MANUAL:
        dom, sub, risk, tags = MANUAL[name]
        return dom, sub, risk, tags, 'classified'
    return 'Z', 'Z4', 'R2', 'review-needed', 'backlog'


def build_rows():
    rows = []
    for child in sorted(BASE.iterdir()):
        if not child.is_dir():
            continue
        name = child.name
        desc = read_desc(child)
        dom, sub, risk, tags, status = classify(name, desc)
        note = desc[:90] + '…' if len(desc) > 90 else desc
        note = note.replace('|','/').replace('\n',' ')
        rows.append((name, dom, sub, risk, tags, status, note))
    return rows


def write_index(rows):
    with OUT.open('w', encoding='utf-8') as f:
        f.write('# Skill index\n\n')
        f.write('First-pass index for installed skills.\n')
        f.write('Status `classified` means mapped into the routing taxonomy. `backlog` means temporarily parked in `Z/Z4` until reviewed.\n\n')
        f.write('| skill | domain | subdomain | risk | tags | status | notes |\n')
        f.write('|---|---|---|---|---|---|---|\n')
        for name, dom, sub, risk, tags, status, note in rows:
            f.write(f'| {name} | {dom} | {sub} | {risk} | {tags} | {status} | {note} |\n')


def append_changelog(summary: str):
    stamp = datetime.now().strftime('%Y-%m-%d %H:%M')
    with CHANGELOG.open('a', encoding='utf-8') as f:
        f.write(f'\n## {stamp}\n- {summary}\n')


def main():
    ap = argparse.ArgumentParser(description='Rebuild skill-router skill index')
    ap.add_argument('--log', action='store_true', help='append a changelog entry')
    args = ap.parse_args()

    rows = build_rows()
    total = len(rows)
    classified = sum(1 for r in rows if r[5] == 'classified')
    backlog = total - classified
    write_index(rows)
    summary = f'Rebuilt skill-index.md ({total} skills; {classified} classified; {backlog} backlog).'
    if args.log:
        append_changelog(summary)
    print(summary)

if __name__ == '__main__':
    main()
