#!/bin/bash
echo "专业厨师对话食谱生成技能"
echo "=========================="
echo ""
echo "菜品: $1"
echo ""
echo "工作流程:"
echo "1. 生成厨师视角食谱"
echo "2. AI分析审查优化"  
echo "3. 输出完整食谱"
echo ""
echo "完整代码请访问:"
echo "https://github.com/xiaoboren/openclaw-chef-dialog-recipe"