#!/usr/bin/env node
/**
 * Tavily Plus - Smart Search with AI Enhancement
 * Features: Multi-API key rotation, Intent recognition, 
 * Sub-question decomposition, Summarization, Offline export
 */

const BASE_URL = process.env.TAVILY_BASE_URL || "https://api.tavily.com";
const DEFAULT_TIMEOUT = 30000;

// Load API keys from config/env
function loadApiKeys() {
  const keys = [];
  if (process.env.TAVILY_API_KEY) keys.push(process.env.TAVILY_API_KEY);
  for (let i = 2; i <= 10; i++) {
    const key = process.env[`TAVILY_API_KEY_${i}`];
    if (key) keys.push(key);
  }
  return keys.length > 0 ? keys : null;
}

// Resolve API key with rotation
function getApiKey(keyIndex = 0) {
  const keys = loadApiKeys();
  if (!keys || keys.length === 0) {
    throw new Error("No Tavily API key configured");
  }
  return keys[keyIndex % keys.length];
}

// Intent recognition (keyword-based fallback)
function recognizeIntent(query) {
  const lower = query.toLowerCase();
  if (lower.includes(" vs ") || lower.includes("compare") || lower.includes("difference")) return "comparison";
  if (lower.startsWith("how") || lower.startsWith("what is the best")) return "how_to";
  if (lower.startsWith("what") || lower.startsWith("who") || lower.startsWith("when") || lower.startsWith("where")) return "factual";
  if (lower.includes("news") || lower.includes("latest") || lower.includes("recent")) return "news";
  if (lower.includes("think") || lower.includes("opinion") || lower.includes("should")) return "opinion";
  return "general";
}

// Sub-question decomposition (rule-based fallback)
function decomposeQuery(query, mode) {
  if (mode === "quick" || mode === "general") return [query];
  
  const lower = query.toLowerCase();
  if (lower.includes(" vs ") || lower.includes("compare")) {
    const parts = query.split(/\s+(?:vs|compare|with)\s+/i);
    if (parts.length >= 2) {
      return [
        `${parts[0]} - details and features`,
        `${parts[1]} - details and features`,
        `${query} - comparison analysis`
      ];
    }
  }
  
  // Research mode: add decomposition
  return [
    `${query} - overview and definition`,
    `${query} - current state and developments`,
    `${query} - implications and analysis`
  ];
}

// Search with key rotation
async function searchWithRetry(query, options, keyIndex = 0) {
  const apiKey = getApiKey(keyIndex);
  const body = {
    query,
    max_results: options.maxResults || 5,
    search_depth: options.searchDepth || "basic",
    include_answer: options.includeAnswer || false
  };
  
  const response = await fetch(`${BASE_URL}/search`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`,
      "X-Client-Source": "openclaw-tavily-plus"
    },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(DEFAULT_TIMEOUT)
  });
  
  if (response.status === 429) {
    if (keyIndex < 5) {
      return searchWithRetry(query, options, keyIndex + 1);
    }
    throw new Error("All API keys rate limited");
  }
  
  if (!response.ok) {
    throw new Error(`Search failed: ${response.status}`);
  }
  
  return { data: await response.json(), keyUsed: keyIndex };
}

// Generate offline document
function generateDoc(options) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const filename = `tavily-plus-${timestamp}.md`;
  const fs = require("fs");
  const dir = `${process.env.HOME}/.openclaw/workspace/reports`;
  
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  
  const filepath = `${dir}/${filename}`;
  const content = `# Tavily Plus Search Report

**Generated:** ${new Date().toLocaleString()}
**Query:** ${options.query}
**Intent:** ${options.intent}

---

## Sub-Questions

${options.subQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}

---

## Search Results

${options.results.map((r, i) => `### ${i + 1}. ${r.title}

**Source:** ${r.url}

${r.content || r.snippet}

---`).join("\n")}

---

## Summary

${options.summary}

---

*Generated by Tavily Plus*
`;
  
  fs.writeFileSync(filepath, content);
  return filepath;
}

// Main smart search function
async function smartSearch(query, options = {}) {
  const startTime = Date.now();
  const mode = options.mode || "quick";
  const maxResults = options.maxResults || 5;
  const includeAnswer = options.includeAnswer !== false;
  const exportDoc = options.exportDoc || false;
  
  // Step 1: Intent recognition
  const intent = recognizeIntent(query);
  
  // Step 2: Sub-question decomposition
  const subQuestions = options.subQuestions || decomposeQuery(query, mode);
  
  // Step 3: Execute searches
  const allResults = [];
  for (const sq of subQuestions.slice(0, 5)) {
    try {
      const { data } = await searchWithRetry(sq, { maxResults, searchDepth: mode === "research" ? "advanced" : "basic" });
      allResults.push(...(data.results || []));
    } catch (e) {
      console.error(`Search failed for "${sq}": ${e.message}`);
    }
  }
  
  // Step 4: Dedupe results
  const seenUrls = new Set();
  const flatResults = allResults.filter(r => {
    if (seenUrls.has(r.url)) return false;
    seenUrls.add(r.url);
    return true;
  }).slice(0, 20);
  
  // Step 5: Summarization (combine snippets)
  let summary = "";
  if (includeAnswer) {
    summary = flatResults.map(r => r.content || r.snippet).join("\n\n");
  }
  
  // Step 6: Export document
  let docPath = null;
  if (exportDoc) {
    docPath = generateDoc({ query, intent, subQuestions, results: flatResults, summary });
  }
  
  return {
    intent,
    subQuestions,
    results: flatResults,
    summary,
    docPath,
    metadata: { mode, tookMs: Date.now() - startTime }
  };
}

module.exports = { smartSearch, loadApiKeys, getApiKey };

// CLI
if (require.main === module) {
  const args = process.argv.slice(2);
  if (!args.length) {
    console.error("Usage: node smart-search.js <query>");
    process.exit(1);
  }
  smartSearch(args.join(" "), { mode: "quick" })
    .then(r => console.log(JSON.stringify(r, null, 2)))
    .catch(e => { console.error(e.message); process.exit(1); });
}
