#!/usr/bin/env bash
set -euo pipefail

CMD="${1:-help}"
TASK="${2:-general}"
CONTEXT="${3:-excel}"

show_help() {
  cat <<'HELP'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  📊 Macro Helper — Excel VBA 助手
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Usage: bash macro.sh <command> [task] [context]

Commands:
  generate   根据需求生成VBA宏代码
  explain    逐行解释VBA代码功能
  debug      诊断VBA错误并提供修复
  template   VBA模板库（数据处理/报表/邮件/文件操作）
  convert    格式转换（VBA↔Python/JS/Google Apps Script）
  optimize   VBA代码性能优化建议

Options:
  task       任务描述 (data/report/email/file/format/general)
  context    上下文 (excel/access/word/outlook/general)

Examples:
  bash macro.sh generate data excel
  bash macro.sh template report excel
  bash macro.sh convert data python

  Powered by BytesAgain | bytesagain.com | hello@bytesagain.com
HELP
}

cmd_generate() {
  local task="$1" context="$2"
  cat <<EOF
# 🔧 VBA Code Generator

**Task:** ${task} | **Context:** ${context}

---

## Generated VBA Code

\`\`\`vba
Option Explicit

'=============================================================
' Module:  Mod${task^}
' Purpose: ${task} processing macro
' Author:  Generated by Macro Helper
' Date:    $(date +%Y-%m-%d)
'=============================================================

Sub Main_${task^}()
    '--- Performance optimization
    Application.ScreenUpdating = False
    Application.Calculation = xlCalculationManual
    Application.EnableEvents = False

    On Error GoTo ErrorHandler

    '--- Configuration
    Dim ws As Worksheet
    Dim lastRow As Long
    Dim lastCol As Long
    Dim startTime As Double

    startTime = Timer

    Set ws = ThisWorkbook.Sheets("{{sheet_name}}")
    lastRow = ws.Cells(ws.Rows.Count, "A").End(xlUp).Row
    lastCol = ws.Cells(1, ws.Columns.Count).End(xlToLeft).Column

    '--- Main logic
    ' TODO: Add your specific ${task} logic here
    Dim i As Long
    For i = 2 To lastRow
        ' Process each row
        ' ws.Cells(i, 1).Value = ...
    Next i

    '--- Summary
    MsgBox "处理完成！" & vbCrLf & _
           "处理行数: " & lastRow - 1 & vbCrLf & _
           "耗时: " & Format(Timer - startTime, "0.00") & " 秒", _
           vbInformation, "完成"

CleanUp:
    '--- Restore settings
    Application.ScreenUpdating = True
    Application.Calculation = xlCalculationAutomatic
    Application.EnableEvents = True
    Set ws = Nothing
    Exit Sub

ErrorHandler:
    MsgBox "错误 " & Err.Number & ": " & Err.Description, _
           vbCritical, "错误"
    Resume CleanUp
End Sub
\`\`\`

---

## Code Structure Best Practices

\`\`\`vba
' ┌─────────────────────────────────────┐
' │  1. Option Explicit                 │
' │  2. Constants & Module Variables    │
' │  3. Main Procedure                 │
' │     ├─ Performance settings OFF    │
' │     ├─ Error handler setup         │
' │     ├─ Variable declarations       │
' │     ├─ Main logic                  │
' │     ├─ CleanUp label              │
' │     └─ ErrorHandler label         │
' │  4. Helper Functions               │
' │  5. Utility Functions              │
' └─────────────────────────────────────┘
\`\`\`

---

## Common Snippets

### Find Last Row
\`\`\`vba
lastRow = ws.Cells(ws.Rows.Count, "A").End(xlUp).Row
\`\`\`

### Loop Through Range
\`\`\`vba
Dim cell As Range
For Each cell In ws.Range("A2:A" & lastRow)
    ' Process cell.Value
Next cell
\`\`\`

### Array Processing (Fast)
\`\`\`vba
Dim data As Variant
data = ws.Range("A1:Z" & lastRow).Value
' Process data(row, col) in memory
ws.Range("A1:Z" & lastRow).Value = data
\`\`\`

### Dictionary (Unique Values)
\`\`\`vba
Dim dict As Object
Set dict = CreateObject("Scripting.Dictionary")
For i = 2 To lastRow
    dict(ws.Cells(i, 1).Value) = ws.Cells(i, 2).Value
Next i
\`\`\`
EOF
}

cmd_explain() {
  local task="$1" context="$2"
  cat <<EOF
# 🔍 VBA Code Explainer

**Context:** ${context}

---

## How to Use

Paste your VBA code and I'll provide:

### Line-by-Line Explanation Format

\`\`\`vba
' ─── Line 1 ───────────────────────────────
Option Explicit
' 📖 强制要求所有变量必须声明后才能使用
' ⭐ 这是最佳实践，能避免拼写错误导致的bug

' ─── Line 2 ───────────────────────────────
Sub MyMacro()
' 📖 定义一个名为MyMacro的子过程(宏)
' ⭐ Sub = Subroutine，不返回值。用Function返回值

' ─── Line 3 ───────────────────────────────
Application.ScreenUpdating = False
' 📖 关闭屏幕刷新，防止执行过程中屏幕闪烁
' ⭐ 性能优化关键！可提速10-100倍
' ⚠️ 记得在结束时设回True
\`\`\`

---

## VBA Concept Reference

| Concept | Description | Example |
|---------|-------------|---------|
| Sub | 子过程，不返回值 | \`Sub DoWork()\` |
| Function | 函数，返回值 | \`Function Add(a, b) As Long\` |
| Dim | 声明变量 | \`Dim x As Long\` |
| Set | 赋值对象变量 | \`Set ws = Sheets(1)\` |
| With | 简化重复引用 | \`With ws.Range("A1")\` |
| For Each | 遍历集合 | \`For Each cell In Range\` |
| On Error | 错误处理 | \`On Error GoTo Handler\` |

---

## Data Types Quick Reference

| Type | Size | Range | Use For |
|------|------|-------|---------|
| Byte | 1B | 0-255 | Small integers |
| Integer | 2B | -32K~32K | ⚠️ Prefer Long |
| Long | 4B | ±2.1B | Row counts, IDs |
| Double | 8B | ±1.8E308 | Decimals, currency |
| String | Varies | ~2B chars | Text |
| Boolean | 2B | True/False | Flags |
| Variant | 16B+ | Anything | ⚠️ Avoid, slow |
| Date | 8B | Dates | Date/time values |
EOF
}

cmd_debug() {
  local task="$1" context="$2"
  cat <<EOF
# 🐛 VBA Debugger

**Context:** ${context}

---

## Common VBA Errors & Fixes

### Runtime Errors

| Error # | Name | Common Cause | Fix |
|---------|------|-------------|-----|
| 9 | Subscript out of range | Sheet/array index doesn't exist | Check sheet name spelling, array bounds |
| 13 | Type mismatch | Wrong data type | Use CStr/CLng/CDbl conversion |
| 91 | Object variable not set | Missing Set keyword | Add \`Set obj = ...\` |
| 424 | Object required | Using non-object as object | Check variable type |
| 438 | Object doesn't support | Wrong method/property | Check object documentation |
| 1004 | Application/Object error | Protected sheet, invalid range | Unprotect sheet, validate range |

---

### Debugging Techniques

\`\`\`vba
' 1. Immediate Window (Ctrl+G)
Debug.Print "Variable x = " & x
Debug.Print TypeName(myVar)

' 2. Breakpoints (F9)
' Click left margin to add/remove

' 3. Step Through (F8)
' Execute one line at a time

' 4. Watch Window
' Add expressions to monitor

' 5. Error Info
Debug.Print "Error: " & Err.Number & " - " & Err.Description
\`\`\`

---

### Defensive Coding Patterns

\`\`\`vba
' Check if sheet exists
Function SheetExists(sheetName As String) As Boolean
    On Error Resume Next
    SheetExists = Not ThisWorkbook.Sheets(sheetName) Is Nothing
    On Error GoTo 0
End Function

' Check if range is empty
If WorksheetFunction.CountA(ws.Range("A:A")) = 0 Then
    MsgBox "No data found!"
    Exit Sub
End If

' Safe string conversion
Function SafeStr(v As Variant) As String
    If IsNull(v) Or IsEmpty(v) Then
        SafeStr = ""
    Else
        SafeStr = CStr(v)
    End If
End Function
\`\`\`

---

## Debug Checklist

- [ ] \`Option Explicit\` at top of every module?
- [ ] All variables declared with explicit types?
- [ ] Error handler in every Sub/Function?
- [ ] ScreenUpdating restored in CleanUp?
- [ ] Sheet names match exactly (case-sensitive)?
- [ ] Range references valid (no merged cells issues)?
- [ ] Object variables Set to Nothing in CleanUp?
EOF
}

cmd_template() {
  local task="$1" context="$2"
  cat <<EOF
# 📚 VBA Template Library

**Category:** ${task} | **Platform:** ${context}

---

## Template 1: Data Cleaning 数据清洗

\`\`\`vba
Sub CleanData()
    Application.ScreenUpdating = False
    On Error GoTo ErrHandler

    Dim ws As Worksheet: Set ws = ActiveSheet
    Dim lastRow As Long: lastRow = ws.Cells(ws.Rows.Count, 1).End(xlUp).Row
    Dim i As Long

    For i = lastRow To 2 Step -1
        ' Remove blank rows
        If WorksheetFunction.CountA(ws.Rows(i)) = 0 Then
            ws.Rows(i).Delete
        End If
    Next i

    ' Trim spaces
    Dim cell As Range
    For Each cell In ws.UsedRange
        If Not IsEmpty(cell) And VarType(cell.Value) = vbString Then
            cell.Value = Trim(cell.Value)
        End If
    Next cell

    MsgBox "Data cleaned!", vbInformation
ErrHandler:
    Application.ScreenUpdating = True
End Sub
\`\`\`

---

## Template 2: Report Generator 报表生成

\`\`\`vba
Sub GenerateReport()
    Application.ScreenUpdating = False
    On Error GoTo ErrHandler

    Dim wsSrc As Worksheet: Set wsSrc = Sheets("Data")
    Dim wsRpt As Worksheet

    ' Create or clear report sheet
    On Error Resume Next
    Set wsRpt = Sheets("Report")
    On Error GoTo ErrHandler

    If wsRpt Is Nothing Then
        Set wsRpt = Sheets.Add(After:=Sheets(Sheets.Count))
        wsRpt.Name = "Report"
    Else
        wsRpt.Cells.Clear
    End If

    ' Headers
    wsRpt.Range("A1:D1").Value = Array("Category", "Count", "Total", "Average")
    wsRpt.Range("A1:D1").Font.Bold = True

    ' Add report logic here...

    wsRpt.Columns("A:D").AutoFit
    MsgBox "Report generated!", vbInformation

ErrHandler:
    Application.ScreenUpdating = True
End Sub
\`\`\`

---

## Template 3: Email via Outlook 邮件发送

\`\`\`vba
Sub SendEmail()
    Dim olApp As Object: Set olApp = CreateObject("Outlook.Application")
    Dim olMail As Object: Set olMail = olApp.CreateItem(0)

    With olMail
        .To = "recipient@example.com"
        .CC = ""
        .Subject = "Report - " & Format(Date, "yyyy-mm-dd")
        .HTMLBody = "<h2>Report</h2><p>Please find attached.</p>"
        .Attachments.Add ThisWorkbook.FullName
        .Display  ' Use .Send to send directly
    End With

    Set olMail = Nothing
    Set olApp = Nothing
End Sub
\`\`\`

---

## Template 4: File Operations 文件操作

\`\`\`vba
Sub ImportCSVFiles()
    Dim folderPath As String
    Dim fileName As String

    folderPath = ThisWorkbook.Path & "\\data\\"
    fileName = Dir(folderPath & "*.csv")

    Do While fileName <> ""
        ' Import each CSV
        Workbooks.Open folderPath & fileName
        ' Process...
        ActiveWorkbook.Close SaveChanges:=False
        fileName = Dir()
    Loop
End Sub
\`\`\`

---

## More Templates Available

| Category | Templates |
|----------|-----------|
| Data Processing | Dedup, VLOOKUP replacement, Pivot summary |
| Formatting | Conditional format, Header styling, Print setup |
| Charts | Auto-chart, Dashboard update |
| User Forms | Input dialog, Progress bar, Settings form |
| Utilities | Timer, Logger, Config reader |
EOF
}

cmd_convert() {
  local task="$1" context="$2"
  cat <<EOF
# 🔄 Code Conversion Guide

**From:** VBA | **To:** ${context}

---

## VBA → Python (openpyxl/pandas)

| VBA | Python (pandas) |
|-----|-----------------|
| \`Set ws = Sheets("Data")\` | \`df = pd.read_excel("file.xlsx", sheet_name="Data")\` |
| \`lastRow = ws.Cells(Rows.Count,1).End(xlUp).Row\` | \`len(df)\` |
| \`ws.Cells(i, 1).Value\` | \`df.iloc[i-2, 0]\` |
| \`For i = 2 To lastRow\` | \`for idx, row in df.iterrows():\` |
| \`WorksheetFunction.Sum(...)\` | \`df['col'].sum()\` |
| \`ws.Range("A1").AutoFilter\` | \`df[df['col'] > value]\` |

### Example Conversion

**VBA:**
\`\`\`vba
Sub SumByCategory()
    Dim dict As Object: Set dict = CreateObject("Scripting.Dictionary")
    Dim ws As Worksheet: Set ws = Sheets("Data")
    Dim i As Long
    For i = 2 To ws.Cells(Rows.Count, 1).End(xlUp).Row
        Dim key As String: key = ws.Cells(i, 1).Value
        If dict.Exists(key) Then
            dict(key) = dict(key) + ws.Cells(i, 2).Value
        Else
            dict(key) = ws.Cells(i, 2).Value
        End If
    Next i
End Sub
\`\`\`

**Python:**
\`\`\`python
import pandas as pd

df = pd.read_excel("file.xlsx", sheet_name="Data")
result = df.groupby(df.columns[0])[df.columns[1]].sum()
print(result)
\`\`\`

---

## VBA → Google Apps Script

| VBA | Google Apps Script |
|-----|-------------------|
| \`ThisWorkbook\` | \`SpreadsheetApp.getActive()\` |
| \`Sheets("Name")\` | \`ss.getSheetByName("Name")\` |
| \`ws.Cells(r, c).Value\` | \`sheet.getRange(r, c).getValue()\` |
| \`MsgBox\` | \`Browser.msgBox()\` |
| \`Application.ScreenUpdating\` | N/A (no equivalent needed) |

---

## VBA → JavaScript (SheetJS/ExcelJS)

\`\`\`javascript
// Node.js with ExcelJS
const ExcelJS = require('exceljs');
const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile('file.xlsx');
const sheet = workbook.getWorksheet('Data');

sheet.eachRow((row, rowNumber) => {
    if (rowNumber > 1) {
        console.log(row.getCell(1).value);
    }
});
\`\`\`
EOF
}

cmd_optimize() {
  local task="$1" context="$2"
  cat <<EOF
# ⚡ VBA Performance Optimization

**Task:** ${task}

---

## Top 10 Optimization Rules

### 1. Disable Screen Updates ⭐⭐⭐
\`\`\`vba
Application.ScreenUpdating = False    ' 10-100x speedup
Application.Calculation = xlCalculationManual
Application.EnableEvents = False
\`\`\`

### 2. Use Arrays Instead of Cell-by-Cell ⭐⭐⭐
\`\`\`vba
' ❌ SLOW: 10,000 cells = 10,000 read operations
For i = 1 To 10000
    result = result + ws.Cells(i, 1).Value
Next i

' ✅ FAST: 1 read + memory processing
Dim data As Variant
data = ws.Range("A1:A10000").Value
For i = 1 To 10000
    result = result + data(i, 1)
Next i
\`\`\`

### 3. Avoid Select/Activate ⭐⭐⭐
\`\`\`vba
' ❌ SLOW
Sheets("Data").Select
Range("A1").Select
Selection.Value = "Hello"

' ✅ FAST
Sheets("Data").Range("A1").Value = "Hello"
\`\`\`

### 4. Use With Blocks ⭐⭐
\`\`\`vba
With ws.Range("A1:D1")
    .Font.Bold = True
    .Font.Size = 12
    .Interior.Color = RGB(0, 120, 215)
    .Font.Color = vbWhite
End With
\`\`\`

### 5. Declare Specific Types ⭐⭐
\`\`\`vba
' ❌ Variant is 2-10x slower
Dim x As Variant

' ✅ Use specific type
Dim x As Long
\`\`\`

### 6. Use Long Instead of Integer ⭐
\`\`\`vba
' ❌ Integer is actually slower on 32/64-bit systems
Dim i As Integer

' ✅ Long is native word size
Dim i As Long
\`\`\`

### 7. Minimize Worksheet Function Calls
### 8. Use Early Binding When Possible
### 9. Avoid Clipboard Operations (Copy/Paste)
### 10. Release Object References

---

## Performance Comparison

| Operation | Time (10K rows) | Time (100K rows) |
|-----------|-----------------|-------------------|
| Cell-by-cell read | ~5s | ~50s |
| Array read | ~0.05s | ~0.5s |
| With Select | ~3s | ~30s |
| Without Select | ~0.5s | ~5s |
| ScreenUpdating ON | ~10s | ~100s |
| ScreenUpdating OFF | ~1s | ~10s |
EOF
}

case "$CMD" in
  generate) cmd_generate "$TASK" "$CONTEXT" ;;
  explain)  cmd_explain "$TASK" "$CONTEXT" ;;
  debug)    cmd_debug "$TASK" "$CONTEXT" ;;
  template) cmd_template "$TASK" "$CONTEXT" ;;
  convert)  cmd_convert "$TASK" "$CONTEXT" ;;
  optimize) cmd_optimize "$TASK" "$CONTEXT" ;;
  help|--help|-h) show_help ;;
  *)
    echo "❌ Unknown command: $CMD"
    echo "Run 'bash macro.sh help' for usage."
    exit 1
    ;;
esac
