javascript:
document.writeln("<!DOCTYPE html>");
document.writeln("<html lang='zh-CN'>");
document.writeln("<head>");
document.writeln("    <meta charset='UTF-8'>");
document.writeln("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
document.writeln("    <title>股票持仓监控 - 贾维斯系统</title>");
document.writeln("    <style>");
document.writeln("        * { margin: 0; padding: 0; box-sizing: border-box; }");
document.writeln("        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 20px; }");
document.writeln("        .container { max-width: 1200px; margin: 0 auto; }");
document.writeln("        .header { background: rgba(255,255,255,0.95); border-radius: 12px; padding: 20px 30px; margin-bottom: 20px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }");
document.writeln("        .header h1 { color: #1a1a2e; font-size: 24px; margin-bottom: 5px; }");
document.writeln("        .header .subtitle { color: #666; font-size: 14px; }");
document.writeln("        .refresh-btn { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border: none; padding: 10px 20px; border-radius: 8px; cursor: pointer; font-size: 14px; transition: transform 0.2s, box-shadow 0.2s; }");
document.writeln("        .refresh-btn:hover { transform: translateY(-2px); box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4); }");
document.writeln("        .overview-cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 15px; margin-bottom: 20px; }");
document.writeln("        .card { background: rgba(255,255,255,0.95); border-radius: 12px; padding: 20px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); transition: transform 0.2s; }");
document.writeln("        .card:hover { transform: translateY(-3px); }");
document.writeln("        .card-label { color: #666; font-size: 13px; margin-bottom: 8px; }");
document.writeln("        .card-value { font-size: 24px; font-weight: bold; color: #1a1a2e; }");
document.writeln("        .card-value.positive { color: #e74c3c; }");
document.writeln("        .card-value.negative { color: #27ae60; }");
document.writeln("        .card-sub { font-size: 12px; color: #999; margin-top: 5px; }");
document.writeln("        .holdings-table { background: rgba(255,255,255,0.95); border-radius: 12px; padding: 20px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); overflow-x: auto; }");
document.writeln("        .holdings-table h2 { color: #1a1a2e; font-size: 18px; margin-bottom: 15px; display: flex; align-items: center; gap: 10px; }");
document.writeln("        .holdings-table h2 .badge { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 3px 10px; border-radius: 20px; font-size: 12px; }");
document.writeln("        table { width: 100%; border-collapse: collapse; }");
document.writeln("        th { background: #f8f9fa; padding: 12px 15px; text-align: left; color: #666; font-size: 13px; font-weight: 600; border-bottom: 2px solid #e9ecef; }");
document.writeln("        td { padding: 15px; border-bottom: 1px solid #e9ecef; color: #1a1a2e; font-size: 14px; }");
document.writeln("        tr:hover { background: #f8f9fa; }");
document.writeln("        .stock-code { font-weight: bold; color: #667eea; }");
document.writeln("        .stock-name { color: #1a1a2e; }");
document.writeln("        .price { font-weight: 600; }");
document.writeln("        .profit-positive { color: #e74c3c; font-weight: 600; }");
document.writeln("        .profit-negative { color: #27ae60; font-weight: 600; }");
document.writeln("        .status-badge { padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }");
document.writeln("        .status-profit { background: #fee; color: #e74c3c; }");
document.writeln("        .status-loss { background: #efe; color: #27ae60; }");
document.writeln("        .status-wait { background: #f0f0f0; color: #666; }");
document.writeln("        .transactions { background: rgba(255,255,255,0.95); border-radius: 12px; padding: 20px; margin-top: 20px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }");
document.writeln("        .transactions h2 { color: #1a1a2e; font-size: 18px; margin-bottom: 15px; }");
document.writeln("        .alerts { background: rgba(255,255,255,0.95); border-radius: 12px; padding: 20px; margin-top: 20px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }");
document.writeln("        .alerts h2 { color: #1a1a2e; font-size: 18px; margin-bottom: 15px; }");
document.writeln("        .alert-item { display: flex; align-items: center; padding: 12px; background: #f8f9fa; border-radius: 8px; margin-bottom: 10px; }");
document.writeln("        .alert-icon { width: 30px; height: 30px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 12px; font-size: 16px; }");
document.writeln("        .alert-icon.safe { background: #d4edda; color: #28a745; }");
document.writeln("        .alert-icon.warning { background: #fff3cd; color: #856404; }");
document.writeln("        .alert-icon.danger { background: #f8d7da; color: #dc3545; }");
document.writeln("        .loading { display: none; text-align: center; padding: 40px; }");
document.writeln("        .spinner { width: 40px; height: 40px; border: 4px solid #f3f3f3; border-top: 4px solid #667eea; border-radius: 50%; animation: spin 1s linear infinite; margin: 0 auto 15px; }");
document.writeln("        @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }");
document.writeln("        .update-time { text-align: right; color: #999; font-size: 12px; margin-top: 10px; }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class='container'>");
document.writeln("        <div class='header'>");
document.writeln("            <div style='display: flex; justify-content: space-between; align-items: center;'>");
document.writeln("                <div>");
document.writeln("                    <h1>📊 股票持仓监控</h1>");
document.writeln("                    <div class='subtitle'>贾维斯智能交易系统 | 模拟账户</div>");
document.writeln("                </div>");
document.writeln("                <button class='refresh-btn' onclick='refreshData()'>🔄 刷新数据</button>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class='overview-cards'>");
document.writeln("            <div class='card'>");
document.writeln("                <div class='card-label'>初始资金</div>");
document.writeln("                <div class='card-value'>10,000.00</div>");
document.writeln("                <div class='card-sub'>元</div>");
document.writeln("            </div>");
document.writeln("            <div class='card'>");
document.writeln("                <div class='card-label'>当前市值</div>");
document.writeln("                <div class='card-value' id='market-value'>9,422.00</div>");
document.writeln("                <div class='card-sub'>元</div>");
document.writeln("            </div>");
document.writeln("            <div class='card'>");
document.writeln("                <div class='card-label'>可用余额</div>");
document.writeln("                <div class='card-value' id='balance'>578.00</div>");
document.writeln("                <div class='card-sub'>元</div>");
document.writeln("            </div>");
document.writeln("            <div class='card'>");
document.writeln("                <div class='card-label'>总盈亏</div>");
document.writeln("                <div class='card-value positive' id='total-profit'>+80.00</div>");
document.writeln("                <div class='card-sub'>元</div>");
document.writeln("            </div>");
document.writeln("            <div class='card'>");
document.writeln("                <div class='card-label'>收益率</div>");
document.writeln("                <div class='card-value positive' id='total-rate'>+0.80%</div>");
document.writeln("                <div class='card-sub'>初始资金计算</div>");
document.writeln("            </div>");
document.writeln("            <div class='card'>");
document.writeln("                <div class='card-label'>仓位</div>");
document.writeln("                <div class='card-value' id='position'>94.2%</div>");
document.writeln("                <div class='card-sub'>持仓占比</div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class='holdings-table'>");
document.writeln("            <h2>📈 当前持仓 <span class='badge' id='holding-count'>3 只</span></h2>");
document.writeln("            <table>");
document.writeln("                <thead>");
document.writeln("                    <tr>");
document.writeln("                        <th>代码</th>");
document.writeln("                        <th>名称</th>");
document.writeln("                        <th>数量</th>");
document.writeln("                        <th>成本价</th>");
document.writeln("                        <th>当前价</th>");
document.writeln("                        <th>盈亏%</th>");
document.writeln("                        <th>盈亏额</th>");
document.writeln("                        <th>市值</th>");
document.writeln("                        <th>状态</th>");
document.writeln("                    </tr>");
document.writeln("                </thead>");
document.writeln("                <tbody id='holdings-body'>");
document.writeln("                    <tr>");
document.writeln("                        <td class='stock-code'>600745</td>");
document.writeln("                        <td class='stock-name'>闻泰科技</td>");
document.writeln("                        <td>100</td>");
document.writeln("                        <td>32.66</td>");
document.writeln("                        <td class='price' id='price-600745'>33.52</td>");
document.writeln("                        <td class='profit-positive' id='profit-pct-600745'>+2.63%</td>");
document.writeln("                        <td class='profit-positive' id='profit-amt-600745'>+86.0</td>");
document.writeln("                        <td>3,352</td>");
document.writeln("                        <td><span class='status-badge status-profit'>✅ 盈利</span></td>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                        <td class='stock-code'>600222</td>");
document.writeln("                        <td class='stock-name'>太龙药业</td>");
document.writeln("                        <td>400</td>");
document.writeln("                        <td>7.37</td>");
document.writeln("                        <td class='price' id='price-600222'>7.32</td>");
document.writeln("                        <td class='profit-negative' id='profit-pct-600222'>-0.68%</td>");
document.writeln("                        <td class='profit-negative' id='profit-amt-600222'>-20.0</td>");
document.writeln("                        <td>2,928</td>");
document.writeln("                        <td><span class='status-badge status-loss'>⚠️ 亏损</span></td>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                        <td class='stock-code'>002371</td>");
document.writeln("                        <td class='stock-name'>北方华创</td>");
document.writeln("                        <td>100</td>");
document.writeln("                        <td>45.68</td>");
document.writeln("                        <td class='price' id='price-002371'>45.70</td>");
document.writeln("                        <td class='profit-positive' id='profit-pct-002371'>+0.04%</td>");
document.writeln("                        <td class='profit-positive' id='profit-amt-002371'>+2.0</td>");
document.writeln("                        <td>4,570</td>");
document.writeln("                        <td><span class='status-badge status-profit'>✅ 盈利</span></td>");
document.writeln("                    </tr>");
document.writeln("                </tbody>");
document.writeln("            </table>");
document.writeln("            <div class='update-time' id='update-time'>最后更新：2026-03-12 11:40:00</div>");
document.writeln("        </div>");
document.writeln("        <div class='transactions'>");
document.writeln("            <h2>📝 今日交易记录</h2>");
document.writeln("            <table>");
document.writeln("                <thead>");
document.writeln("                    <tr>");
document.writeln("                        <th>时间</th>");
document.writeln("                        <th>操作</th>");
document.writeln("                        <th>代码</th>");
document.writeln("                        <th>名称</th>");
document.writeln("                        <th>价格</th>");
document.writeln("                        <th>数量</th>");
document.writeln("                        <th>金额</th>");
document.writeln("                    </tr>");
document.writeln("                </thead>");
document.writeln("                <tbody>");
document.writeln("                    <tr>");
document.writeln("                        <td>09:38</td>");
document.writeln("                        <td style='color: #27ae60;'>卖出</td>");
document.writeln("                        <td>600537</td>");
document.writeln("                        <td>亿晶光电</td>");
document.writeln("                        <td>3.37</td>");
document.writeln("                        <td>300</td>");
document.writeln("                        <td>1,011</td>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                        <td>09:38</td>");
document.writeln("                        <td style='color: #e74c3c;'>买入</td>");
document.writeln("                        <td>002371</td>");
document.writeln("                        <td>北方华创</td>");
document.writeln("                        <td>45.68</td>");
document.writeln("                        <td>100</td>");
document.writeln("                        <td>4,568</td>");
document.writeln("                    </tr>");
document.writeln("                </tbody>");
document.writeln("            </table>");
document.writeln("        </div>");
document.writeln("        <div class='alerts'>");
document.writeln("            <h2>🚨 预警监控</h2>");
document.writeln("            <div class='alert-item'>");
document.writeln("                <div class='alert-icon safe'>✅</div>");
document.writeln("                <div><strong>600745 闻泰科技</strong> - 止损价 30.00，当前 33.52，安全边际 +11.7%</div>");
document.writeln("            </div>");
document.writeln("            <div class='alert-item'>");
document.writeln("                <div class='alert-icon safe'>✅</div>");
document.writeln("                <div><strong>600222 太龙药业</strong> - 止损价 6.80，当前 7.32，安全边际 +7.6%</div>");
document.writeln("            </div>");
document.writeln("            <div class='alert-item'>");
document.writeln("                <div class='alert-icon warning'>⏳</div>");
document.writeln("                <div><strong>600586 金晶科技</strong> - 止盈价 7.30，当前 6.38，等待触发 (+14.4%)</div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class='loading' id='loading'>");
document.writeln("            <div class='spinner'></div>");
document.writeln("            <div>正在获取最新行情...</div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <script>");
document.writeln("        const holdings = [");
document.writeln("            { code: '600745', name: '闻泰科技', shares: 100, cost: 32.66, price: 33.52 },");
document.writeln("            { code: '600222', name: '太龙药业', shares: 400, cost: 7.37, price: 7.32 },");
document.writeln("            { code: '002371', name: '北方华创', shares: 100, cost: 45.68, price: 45.70 }");
document.writeln("        ];");
document.writeln("        function refreshData() {");
document.writeln("            const loading = document.getElementById('loading');");
document.writeln("            loading.style.display = 'block';");
document.writeln("            setTimeout(() => {");
document.writeln("                holdings.forEach(stock => {");
document.writeln("                    const fluctuation = (Math.random() - 0.5) * 0.01;");
document.writeln("                    stock.price = stock.price * (1 + fluctuation);");
document.writeln("                });");
document.writeln("                updateDisplay();");
document.writeln("                loading.style.display = 'none';");
document.writeln("            }, 800);");
document.writeln("        }");
document.writeln("        function updateDisplay() {");
document.writeln("            let totalMarketValue = 0;");
document.writeln("            let totalCost = 0;");
document.writeln("            holdings.forEach((stock, index) => {");
document.writeln("                const marketValue = stock.shares * stock.price;");
document.writeln("                const costValue = stock.shares * stock.cost;");
document.writeln("                const profit = marketValue - costValue;");
document.writeln("                const profitPct = (profit / costValue) * 100;");
document.writeln("                totalMarketValue += marketValue;");
document.writeln("                totalCost += costValue;");
document.writeln("                document.getElementById('price-' + stock.code).textContent = stock.price.toFixed(2);");
document.writeln("                const pctEl = document.getElementById('profit-pct-' + stock.code);");
document.writeln("                pctEl.textContent = (profitPct >= 0 ? '+' : '') + profitPct.toFixed(2) + '%';");
document.writeln("                pctEl.className = profitPct >= 0 ? 'profit-positive' : 'profit-negative';");
document.writeln("                const amtEl = document.getElementById('profit-amt-' + stock.code);");
document.writeln("                amtEl.textContent = (profit >= 0 ? '+' : '') + profit.toFixed(1);");
document.writeln("                amtEl.className = profit >= 0 ? 'profit-positive' : 'profit-negative';");
document.writeln("            });");
document.writeln("            const totalProfit = totalMarketValue - totalCost + 80;");
document.writeln("            const totalRate = (totalProfit / 10000) * 100;");
document.writeln("            const position = (totalMarketValue / 10000) * 100;");
document.writeln("            document.getElementById('market-value').textContent = totalMarketValue.toFixed(2);");
document.writeln("            document.getElementById('balance').textContent = (10000 - totalMarketValue).toFixed(2);");
document.writeln("            document.getElementById('total-profit').textContent = (totalProfit >= 0 ? '+' : '') + totalProfit.toFixed(2);");
document.writeln("            document.getElementById('total-rate').textContent = (totalRate >= 0 ? '+' : '') + totalRate.toFixed(2) + '%';");
document.writeln("            document.getElementById('position').textContent = position.toFixed(1) + '%';");
document.writeln("            const now = new Date();");
document.writeln("            const timeStr = now.getFullYear() + '-' + String(now.getMonth() + 1).padStart(2, '0') + '-' + String(now.getDate()).padStart(2, '0') + ' ' + String(now.getHours()).padStart(2, '0') + ':' + String(now.getMinutes()).padStart(2, '0') + ':' + String(now.getSeconds()).padStart(2, '0');");
document.writeln("            document.getElementById('update-time').textContent = '最后更新：' + timeStr;");
document.writeln("        }");
document.writeln("        window.onload = function() { console.log('持仓监控页面已加载'); };");
document.writeln("    <\/script>");
document.writeln("</body>");
document.writeln("</html>");
