#!/usr/bin/env python3
"""
AIGC Image Generator - OpenClaw Skill
调用本地 AIGC 接口生成图片，并上传到用户 OSS
"""

import requests
import time
import uuid
import sys
import argparse
import json
import os
import threading
import hashlib
from urllib.parse import urlparse
from datetime import datetime, timedelta

# ========== Rate Limiting ==========
_rate_limit_lock = threading.Lock()
_rate_limit_store = {}  # {client_key: [(timestamp, count), ...]}

RATE_LIMIT_MAX = 20          # 最多 20 次
RATE_LIMIT_WINDOW = 60       # 滑动窗口 60 秒

def _check_rate_limit(client_id: str) -> bool:
    """检查是否超过频率限制，返回 True 表示允许调用"""
    now = datetime.now()
    window_start = now - timedelta(seconds=RATE_LIMIT_WINDOW)
    key = hashlib.sha256(client_id.encode()).hexdigest()[:16]
    with _rate_limit_lock:
        # 清理过期记录
        _rate_limit_store[key] = [
            ts for ts in _rate_limit_store.get(key, [])
            if ts > window_start
        ]
        count = len(_rate_limit_store[key])
        if count >= RATE_LIMIT_MAX:
            return False
        _rate_limit_store[key].append(now)
        return True

def _get_rate_limit_remaining(client_id: str) -> int:
    """获取剩余可调用次数"""
    now = datetime.now()
    window_start = now - timedelta(seconds=RATE_LIMIT_WINDOW)
    key = hashlib.sha256(client_id.encode()).hexdigest()[:16]
    with _rate_limit_lock:
        valid = [ts for ts in _rate_limit_store.get(key, []) if ts > window_start]
        return max(0, RATE_LIMIT_MAX - len(valid))
# ===================================

BASE_URL = "http://localhost:8082"
CLIENT_ID = "openclaw-kinggu"
PROVIDER = 4

# 用户 OSS 配置（建议通过环境变量设置，或写入同目录 config.local.json）
OSS_UPLOAD_URL = "https://tczlld.com/aistudio/api/oss/files"

def _load_oss_token():
    """优先从环境变量读取，回退到 config.local.json"""
    token = os.environ.get('AIGC_OSS_TOKEN', '')
    if token:
        return token
    # 回退到本地配置文件（不提交到 git）
    local_config_path = os.path.join(os.path.dirname(__file__), 'config.local.json')
    try:
        with open(local_config_path, 'r') as f:
            cfg = json.load(f)
            return cfg.get('oss_token', '')
    except Exception:
        return ''

OSS_TOKEN = _load_oss_token()

# 飞书文件发送器路径
FEISHU_SENDER_SCRIPT = "/Users/jackgu/.openclaw/workspace/skills/feishu-file-sender/scripts/feishu_file_sender.py"

def upload_to_feishu(image_url):
    """上传图片到飞书（通过文件发送器）"""
    print(f"📤 上传图片到飞书: {image_url}")
    try:
        # 下载图片
        img_response = requests.get(image_url, timeout=30)
        img_response.raise_for_status()
        
        # 保存到临时文件
        import tempfile
        import subprocess
        temp_file = tempfile.NamedTemporaryFile(suffix='.png', delete=False)
        temp_file.write(img_response.content)
        temp_file.close()
        
        print(f"📁 临时文件: {temp_file.name}")
        
        # 使用飞书文件发送器发送
        # chat_id 从环境变量获取
        chat_id = os.environ.get('OPENCLAW_CHAT_ID') or os.environ.get('FEISHU_CHAT_ID')
        if not chat_id:
            print(f"⚠️ 未获取到飞书 chat_id，跳过飞书发送", file=sys.stderr)
            os.unlink(temp_file.name)
            return None
        
        cmd = ['python3', FEISHU_SENDER_SCRIPT, '--file', temp_file.name, '--receive-id', chat_id]
        print(f"📤 执行命令: {' '.join(cmd)}")
        
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        print(f"📤 返回: {result.stdout}")
        if result.stderr:
            print(f"📤 错误: {result.stderr}", file=sys.stderr)
        
        # 清理临时文件
        os.unlink(temp_file.name)
        
        if result.returncode == 0:
            print(f"✅ 飞书发送成功")
            return "sent"
        else:
            print(f"⚠️ 飞书发送失败", file=sys.stderr)
            return None
            
    except Exception as e:
        print(f"⚠️ 飞书上传异常: {e}", file=sys.stderr)
        return None

def generate_image(prompt, negative_prompt="", aspect_ratio=1, batch_size=1):
    """提交图片生成任务"""
    # 频率限制检查
    if not _check_rate_limit(CLIENT_ID):
        remaining = _get_rate_limit_remaining(CLIENT_ID)
        print(f"❌ 频率超限: 60秒内最多调用 {RATE_LIMIT_MAX} 次，当前剩余 {remaining} 次", file=sys.stderr)
        return None

    # OSS Token 检查
    if not OSS_TOKEN:
        print(f"❌ OSS_TOKEN 未设置，请设置环境变量 AIGC_OSS_TOKEN", file=sys.stderr)
        return None

    request_id = str(uuid.uuid4())
    
    payload = {
        "clientId": CLIENT_ID,
        "requestId": request_id,
        "provider": PROVIDER,
        "prompt": prompt,
        "negativePrompt": negative_prompt,
        "aspectRatio": aspect_ratio,
        "batchSize": batch_size,
        "note": f"Generated by OpenClaw at {time.strftime('%Y-%m-%d %H:%M:%S')}"
    }
    
    try:
        response = requests.post(
            f"{BASE_URL}/image/generate",
            json=payload,
            timeout=10
        )
        response.raise_for_status()
        result = response.json()
        
        if result.get("code") != 200:
            print(f"❌ 生成失败: {result.get('message', 'Unknown error')}", file=sys.stderr)
            return None
            
        task_id = result.get("data", {}).get("promptId")
        if not task_id:
            print("❌ 未获取到任务ID", file=sys.stderr)
            return None
            
        print(f"✅ 任务已提交: {task_id}")
        return task_id
        
    except requests.exceptions.RequestException as e:
        print(f"❌ 请求失败: {e}", file=sys.stderr)
        return None

def query_task(task_id, max_wait=120):
    """轮询任务状态，直到完成或超时"""
    start_time = time.time()
    
    while time.time() - start_time < max_wait:
        try:
            response = requests.get(
                f"{BASE_URL}/task/query",
                params={"taskId": task_id},
                timeout=10
            )
            response.raise_for_status()
            result = response.json()
            
            if result.get("code") != 200:
                print(f"❌ 查询失败: {result.get('message')}", file=sys.stderr)
                return None
                
            data = result.get("data", {})
            status = data.get("status", 0)
            status_desc = data.get("statusDesc", "Unknown")
            progress = data.get("progress", 0)
            result_urls = data.get("resultUrls")
            
            # 显示进度
            if progress > 0 and progress < 1.0:
                print(f"⏳ 生成中... {int(progress * 100)}% ({status_desc})")
            
            # 检查是否完成 (status=1 表示已完成)
            if status == 1:
                if result_urls and len(result_urls) > 0:
                    # resultUrls 已填充，任务真正完成
                    print(f"✅ 生成完成！")
                    # 上传到用户 OSS
                    oss_urls = upload_to_oss(result_urls)
                    # 上传到飞书
                    feishu_keys = []
                    for url in result_urls:
                        key = upload_to_feishu(url)
                        feishu_keys.append(key)
                    
                    # 返回结果（包含 OSS URL 和飞书 image_key）
                    result = {
                        "oss_urls": oss_urls if oss_urls else result_urls,
                        "feishu_keys": feishu_keys
                    }
                    return result
                else:
                    # 状态已完成但 resultUrls 还未填充，继续等待
                    if progress >= 1.0:
                        print(f"⏳ 任务已完成，等待图片上传... ({status_desc})")
                    
            elif status < 0:  # 失败状态
                print(f"❌ 生成失败: {data.get('message', status_desc)}", file=sys.stderr)
                return None
                
            # 等待后继续轮询
            time.sleep(2)
            
        except requests.exceptions.RequestException as e:
            print(f"❌ 查询失败: {e}", file=sys.stderr)
            time.sleep(2)
            continue
    
    print(f"⏱️ 超时：任务未在 {max_wait} 秒内完成", file=sys.stderr)
    return None

def upload_to_oss(image_urls):
    """上传图片到用户 OSS"""
    uploaded_urls = []
    
    for url in image_urls:
        print(f"📤 上传图片到 OSS: {url}")
        try:
            # 下载原图
            img_response = requests.get(url, timeout=30)
            img_response.raise_for_status()
            
            # 获取文件名
            parsed = urlparse(url)
            filename = os.path.basename(parsed.path) or f"aigc_{int(time.time())}.png"
            
            # 上传到 OSS
            files = {'file': (filename, img_response.content, 'image/png')}
            headers = {'Authorization': f'Bearer {OSS_TOKEN}'}
            
            upload_response = requests.post(
                OSS_UPLOAD_URL,
                files=files,
                headers=headers,
                timeout=30
            )
            upload_response.raise_for_status()
            result = upload_response.json()
            
            if result.get("code") == 200:
                oss_url = result.get("data", {}).get("url")
                if oss_url:
                    print(f"✅ 上传成功: {oss_url}")
                    uploaded_urls.append(oss_url)
                else:
                    print(f"⚠️ 上传成功但未获取到 URL", file=sys.stderr)
                    uploaded_urls.append(url)  # 返回原 URL
            else:
                print(f"⚠️ 上传失败: {result.get('message')}", file=sys.stderr)
                uploaded_urls.append(url)  # 返回原 URL
                
        except Exception as e:
            print(f"⚠️ 上传失败: {e}", file=sys.stderr)
            uploaded_urls.append(url)  # 返回原 URL
    
    return uploaded_urls if uploaded_urls else None

def main():
    parser = argparse.ArgumentParser(description="AIGC Image Generator")
    parser.add_argument("prompt", help="图片描述文本")
    parser.add_argument("--negative", default="", help="负面提示词")
    parser.add_argument("--ratio", type=int, default=1, choices=[1,2,3,4,5], 
                       help="图片比例 (1=1:1, 2=3:4, 3=4:3, 4=9:16, 5=16:9)")
    parser.add_argument("--batch", type=int, default=1, choices=[1,2,3,4],
                       help="生成数量")
    parser.add_argument("--timeout", type=int, default=120,
                       help="最大等待时间（秒）")
    
    args = parser.parse_args()
    
    print(f"🎨 开始生成图片...")
    print(f"📝 提示词: {args.prompt}")
    if args.negative:
        print(f"🚫 负面提示词: {args.negative}")
    
    # 提交任务
    task_id = generate_image(
        prompt=args.prompt,
        negative_prompt=args.negative,
        aspect_ratio=args.ratio,
        batch_size=args.batch
    )
    
    if not task_id:
        sys.exit(1)
    
    # 查询结果
    result = query_task(task_id, max_wait=args.timeout)
    
    if not result:
        sys.exit(1)
    
    oss_urls = result.get("oss_urls", [])
    feishu_keys = result.get("feishu_keys", [])
    
    # 打印最终结果
    print(f"🎉 图片生成完成！")
    for i, url in enumerate(oss_urls, 1):
        print(f"图片 {i}: {url}")
    for i, key in enumerate(feishu_keys, 1):
        if key:
            print(f"飞书图片 {i}: {key}")
    
    sys.exit(0)

if __name__ == "__main__":
    main()
