#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def main():
    p = argparse.ArgumentParser(description="Scaffold a Poke recipe MVP folder")
    p.add_argument("--idea", required=True, help="Human-friendly idea name, e.g. 'Expiry Ping'")
    p.add_argument("--slug", required=True, help="kebab-case slug, e.g. expiry-ping")
    p.add_argument("--out", required=True, help="Output folder, e.g. recipes/poke/expiry-ping")
    args = p.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    recipe = {
        "name": args.idea,
        "slug": args.slug,
        "description": f"Micro recipe MVP for {args.idea}. Replace with specific one-line user value.",
        "onboarding": {
            "inputContext": "Ask for only minimum required context.",
            "prefilledFirstText": f"Tell me what you need for {args.idea}, and I will help immediately.",
        },
        "integrations": {
            "required": [
                {
                    "name": f"{args.idea} MCP",
                    "url": "TODO",
                    "shareWithUsers": False,
                    "notes": "Replace TODO with real MCP URL before publish.",
                }
            ]
        },
        "automations": [],
        "sandboxTestPrompts": [
            "Happy path",
            "Edge case",
            "Ambiguous input",
            "Failure recovery",
            "Concise summary",
        ],
        "publishChecklist": [
            "Integration tested",
            "One-turn usefulness",
            "Narrow scope maintained",
            "Sandbox prompts pass",
        ],
    }

    integration = {
        "name": f"{args.idea} MCP",
        "serverUrl": "TODO",
        "authType": "None",
        "shortDescription": f"MCP integration for {args.idea}",
        "description": "Replace with concrete capabilities and boundary.",
    }

    (out / "recipe.json").write_text(json.dumps(recipe, indent=2) + "\n")
    (out / "integration.json").write_text(json.dumps(integration, indent=2) + "\n")
    (out / "sandbox-prompts.md").write_text(
        "# Sandbox prompts\n\n"
        "1. Happy path: standard request with complete inputs\n"
        "2. Edge case: minimal/partial input\n"
        "3. Ambiguous input: multiple possible interpretations\n"
        "4. Failure mode + recovery: missing integration/data handling\n"
        "5. One-line summary output request\n"
    )
    (out / "ralph-loop.md").write_text(
        "# Ralph loop v1\n\n"
        "Weekly:\n"
        "1. Collect failed prompts\n"
        "2. Classify by failure type\n"
        "3. Patch prompt/tool behavior\n"
        "4. Re-run sandbox regression\n"
        "5. Publish changelog\n"
    )
    (out / "verdict.md").write_text(
        "# Publish-readiness verdict\n\n"
        "Status: NOT_READY\n\n"
        "## Gate checks\n"
        "- [ ] Name is specific and clear\n"
        "- [ ] Description matches actual behavior\n"
        "- [ ] Onboarding asks only minimum context\n"
        "- [ ] Integration URL is real and tested\n"
        "- [ ] 5 sandbox prompts pass\n"
        "- [ ] Error/fallback behavior is explicit\n"
        "- [ ] Publishing lock is acknowledged\n"
        "\n"
        "## Improvements\n"
        "- Replace TODO integration URL\n"
        "- Tighten first message for one-turn value\n"
        "- Add one negative test scenario\n"
    )
    (out / "README.md").write_text(
        f"# {args.idea} (MVP)\n\n"
        "Generated by infinity-poke-recipe-generator scaffold.\n"
        "Fill TODO values, then copy fields into Poke Kitchen.\n"
    )

    print(f"Generated MVP scaffold at: {out}")


if __name__ == "__main__":
    main()
