#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
密码生成器
生成安全的随机密码
"""
import sys; sys.stdout.reconfigure(encoding='utf-8')
import os
import secrets
import string
from datetime import datetime

CHARSET_ALPHA = string.ascii_letters          # a-zA-Z
CHARSET_NUM = string.digits                   # 0-9
CHARSET_SYMBOL = string.punctuation           # !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
CHARSET_ALNUM = CHARSET_ALPHA + CHARSET_NUM   # 字母+数字
CHARSET_ALL = CHARSET_ALPHA + CHARSET_NUM + CHARSET_SYMBOL  # 全部

def generate(length=24, charset=CHARSET_ALL):
    return "".join(secrets.choice(charset) for _ in range(length))

def parse_args():
    args = sys.argv[1:]
    length = 24
    charset = CHARSET_ALL
    save_key = None

    i = 0
    while i < len(args):
        if args[i] == "--help" or args[i] == "-h":
            print_help()
            sys.exit(0)
        elif args[i].isdigit():
            length = int(args[i])
        elif args[i] == "--no-symbols":
            charset = CHARSET_ALNUM
        elif args[i] == "--numeric":
            charset = CHARSET_NUM
        elif args[i] == "--alpha":
            charset = CHARSET_ALPHA
        elif args[i] == "--save" and i + 1 < len(args):
            save_key = args[i + 1]
            i += 1
        i += 1

    return length, charset, save_key

def print_help():
    print("""密码生成器

用法:
  python genpass.py [长度] [选项]

长度:
  默认 24位

选项:
  --no-symbols   不含符号（仅字母+数字）
  --numeric      仅数字
  --alpha        仅字母
  --save <key>   生成后保存到 secrets.json

示例:
  python genpass.py              # 24位，包含所有字符
  python genpass.py 32            # 32位
  python genpass.py 16 --no-symbols  # 16位，字母+数字
  python genpass.py 20 --save github  # 生成并保存到 github
""")

if __name__ == "__main__":
    length, charset, save_key = parse_args()

    password = generate(length, charset)

    # 评估密码强度
    has_lower = any(c in string.ascii_lowercase for c in password)
    has_upper = any(c in string.ascii_uppercase for c in password)
    has_digit = any(c in string.digits for c in password)
    has_sym = any(c in string.punctuation for c in password)
    strength = sum([has_lower, has_upper, has_digit, has_sym])

    strength_label = ["弱", "一般", "良好", "优秀", "极强"][min(strength, 4)]

    print(f"\n密码 ({length}位, 强度:{strength_label}):")
    print(f"  {password}")

    if save_key:
        import re
        if not re.fullmatch(r'[a-zA-Z0-9_\-]{1,64}', save_key):
            print(f"[错误] Invalid key format: {save_key!r}"); sys.exit(1)
        import os, json, stat
        SECRETS_FILE = os.path.expanduser("~/.openclaw/workspace/secrets.json")
        AUDIT_FILE   = os.path.expanduser("~/.openclaw/workspace/secrets.audit.log")
        def _audit(action, key, success=True):
            entry = {"ts": datetime.now().isoformat(), "action": action, "key": key, "success": success}
            try:
                with open(AUDIT_FILE, "a", encoding="utf-8") as f:
                    f.write(json.dumps(entry, ensure_ascii=False) + "\n")
                os.chmod(AUDIT_FILE, stat.S_IRUSR | stat.S_IWUSR)
            except Exception: pass
        def _mask(v):
            s = str(v); return (s[:6]+"..."+s[-4:]) if len(s)>10 else s[:2]+"**"
        data = {"categories":["social","cloud","dev","marketing","other"],"entries":{}}
        if os.path.exists(SECRETS_FILE):
            with open(SECRETS_FILE, encoding="utf-8") as f:
                data = json.load(f)
        now_str = "2026-04-15"
        data["entries"][save_key] = {
            "name": save_key, "category": "other",
            "fields": {"password": password},
            "expire_at": None, "note": "generated by genpass",
            "created_at": now_str, "read_count": 0, "last_read": None
        }
        with open(SECRETS_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        os.chmod(SECRETS_FILE, stat.S_IRUSR | stat.S_IWUSR)
        _audit("genpass_save", save_key, True)
        print(f"\n[OK] 已保存到 secrets.json [{save_key}]")
