#!/usr/bin/env python3
"""
session-cleanup / test_simulated_session.py
-------------------------------------------
Simulated session test — mimics an Agent using the Skill through a full lifecycle:
  Phase 1: 开启追踪 → --init → --add (various) → --skip-add → --show
  Phase 2: 清理 → --track-file --dry-run → --track-file (actual)
  Phase 3: 清除记录 → delete session-track.json → verify gone

This test creates real temp files, adds them to tracking, and verifies they get cleaned.
Run: python test_simulated_session.py
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

SCRIPT = str(Path(__file__).parent / "cleanup.py")
PYTHON = sys.executable
PASS = FAIL = 0
issues = []


def run(args):
    """Run cleanup.py and return (exitcode, stdout)."""
    r = subprocess.run(
        [PYTHON, SCRIPT] + args,
        capture_output=True, text=True, encoding="utf-8", errors="replace"
    )
    return r.returncode, r.stdout


def test(name, condition, detail=""):
    global PASS, FAIL
    if condition:
        PASS += 1
        print(f"  ✅ {name}")
    else:
        FAIL += 1
        print(f"  ❌ {name} — {detail}")
        issues.append(f"{name}: {detail}")


def section(title):
    print(f"\n{'═' * 60}")
    print(f"  {title}")
    print(f"{'═' * 60}")


# ══════════════════════════════════════════════════════════════
# Setup: create a temporary workspace that mimics a real project
# ══════════════════════════════════════════════════════════════

tmpdir = tempfile.mkdtemp(prefix="session_cleanup_test_")
workspace = os.path.join(tmpdir, "myproject")
os.makedirs(os.path.join(workspace, ".workbuddy"))
os.makedirs(os.path.join(workspace, "generated-images"))
os.makedirs(os.path.join(workspace, "src"))

track_path = os.path.join(workspace, ".workbuddy", "session-track.json")

# Also create some temp files in OS TEMP (simulating agent-generated temp files)
os_temp = os.environ.get("TEMP", "/tmp")
temp_files = []
for name in ["demo_script.py", "test_output.txt", "scratch_data.json"]:
    fp = os.path.join(os_temp, f"agent_test_{name}")
    with open(fp, "w", encoding="utf-8") as f:
        f.write(f"# auto-generated by agent — {name}")
    temp_files.append(fp)

# Create a generated image in workspace
img_path = os.path.join(workspace, "generated-images", "ai_pic.png")
with open(img_path, "wb") as f:
    f.write(b"\x89PNG fake image data")

# Create a workspace source file (should NOT be auto-deleted by script)
src_path = os.path.join(workspace, "src", "main.py")
with open(src_path, "w", encoding="utf-8") as f:
    f.write("print('hello world')")

try:
    # ══════════════════════════════════════════════════════════
    section("Phase 1 · 开启清理追踪")
    # ══════════════════════════════════════════════════════════

    print("\n📝 模拟 Agent 执行: --init")
    ec, out = run(["--init", workspace])
    test("追踪已开启", ec == 0)
    test("session-track.json 已创建", os.path.exists(track_path))

    with open(track_path, encoding="utf-8") as f:
        track = json.load(f)
    test("workspace 字段正确", track["workspace"] == workspace)
    test("items 为空", all(len(v) == 0 for v in track["items"].values()))

    # --- 模拟 Agent 在对话中产生了各种资源 ---

    print("\n📝 模拟: Agent 写入临时文件到 %TEMP%")
    for fp in temp_files:
        ec, out = run(["--add", "temp_files", fp, "--track-file", track_path])
        test(f"--add temp_file: {Path(fp).name}", ec == 0 and "Added" in out)

    print("\n📝 模拟: Agent 调用 pip install requests")
    ec, out = run(["--add", "pip_packages", "requests", "--track-file", track_path])
    test("--add pip_package: requests", ec == 0)

    print("\n📝 模拟: Agent 调用 npm install -g lodash")
    ec, out = run(["--add", "npm_packages", "lodash", "--track-file", track_path])
    test("--add npm_package: lodash", ec == 0)

    print("\n📝 模拟: Agent 安装 winget install Ripgrep.MSU")
    ec, out = run(["--add", "system_software", "Ripgrep.MSU", "--track-file", track_path])
    test("--add system_software: Ripgrep.MSU", ec == 0)

    print("\n📝 模拟: Agent 生成图片到 generated-images/")
    ec, out = run(["--add", "temp_files", img_path.replace("\\", "/"), "--track-file", track_path])
    test("--add generated image", ec == 0)

    print("\n📝 模拟: Agent 安装了一个 Skill")
    skill_path = os.path.join(str(Path.home()), ".workbuddy", "skills", "test-dummy-skill")
    ec, out = run(["--add", "skills", skill_path, "--track-file", track_path])
    test("--add skill", ec == 0)

    print("\n📝 模拟: Agent 产生了其他临时文件")
    ec, out = run(["--add", "other", "/tmp/extra_resource.tmp", "--track-file", track_path])
    test("--add other", ec == 0)

    # --- 模拟: 用户要求保留某个文件 ---

    print("\n📝 模拟: 用户说 '跳过 scratch_data'")
    ec, out = run(["--skip-add", "scratch_data", "--track-file", track_path])
    test("--skip-add scratch_data", ec == 0 and "Added" in out)

    # --- 查看当前追踪 ---

    print("\n📝 模拟: 用户说 '列出临时文件'")
    ec, out = run(["--show", "--track-file", track_path])
    test("--show 显示所有分类", all(cat in out for cat in ["temp_files", "pip_packages", "npm_packages", "system_software", "skills", "other"]))
    test("--show 标记跳过项", "scratch_data" in out and ("skipped" in out.lower() or "保留" in out))

    # 验证 JSON 状态
    with open(track_path, encoding="utf-8") as f:
        track = json.load(f)
    test("track 有 4 个 temp_files (3 OS TEMP + 1 generated-image)", len(track["items"]["temp_files"]) == 4,
         f"实际: {len(track['items']['temp_files'])}")
    test("track 有 1 个 pip_package", len(track["items"]["pip_packages"]) == 1)
    test("track 有 1 个 npm_package", len(track["items"]["npm_packages"]) == 1)
    test("track 有 1 个 system_software", len(track["items"]["system_software"]) == 1)
    test("track 有 1 个 skill", len(track["items"]["skills"]) == 1)
    test("track 有 1 个 other", len(track["items"]["other"]) == 1)
    test("skip_list 有 1 项", len(track["skip_list"]) == 1)

    # ══════════════════════════════════════════════════════════
    section("Phase 2 · 清理垃圾文件")
    # ══════════════════════════════════════════════════════════

    # Step A: 展示清单 (already tested via --show)

    # Step C: 先 dry-run

    print("\n📝 模拟: 用户说 '清理垃圾文件' → 先预览")
    ec, out = run(["--track-file", track_path, "--dry-run"])
    test("dry-run 成功", ec == 0)
    test("dry-run 显示 DRY-RUN", "DRY-RUN" in out)

    # Verify scratch_data (skip_list) is NOT in dry-run output
    sys.path.insert(0, str(Path(__file__).parent))
    import cleanup
    manifest, ws = cleanup.load_track_as_manifest(track_path)
    test("skip_list 项被排除", "scratch_data" not in str(manifest))
    test("workspace 正确传递", ws == workspace)

    # Step C: 实际执行

    print("\n📝 模拟: 确认清理 → 执行实际删除")
    ec, out = run(["--track-file", track_path])
    test("实际清理执行成功", ec == 0)

    # Verify: temp files in OS TEMP should be deleted (or moved to recycle bin)
    remaining_temp = [fp for fp in temp_files if os.path.exists(fp)]
    test("OS TEMP 文件已删除", len(remaining_temp) <= 1,
         f"仍有 {len(remaining_temp)} 个文件: {remaining_temp}")

    # Verify: generated-images file should be deleted
    test("generated-images 文件已删除", not os.path.exists(img_path))

    # Verify: workspace source should be preserved
    test("workspace 源码未被删除", os.path.exists(src_path),
         "src/main.py should NOT be deleted by cleanup script")

    # pip/npm/system_software: these should be skipped (not installed or interactive)
    test("pip 卸载输出包含 skip/fail 信息",
         "SKIP" in out or "Failed" in out or "skip" in out.lower() or "not installed" in out.lower())

    # ══════════════════════════════════════════════════════════
    section("Phase 3 · 清除记录")
    # ══════════════════════════════════════════════════════════

    print("\n📝 模拟: 用户说 '清除记录'")
    # Agent should use delete_file tool, but we simulate with os.remove
    if os.path.exists(track_path):
        os.remove(track_path)
    test("session-track.json 已删除", not os.path.exists(track_path))
    test(".workbuddy 目录仍在", os.path.isdir(os.path.join(workspace, ".workbuddy")))

    # ══════════════════════════════════════════════════════════
    section("Phase 4 · 边界场景验证")
    # ══════════════════════════════════════════════════════════

    # 4a: 重复 init（恢复中断会话）
    print("\n📝 模拟: 会话中断后重新开启追踪")
    ec, out = run(["--init", workspace])
    test("重复 init 成功", ec == 0)
    with open(track_path, encoding="utf-8") as f:
        new_track = json.load(f)
    test("新 track 是干净的", all(len(v) == 0 for v in new_track["items"].values()))

    # 4b: 大量条目（6+ items 测试脚本模式）
    print("\n📝 模拟: 大量临时文件 (7 items, 触发脚本模式)")
    for i in range(7):
        fp = os.path.join(os_temp, f"agent_bulk_{i}.tmp")
        with open(fp, "w") as f:
            f.write(f"bulk test {i}")
        run(["--add", "temp_files", fp, "--track-file", track_path])

    with open(track_path, encoding="utf-8") as f:
        bulk_track = json.load(f)
    test("7 个 temp_files 已追踪", len(bulk_track["items"]["temp_files"]) == 7)

    ec, out = run(["--track-file", track_path])
    test("批量清理成功", ec == 0)

    # 4c: 空 track file 清理
    print("\n📝 模拟: 空追踪文件清理")
    ec2, out2 = run(["--init", workspace])
    ec2, out2 = run(["--track-file", track_path])
    test("空 track 清理成功", ec2 == 0 and "Cleanup complete" in out2)

    # 4d: 不存在的 track file
    ec3, _ = run(["--track-file", "C:/nonexistent_12345/session-track.json"])
    test("不存在的 track 文件报错", ec3 == 2)

    # 4e: 路径含特殊字符
    print("\n📝 模拟: 路径含空格和中文")
    special_dir = os.path.join(os_temp, "测试 目录")
    os.makedirs(special_dir, exist_ok=True)
    special_file = os.path.join(special_dir, "特殊文件.py")
    with open(special_file, "w", encoding="utf-8") as f:
        f.write("# test")
    ec4, _ = run(["--paths", special_file, "--dry-run"])
    test("特殊字符路径 dry-run 成功", ec4 == 0)
    # Cleanup
    if os.path.exists(special_dir):
        shutil.rmtree(special_dir, ignore_errors=True)

    # 4f: --manifest with --workspace
    print("\n📝 模拟: --manifest + --workspace 组合")
    manifest_data = {
        "temp_files": [img_path],
        "pip_packages": [],
        "npm_packages": [],
        "skills": [],
        "other": [src_path]
    }
    manifest_path = os.path.join(tmpdir, "test_manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest_data, f)
    ec5, out5 = run(["--manifest", manifest_path, "--workspace", workspace, "--dry-run"])
    test("manifest + workspace dry-run 成功", ec5 == 0)

    # img_path doesn't exist anymore (deleted earlier), so it should be in skipped count
    test("manifest: 已删文件被 skip", "Skipped" in out5 or "skipped" in out5.lower())

finally:
    # ══════════════════════════════════════════════════════════
    # Cleanup all temp files/dirs
    # ══════════════════════════════════════════════════════════
    for fp in temp_files:
        if os.path.exists(fp):
            os.unlink(fp)
    # Clean up bulk temp files
    for i in range(7):
        fp = os.path.join(os_temp, f"agent_bulk_{i}.tmp")
        if os.path.exists(fp):
            os.unlink(fp)
    if os.path.exists(tmpdir):
        shutil.rmtree(tmpdir, ignore_errors=True)


# ══════════════════════════════════════════════════════════════
print(f"\n{'═' * 60}")
print(f"  模拟对话测试结果")
print(f"{'═' * 60}")
print(f"  通过: {PASS}  |  失败: {FAIL}  |  总计: {PASS + FAIL}")
if issues:
    print(f"\n  ⚠️  发现问题:")
    for i in issues:
        print(f"    • {i}")
if FAIL == 0:
    print(f"\n  🎉 模拟对话测试全部通过！")
else:
    print(f"\n  ❌ 部分测试失败，请查看上方详情。")
sys.exit(0 if FAIL == 0 else 1)
