#!/usr/bin/env python3
"""
Generate Python Dependencies List
自动检测并生成 Python 依赖列表，用于备份

Usage:
    python3 gen-requirements.py [--output <file>]
"""

import sys
import pkg_resources
import json
from pathlib import Path

WORKSPACE_DIR = Path.home() / ".openclaw" / "workspace"
DEFAULT_OUTPUT = WORKSPACE_DIR / "requirements.txt"

# 过滤掉系统包，只保留用户包
SYSTEM_PACKAGES = {
    'Babel', 'Brlapi', 'PyGObject', 'PyJWT', 'PyQt5', 'PyQt5-sip',
    'PyYAML', 'attrs', 'bcc', 'blinker', 'certifi', 'chardet', 'click',
    'cloud-init', 'colorama', 'command-not-found', 'configobj', 'cryptography',
    'cupshelpers', 'dbus-python', 'defer', 'distro', 'distro-info',
    'galternatives', 'httplib2', 'idna', 'jsonpatch', 'jsonpointer',
    'language-selector', 'launchpadlib', 'lazr.restfulclient', 'macaroonbak',
    'oauthlib', 'oauthlib', 'onionshare', 'openstack', 'pbr', 'pycairo',
    'pycups', 'pyparsing', 'python-apt', 'python-dateutil', 'python-debian',
    'pytz', 'pyxdg', 'reportlab', 'requests', 'sessioninstaller', 'six',
    'software-properties-gtk', 'systemd-python', 'ubuntu-drivers-common',
    'ubuntu-pro-client', 'ubuntu-restricted-addons', 'ufw', 'unattended-upgrades',
    'urllib3', 'usb-creator', 'wadllib', 'zope.interface', 'lazr.uri'
}

def get_user_packages():
    """获取用户安装的包（排除系统包）"""
    user_packages = []
    for dist in pkg_resources.working_set:
        name = dist.project_name
        # 排除系统包和版本不确定的包
        if name not in SYSTEM_PACKAGES and not name.startswith('_'):
            user_packages.append(f"{name}=={dist.version}")
    return sorted(user_packages)

def main():
    output = DEFAULT_OUTPUT
    
    # Parse arguments
    for i, arg in enumerate(sys.argv):
        if arg == "--output" and i + 1 < len(sys.argv):
            output = Path(sys.argv[i + 1])
    
    packages = get_user_packages()
    
    # Write requirements.txt
    with open(output, 'w') as f:
        f.write("# Python dependencies - Generated by ClawMerge\n")
        f.write("# Run 'pip3 install -r requirements.txt' to install\n\n")
        for pkg in packages:
            f.write(pkg + "\n")
    
    print(f"✓ Generated {len(packages)} packages to {output}")
    
    # Also generate a JSON summary
    json_output = output.with_suffix('.json')
    json_data = {
        "_meta": {
            "generated_by": "gen-requirements.py",
            "total_packages": len(packages)
        },
        "packages": packages
    }
    
    import json as json_module
    with open(json_output, 'w') as f:
        json_module.dump(json_data, f, indent=2)
    
    print(f"✓ JSON summary: {json_output}")

if __name__ == "__main__":
    main()
