#!/usr/bin/env python3
"""
emoTwin Execution Script - Real API calls only
Content is generated by LLM (OpenClaw Agent), not templates
"""

import os
import sys
import json
import hashlib
from datetime import datetime
from pathlib import Path

scripts_dir = Path(__file__).parent
sys.path.insert(0, str(scripts_dir))

import requests
from emotwin_moltcn import MoltcnClient
from emotwin_moment_card import EmoTwinMomentCard, Moment

EMOPAD_URL = "http://127.0.0.1:8766/pad"
POST_HISTORY_FILE = Path.home() / ".emotwin" / "post_history.json"

def read_pad_data():
    try:
        response = requests.get(EMOPAD_URL, timeout=5)
        if response.status_code == 200:
            return response.json()
        return None
    except Exception as e:
        print(f"❌ Failed to read PAD: {e}")
        return None

def load_post_history():
    if POST_HISTORY_FILE.exists():
        try:
            with open(POST_HISTORY_FILE, 'r') as f:
                return json.load(f)
        except:
            return []
    return []

def save_post_history(history):
    POST_HISTORY_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(POST_HISTORY_FILE, 'w') as f:
        json.dump(history[-50:], f)

def is_duplicate_content(content, history):
    content_hash = hashlib.md5(content.encode()).hexdigest()[:16]
    for post in history:
        if post.get('hash') == content_hash:
            return True
        if post.get('content_preview') == content[:100]:
            return True
    return False

def add_to_history(title, content):
    history = load_post_history()
    history.append({
        'timestamp': datetime.now().isoformat(),
        'title': title,
        'content_preview': content[:100],
        'hash': hashlib.md5(content.encode()).hexdigest()[:16]
    })
    save_post_history(history)

def execute_real_post(submolt, title, content):
    """Execute REAL post creation with provided content (generated by LLM)"""
    try:
        # Check for duplicate
        history = load_post_history()
        if is_duplicate_content(content, history):
            print(f"⚠️  Duplicate content detected, skipping post")
            return {'success': False, 'action': 'skipped', 'reason': 'duplicate'}
        
        print(f"\n📝 [Posting to /r/{submolt}]")
        print(f"Title: {title}")
        print(f"Content: {content[:80]}...")
        
        client = MoltcnClient()
        result = client.create_post(submolt=submolt, title=title, content=content)
        
        if result and result.get('success'):
            post_id = result.get('data', {}).get('id', 'unknown')
            print(f"✅ Post successful! ID: {post_id}")
            add_to_history(title, content)
            return {'success': True, 'action': 'create_post', 'post_id': post_id, 'submolt': submolt, 'title': title}
        else:
            print(f"❌ Post failed: {result}")
            return {'success': False, 'error': 'API failed'}
            
    except Exception as e:
        print(f"❌ Post error: {e}")
        return {'success': False, 'error': str(e)}

def execute_real_comment(post_id, content):
    """Execute REAL comment with provided content (generated by LLM)"""
    try:
        print(f"\n💬 [Commenting on post {post_id}]")
        print(f"Content: {content}")
        
        client = MoltcnClient()
        result = client.add_comment(post_id, content)
        
        if result and result.get('success'):
            comment_id = result.get('data', {}).get('id', 'unknown')
            print(f"✅ Comment successful! ID: {comment_id}")
            return {'success': True, 'action': 'comment', 'post_id': post_id, 'comment_id': comment_id}
        else:
            print(f"❌ Comment failed: {result}")
            return {'success': False, 'error': 'API failed'}
            
    except Exception as e:
        print(f"❌ Comment error: {e}")
        return {'success': False, 'error': str(e)}

def execute_real_like(post_id):
    """Execute REAL like"""
    try:
        print(f"\n👍 [Liking post {post_id}]")
        
        client = MoltcnClient()
        result = client.like_post(post_id)
        
        if result:
            print(f"✅ Like successful!")
            return {'success': True, 'action': 'like', 'post_id': post_id}
        else:
            print(f"❌ Like failed")
            return {'success': False, 'error': 'API failed'}
            
    except Exception as e:
        print(f"❌ Like error: {e}")
        return {'success': False, 'error': str(e)}

def get_recent_posts(limit=5):
    """Get recent posts for commenting/liking"""
    try:
        client = MoltcnClient()
        return client.get_feed(limit=limit)
    except Exception as e:
        print(f"❌ Failed to get posts: {e}")
        return []

def get_available_submolts():
    """Get list of available submolts for LLM to choose from"""
    try:
        import requests
        resp = requests.get('https://www.moltbook.cn/api/v1/submolts', 
                          headers={'Authorization': f'Bearer {os.environ.get("MOLTCN_TOKEN", "")}'})
        if resp.status_code == 200:
            data = resp.json()
            submolts = []
            for sub in data.get('data', []):
                submolts.append({
                    'name': sub['name'],
                    'display_name': sub.get('display_name', sub['name']),
                    'description': sub.get('description', '无描述')[:100]  # Truncate long descriptions
                })
            return submolts
        return []
    except Exception as e:
        print(f"❌ Failed to get submolts: {e}")
        return []

# CRITICAL: This script MUST execute REAL API calls, NEVER simulate
# All functions in this file perform actual Moltcn/Moltbook API operations
# There are NO simulation or demo code paths
#
# Architecture:
# - OpenClaw Agent (LLM) reads PAD, makes decisions, generates content
# - This script ONLY executes the actual API calls
# - NO mock responses, NO fake data, NO simulation allowed
#
# Usage:
#   from emotwin_social_cycle import execute_real_post, execute_real_comment, execute_real_like
#   # LLM decides action and generates content based on emotion PAD
#   result = execute_real_post(submolt, title, content)  # REAL API call
