#!/usr/bin/env python3
"""Paper Trading Plan Generator"""
import argparse

def main():
    p = argparse.ArgumentParser(description='Generate paper trading plan')
    p.add_argument('--ticker', required=True)
    p.add_argument('--direction', required=True, choices=['long', 'short'])
    p.add_argument('--entry', type=float, required=True)
    p.add_argument('--stop', type=float, required=True)
    p.add_argument('--target', type=float, required=True)
    p.add_argument('--price', type=float, default=None)
    p.add_argument('--account', type=float, default=10000)
    p.add_argument('--risk-pct', type=float, default=2.0)
    args = p.parse_args()

    risk = abs(args.entry - args.stop)
    reward = abs(args.target - args.entry)
    rr = reward / risk if risk else 0
    direction = args.direction.upper()

    risk_amount = args.account * (args.risk_pct / 100)
    per_share = abs(args.entry - args.stop)
    shares = int(risk_amount / per_share) if per_share else 0
    total_cost = shares * args.entry

    print(f"""
=== PAPER TRADING PLAN ===
Symbol:     {args.ticker}
Direction:  {direction}
Entry:      {args.entry}
Stop Loss:  {args.stop} ({'-' if direction == 'LONG' else '+'}{risk/args.entry*100:.1f}%)
Take Profit:{args.target} ({'+' if direction == 'LONG' else '-'}{reward/args.entry*100:.1f}%)
Risk/Reward: 1:{rr:.1f}

Position Size:
- Max {args.risk_pct}% account at risk = ${risk_amount:.0f}
- Per-share risk: ${per_share:.2f}
- Shares: {shares}
- Estimated cost: ${total_cost:.0f}

Failure Conditions:
- Price breaks {args.stop} → Exit immediately
- VIX > 30 → Reduce size by 50%
- Major news event → Re-evaluate before entry

Execution Checklist:
[ ] Confirm entry above/below key level
[ ] Check VIX context
[ ] Verify no major earnings/news during trade
[ ] Set stop loss immediately after entry
[ ] Log trade in journal

Generated by Beta | Paper Trading Research Agent
""")

if __name__ == '__main__':
    main()
