#!/usr/bin/env python3
"""
Prepare standard trigger batch artifacts for evaluator-compatible delivery.

Examples:
  python scripts/prepare_trigger_batch.py --type positive --output outputs/should_trigger.jsonc
  python scripts/prepare_trigger_batch.py --type negative --output outputs/should_not_trigger.jsonc
"""

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_BY_TYPE = {
    "positive": ROOT / "evals/triggering/autoGenerated/should_trigger.jsonc",
    "negative": ROOT / "evals/triggering/autoGenerated/should_not_trigger.jsonc",
}
EXPECTED_FILENAME = {
    "positive": "should_trigger.jsonc",
    "negative": "should_not_trigger.jsonc",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Copy standard trigger jsonc template to evaluator output path."
    )
    parser.add_argument(
        "--type",
        required=True,
        choices=["positive", "negative"],
        help="Trigger batch type.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output jsonc path (for example outputs/should_trigger.jsonc).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing output file.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    src = SOURCE_BY_TYPE[args.type]
    dst = Path(args.output).expanduser().resolve()

    if not src.exists():
        raise FileNotFoundError(f"Template not found: {src}")

    if dst.exists() and not args.force:
        raise FileExistsError(
            f"Output already exists: {dst}. Use --force to overwrite."
        )

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")

    expected = EXPECTED_FILENAME[args.type]
    filename_note = ""
    if dst.name != expected:
        filename_note = (
            f"\n[WARN] Recommended filename for {args.type} batch is '{expected}'."
        )

    print(
        f"[OK] Generated {args.type} trigger artifact: {dst}"
        f"\n[INFO] Source template: {src}{filename_note}"
    )


if __name__ == "__main__":
    main()
