#!/bin/bash
# generate-skill-draft.sh — Generate a SKILL.md draft from a recurring pattern
# Usage: ./generate-skill-draft.sh "<pattern_name>" [category]
# Outputs SKILL.md compatible content to stdout

WORKSPACE="${HOME}/.openclaw/workspace"
LEARNINGS_DIR="$WORKSPACE/.learnings"
PATTERN_NAME="${1:-}"
CATEGORY="${2:-unknown}"

if [ -z "$PATTERN_NAME" ]; then
    echo "ERROR: Pattern name required" >&2
    echo "Usage: $0 <pattern_name> [category]" >&2
    exit 1
fi

# Sanitize pattern name for use as skill directory
SKILL_DIR_NAME=$(echo "$PATTERN_NAME" | sed 's/[^a-zA-Z0-9_-]/_/g' | tr '[:upper:]' '[:lower:]')
TODAY=$(date +%Y-%m-%d)

# Collect related learnings as tab-separated: entry_id | summary | area
declare -a related_entries

# Helper: extract entry block and parse fields
extract_entry() {
    local file="$1"
    local entry_start="$2"
    local block

    block=$(sed -n "${entry_start},+30p" "$file" 2>/dev/null)

    local eid summary area
    eid=$(echo "$block" | head -1 | grep -oP '\[[A-Z]+-[0-9]+-[0-9]+\]' | head -1)
    # Summary is the line after "### Summary" (not the "Summary" word itself)
    summary=$(echo "$block" | sed -n '/^### Summary$/,/^###\|^## \|^---/p' | grep -v "^### Summary$" | grep -v "^---$" | head -1 | sed 's/^[[:space:]]*//')
    # Area: try **bold** format first, then plain
    area=$(echo "$block" | grep -oP 'Area:\s*\*\*[^*]+\*\*' | head -1 | sed 's/Area:\s*\*\*//;s/\*\*//')
    [ -z "$area" ] && area=$(echo "$block" | grep -oP 'Area:\s*\**[^*]+\**' | head -1 | sed 's/Area:\s*\*\*//;s/\*\*//')
    [ -z "$area" ] && area=$(echo "$block" | grep -oP 'Area:\s*[^\n]+' | head -1 | sed 's/Area:[[:space:]]*//' | tr -d '*' | tr '[:upper:]' '[:lower:]')
    [ -z "$area" ] && area="general"

    if [ -n "$eid" ] && [ -n "$summary" ]; then
        echo -e "${eid}\t${summary}\t${area}"
    fi
}

# Scan LEARNINGS.md
while IFS= read -r line; do
    entry_start=$(echo "$line" | cut -d: -f1)
    result=$(extract_entry "$LEARNINGS_DIR/LEARNINGS.md" "$entry_start")
    [ -n "$result" ] && related_entries+=("$result")
done < <(grep -n "^## \[LRN-" "$LEARNINGS_DIR/LEARNINGS.md" 2>/dev/null)

# Scan ERRORS.md
while IFS= read -r line; do
    entry_start=$(echo "$line" | cut -d: -f1)
    result=$(extract_entry "$LEARNINGS_DIR/ERRORS.md" "$entry_start")
    [ -n "$result" ] && related_entries+=("$result")
done < <(grep -n "^## \[ERR-" "$LEARNINGS_DIR/ERRORS.md" 2>/dev/null)

# --- Output SKILL.md content using printf ---
printf '# SKILL.md — Skill: %s\n\n' "$PATTERN_NAME"
printf '> **Generated**: %s\n' "$TODAY"
printf '> **Source**: Recurring pattern detection (≥3 occurrences)\n'
printf '> **Auto-generated draft** — review and customize before installing\n\n'
printf '## Description\n\n'
printf 'This skill was auto-generated because the pattern "%s" appeared in %d or more learnings.\n\n' "$PATTERN_NAME" "${#related_entries[@]}"
printf '## When to Use This Skill\n\n'
printf 'Use this skill when handling tasks related to **%s**.\n\n' "$PATTERN_NAME"
printf 'Trigger conditions:\n'
printf '%s\n' "- Task involves: $PATTERN_NAME"
printf '%s\n' "- Error/warning related to: $PATTERN_NAME"
printf '%s\n\n' "- Configuration of: $PATTERN_NAME"
printf '## How to Handle\n\n'
printf '### Key Lessons Learned\n\n'

# Output related learnings
if [ ${#related_entries[@]} -gt 0 ]; then
    for entry in "${related_entries[@]}"; do
        IFS=$'\t' read -r eid esum earea <<< "$entry"
        printf '%s\n' "- **$eid** ($earea): $esum"
    done
else
    printf '%s\n' "- *(No specific learnings found — skill is based on pattern name only)*"
fi

printf '\n### Common Pitfalls\n\n'
printf '%s\n\n' "- *(Document common mistakes here based on learnings)*"
printf '### Recommended Approach\n\n'
printf '1. *(Step 1 based on learnings)*\n'
printf '2. *(Step 2 based on learnings)*\n'
printf '3. *(Step 3 based on learnings)*\n\n'
printf '## Installation\n\n'
printf '```bash\n'
printf '# Create skill directory\n'
printf 'mkdir -p ~/.openclaw/workspace/skills/%s\n\n' "$SKILL_DIR_NAME"
printf '# Save this as SKILL.md\n'
printf '# Then run: openclaw skills scan\n'
printf '```\n\n'
printf '## Files\n\n'
printf '%s\n\n' "- \`~/.openclaw/workspace/skills/$SKILL_DIR_NAME/SKILL.md\` — this file"
printf '%s\n\n' '---'
printf '*This skill was auto-generated by the OpenClaw self-improving system.*\n'
printf '*Source learnings: %d entries*\n' "${#related_entries[@]}"
