"1":
  - identification
  - product and company identification
  - identification of the substance/mixture and of the company/undertaking
"2":
  - hazards identification
  - hazard identification
  - hazard(s) identification
"3":
  - composition/information on ingredients
  - composition information on ingredients
"4":
  - first-aid measures
  - first aid measures
"5":
  - fire-fighting measures
  - firefighting measures
"6":
  - accidental release measures
"7":
  - handling and storage
"8":
  - exposure controls/personal protection
"9":
  - physical and chemical properties
"10":
  - stability and reactivity
"11":
  - toxicological information
"12":
  - ecological information
"13":
  - disposal considerations
"14":
  - transport information
"15":
  - regulatory information
"16":
  - other information
