#!/usr/bin/env python3
"""
AI Advisor - Use LLM to provide intelligent optimization suggestions
Usage: python ai_advisor.py /path/to/skill [--model kimi/gpt4]
"""

import os
import sys
import json
import argparse
from pathlib import Path

class AIAdvisor:
    def __init__(self, skill_path: str):
        self.skill_path = Path(skill_path)
        self.skill_md = self.skill_path / "SKILL.md"
        
    def read_skill(self):
        """Read skill content"""
        if not self.skill_md.exists():
            return None
        return self.skill_md.read_text(encoding='utf-8')
    
    def analyze_with_ai(self, content: str):
        """Generate AI-powered optimization suggestions"""
        
        # Since we don't have direct LLM API, we'll generate structured prompts
        # that the user can run with their AI assistant
        
        analysis_prompt = f"""
你是一位专业的 Agent Skill 优化专家。请分析以下 Skill 并提供具体的优化建议。

## 待分析的 Skill

```markdown
{content[:3000]}  # First 3000 chars
```

## 请从以下维度分析

1. **触发条件清晰度**
   - 描述是否明确说明了何时使用？
   - 是否有"不要用"的反面例子？
   - 建议如何改进？

2. **设计模式应用**
   - 当前应用了哪些 Google 设计模式？
   - 还缺少哪些可以应用的模式？
   - 具体如何添加？

3. **内容质量问题**
   - 是否有冗余内容？
   - 指令是否可操作？
   - 是否需要渐进式披露？

4. **用户体验优化**
   - 是否有清晰的使用示例？
   - 错误处理是否完善？
   - 输出格式是否标准化？

## 输出格式

请按以下格式提供建议：

### 🔴 关键问题（必须修复）
1. [问题描述]
   - 影响：[为什么重要]
   - 建议：[具体修改方案]

### 🟡 改进建议（强烈建议）
1. [建议描述]
   - 收益：[改进后效果]
   - 实现：[如何操作]

### 🟢 优化机会（可选增强）
1. [机会描述]
   - 价值：[带来的好处]

### 📋 优化后的 SKILL.md 草稿
请提供优化后的前500字草稿
"""
        
        return {
            "prompt": analysis_prompt,
            "suggestions": self.generate_suggestions(content)
        }
    
    def generate_suggestions(self, content: str):
        """Generate rule-based suggestions as fallback"""
        suggestions = []
        
        # Check for common issues
        if 'when to use' not in content.lower() and 'use when' not in content.lower():
            suggestions.append({
                "type": "critical",
                "issue": "缺少明确的触发条件",
                "suggestion": "在 description 中添加 'Use when: (1)..., (2)..., (3)...'",
                "example": 'Use when: (1) Analyzing skill quality, (2) Before publishing to ClawHub'
            })
        
        if '## Quick Start' not in content:
            suggestions.append({
                "type": "important",
                "issue": "缺少 Quick Start 部分",
                "suggestion": "添加 ## Quick Start 章节，包含最简单的使用命令",
                "example": "## Quick Start\\n\\n```bash\\npython scripts/main.py --input file.txt\\n```"
            })
        
        if content.count('#') < 5:
            suggestions.append({
                "type": "improvement",
                "issue": "章节结构过于简单",
                "suggestion": "使用多级标题组织内容，提高可读性"
            })
        
        if 'template' not in content.lower() and 'generator' not in content.lower():
            suggestions.append({
                "type": "pattern",
                "issue": "未应用 Generator 模式",
                "suggestion": "如果 Skill 产生标准化输出，添加 Output Template 部分"
            })
        
        if 'checklist' not in content.lower() and 'reviewer' not in content.lower():
            suggestions.append({
                "type": "pattern",
                "issue": "未应用 Reviewer 模式",
                "suggestion": "添加 ## Checklist 部分，列出执行前必须检查的项目"
            })
        
        return suggestions
    
    def generate_report(self, ai_analysis: dict):
        """Generate AI advisor report"""
        report = f"""# AI 优化建议报告

## Skill: {self.skill_path.name}

## 🎯 AI 分析提示词

以下提示词可以在 Kimi、GPT-4 等 AI 助手中运行，获取深度分析：

```
{ai_analysis['prompt'][:500]}...
```

## 📋 自动检测到的建议

"""
        
        for suggestion in ai_analysis['suggestions']:
            emoji = {"critical": "🔴", "important": "🟡", "improvement": "🟢", "pattern": "🎨"}.get(suggestion['type'], "💡")
            report += f"""
### {emoji} [{suggestion['type'].upper()}] {suggestion['issue']}

**问题**: {suggestion['issue']}

**建议**: {suggestion['suggestion']}

{f"**示例**: {suggestion['example']}" if 'example' in suggestion else ""}

---
"""
        
        report += """
## 🚀 下一步操作

```bash
# 根据建议进行优化
python scripts/optimize_skill.py "/path/to/{self.skill_path.name}" \\
  --output "./{self.skill_path.name}-optimized"

# 或使用一键优化
python scripts/auto_optimize.py "/path/to/{self.skill_path.name}"
```

---
*Generated by AI Advisor v3.0*
"""
        
        return report
    
    def run(self):
        """Run AI advisor"""
        print(f"🤖 AI Advisor analyzing: {self.skill_path.name}")
        
        content = self.read_skill()
        if not content:
            print("❌ SKILL.md not found!")
            return
        
        ai_analysis = self.analyze_with_ai(content)
        report = self.generate_report(ai_analysis)
        
        # Save report
        report_path = self.skill_path / ".ai_advisor_report.md"
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report)
        
        print(f"✅ AI report saved: {report_path}")
        print(f"\n📊 Found {len(ai_analysis['suggestions'])} suggestions")
        
        # Print summary
        critical = sum(1 for s in ai_analysis['suggestions'] if s['type'] == 'critical')
        important = sum(1 for s in ai_analysis['suggestions'] if s['type'] == 'important')
        
        if critical > 0:
            print(f"🔴 Critical: {critical}")
        if important > 0:
            print(f"🟡 Important: {important}")
        
        print("\n💡 To get deeper AI analysis, run the prompt in the report with Kimi/GPT-4")

def main():
    parser = argparse.ArgumentParser(description='AI-powered skill optimization advisor')
    parser.add_argument('skill_path', help='Path to skill folder')
    parser.add_argument('--model', default='kimi', help='AI model to use (kimi/gpt4)')
    
    args = parser.parse_args()
    
    advisor = AIAdvisor(args.skill_path)
    advisor.run()

if __name__ == "__main__":
    main()
