#!/usr/bin/env node
/**
 * Token Pilot — Auto-generate SKILLS.md catalog
 * 
 * Scans all installed skills and generates a lightweight catalog index.
 * This catalog can replace loading every SKILL.md at session start.
 * 
 * Usage:
 *   node catalog.js [skills-dir] [--output path]
 * 
 * Pure Node.js, zero dependencies.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

const OPENCLAW_HOME = path.join(os.homedir(), '.openclaw');

function extractFrontmatter(content) {
  const m = content.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const fm = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^(\w+)\s*:\s*(.+)/);
    if (kv) fm[kv[1].trim()] = kv[2].trim();
  }
  return fm;
}

function estimateTokens(text) {
  let tokens = 0;
  for (const ch of text) {
    tokens += ch.charCodeAt(0) > 0x2000 ? 1.5 : 0.25;
  }
  return Math.round(tokens);
}

function main() {
  const args = process.argv.slice(2);
  let skillsDir = path.join(OPENCLAW_HOME, 'skills');
  let outputPath = null;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--output' || args[i] === '-o') {
      outputPath = args[++i];
    } else if (!args[i].startsWith('-')) {
      skillsDir = args[i];
    }
  }

  // Also scan builtin skills
  const builtinDir = path.join(
    process.env.APPDATA || path.join(os.homedir(), '.local/share'),
    'npm/node_modules/openclaw/skills'
  );

  const allDirs = [
    { dir: skillsDir, label: 'installed' },
    { dir: builtinDir, label: 'builtin' },
  ];

  const skills = [];

  for (const { dir, label } of allDirs) {
    if (!fs.existsSync(dir)) continue;
    for (const name of fs.readdirSync(dir)) {
      const skillMd = path.join(dir, name, 'SKILL.md');
      if (!fs.existsSync(skillMd)) continue;

      const content = fs.readFileSync(skillMd, 'utf-8');
      const fm = extractFrontmatter(content);
      const tokens = estimateTokens(content);

      skills.push({
        name: fm.name || name,
        slug: name,
        description: (fm.description || '').substring(0, 80).replace(/\n/g, ' '),
        tokens,
        source: label,
      });
    }
  }

  // Sort by name
  skills.sort((a, b) => a.name.localeCompare(b.name));

  // Generate markdown
  const lines = [
    '# SKILLS.md — Available Skills Catalog',
    '',
    `> Auto-generated by Token Pilot. ${skills.length} skills indexed.`,
    '> Load individual SKILL.md files only when a task needs them.',
    '',
    '| Skill | Tokens | Source | Description |',
    '|-------|--------|--------|-------------|',
  ];

  for (const s of skills) {
    lines.push(`| ${s.name} | ~${s.tokens} | ${s.source} | ${s.description} |`);
  }

  lines.push('');
  lines.push(`_Total: ${skills.length} skills. Catalog cost: ~${estimateTokens(lines.join('\n'))} tokens vs loading all: ~${skills.reduce((a, b) => a + b.tokens, 0)} tokens._`);

  const output = lines.join('\n');

  if (outputPath) {
    fs.writeFileSync(outputPath, output, 'utf-8');
    console.log(`Catalog written to ${outputPath}`);
  } else {
    console.log(output);
  }
}

main();
