#!/usr/bin/env python3
"""
Omni-Memory 初始化脚本
创建目录结构和初始文件
"""

import os
from datetime import datetime

WORKSPACE_ROOT = os.getcwd()
MEMORY_DIR = os.path.join(WORKSPACE_ROOT, "memory")
SESSION_STATE_PATH = os.path.join(WORKSPACE_ROOT, "SESSION-STATE.md")
MEMORY_INDEX_PATH = os.path.join(WORKSPACE_ROOT, "MEMORY.md")


def init_memory_system():
    """初始化记忆系统"""
    
    # 创建目录结构
    dirs = [
        MEMORY_DIR,
        os.path.join(MEMORY_DIR, "user"),
        os.path.join(MEMORY_DIR, "feedback"),
        os.path.join(MEMORY_DIR, "project"),
        os.path.join(MEMORY_DIR, "reference"),
        os.path.join(MEMORY_DIR, "vectors"),
        os.path.join(MEMORY_DIR, "archive"),
    ]
    
    for d in dirs:
        os.makedirs(d, exist_ok=True)
        print(f"[CREATE] {d}")
    
    # 创建SESSION-STATE.md
    session_template = """# SESSION-STATE.md — 活跃工作记忆

此文件是Agent的"热内存"，在压缩、重启、切换任务后依然存活。

## Current Task
[None]

## Key Context
- User preference: [pending]
- Decision made: [pending]
- Blocker: [pending]

## Pending Actions
- [ ] None

## Recent Decisions
[None yet]

---
*Last updated: {timestamp}*
*Rule: Write BEFORE responding (WAL protocol)*
""".format(timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"))
    
    if not os.path.exists(SESSION_STATE_PATH):
        with open(SESSION_STATE_PATH, 'w', encoding='utf-8') as f:
            f.write(session_template)
        print(f"[CREATE] {SESSION_STATE_PATH}")
    else:
        print(f"[SKIP] {SESSION_STATE_PATH} already exists")
    
    # 创建MEMORY.md
    memory_template = """# MEMORY.md — 长期记忆索引

此文件是长期记忆的目录，不存储具体内容，只指向分类文件。

## User Memory
用户画像、偏好、角色信息
<!-- 格式: - [文件名](memory/user/文件名.md) — 简短描述 -->

## Feedback Memory
用户纠正、确认、风格指导
<!-- 格式: - [文件名](memory/feedback/文件名.md) — 简短描述 -->

## Project Memory
项目状态、决策、推理过程
<!-- 格式: - [文件名](memory/project/文件名.md) — 简短描述 -->

## Reference
外部资源、工具、位置信息
<!-- 格式: - [文件名](memory/reference/文件名.md) — 简短描述 -->

---
*Created: {timestamp}*
*Max size: 5KB (prune when exceeded)*
""".format(timestamp=datetime.now().strftime("%Y-%m-%d"))
    
    if not os.path.exists(MEMORY_INDEX_PATH):
        with open(MEMORY_INDEX_PATH, 'w', encoding='utf-8') as f:
            f.write(memory_template)
        print(f"[CREATE] {MEMORY_INDEX_PATH}")
    else:
        print(f"[SKIP] {MEMORY_INDEX_PATH} already exists")
    
    # 创建今日daily log
    today = datetime.now().strftime("%Y-%m-%d")
    daily_log_path = os.path.join(MEMORY_DIR, f"{today}.md")
    
    daily_template = """# {date} Daily Log

## Session Log

### Session Start
- Time: {time}
- Context: Memory system initialized

---
*Auto-generated by omni-memory init*
""".format(date=today, time=datetime.now().strftime("%H:%M"))
    
    if not os.path.exists(daily_log_path):
        with open(daily_log_path, 'w', encoding='utf-8') as f:
            f.write(daily_template)
        print(f"[CREATE] {daily_log_path}")
    
    print("\n[OK] Omni-Memory system initialized successfully!")
    print("\nDirectory structure:")
    print(f"  {WORKSPACE_ROOT}/")
    print(f"  ├── SESSION-STATE.md     # Hot RAM (WAL protected)")
    print(f"  ├── MEMORY.md            # Long-term index")
    print(f"  └── memory/")
    print(f"      ├── user/            # User profile & preferences")
    print(f"      ├── feedback/        # Corrections & confirmations")
    print(f"      ├── project/         # Decisions & reasoning")
    print(f"      ├── reference/       # External resources")
    print(f"      ├── vectors/         # Vector database")
    print(f"      ├── archive/         # Archived daily logs")
    print(f"      └── {today}.md       # Today's log")


if __name__ == "__main__":
    init_memory_system()
