#!/usr/bin/env bash
# GraphQL Builder — Generate GraphQL schemas, resolvers, queries, mutations
# Usage: bash main.sh --type <schema|query|mutation|resolver> --entity <name> [options]
set -euo pipefail

TYPE=""
ENTITY=""
FIELDS=""
RELATIONS=""
OUTPUT=""
LANG="javascript"

show_help() {
    cat << 'HELPEOF'
GraphQL Builder — Generate type-safe GraphQL schemas and operations

Usage: bash main.sh --type <type> --entity <name> [options]

Options:
  --type <type>      Output type: schema, query, mutation, resolver, full
  --entity <name>    Entity name (e.g., User, Product, Order)
  --fields <fields>  Comma-separated fields (name:Type format)
  --relations <rels> Comma-separated relations (name:Entity format)
  --lang <lang>      Resolver language: javascript, typescript, python
  --output <file>    Output file (default: stdout)
  --help             Show this help

Field Types: String, Int, Float, Boolean, ID, DateTime, JSON
Add ! suffix for required: name:String!

Examples:
  bash main.sh --type full --entity User --fields "name:String!,email:String!,age:Int"
  bash main.sh --type schema --entity Product --fields "title:String!,price:Float!,stock:Int" --relations "category:Category"
  bash main.sh --type query --entity Order
  bash main.sh --type resolver --entity User --lang typescript

Powered by BytesAgain | bytesagain.com | hello@bytesagain.com
HELPEOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --type) TYPE="$2"; shift 2;;
        --entity) ENTITY="$2"; shift 2;;
        --fields) FIELDS="$2"; shift 2;;
        --relations) RELATIONS="$2"; shift 2;;
        --lang) LANG="$2"; shift 2;;
        --output) OUTPUT="$2"; shift 2;;
        --help|-h) show_help; exit 0;;
        *) shift;;
    esac
done

[ -z "$TYPE" ] && { echo "Error: --type required"; show_help; exit 1; }
[ -z "$ENTITY" ] && { echo "Error: --entity required"; show_help; exit 1; }

generate_graphql() {
    python3 << PYEOF
import sys

gtype = "$TYPE"
entity = "$ENTITY"
fields_str = "$FIELDS"
relations_str = "$RELATIONS"
lang = "$LANG"

# Parse fields
fields = []
if fields_str:
    for f in fields_str.split(","):
        f = f.strip()
        if ":" in f:
            name, ftype = f.split(":", 1)
            fields.append((name.strip(), ftype.strip()))
        else:
            fields.append((f.strip(), "String"))

# Parse relations
relations = []
if relations_str:
    for r in relations_str.split(","):
        r = r.strip()
        if ":" in r:
            name, rtype = r.split(":", 1)
            relations.append((name.strip(), rtype.strip()))

# Default fields if none given
if not fields:
    fields = [("id", "ID!"), ("createdAt", "DateTime"), ("updatedAt", "DateTime")]

entity_lower = entity[0].lower() + entity[1:]
entity_plural = entity_lower + "s"

def gen_schema():
    lines = []
    lines.append("# ══════════════════════════════════════")
    lines.append("# GraphQL Schema: {}".format(entity))
    lines.append("# Generated by BytesAgain GraphQL Builder")
    lines.append("# ══════════════════════════════════════")
    lines.append("")
    
    # Scalar types
    lines.append("scalar DateTime")
    lines.append("scalar JSON")
    lines.append("")
    
    # Main type
    lines.append("type {} {{".format(entity))
    lines.append("  id: ID!")
    for name, ftype in fields:
        if name != "id":
            lines.append("  {}: {}".format(name, ftype))
    for name, rtype in relations:
        lines.append("  {}: {}".format(name, rtype))
    lines.append("  createdAt: DateTime")
    lines.append("  updatedAt: DateTime")
    lines.append("}")
    lines.append("")
    
    # Input types
    lines.append("input Create{}Input {{".format(entity))
    for name, ftype in fields:
        if name not in ("id", "createdAt", "updatedAt"):
            lines.append("  {}: {}".format(name, ftype))
    lines.append("}")
    lines.append("")
    
    lines.append("input Update{}Input {{".format(entity))
    for name, ftype in fields:
        if name not in ("id", "createdAt", "updatedAt"):
            clean_type = ftype.replace("!", "")
            lines.append("  {}: {}".format(name, clean_type))
    lines.append("}")
    lines.append("")
    
    # Filter & pagination
    lines.append("input {}Filter {{".format(entity))
    lines.append("  search: String")
    for name, ftype in fields:
        clean = ftype.replace("!", "")
        if clean in ("String", "Int", "Float", "Boolean", "ID"):
            lines.append("  {}: {}".format(name, clean))
    lines.append("}")
    lines.append("")
    
    lines.append("input PaginationInput {")
    lines.append("  page: Int = 1")
    lines.append("  limit: Int = 20")
    lines.append("  sortBy: String")
    lines.append("  sortOrder: SortOrder = DESC")
    lines.append("}")
    lines.append("")
    
    lines.append("enum SortOrder { ASC DESC }")
    lines.append("")
    
    # Connection type
    lines.append("type {}Connection {{".format(entity))
    lines.append("  items: [{}!]!".format(entity))
    lines.append("  total: Int!")
    lines.append("  page: Int!")
    lines.append("  pages: Int!")
    lines.append("}")
    lines.append("")
    
    # Queries
    lines.append("type Query {")
    lines.append("  {}(id: ID!): {}".format(entity_lower, entity))
    lines.append("  {}(filter: {}Filter, pagination: PaginationInput): {}Connection!".format(entity_plural, entity, entity))
    lines.append("}")
    lines.append("")
    
    # Mutations
    lines.append("type Mutation {")
    lines.append("  create{}(input: Create{}Input!): {}!".format(entity, entity, entity))
    lines.append("  update{}(id: ID!, input: Update{}Input!): {}!".format(entity, entity, entity))
    lines.append("  delete{}(id: ID!): Boolean!".format(entity))
    lines.append("}")
    
    return "\n".join(lines)

def gen_query():
    lines = []
    lines.append("# ── Queries for {} ──".format(entity))
    lines.append("")
    lines.append("# Get single {}".format(entity_lower))
    lines.append("query Get{}($id: ID!) {{".format(entity))
    lines.append("  {}(id: $id) {{".format(entity_lower))
    lines.append("    id")
    for name, _ in fields:
        if name != "id":
            lines.append("    {}".format(name))
    for name, rtype in relations:
        lines.append("    {} {{ id }}".format(name))
    lines.append("    createdAt")
    lines.append("    updatedAt")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    
    lines.append("# List {}".format(entity_plural))
    lines.append("query List{}($filter: {}Filter, $pagination: PaginationInput) {{".format(entity + "s", entity))
    lines.append("  {}(filter: $filter, pagination: $pagination) {{".format(entity_plural))
    lines.append("    items {")
    lines.append("      id")
    for name, _ in fields[:3]:
        if name != "id":
            lines.append("      {}".format(name))
    lines.append("    }")
    lines.append("    total")
    lines.append("    page")
    lines.append("    pages")
    lines.append("  }")
    lines.append("}")
    
    return "\n".join(lines)

def gen_mutation():
    lines = []
    lines.append("# ── Mutations for {} ──".format(entity))
    lines.append("")
    lines.append("mutation Create{}($input: Create{}Input!) {{".format(entity, entity))
    lines.append("  create{}(input: $input) {{".format(entity))
    lines.append("    id")
    for name, _ in fields:
        if name != "id":
            lines.append("    {}".format(name))
    lines.append("  }")
    lines.append("}")
    lines.append("")
    
    lines.append("mutation Update{}($id: ID!, $input: Update{}Input!) {{".format(entity, entity))
    lines.append("  update{}(id: $id, input: $input) {{".format(entity))
    lines.append("    id")
    for name, _ in fields:
        if name != "id":
            lines.append("    {}".format(name))
    lines.append("  }")
    lines.append("}")
    lines.append("")
    
    lines.append("mutation Delete{}($id: ID!) {{".format(entity))
    lines.append("  delete{}(id: $id)".format(entity))
    lines.append("}")
    
    return "\n".join(lines)

def gen_resolver():
    if lang == "typescript":
        return """// ── Resolvers for {entity} ──
import {{ {entity} }} from './models';

export const {lower}Resolvers = {{
  Query: {{
    {lower}: async (_: any, {{ id }}: {{ id: string }}) => {{
      return await {entity}.findById(id);
    }},
    {plural}: async (_: any, {{ filter, pagination }}: any) => {{
      const {{ page = 1, limit = 20, sortBy = 'createdAt', sortOrder = 'DESC' }} = pagination || {{}};
      const query = filter?.search
        ? {{ $text: {{ $search: filter.search }} }}
        : {{}};
      const total = await {entity}.countDocuments(query);
      const items = await {entity}.find(query)
        .sort({{ [sortBy]: sortOrder === 'DESC' ? -1 : 1 }})
        .skip((page - 1) * limit)
        .limit(limit);
      return {{ items, total, page, pages: Math.ceil(total / limit) }};
    }},
  }},
  Mutation: {{
    create{entity}: async (_: any, {{ input }}: any) => {{
      return await {entity}.create(input);
    }},
    update{entity}: async (_: any, {{ id, input }}: any) => {{
      return await {entity}.findByIdAndUpdate(id, input, {{ new: true }});
    }},
    delete{entity}: async (_: any, {{ id }}: {{ id: string }}) => {{
      await {entity}.findByIdAndDelete(id);
      return true;
    }},
  }},
}};""".format(entity=entity, lower=entity_lower, plural=entity_plural)
    else:
        return """// ── Resolvers for {entity} ──
const {lower}Resolvers = {{
  Query: {{
    {lower}: async (_, {{ id }}, context) => {{
      return await context.db.{lower}.findById(id);
    }},
    {plural}: async (_, {{ filter, pagination }}, context) => {{
      const {{ page = 1, limit = 20 }} = pagination || {{}};
      const query = filter || {{}};
      const total = await context.db.{lower}.count(query);
      const items = await context.db.{lower}.findAll({{
        where: query,
        offset: (page - 1) * limit,
        limit
      }});
      return {{ items, total, page, pages: Math.ceil(total / limit) }};
    }},
  }},
  Mutation: {{
    create{entity}: async (_, {{ input }}, context) => {{
      return await context.db.{lower}.create(input);
    }},
    update{entity}: async (_, {{ id, input }}, context) => {{
      return await context.db.{lower}.update(id, input);
    }},
    delete{entity}: async (_, {{ id }}, context) => {{
      await context.db.{lower}.delete(id);
      return true;
    }},
  }},
}};

module.exports = {lower}Resolvers;""".format(entity=entity, lower=entity_lower, plural=entity_plural)

# Generate based on type
sections = []
if gtype in ("schema", "full"):
    sections.append(gen_schema())
if gtype in ("query", "full"):
    sections.append(gen_query())
if gtype in ("mutation", "full"):
    sections.append(gen_mutation())
if gtype in ("resolver", "full"):
    sections.append(gen_resolver())

if not sections:
    print("Error: Unknown type '{}'".format(gtype))
    sys.exit(1)

print("\n\n".join(sections))
print("")
print("# ---")
print("# Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
}

if [ -n "$OUTPUT" ]; then
    generate_graphql > "$OUTPUT"
    echo "Saved to $OUTPUT"
else
    generate_graphql
fi
