import os
import argparse
from scanner import get_recent_memory_files
from analyzer import InsightAnalyzer
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

def run_pie(days=7, provider=None):
    print(f"🚀 Starting PIE (Personal Insight Engine)...")
    print(f"📅 Lookback period: {days} days")
    
    # 1. Discovery
    files = get_recent_memory_files(days=days)
    if not files:
        print("❌ No memory files found in the specified period.")
        return

    print(f"📂 Found {len(files)} files. Processing...")

    # 2. Aggregation and Cleaning
    analyzer = InsightAnalyzer(provider=provider)
    if not analyzer.api_key:
        print("❌ Error: No API key found. Please set GEMINI_API_KEY or ZHIPU_API_KEY.")
        return
    
    print(f"🤖 Using provider: {analyzer.provider.upper()}")
    
    full_text = ""
    for f in files:
        with open(f, 'r', encoding='utf-8') as file:
            content = file.read()
            clean = analyzer.clean_content(content)
            full_text += f"\n--- File: {f.name} ---\n{clean}\n"

    # 3. LLM Synthesis
    print(f"🧠 Analyzing content with LLM...")
    insights = analyzer.get_insights(full_text)

    # 4. Reporting
    report = f"""
# 🥧 PIE: Weekly Strategic Review
**Date Range**: Last {days} days
**Files Scanned**: {len(files)}

## 🔍 Top 3 Strategic Insights

{insights}

---
*Generated by Cipher (OpenSpec Agent)*
"""
    print("\n" + "="*40)
    print(report)
    print("="*40)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Personal Insight Engine")
    parser.add_argument("--days", type=int, default=7, help="Number of days to look back")
    parser.add_argument("--provider", type=str, choices=["gemini", "zhipu"], help="Force a specific LLM provider")
    args = parser.parse_args()
    
    run_pie(days=args.days, provider=args.provider)
