module.exports = {
  POLICY_MISSING: 'POLICY_MISSING',
  POLICY_INVALID: 'POLICY_INVALID',
  CHAIN_DENIED: 'CHAIN_DENIED',
  ASSET_DENIED: 'ASSET_DENIED',
  RECIPIENT_DENIED: 'RECIPIENT_DENIED',
  PER_TX_EXCEEDED: 'PER_TX_EXCEEDED',
  DAILY_CAP_EXCEEDED: 'DAILY_CAP_EXCEEDED',
  RATE_LIMITED: 'RATE_LIMITED',
  ACTION_DENIED: 'ACTION_DENIED',
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
  WALLET_UNDERFUNDED: 'WALLET_UNDERFUNDED',
};
