# -*- coding: utf-8 -*-
"""
tencentcloud-aigc-recog-image: Tencent Cloud AI-Generated Image Detection Skill
Calls the ImageModeration API with Type=IMAGE_AIGC to detect whether an image
is generated by AI.

Usage:
  python main.py "https://example.com/image.jpg"
  python main.py /path/to/image.png
  python main.py --url "https://example.com/image.jpg"
  python main.py --file /path/to/image.png
  python main.py --data-id my_id /path/to/image.png
"""

import json
import os
import sys
import base64  # noqa: E402

try:
    from tencentcloud.common import credential  # noqa: E402
    from tencentcloud.common.profile.client_profile import ClientProfile  # noqa: E402
    from tencentcloud.common.profile.http_profile import HttpProfile  # noqa: E402
    from tencentcloud.common.exception.tencent_cloud_sdk_exception import TencentCloudSDKException  # noqa: E402
    from tencentcloud.ims.v20201229 import ims_client, models  # noqa: E402
except ImportError:
    print("错误: 缺少依赖 tencentcloud-sdk-python，请执行: pip install tencentcloud-sdk-python", file=sys.stderr)
    sys.exit(1)

# Maximum file size: 5MB
MAX_FILE_SIZE = 5 * 1024 * 1024

# Supported image extensions
SUPPORTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".gif", ".webp"}


# ============================================================
# Part 1: Credential checking
# ============================================================

def get_credentials():
    """
    Check Tencent Cloud API credential environment variables.
    Supports TENCENTCLOUD_TOKEN for temporary credentials (STS Token).
    Outputs a configuration guide and exits if missing.
    """
    secret_id = os.getenv("TENCENTCLOUD_SECRET_ID")
    secret_key = os.getenv("TENCENTCLOUD_SECRET_KEY")
    token = os.getenv("TENCENTCLOUD_TOKEN")

    if not secret_id or not secret_key:
        missing = []
        if not secret_id:
            missing.append("TENCENTCLOUD_SECRET_ID")
        if not secret_key:
            missing.append("TENCENTCLOUD_SECRET_KEY")
        error_msg = {
            "error": "CREDENTIALS_NOT_CONFIGURED",
            "message": f"缺少环境变量: {', '.join(missing)}",
            "guide": {
                "step1": "开通AI生成图片检测服务: https://console.cloud.tencent.com/cms/clouds/LLM",
                "step2": "获取 API 密钥: https://console.cloud.tencent.com/cam/capi",
                "step3_linux": (
                    'export TENCENTCLOUD_SECRET_ID="your_secret_id"\n'
                    'export TENCENTCLOUD_SECRET_KEY="your_secret_key"'
                ),
                "step3_windows": (
                    '$env:TENCENTCLOUD_SECRET_ID = "your_secret_id"\n'
                    '$env:TENCENTCLOUD_SECRET_KEY = "your_secret_key"'
                ),
            },
        }
        print(json.dumps(error_msg, ensure_ascii=False, indent=2))
        sys.exit(1)

    # Support temporary credentials (STS Token)
    if token:
        cred = credential.Credential(secret_id, secret_key, token)
    else:
        cred = credential.Credential(secret_id, secret_key)

    return cred


def get_biz_type():
    """
    Get the BizType from TENCENTCLOUD_AIGC_RECOG_IMAGE_BIZ_TYPE environment variable.
    Each user must use their own BizType; exits with error if empty.
    """
    biz_type = os.getenv("TENCENTCLOUD_AIGC_RECOG_IMAGE_BIZ_TYPE", "").strip()

    if not biz_type:
        error_msg = {
            "error": "BIZ_TYPE_NOT_CONFIGURED",
            "message": "缺少环境变量: TENCENTCLOUD_AIGC_RECOG_IMAGE_BIZ_TYPE",
            "guide": {
                "step1": "在腾讯云控制台获取图片AI生成检测配套策略: https://console.cloud.tencent.com/cms/clouds/manage",
                "step2_linux": 'export TENCENTCLOUD_AIGC_RECOG_IMAGE_BIZ_TYPE="your_biz_type"',
                "step2_windows": '$env:TENCENTCLOUD_AIGC_RECOG_IMAGE_BIZ_TYPE = "your_biz_type"',
            },
        }
        print(json.dumps(error_msg, ensure_ascii=False, indent=2))
        sys.exit(1)

    return biz_type


# ============================================================
# Part 2: Command-line argument parsing
# ============================================================

def parse_args():
    """
    Parse command-line arguments.
    Supports: positional arg (URL or file path), --url, --file, --data-id
    """
    import argparse

    parser = argparse.ArgumentParser(
        description="Tencent Cloud AI-Generated Image Detection (ImageModeration IMAGE_AIGC)"
    )
    parser.add_argument(
        "image", nargs="?", default=None,
        help="Image URL or local file path (auto-detected)"
    )
    parser.add_argument(
        "--url", dest="image_url", default=None,
        help="Specify image URL"
    )
    parser.add_argument(
        "--file", dest="file_path", default=None,
        help="Specify local image file path"
    )
    parser.add_argument(
        "--data-id", dest="data_id", default=None,
        help="Business data identifier for correlating results (optional, max 128 chars)"
    )

    args = parser.parse_args()
    return args


def is_url(s):
    """Check if a string looks like a URL."""
    return s.startswith("http://") or s.startswith("https://")


def get_image_input(args):
    """
    Determine image input based on command-line arguments.
    Returns a tuple: (image_url, file_content_base64)
    Exactly one of them will be non-None.

    Priority: --url > --file > positional arg (auto-detect URL vs file path)
    """
    image_url = None
    file_content_base64 = None

    if args.image_url:
        # Explicit URL via --url
        image_url = args.image_url

    elif args.file_path:
        # Explicit file via --file
        file_content_base64 = read_image_file(args.file_path)

    elif args.image is not None:
        # Positional arg: auto-detect URL vs file path
        if is_url(args.image):
            image_url = args.image
        elif os.path.isfile(args.image):
            file_content_base64 = read_image_file(args.image)
        else:
            # Treat as URL if not a local file
            image_url = args.image

    else:
        # No input provided
        print(json.dumps({
            "error": "NO_INPUT",
            "message": "未提供待检测图片。",
            "usage": {
                "url": 'python main.py "https://example.com/image.jpg"',
                "file": "python main.py /path/to/image.png",
                "url_flag": 'python main.py --url "https://example.com/image.jpg"',
                "file_flag": "python main.py --file /path/to/image.png",
            },
        }, ensure_ascii=False, indent=2))
        sys.exit(1)

    return image_url, file_content_base64


def read_image_file(file_path):
    """
    Read a local image file and return its Base64-encoded content.
    Validates file existence, extension, and size.
    """
    if not os.path.isfile(file_path):
        print(json.dumps({
            "error": "FILE_NOT_FOUND",
            "message": f"指定的文件不存在: {file_path}",
        }, ensure_ascii=False, indent=2))
        sys.exit(1)

    # Check file extension
    _, ext = os.path.splitext(file_path)
    if ext.lower() not in SUPPORTED_EXTENSIONS:
        print(json.dumps({
            "error": "UNSUPPORTED_FORMAT",
            "message": f"不支持的图片格式: {ext}。支持的格式: {', '.join(sorted(SUPPORTED_EXTENSIONS))}",
        }, ensure_ascii=False, indent=2))
        sys.exit(1)

    # Check file size
    file_size = os.path.getsize(file_path)
    if file_size > MAX_FILE_SIZE:
        print(json.dumps({
            "error": "FILE_TOO_LARGE",
            "message": f"图片文件大小为 {file_size / 1024 / 1024:.2f}MB，超过 API 限制的 5MB。",
        }, ensure_ascii=False, indent=2))
        sys.exit(1)

    if file_size == 0:
        print(json.dumps({
            "error": "EMPTY_FILE",
            "message": "图片文件为空，请提供有效的图片文件。",
        }, ensure_ascii=False, indent=2))
        sys.exit(1)

    with open(file_path, "rb") as f:
        content = f.read()

    return base64.b64encode(content).decode("utf-8")


# ============================================================
# Part 3: API call and result output
# ============================================================

def call_image_moderation(cred, image_url=None, file_content=None,
                          data_id=None, biz_type=None):
    """
    Call Tencent Cloud ImageModeration API with Type=IMAGE_AIGC
    for AI-generated image detection.
    Returns the parsed API response.
    """
    # Configure HTTP Profile
    http_profile = HttpProfile()
    http_profile.endpoint = "ims.tencentcloudapi.com"

    # Configure Client Profile
    client_profile = ClientProfile()
    client_profile.httpProfile = http_profile

    # Create client (Region: Guangzhou, default for IMS service)
    client = ims_client.ImsClient(cred, "ap-guangzhou", client_profile)

    # Build request
    req = models.ImageModerationRequest()

    # Set image input: URL or Base64 content
    if image_url:
        req.FileUrl = image_url
    elif file_content:
        req.FileContent = file_content

    # Set detection type to AI-generated image
    req.Type = "IMAGE_AIGC"

    # Optional parameters
    if data_id:
        req.DataId = data_id
    if biz_type:
        req.BizType = biz_type

    # Send request
    resp = client.ImageModeration(req)
    return resp


def format_output(resp):
    """
    Parse API response and output structured JSON result.
    """
    # Convert response to dict
    resp_dict = json.loads(resp.to_json_string())

    result = {
        "suggestion": resp_dict.get("Suggestion", ""),
        "label": resp_dict.get("Label", ""),
        "score": resp_dict.get("Score", 0),
    }

    # Sub-label
    sub_label = resp_dict.get("SubLabel")
    if sub_label:
        result["sub_label"] = sub_label

    # Detailed detection results (LabelResults)
    label_results = resp_dict.get("LabelResults")
    if label_results:
        result["detail_results"] = []
        for item in label_results:
            detail = {
                "label": item.get("Label", ""),
                "suggestion": item.get("Suggestion", ""),
                "score": item.get("Score", 0),
            }
            sub = item.get("SubLabel")
            if sub:
                detail["sub_label"] = sub
            result["detail_results"].append(detail)

    # Object detection results (ObjectResults)
    object_results = resp_dict.get("ObjectResults")
    if object_results:
        result["object_results"] = []
        for item in object_results:
            obj = {
                "label": item.get("Label", ""),
                "suggestion": item.get("Suggestion", ""),
                "score": item.get("Score", 0),
            }
            sub = item.get("SubLabel")
            if sub:
                obj["sub_label"] = sub
            names = item.get("Names")
            if names:
                obj["names"] = names
            result["object_results"].append(obj)

    # OCR results (OcrResults)
    ocr_results = resp_dict.get("OcrResults")
    if ocr_results:
        result["ocr_results"] = []
        for item in ocr_results:
            ocr = {
                "label": item.get("Label", ""),
                "suggestion": item.get("Suggestion", ""),
                "score": item.get("Score", 0),
            }
            text = item.get("Text")
            if text:
                ocr["text"] = text
            result["ocr_results"].append(ocr)

    # Extra info
    extra = resp_dict.get("Extra")
    if extra:
        result["extra"] = extra

    # DataId passthrough
    data_id = resp_dict.get("DataId")
    if data_id:
        result["data_id"] = data_id

    # Request ID
    result["request_id"] = resp_dict.get("RequestId", "")

    return result


# ============================================================
# Main function
# ============================================================

def main():
    args = parse_args()
    image_url, file_content = get_image_input(args)
    cred = get_credentials()
    biz_type = get_biz_type()

    try:
        resp = call_image_moderation(
            cred,
            image_url=image_url,
            file_content=file_content,
            data_id=args.data_id,
            biz_type=biz_type,
        )
        result = format_output(resp)
        print(json.dumps(result, ensure_ascii=False, indent=2))

    except TencentCloudSDKException as err:
        print(json.dumps({
            "error": "API_ERROR",
            "code": err.code,
            "message": err.message,
            "request_id": err.requestId or "",
        }, ensure_ascii=False, indent=2))
        sys.exit(1)

    except Exception as err:
        print(json.dumps({
            "error": "UNEXPECTED_ERROR",
            "message": str(err),
        }, ensure_ascii=False, indent=2))
        sys.exit(1)


if __name__ == "__main__":
    main()
