/**
 * Clever Compact v2.2.0 — OpenClaw Plugin
 * Publisher: Axiom Stream Group
 * https://clawhub.ai/jfulmines-star/clever-compact
 *
 * Architecture: single lifecycle hook + explicit write function.
 *
 * Hook:
 *   before_prompt_build → inject state file ONCE per process (session start only)
 *
 * Write side:
 *   writeState(summary?) — call this before compaction or /new.
 *   The plugin exposes this as api.fn("clever-compact:write") so agents can
 *   trigger it via tool call or the manual trigger phrase.
 *
 * Note: OpenClaw does not currently expose a pre-compaction hook.
 * The write must be triggered explicitly (agent tool call, heartbeat, or
 * the "Pre-compaction memory flush" cron pattern). See SKILL.md for setup.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "fs";
import { join } from "path";

const VERSION = "2.2.3";
const MAX_STATE_AGE_HOURS = 72;
const STATE_FILE_PREFIX = "compact-state-";
const RESTORE_HEADER = "## 🔄 Clever Compact — Resuming Previous Session\n\n";

// Inject only once per process lifecycle (session start).
// Prevents prepending state file to every single prompt turn.
let hasInjectedThisSession = false;

function getMemoryDir(): string {
  const workspace =
    process.env.OPENCLAW_WORKSPACE ||
    (process.env.HOME
      ? join(process.env.HOME, ".openclaw", "workspace")
      : process.cwd());
  const dir = join(workspace, "memory");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  return dir;
}

function timestampedFilename(): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${STATE_FILE_PREFIX}${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}.md`;
}

function findMostRecentStateFile(): string | null {
  const memDir = getMemoryDir();
  const files = readdirSync(memDir)
    .filter((f) => f.startsWith(STATE_FILE_PREFIX) && f.endsWith(".md"))
    .sort()
    .reverse();

  if (!files.length) return null;

  // Age check — ignore files older than MAX_STATE_AGE_HOURS
  const match = files[0].match(
    /compact-state-(\d{4})-(\d{2})-(\d{2})-(\d{2})(\d{2})\.md/
  );
  if (match) {
    const [, y, mo, d, h, mi] = match;
    const fileDate = new Date(`${y}-${mo}-${d}T${h}:${mi}:00`);
    const ageHours = (Date.now() - fileDate.getTime()) / (1000 * 60 * 60);
    if (ageHours > MAX_STATE_AGE_HOURS) return null;
  }

  return join(memDir, files[0]);
}

export function writeState(summary?: string): string {
  const memDir = getMemoryDir();
  const filename = timestampedFilename();
  const filepath = join(memDir, filename);

  const now = new Date().toISOString();
  const body =
    summary ||
    `## Active Workstreams
_(No summary provided — agent should describe active workstreams here)_

## Key Decisions
_(None captured)_

## Open Tasks
_(None captured)_

## Remember Flags
_(None captured)_`;

  const content = `# Compact State — ${now}
_Generated by Clever Compact v${VERSION} | Axiom Stream Group_
_Pre-compaction save. Read this file at session start to restore context._

> ⚠️ Security: Do NOT include API keys, passwords, tokens, or sensitive credentials in this file.
> State files are stored in plaintext. Review memory/compact-state-*.md files periodically.

${body}

---
_Next session: read this file before responding to anything._
`;

  writeFileSync(filepath, content, "utf-8");
  return filepath;
}

export default function register(api: any) {

  /**
   * Expose writeState so agents can trigger it via tool call or manual phrase.
   * Usage: api.fn("clever-compact:write")(summary?)
   */
  if (api.fn) {
    api.fn("clever-compact:write", writeState);
  }

  /**
   * before_prompt_build
   * Fires on every turn — but we only inject ONCE per process (session start).
   * After the first injection, hasInjectedThisSession = true and we return
   * undefined for all subsequent turns. Zero token overhead mid-session.
   */
  api.on("before_prompt_build", (_event: any, _ctx: any) => {
    if (hasInjectedThisSession) return;

    const stateFile = findMostRecentStateFile();
    if (!stateFile) {
      // No state file — mark as done so we don't check again this session
      hasInjectedThisSession = true;
      return;
    }

    try {
      const content = readFileSync(stateFile, "utf-8");
      hasInjectedThisSession = true;
      return {
        prependSystemContext: `${RESTORE_HEADER}${content}\n\n---\n\n`,
      };
    } catch {
      hasInjectedThisSession = true;
      return;
    }
  });
}
