#!/bin/bash
# icf_review_workflow.sh - Step-by-step ICF review workflow guidance
# Run this script to see the review process and example commands

echo "=============================================="
echo "   ICF Review Workflow - Step-by-Step Guide"
echo "=============================================="
echo ""

echo "STEP 1: CONVERT PDF TO MARKDOWN"
echo "-------------------------------"
echo "Convert the ICF PDF document to markdown for review."
echo ""
echo "Command:"
echo "  ./pdf_to_icf_md.sh <input.pdf> [output.md]"
echo ""
echo "Example:"
echo "  ./pdf_to_icf_md.sh protocol_icf.pdf icf_review.md"
echo ""
echo "This will:"
echo "  - Extract text using markitdown"
echo "  - Remove form feed (\\f) characters"
echo "  - Generate a clean markdown file"
echo ""
read -p "Press Enter to continue to Step 2..."

echo ""
echo "STEP 2: REVIEW USING 16-POINT CHECKLIST"
echo "---------------------------------------"
echo "Review the markdown ICF against the regulatory checklist."
echo ""
echo "Checklist categories:"
echo "  1. Study Identification"
echo "  2. Sponsor Information"
echo "  3. IRB/IEC Information"
echo "  4. Purpose & Procedures"
echo "  5. Eligibility Criteria"
echo "  6. Risks & Benefits"
echo "  7. Alternatives & Confidentiality"
echo "  8. Voluntary Participation & Signatures"
echo ""
echo "Reference files:"
echo "  - REFERENCES/FDA_ICF_Guidance.pdf"
echo "  - REFERENCES/ICF_Checklist.md"
echo ""
echo "Tip: Open the markdown file in a text editor or use:"
echo "  cat icf_review.md | less"
echo ""
read -p "Press Enter to continue to Step 3..."

echo ""
echo "STEP 3: GENERATE STRUCTURED REPORT"
echo "-----------------------------------"
echo "Create a structured review report based on findings."
echo ""
echo "Manual process:"
echo "  1. Note any deficiencies or concerns"
echo "  2. Rate compliance (Adequate/Inadequate/Needs Clarification)"
echo "  3. List required revisions"
echo "  4. Document recommendations"
echo ""
echo "Reference report template:"
echo "  - EXAMPLES/ICF_Review_Report_Example.md"
echo ""
echo "Example output structure:"
echo "  ## ICF Review Report"
echo "  ### Study: [Protocol Title]"
echo "  ### Checklist Compliance"
echo "  ### Findings"
echo "  ### Recommendations"
echo ""
read -p "Press Enter to return to menu..."

echo ""
echo "=============================================="
echo "   QUICK REFERENCE COMMANDS"
echo "=============================================="
echo ""
echo "# Full workflow example:"
echo "  cd /tmp/icf-review-skill"
echo "  ./scripts/pdf_to_icf_md.sh study_icf.pdf icf.md"
echo "  # Review icf.md against checklist in REFERENCES/"
echo "  # Generate report using EXAMPLES/ICF_Review_Report_Example.md as template"
echo ""
echo "# View checklist:"
echo "  cat REFERENCES/ICF_Checklist.md"
echo ""
echo "# View example report:"
echo "  cat EXAMPLES/ICF_Review_Report_Example.md"
echo ""
echo "=============================================="
