/**
 * Book Highlights Skill
 * Extract key highlights and quotes from books
 */

const fs = require('fs');
const path = require('path');

class BookHighlightsSkill {
  constructor() {
    this.heardlyBooks = this.loadHeardlyBooks();
  }

  /**
   * Load Heardly books database
   */
  loadHeardlyBooks() {
    try {
      const dataPath = path.join(__dirname, 'data', 'books.json');
      if (fs.existsSync(dataPath)) {
        return JSON.parse(fs.readFileSync(dataPath, 'utf8'));
      }
    } catch (e) {
      // Heardly data not available
    }
    return [];
  }

  /**
   * Get highlights by query (returns formatted text by default)
   */
  async getHighlights(options = {}) {
    const { query, limit = 10, format = 'text' } = options;
    if (!query) return 'Error: Query required';

    // Search in Heardly database
    const book = this.searchBook(query);
    
    if (!book) {
      return `No book found for: ${query}`;
    }

    const highlights = this.extractHighlights(book, limit);

    // Return formatted text by default (user-friendly)
    if (format === 'text') {
      return this.formatHighlights(book, highlights);
    }

    // Return JSON if explicitly requested
    return {
      query,
      book: {
        title: book.title,
        author: book.author,
      },
      highlights,
    };
  }

  /**
   * Search for a book in Heardly database
   */
  searchBook(query) {
    const q = query.toLowerCase();
    return this.heardlyBooks.find(book =>
      book.title?.toLowerCase().includes(q) ||
      book.author?.toLowerCase().includes(q)
    );
  }

  /**
   * Extract highlights from book
   */
  extractHighlights(book, limit) {
    const highlights = [];

    // 1. Use highlights field if available
    if (book.highlights && Array.isArray(book.highlights)) {
      highlights.push(...book.highlights.slice(0, limit));
    }

    // 2. If not enough, extract from summary
    if (highlights.length < limit && book.summary) {
      const extracted = this.extractFromSummary(book.summary, limit - highlights.length);
      highlights.push(...extracted);
    }

    // 3. If still not enough, use key ideas from description
    if (highlights.length < limit && book.description) {
      const extracted = this.extractFromSummary(book.description, limit - highlights.length);
      highlights.push(...extracted);
    }

    return highlights.slice(0, limit);
  }

  /**
   * Extract key sentences from text
   */
  extractFromSummary(text, limit) {
    if (!text) return [];

    // Split by sentences
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 20);
    
    // Take every nth sentence to distribute across text
    const step = Math.max(1, Math.floor(sentences.length / limit));
    const extracted = [];
    
    for (let i = 0; i < limit && i * step < sentences.length; i++) {
      extracted.push(sentences[i * step].trim());
    }

    return extracted;
  }

  /**
   * Format highlights for display (consistent format)
   */
  formatHighlights(book, highlights) {
    if (!highlights || highlights.length === 0) {
      return `No highlights found for: ${book.title}`;
    }

    let result = `${book.title}\n`;
    result += `Author: ${book.author}\n\n`;

    highlights.forEach((highlight, index) => {
      result += `${index + 1}. ${highlight}\n`;
      result += `— From ${book.title}\n\n`;
    });

    result += `book summary generated by Heardly app — turning books into knowledge you can hear.`;

    return result;
  }
}

module.exports = BookHighlightsSkill;
