import os
import subprocess
import sys
from security_utils import (
    assert_safe_file_target,
    atomic_write_text,
    clean_secure_workspace,
    get_secure_workspace,
)

def trigger_evolution(skill_path, task_desc, trace_file, feedback_file, interactive=False):
    """
    Triggers the skill evolution process from within a Python application.
    Returns the update report as a string.
    """
    # 1. Setup secure workspace
    secure_dir = get_secure_workspace(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    
    # 2. If input files are not already in secure dir, copy/move them or just ensure they are handled safely.
    # Ideally, the caller should have written them securely, but we can't enforce that here.
    # However, optimize_skill.py needs to read them.
    # If the user passed paths, we use them.
    # But for extra security, we could mandate they be in secure_dir, or we just rely on optimize_skill reading them.
    # Since optimize_skill runs locally, reading files is generally okay. 
    # The risk is if the trace file contains malicious content AND is world-readable/writable while we process it.
    
    # Let's assume the trace_file and feedback_file provided by caller are already where they need to be.
    # But to answer the user's request of "restricting access during update":
    # We can copy them to secure workspace and only operate on them there?
    # No, optimize_skill just reads them.
    
    # The main "secure folder" request implies where we store intermediate data.
    # In hook_wrapper, we are just a wrapper.
    # But if we want to enforce security, we can copy the input files to our secure workspace before processing
    # to ensure no one modifies them during the race condition of the update process.
    
    secure_trace = os.path.join(secure_dir, "secure_trace.log")
    secure_feedback = os.path.join(secure_dir, "secure_feedback.txt")
    
    try:
        skill_path = assert_safe_file_target(skill_path, must_exist=True, require_write=True)
        trace_file = assert_safe_file_target(trace_file, must_exist=True, require_write=False)
        feedback_file = assert_safe_file_target(feedback_file, must_exist=True, require_write=False)

        # Copy content to secure location to prevent tampering during optimization
        with open(trace_file, 'r', encoding='utf-8') as src:
            atomic_write_text(secure_trace, src.read())
            
        with open(feedback_file, 'r', encoding='utf-8') as src:
            atomic_write_text(secure_feedback, src.read())
            
        script_path = os.path.join(os.path.dirname(__file__), "optimize_skill.py")
        
        cmd = [
            sys.executable, script_path,
            "--skill-path", skill_path,
            "--task-desc", task_desc,
            "--trace-file", secure_trace,
            "--feedback-file", secure_feedback
        ]
        
        if interactive:
            cmd.append("--interactive")
        
        print(f"Triggering evolution for {skill_path}...")
        
        # Run the optimization script
        subprocess.run(cmd, check=True)
        
        # Read the report generated by the script
        skill_dir = os.path.dirname(skill_path)
        report_path = os.path.join(skill_dir, "last_update.md")
        
        if os.path.exists(report_path):
            with open(report_path, 'r', encoding='utf-8') as f:
                return f.read()
        else:
            return "Evolution completed successfully, but no report file was generated."
            
    except subprocess.CalledProcessError as e:
        return f"Error triggering evolution: {e}"
    except Exception as e:
        return f"Unexpected error: {e}"
    finally:
        clean_secure_workspace(secure_dir)

if __name__ == "__main__":
    # Example usage
    if len(sys.argv) < 5:
        print("Usage: python hook_wrapper.py <skill_path> <task_desc> <trace_file> <feedback_file>")
        sys.exit(1)
        
    report = trigger_evolution(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
    print("\n=== Update Report ===\n")
    print(report)
