#!/usr/bin/env python3
"""EduClaw schema — 32 tables, 88 indexes, 419 columns.

Generated by ERPForge Schema DSL (generate_schema.py)
Post-processed to add table-level UNIQUE/CHECK constraints and fix
prerequisite_course_id FK (generator limitation with same-table double refs).

Tables: 32 | Indexes: 88 | Columns: 419

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Owning skill: educlaw (standalone — no parent product)
Run: python3 init_db.py [db_path]
"""
import os
import sqlite3
import sys


DEFAULT_DB_PATH = os.path.expanduser("~/.openclaw/erpclaw/data.sqlite")


def create_educlaw_tables(db_path):
    conn = sqlite3.connect(db_path)
    conn.execute("PRAGMA foreign_keys=ON")

    # Verify foundation exists
    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table'"
    ).fetchall()]
    if "company" not in tables:
        print("ERROR: Foundation tables not found. Run erpclaw first.")
        sys.exit(1)

    conn.executescript("""
        -- ==========================================================
        -- EduClaw Domain Tables
        -- Generated by ERPForge Schema DSL
        -- Tables: 32 | Columns: 419
        -- ==========================================================

        -- educlaw_academic_year (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_academic_year (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL DEFAULT '',
            start_date TEXT NOT NULL DEFAULT '',
            end_date TEXT NOT NULL DEFAULT '',
            is_active INTEGER NOT NULL DEFAULT 1,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(company_id, name),
            CHECK(start_date < end_date)
        );

        -- educlaw_academic_term (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_academic_term (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL DEFAULT '',
            term_type TEXT NOT NULL DEFAULT '' CHECK(term_type IN ('semester','quarter','trimester','summer','custom')),
            academic_year_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_year(id) ON DELETE RESTRICT,
            start_date TEXT NOT NULL DEFAULT '',
            end_date TEXT NOT NULL DEFAULT '',
            enrollment_start_date TEXT NOT NULL DEFAULT '',
            enrollment_end_date TEXT NOT NULL DEFAULT '',
            grade_submission_deadline TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'setup' CHECK(status IN ('setup','enrollment_open','active','grades_open','grades_finalized','closed')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            CHECK(start_date < end_date)
        );

        -- educlaw_announcement (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_announcement (
            id TEXT PRIMARY KEY,
            title TEXT NOT NULL DEFAULT '',
            body TEXT NOT NULL DEFAULT '',
            priority TEXT NOT NULL DEFAULT 'normal' CHECK(priority IN ('normal','urgent','emergency')),
            audience_type TEXT NOT NULL DEFAULT '' CHECK(audience_type IN ('all','students','guardians','staff','program','section','department','grade_level')),
            audience_filter TEXT NOT NULL DEFAULT '{}',
            publish_date TEXT NOT NULL DEFAULT '',
            expiry_date TEXT NOT NULL DEFAULT '',
            announcement_status TEXT NOT NULL DEFAULT 'draft' CHECK(announcement_status IN ('draft','published','archived')),
            published_by TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_course (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_course (
            id TEXT PRIMARY KEY,
            course_code TEXT NOT NULL DEFAULT '',
            name TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            credit_hours TEXT NOT NULL DEFAULT '0',
            department_id TEXT REFERENCES department(id) ON DELETE RESTRICT,
            course_type TEXT NOT NULL DEFAULT 'lecture' CHECK(course_type IN ('lecture','lab','seminar','independent_study','internship','online')),
            grade_level TEXT NOT NULL DEFAULT '',
            max_enrollment INTEGER NOT NULL DEFAULT 0,
            is_active INTEGER NOT NULL DEFAULT 1,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(company_id, course_code)
        );

        -- educlaw_course_prerequisite (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_course_prerequisite (
            id TEXT PRIMARY KEY,
            course_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_course(id) ON DELETE RESTRICT,
            prerequisite_course_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_course(id) ON DELETE RESTRICT,
            min_grade TEXT NOT NULL DEFAULT '',
            is_corequisite INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(course_id, prerequisite_course_id),
            CHECK(course_id != prerequisite_course_id)
        );

        -- educlaw_fee_category (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_fee_category (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            revenue_account_id TEXT REFERENCES account(id) ON DELETE RESTRICT,
            is_active INTEGER NOT NULL DEFAULT 1,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_grading_scale (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_grading_scale (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            is_default INTEGER NOT NULL DEFAULT 0,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(company_id, name)
        );

        -- educlaw_grading_scale_entry (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_grading_scale_entry (
            id TEXT PRIMARY KEY,
            grading_scale_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_grading_scale(id) ON DELETE RESTRICT,
            letter_grade TEXT NOT NULL DEFAULT '',
            grade_points TEXT NOT NULL DEFAULT '0',
            min_percentage TEXT NOT NULL DEFAULT '0',
            max_percentage TEXT NOT NULL DEFAULT '0',
            description TEXT NOT NULL DEFAULT '',
            is_passing INTEGER NOT NULL DEFAULT 1,
            counts_in_gpa INTEGER NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(grading_scale_id, letter_grade),
            CHECK(CAST(min_percentage AS REAL) <= CAST(max_percentage AS REAL))
        );

        -- educlaw_guardian (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_guardian (
            id TEXT PRIMARY KEY,
            first_name TEXT NOT NULL DEFAULT '',
            last_name TEXT NOT NULL DEFAULT '',
            full_name TEXT NOT NULL DEFAULT '',
            relationship TEXT NOT NULL DEFAULT '' CHECK(relationship IN ('father','mother','guardian','grandparent','stepparent','foster_parent','other')),
            email TEXT NOT NULL DEFAULT '',
            phone TEXT NOT NULL DEFAULT '',
            alternate_phone TEXT NOT NULL DEFAULT '',
            address TEXT NOT NULL DEFAULT '{}',
            occupation TEXT NOT NULL DEFAULT '',
            employer TEXT NOT NULL DEFAULT '',
            customer_id TEXT REFERENCES customer(id) ON DELETE RESTRICT,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_instructor (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_instructor (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            employee_id TEXT NOT NULL UNIQUE DEFAULT '' REFERENCES employee(id) ON DELETE RESTRICT,
            credentials TEXT NOT NULL DEFAULT '[]',
            specializations TEXT NOT NULL DEFAULT '[]',
            max_teaching_load_hours INTEGER NOT NULL DEFAULT 0,
            office_location TEXT NOT NULL DEFAULT '',
            office_hours TEXT NOT NULL DEFAULT '[]',
            bio TEXT NOT NULL DEFAULT '',
            is_active INTEGER NOT NULL DEFAULT 1,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_notification (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_notification (
            id TEXT PRIMARY KEY,
            recipient_type TEXT NOT NULL DEFAULT '' CHECK(recipient_type IN ('student','guardian','employee')),
            recipient_id TEXT NOT NULL DEFAULT '',
            notification_type TEXT NOT NULL DEFAULT '' CHECK(notification_type IN ('grade_posted','fee_due','absence','announcement','progress_report','emergency','acceptance','enrollment_confirmed')),
            title TEXT NOT NULL DEFAULT '',
            message TEXT NOT NULL DEFAULT '',
            reference_type TEXT NOT NULL DEFAULT '',
            reference_id TEXT NOT NULL DEFAULT '',
            is_read INTEGER NOT NULL DEFAULT 0,
            sent_via TEXT NOT NULL DEFAULT 'system' CHECK(sent_via IN ('system','email')),
            sent_at TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_program (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_program (
            id TEXT PRIMARY KEY,
            code TEXT NOT NULL DEFAULT '',
            name TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            program_type TEXT NOT NULL DEFAULT '' CHECK(program_type IN ('k12','associate','bachelor','master','doctoral','certificate','diploma')),
            department_id TEXT REFERENCES department(id) ON DELETE RESTRICT,
            total_credits_required TEXT NOT NULL DEFAULT '0',
            duration_years INTEGER NOT NULL DEFAULT 0,
            is_active INTEGER NOT NULL DEFAULT 1,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(company_id, code)
        );

        -- educlaw_fee_structure (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_fee_structure (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL DEFAULT '',
            program_id TEXT REFERENCES educlaw_program(id) ON DELETE RESTRICT,
            academic_term_id TEXT REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT,
            grade_level TEXT NOT NULL DEFAULT '',
            total_amount TEXT NOT NULL DEFAULT '0',
            is_active INTEGER NOT NULL DEFAULT 1,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            CHECK(CAST(total_amount AS REAL) >= 0)
        );

        -- educlaw_fee_structure_item (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_fee_structure_item (
            id TEXT PRIMARY KEY,
            fee_structure_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_fee_structure(id) ON DELETE RESTRICT,
            fee_category_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_fee_category(id) ON DELETE RESTRICT,
            amount TEXT NOT NULL DEFAULT '0',
            description TEXT NOT NULL DEFAULT '',
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(fee_structure_id, fee_category_id),
            CHECK(CAST(amount AS REAL) >= 0)
        );

        -- educlaw_program_requirement (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_program_requirement (
            id TEXT PRIMARY KEY,
            program_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_program(id) ON DELETE RESTRICT,
            course_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_course(id) ON DELETE RESTRICT,
            requirement_type TEXT NOT NULL DEFAULT '' CHECK(requirement_type IN ('required','elective','core','major','general_education')),
            credit_category TEXT NOT NULL DEFAULT '',
            min_grade TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(program_id, course_id)
        );

        -- educlaw_room (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_room (
            id TEXT PRIMARY KEY,
            room_number TEXT NOT NULL DEFAULT '',
            building TEXT NOT NULL DEFAULT '',
            capacity INTEGER NOT NULL DEFAULT 0,
            room_type TEXT NOT NULL DEFAULT 'classroom' CHECK(room_type IN ('classroom','lab','auditorium','gym','library','office')),
            facilities TEXT NOT NULL DEFAULT '[]',
            is_active INTEGER NOT NULL DEFAULT 1,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(company_id, building, room_number),
            CHECK(capacity > 0)
        );

        -- educlaw_section (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_section (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            section_number TEXT NOT NULL DEFAULT '',
            course_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_course(id) ON DELETE RESTRICT,
            academic_term_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT,
            instructor_id TEXT REFERENCES educlaw_instructor(id) ON DELETE RESTRICT,
            room_id TEXT REFERENCES educlaw_room(id) ON DELETE RESTRICT,
            days_of_week TEXT NOT NULL DEFAULT '[]',
            start_time TEXT NOT NULL DEFAULT '',
            end_time TEXT NOT NULL DEFAULT '',
            max_enrollment INTEGER NOT NULL DEFAULT 0,
            current_enrollment INTEGER NOT NULL DEFAULT 0,
            waitlist_enabled INTEGER NOT NULL DEFAULT 0,
            waitlist_max INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','scheduled','open','closed','cancelled')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT '',
            CHECK(max_enrollment > 0),
            CHECK(current_enrollment >= 0)
        );

        -- educlaw_assessment_plan (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_assessment_plan (
            id TEXT PRIMARY KEY,
            section_id TEXT NOT NULL UNIQUE DEFAULT '' REFERENCES educlaw_section(id) ON DELETE RESTRICT,
            grading_scale_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_grading_scale(id) ON DELETE RESTRICT,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_assessment_category (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_assessment_category (
            id TEXT PRIMARY KEY,
            assessment_plan_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_assessment_plan(id) ON DELETE RESTRICT,
            name TEXT NOT NULL DEFAULT '',
            weight_percentage TEXT NOT NULL DEFAULT '0',
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_assessment (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_assessment (
            id TEXT PRIMARY KEY,
            assessment_plan_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_assessment_plan(id) ON DELETE RESTRICT,
            category_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_assessment_category(id) ON DELETE RESTRICT,
            name TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            max_points TEXT NOT NULL DEFAULT '0',
            due_date TEXT NOT NULL DEFAULT '',
            is_published INTEGER NOT NULL DEFAULT 0,
            allows_extra_credit INTEGER NOT NULL DEFAULT 0,
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_student_applicant (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_student_applicant (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            first_name TEXT NOT NULL DEFAULT '',
            middle_name TEXT NOT NULL DEFAULT '',
            last_name TEXT NOT NULL DEFAULT '',
            date_of_birth TEXT NOT NULL DEFAULT '',
            gender TEXT NOT NULL DEFAULT '' CHECK(gender IN ('male','female','non_binary','prefer_not_to_say','')),
            email TEXT NOT NULL DEFAULT '',
            phone TEXT NOT NULL DEFAULT '',
            address TEXT NOT NULL DEFAULT '{}',
            applying_for_program_id TEXT REFERENCES educlaw_program(id) ON DELETE RESTRICT,
            applying_for_term_id TEXT REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT,
            previous_school TEXT NOT NULL DEFAULT '',
            previous_school_address TEXT NOT NULL DEFAULT '',
            transfer_records TEXT NOT NULL DEFAULT '',
            application_date TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'applied' CHECK(status IN ('applied','under_review','accepted','rejected','waitlisted','pending_info','confirmed','enrolled')),
            reviewed_by TEXT NOT NULL DEFAULT '',
            review_date TEXT NOT NULL DEFAULT '',
            review_notes TEXT NOT NULL DEFAULT '',
            acceptance_deadline TEXT NOT NULL DEFAULT '',
            guardian_info TEXT NOT NULL DEFAULT '[]',
            documents TEXT NOT NULL DEFAULT '[]',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_student (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_student (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            first_name TEXT NOT NULL DEFAULT '',
            middle_name TEXT NOT NULL DEFAULT '',
            last_name TEXT NOT NULL DEFAULT '',
            full_name TEXT NOT NULL DEFAULT '',
            date_of_birth TEXT NOT NULL DEFAULT '',
            gender TEXT NOT NULL DEFAULT '' CHECK(gender IN ('male','female','non_binary','prefer_not_to_say','')),
            email TEXT NOT NULL DEFAULT '',
            phone TEXT NOT NULL DEFAULT '',
            address TEXT NOT NULL DEFAULT '{}',
            emergency_contact TEXT NOT NULL DEFAULT '{}',
            student_applicant_id TEXT REFERENCES educlaw_student_applicant(id) ON DELETE RESTRICT,
            customer_id TEXT REFERENCES customer(id) ON DELETE RESTRICT,
            current_program_id TEXT REFERENCES educlaw_program(id) ON DELETE RESTRICT,
            grade_level TEXT NOT NULL DEFAULT '',
            cohort_year INTEGER NOT NULL DEFAULT 0,
            cumulative_gpa TEXT NOT NULL DEFAULT '',
            total_credits_earned TEXT NOT NULL DEFAULT '0',
            academic_standing TEXT NOT NULL DEFAULT 'good' CHECK(academic_standing IN ('good','deans_list','honor_roll','probation','suspension')),
            status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','graduated','withdrawn','suspended','expelled','transferred','inactive')),
            registration_hold INTEGER NOT NULL DEFAULT 0,
            directory_info_opt_out INTEGER NOT NULL DEFAULT 0,
            is_coppa_applicable INTEGER NOT NULL DEFAULT 0,
            coppa_consent_type TEXT NOT NULL DEFAULT '' CHECK(coppa_consent_type IN ('parent','school','')),
            coppa_consent_date TEXT NOT NULL DEFAULT '',
            photo TEXT NOT NULL DEFAULT '',
            ssn_encrypted TEXT NOT NULL DEFAULT '',
            enrollment_date TEXT NOT NULL DEFAULT '',
            graduation_date TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_consent_record (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_consent_record (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            consent_type TEXT NOT NULL DEFAULT '' CHECK(consent_type IN ('ferpa_directory','ferpa_disclosure','coppa_collection','coppa_school_consent')),
            granted_by TEXT NOT NULL DEFAULT '',
            granted_by_relationship TEXT NOT NULL DEFAULT '' CHECK(granted_by_relationship IN ('parent','student','school_official','')),
            consent_date TEXT NOT NULL DEFAULT '',
            expiry_date TEXT NOT NULL DEFAULT '',
            is_revoked INTEGER NOT NULL DEFAULT 0,
            revoked_date TEXT NOT NULL DEFAULT '',
            third_party_name TEXT NOT NULL DEFAULT '',
            purpose TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_course_enrollment (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_course_enrollment (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            section_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_section(id) ON DELETE RESTRICT,
            enrollment_date TEXT NOT NULL DEFAULT '',
            enrollment_status TEXT NOT NULL DEFAULT 'enrolled' CHECK(enrollment_status IN ('enrolled','completed','dropped','withdrawn','incomplete','waitlisted')),
            drop_date TEXT NOT NULL DEFAULT '',
            drop_reason TEXT NOT NULL DEFAULT '',
            final_letter_grade TEXT NOT NULL DEFAULT '',
            final_grade_points TEXT NOT NULL DEFAULT '0',
            final_percentage TEXT NOT NULL DEFAULT '0',
            grade_submitted_by TEXT NOT NULL DEFAULT '',
            grade_submitted_at TEXT NOT NULL DEFAULT '',
            is_grade_submitted INTEGER NOT NULL DEFAULT 0,
            is_repeat INTEGER NOT NULL DEFAULT 0,
            grade_type TEXT NOT NULL DEFAULT 'letter' CHECK(grade_type IN ('letter','pass_fail','audit')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_assessment_result (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_assessment_result (
            id TEXT PRIMARY KEY,
            assessment_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_assessment(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            course_enrollment_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_course_enrollment(id) ON DELETE RESTRICT,
            points_earned TEXT NOT NULL DEFAULT '',
            is_exempt INTEGER NOT NULL DEFAULT 0,
            is_late INTEGER NOT NULL DEFAULT 0,
            comments TEXT NOT NULL DEFAULT '',
            graded_by TEXT NOT NULL DEFAULT '',
            graded_at TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_data_access_log (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_data_access_log (
            id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL DEFAULT '',
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            data_category TEXT NOT NULL DEFAULT '' CHECK(data_category IN ('demographics','grades','attendance','financial','health','discipline','communications')),
            access_type TEXT NOT NULL DEFAULT '' CHECK(access_type IN ('view','export','print','api')),
            access_reason TEXT NOT NULL DEFAULT '',
            is_emergency_access INTEGER NOT NULL DEFAULT 0,
            ip_address TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_grade_amendment (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_grade_amendment (
            id TEXT PRIMARY KEY,
            course_enrollment_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_course_enrollment(id) ON DELETE RESTRICT,
            old_letter_grade TEXT NOT NULL DEFAULT '',
            new_letter_grade TEXT NOT NULL DEFAULT '',
            old_grade_points TEXT NOT NULL DEFAULT '0',
            new_grade_points TEXT NOT NULL DEFAULT '0',
            reason TEXT NOT NULL DEFAULT '',
            amended_by TEXT NOT NULL DEFAULT '',
            approved_by TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_program_enrollment (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_program_enrollment (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            program_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_program(id) ON DELETE RESTRICT,
            academic_year_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_year(id) ON DELETE RESTRICT,
            enrollment_date TEXT NOT NULL DEFAULT '',
            enrollment_status TEXT NOT NULL DEFAULT 'active' CHECK(enrollment_status IN ('active','completed','withdrawn','suspended')),
            fee_invoice_id TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_scholarship (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_scholarship (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL DEFAULT '',
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            academic_term_id TEXT REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT,
            discount_type TEXT NOT NULL DEFAULT '' CHECK(discount_type IN ('fixed','percentage')),
            discount_amount TEXT NOT NULL DEFAULT '0',
            applies_to_category_id TEXT REFERENCES educlaw_fee_category(id) ON DELETE RESTRICT,
            scholarship_status TEXT NOT NULL DEFAULT 'active' CHECK(scholarship_status IN ('active','expired','revoked')),
            reason TEXT NOT NULL DEFAULT '',
            approved_by TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_student_attendance (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_student_attendance (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            attendance_date TEXT NOT NULL DEFAULT '',
            section_id TEXT REFERENCES educlaw_section(id) ON DELETE RESTRICT,
            attendance_status TEXT NOT NULL DEFAULT '' CHECK(attendance_status IN ('present','absent','tardy','excused','half_day')),
            late_minutes INTEGER NOT NULL DEFAULT 0,
            comments TEXT NOT NULL DEFAULT '',
            marked_by TEXT NOT NULL DEFAULT '',
            source TEXT NOT NULL DEFAULT 'manual' CHECK(source IN ('manual','biometric','app')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_student_guardian (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_student_guardian (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            guardian_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_guardian(id) ON DELETE RESTRICT,
            relationship TEXT NOT NULL DEFAULT '' CHECK(relationship IN ('father','mother','guardian','grandparent','stepparent','foster_parent','other')),
            has_custody INTEGER NOT NULL DEFAULT 1,
            can_pickup INTEGER NOT NULL DEFAULT 1,
            receives_communications INTEGER NOT NULL DEFAULT 1,
            is_primary_contact INTEGER NOT NULL DEFAULT 0,
            is_emergency_contact INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_waitlist (owned by educlaw)
        CREATE TABLE IF NOT EXISTS educlaw_waitlist (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            section_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_section(id) ON DELETE RESTRICT,
            position INTEGER NOT NULL DEFAULT 0,
            requested_date TEXT NOT NULL DEFAULT '',
            waitlist_status TEXT NOT NULL DEFAULT 'waiting' CHECK(waitlist_status IN ('waiting','offered','accepted','expired','cancelled')),
            offer_expires_at TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- ==========================================================
        -- Indexes
        -- ==========================================================

        CREATE INDEX IF NOT EXISTS idx_academic_year_company_active ON educlaw_academic_year(company_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_academic_year_company_name ON educlaw_academic_year(company_id, name);
        CREATE INDEX IF NOT EXISTS idx_academic_term_year ON educlaw_academic_term(academic_year_id);
        CREATE INDEX IF NOT EXISTS idx_academic_term_company_status ON educlaw_academic_term(company_id, status);
        CREATE INDEX IF NOT EXISTS idx_academic_term_dates ON educlaw_academic_term(start_date, end_date);
        CREATE INDEX IF NOT EXISTS idx_announcement_company_status ON educlaw_announcement(company_id, announcement_status, publish_date);
        CREATE INDEX IF NOT EXISTS idx_announcement_audience ON educlaw_announcement(audience_type);
        CREATE INDEX IF NOT EXISTS idx_course_company_code ON educlaw_course(company_id, course_code);
        CREATE INDEX IF NOT EXISTS idx_course_department ON educlaw_course(department_id);
        CREATE INDEX IF NOT EXISTS idx_course_grade_level ON educlaw_course(grade_level);
        CREATE INDEX IF NOT EXISTS idx_course_active ON educlaw_course(company_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_prereq_course ON educlaw_course_prerequisite(course_id);
        CREATE INDEX IF NOT EXISTS idx_prereq_prereq ON educlaw_course_prerequisite(prerequisite_course_id);
        CREATE INDEX IF NOT EXISTS idx_fee_category_company ON educlaw_fee_category(company_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_grading_scale_company ON educlaw_grading_scale(company_id);
        CREATE INDEX IF NOT EXISTS idx_grading_scale_default ON educlaw_grading_scale(company_id, is_default);
        CREATE INDEX IF NOT EXISTS idx_scale_entry_scale ON educlaw_grading_scale_entry(grading_scale_id);
        CREATE INDEX IF NOT EXISTS idx_scale_entry_sort ON educlaw_grading_scale_entry(grading_scale_id, sort_order);
        CREATE INDEX IF NOT EXISTS idx_guardian_company_name ON educlaw_guardian(company_id, last_name, first_name);
        CREATE INDEX IF NOT EXISTS idx_guardian_email ON educlaw_guardian(email);
        CREATE INDEX IF NOT EXISTS idx_guardian_customer ON educlaw_guardian(customer_id);
        CREATE INDEX IF NOT EXISTS idx_instructor_employee ON educlaw_instructor(employee_id);
        CREATE INDEX IF NOT EXISTS idx_instructor_company_active ON educlaw_instructor(company_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_instructor_series ON educlaw_instructor(naming_series);
        CREATE INDEX IF NOT EXISTS idx_notification_recipient ON educlaw_notification(recipient_type, recipient_id, is_read);
        CREATE INDEX IF NOT EXISTS idx_notification_company_type ON educlaw_notification(company_id, notification_type);
        CREATE INDEX IF NOT EXISTS idx_notification_created ON educlaw_notification(created_at);
        CREATE INDEX IF NOT EXISTS idx_program_company_code ON educlaw_program(company_id, code);
        CREATE INDEX IF NOT EXISTS idx_program_department ON educlaw_program(department_id);
        CREATE INDEX IF NOT EXISTS idx_program_active ON educlaw_program(company_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_fee_structure_program_term ON educlaw_fee_structure(company_id, program_id, academic_term_id);
        CREATE INDEX IF NOT EXISTS idx_fee_structure_grade_term ON educlaw_fee_structure(company_id, grade_level, academic_term_id);
        CREATE INDEX IF NOT EXISTS idx_fee_structure_active ON educlaw_fee_structure(company_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_fee_item_structure ON educlaw_fee_structure_item(fee_structure_id);
        CREATE INDEX IF NOT EXISTS idx_fee_item_category ON educlaw_fee_structure_item(fee_category_id);
        CREATE INDEX IF NOT EXISTS idx_program_req_program ON educlaw_program_requirement(program_id);
        CREATE INDEX IF NOT EXISTS idx_program_req_course ON educlaw_program_requirement(course_id);
        CREATE INDEX IF NOT EXISTS idx_room_company_building ON educlaw_room(company_id, building, room_number);
        CREATE INDEX IF NOT EXISTS idx_room_active ON educlaw_room(company_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_section_course_term ON educlaw_section(course_id, academic_term_id);
        CREATE INDEX IF NOT EXISTS idx_section_instructor_term ON educlaw_section(instructor_id, academic_term_id);
        CREATE INDEX IF NOT EXISTS idx_section_room_term ON educlaw_section(room_id, academic_term_id);
        CREATE INDEX IF NOT EXISTS idx_section_company_status ON educlaw_section(company_id, status);
        CREATE INDEX IF NOT EXISTS idx_section_series ON educlaw_section(naming_series);
        CREATE INDEX IF NOT EXISTS idx_assessment_plan_section ON educlaw_assessment_plan(section_id);
        CREATE INDEX IF NOT EXISTS idx_assessment_category_plan ON educlaw_assessment_category(assessment_plan_id);
        CREATE INDEX IF NOT EXISTS idx_assessment_category_sort ON educlaw_assessment_category(assessment_plan_id, sort_order);
        CREATE INDEX IF NOT EXISTS idx_assessment_plan_category ON educlaw_assessment(assessment_plan_id, category_id);
        CREATE INDEX IF NOT EXISTS idx_assessment_due_date ON educlaw_assessment(due_date);
        CREATE INDEX IF NOT EXISTS idx_applicant_company_status ON educlaw_student_applicant(company_id, status);
        CREATE INDEX IF NOT EXISTS idx_applicant_term ON educlaw_student_applicant(applying_for_term_id);
        CREATE INDEX IF NOT EXISTS idx_applicant_series ON educlaw_student_applicant(naming_series);
        CREATE INDEX IF NOT EXISTS idx_student_company_status ON educlaw_student(company_id, status);
        CREATE INDEX IF NOT EXISTS idx_student_name ON educlaw_student(company_id, last_name, first_name);
        CREATE INDEX IF NOT EXISTS idx_student_customer ON educlaw_student(customer_id);
        CREATE INDEX IF NOT EXISTS idx_student_program ON educlaw_student(current_program_id);
        CREATE INDEX IF NOT EXISTS idx_student_series ON educlaw_student(naming_series);
        CREATE INDEX IF NOT EXISTS idx_student_coppa ON educlaw_student(is_coppa_applicable);
        CREATE INDEX IF NOT EXISTS idx_consent_student_type ON educlaw_consent_record(student_id, consent_type);
        CREATE INDEX IF NOT EXISTS idx_consent_company_type ON educlaw_consent_record(company_id, consent_type);
        CREATE INDEX IF NOT EXISTS idx_consent_revoked ON educlaw_consent_record(is_revoked);
        CREATE INDEX IF NOT EXISTS idx_course_enroll_student_section ON educlaw_course_enrollment(student_id, section_id);
        CREATE INDEX IF NOT EXISTS idx_course_enroll_section_status ON educlaw_course_enrollment(section_id, enrollment_status);
        CREATE INDEX IF NOT EXISTS idx_course_enroll_student_status ON educlaw_course_enrollment(student_id, enrollment_status);
        CREATE INDEX IF NOT EXISTS idx_course_enroll_grade_submitted ON educlaw_course_enrollment(company_id, is_grade_submitted);
        CREATE INDEX IF NOT EXISTS idx_assessment_result_assessment_student ON educlaw_assessment_result(assessment_id, student_id);
        CREATE INDEX IF NOT EXISTS idx_assessment_result_enrollment ON educlaw_assessment_result(course_enrollment_id);
        CREATE INDEX IF NOT EXISTS idx_assessment_result_student ON educlaw_assessment_result(student_id);
        CREATE INDEX IF NOT EXISTS idx_data_access_student_category ON educlaw_data_access_log(student_id, data_category);
        CREATE INDEX IF NOT EXISTS idx_data_access_user ON educlaw_data_access_log(user_id, created_at);
        CREATE INDEX IF NOT EXISTS idx_data_access_company ON educlaw_data_access_log(company_id, created_at);
        CREATE INDEX IF NOT EXISTS idx_data_access_emergency ON educlaw_data_access_log(is_emergency_access);
        CREATE INDEX IF NOT EXISTS idx_grade_amendment_enrollment ON educlaw_grade_amendment(course_enrollment_id);
        CREATE INDEX IF NOT EXISTS idx_grade_amendment_created ON educlaw_grade_amendment(created_at);
        CREATE INDEX IF NOT EXISTS idx_prog_enroll_student ON educlaw_program_enrollment(student_id);
        CREATE INDEX IF NOT EXISTS idx_prog_enroll_program_year ON educlaw_program_enrollment(program_id, academic_year_id);
        CREATE INDEX IF NOT EXISTS idx_prog_enroll_company_status ON educlaw_program_enrollment(company_id, enrollment_status);
        CREATE INDEX IF NOT EXISTS idx_scholarship_student_term ON educlaw_scholarship(student_id, academic_term_id);
        CREATE INDEX IF NOT EXISTS idx_scholarship_company_status ON educlaw_scholarship(company_id, scholarship_status);
        CREATE INDEX IF NOT EXISTS idx_attendance_student_date_section ON educlaw_student_attendance(student_id, attendance_date, section_id);
        CREATE INDEX IF NOT EXISTS idx_attendance_section_date ON educlaw_student_attendance(section_id, attendance_date);
        CREATE INDEX IF NOT EXISTS idx_attendance_company_date ON educlaw_student_attendance(company_id, attendance_date);
        CREATE INDEX IF NOT EXISTS idx_attendance_student_status ON educlaw_student_attendance(student_id, attendance_status);
        CREATE INDEX IF NOT EXISTS idx_student_guardian_student ON educlaw_student_guardian(student_id);
        CREATE INDEX IF NOT EXISTS idx_student_guardian_guardian ON educlaw_student_guardian(guardian_id);
        CREATE INDEX IF NOT EXISTS idx_waitlist_section_position ON educlaw_waitlist(section_id, position);
        CREATE INDEX IF NOT EXISTS idx_waitlist_student_section ON educlaw_waitlist(student_id, section_id);
        CREATE INDEX IF NOT EXISTS idx_waitlist_status ON educlaw_waitlist(company_id, waitlist_status);
    """)

    conn.commit()
    conn.close()

    print(f"EduClaw schema created: 32 tables", file=sys.stderr)
    print(f"Database: {db_path}", file=sys.stderr)


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    create_educlaw_tables(db_path)
