#!/usr/bin/env python3
"""
monthly_review.py - 月度日记聚合与回顾
读取过去30天日记 → 生成月度总结 → 推飞书卡片
"""

import json
import sys
from pathlib import Path
from datetime import datetime, timedelta

WORKSPACE = Path.home() / ".openclaw" / "workspace"
DIARY_DIR = WORKSPACE / "memory" / "diary"
AUTO_LEARN = WORKSPACE / "memory" / "auto-learn.md"

FEISHU_CHAT_ID = "oc_15949806c791613dbf45b872e8bc111a"


def get_last_month_dates():
    """获取上月日期范围"""
    today = datetime.now()
    # 上月第一天
    if today.month == 1:
        month_start = datetime(today.year - 1, 12, 1)
    else:
        month_start = datetime(today.year, today.month - 1, 1)
    
    # 上月最后一天
    month_end = datetime(today.year, today.month, 1) - timedelta(days=1)
    
    return (
        month_start.strftime("%Y-%m-%d"),
        month_end.strftime("%Y-%m-%d")
    )


def read_diaries_in_range(start_date_str, end_date_str):
    """读取日期范围内的所有日记"""
    diaries = []
    start = datetime.strptime(start_date_str, "%Y-%m-%d")
    end = datetime.strptime(end_date_str, "%Y-%m-%d")
    
    current = start
    while current <= end:
        d_str = current.strftime("%Y-%m-%d")
        diary_file = DIARY_DIR / f"{d_str}.md"
        if diary_file.exists():
            diaries.append({
                "date": d_str,
                "content": diary_file.read_text()
            })
        current += timedelta(days=1)
    
    return diaries


def extract_summary(content):
    """提取中文摘要"""
    try:
        start = content.index('**中文摘要:**') + len('**中文摘要:**')
        end = content.index('\n\n', start)
        return content[start:end].strip()
    except:
        try:
            start = content.index('**中文摘要 (For Jialin):**') + len('**中文摘要 (For Jialin):**')
            end = content.index('\n\n', start)
            return content[start:end].strip()
        except:
            return ""


def extract_key_decisions(content):
    """提取关键决策"""
    decisions = []
    try:
        start = content.index('## 🔑')
        rest = content[start:]
        end = rest.index('\n##', 1) if '\n##' in rest[1:] else len(rest)
        section = rest[:end]
        for line in section.split('\n'):
            if line.strip().startswith('-'):
                decisions.append(line.strip())
    except:
        pass
    return decisions[:3]


def generate_monthly_review_prompt(diaries, month_start, month_end):
    """生成月度回顾 prompt"""

    diary_summaries = []
    for d in diaries:
        zh = extract_summary(d['content'])
        decisions = extract_key_decisions(d['content'])
        diary_summaries.append(f"## {d['date']}\n摘要: {zh[:200]}\n决策: {'; '.join(decisions)}")

    diaries_text = '\n\n'.join(diary_summaries)
    month_label = month_start[:7]

    prompt = f"""你正在生成月度回顾（{month_label}）。

## 本月日记摘要（共 {len(diaries)} 天有记录）
{diaries_text[:3000]}

## 输出要求
生成月度回顾 Markdown，包含：

### 中文部分（给 Jialin）
1. **月度主题**（一句话总结本月核心）
2. **里程碑**（本月最重要的3个成就）
3. **挑战与反思**
4. **下月重点**

### English Section (For HexaLoop)
1. **Monthly Theme**: 英文主题
2. **Key Milestones**: 核心成就
3. **Major Lessons**: 主要教训（2-3条）
4. **System Growth**: 对 HexaLoop 有价值的进化信号

请生成完整 Markdown 后保存到: {DIARY_DIR}/{month_end}_monthly.md

同时，提取本月最有价值的洞察（格式 A）追加到 {AUTO_LEARN}
"""
    return prompt


def build_monthly_feishu_card(month_label, diaries, review_content):
    """构建月度回顾飞书卡片"""

    # 提取月度概览
    try:
        start = review_content.index('**月度主题**') + len('**月度主题**')
        end = review_content.index('##', start)
        theme = review_content[start:end].strip()[:200]
    except:
        theme = f"本月共 {len(diaries)} 天有记录。"

    card = {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {"tag": "plain_text", "text": f"🗓️ {month_label} 月度回顾"},
                "template": "orange"
            },
            "elements": [
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"**🎯 月度主题**\n{theme}"
                    }
                },
                {"tag": "hr"},
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"**📈 月度数据**\n- 记录天数: {len(diaries)} 天\n- Insights → auto-learn.md 已更新"
                    }
                },
                {
                    "tag": "note",
                    "elements": [
                        {"tag": "plain_text", "text": f"Generated by auto-diary monthly skill | {datetime.now().strftime('%Y-%m-%d')}"}
                    ]
                }
            ]
        }
    }

    return card


if __name__ == "__main__":
    month_start, month_end = get_last_month_dates()
    diaries = read_diaries_in_range(month_start, month_end)
    month_label = month_start[:7]

    if not diaries:
        print(f"[auto-diary] 上月（{month_start}~{month_end}）无日记记录")
        sys.exit(0)

    print(f"[auto-diary] 发现 {len(diaries)} 天日记，开始生成月度回顾...")

    # 生成 prompt
    prompt = generate_monthly_review_prompt(diaries, month_start, month_end)
    print(prompt)

    # 保存月度回顾
    review_file = DIARY_DIR / f"{month_end}_monthly.md"
    review_file.write_text(f"# {month_label} 月度回顾\n\n[由 main agent 填充完整内容]")
    print(f"[auto-diary] 月度回顾框架已保存: {review_file}")
