#!/usr/bin/env python3
"""
weekly_review.py - 周度日记聚合与回顾
读取过去7天日记 → 生成周度总结 → 推飞书卡片
"""

import json
import sys
from pathlib import Path
from datetime import datetime, timedelta

WORKSPACE = Path.home() / ".openclaw" / "workspace"
DIARY_DIR = WORKSPACE / "memory" / "diary"
AUTO_LEARN = WORKSPACE / "memory" / "auto-learn.md"

FEISHU_CHAT_ID = "oc_15949806c791613dbf45b872e8bc111a"


def get_week_dates():
    """获取上周一到周日日期"""
    today = datetime.now()
    # 上周一
    week_start = today - timedelta(days=today.weekday() + 7)
    week_end = week_start + timedelta(days=6)
    return (
        week_start.strftime("%Y-%m-%d"),
        week_end.strftime("%Y-%m-%d")
    )


def read_diaries_in_range(start_date, days=7):
    """读取日期范围内的所有日记"""
    diaries = []
    start = datetime.strptime(start_date, "%Y-%m-%d")
    
    for i in range(days):
        d = start + timedelta(days=i)
        d_str = d.strftime("%Y-%m-%d")
        diary_file = DIARY_DIR / f"{d_str}.md"
        if diary_file.exists():
            diaries.append({
                "date": d_str,
                "content": diary_file.read_text()
            })
    
    return diaries


def extract_summary(content):
    """提取中文摘要"""
    try:
        start = content.index('**中文摘要:**') + len('**中文摘要:**')
        end = content.index('\n\n', start)
        return content[start:end].strip()
    except:
        try:
            start = content.index('**中文摘要 (For Jialin):**') + len('**中文摘要 (For Jialin):**')
            end = content.index('\n\n', start)
            return content[start:end].strip()
        except:
            return ""


def extract_en_summary(content):
    """提取英文摘要"""
    try:
        start = content.index('**English Summary (For HexaLoop System):**')
        # 找到下一个 ** 之前的内容
        rest = content[start:]
        end = rest.index('\n##', 1) if '\n##' in rest[1:] else len(rest)
        return rest[:end].strip()
    except:
        return ""


def extract_kpis(content):
    """提取 KPI 指标"""
    kpis = {}
    
    # 简单解析表格
    lines = content.split('\n')
    for line in lines:
        if '|' in line and 'Tasks' in line or 'Sessions' in line:
            parts = [p.strip() for p in line.split('|')]
            if len(parts) >= 4:
                kpis[parts[1]] = parts[2]
    
    return kpis


def generate_weekly_review_prompt(diaries, week_start, week_end):
    """生成周度回顾 prompt"""

    diary_summaries = []
    for d in diaries:
        zh = extract_summary(d['content'])
        en = extract_en_summary(d['content'])
        diary_summaries.append(f"## {d['date']}\n中文: {zh}\nEnglish: {en}")

    diaries_text = '\n\n'.join(diary_summaries)

    prompt = f"""你正在生成周度回顾（{week_start} ~ {week_end}）。

## 本周日记摘要
{diaries_text}

## 输出要求
生成周度回顾 Markdown，包含：

### 中文部分（给 Jialin）
1. **本周概览**（3-5句话总结）
2. **关键进展**（最重要3件事）
3. **问题与反思**（本周遇到的挑战）
4. **下周计划**

### English Section (For HexaLoop)
1. **Weekly Summary**: 英文总结
2. **Top Insights**: 2-3 个核心洞察
3. **Actionable Next Steps**: 下周具体行动

请生成完整 Markdown 后保存到: {DIARY_DIR}/{week_end}_weekly.md

同时，提取本周最有价值的洞察（格式 A）追加到 {AUTO_LEARN}
"""
    return prompt


def build_weekly_feishu_card(week_start, week_end, diaries, review_content):
    """构建周度回顾飞书卡片"""

    # 提取本周统计
    total_tasks = 0
    insights_count = 0
    for d in diaries:
        kpis = extract_kpis(d['content'])
        total_tasks += int(kpis.get('Tasks', 0)) if kpis.get('Tasks', '').isdigit() else 0

    # 提取中文概览
    try:
        start = review_content.index('**本周概览**') + len('**本周概览**')
        end = review_content.index('##', start)
        zh_summary = review_content[start:end].strip()[:300]
    except:
        zh_summary = f"本周共 {len(diaries)} 天有记录，共完成约 {total_tasks} 项任务。"

    card = {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {"tag": "plain_text", "text": f"📊 {week_start} ~ {week_end} 周度回顾"},
                "template": "purple"
            },
            "elements": [
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"**📋 本周概览**\n{zh_summary}"
                    }
                },
                {"tag": "hr"},
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"**📊 数据亮点**\n- 记录天数: {len(diaries)}/7\n- Insights → auto-learn.md 已更新"
                    }
                },
                {
                    "tag": "note",
                    "elements": [
                        {"tag": "plain_text", "text": f"Generated by auto-diary weekly skill | {datetime.now().strftime('%Y-%m-%d')}"}
                    ]
                }
            ]
        }
    }

    return card


if __name__ == "__main__":
    week_start, week_end = get_week_dates()
    diaries = read_diaries_in_range(week_start, 7)

    if not diaries:
        print(f"[auto-diary] 本周（{week_start}~{week_end}）无日记记录")
        sys.exit(0)

    print(f"[auto-diary] 发现 {len(diaries)} 天日记，开始生成周度回顾...")

    # 生成 prompt 让 agent 执行
    prompt = generate_weekly_review_prompt(diaries, week_start, week_end)
    print(prompt)

    # 保存周度回顾
    review_file = DIARY_DIR / f"{week_end}_weekly.md"
    review_file.write_text(f"# {week_start} ~ {week_end} 周度回顾\n\n[由 main agent 填充完整内容]")
    print(f"[auto-diary] 周度回顾框架已保存: {review_file}")
