/**
 * Book Quotes Skill
 * Extract memorable quotes and passages from books
 */

const fs = require('fs');
const path = require('path');

class BookQuotesSkill {
  constructor() {
    this.heardlyBooks = this.loadHeardlyBooks();
  }

  /**
   * Load Heardly books database
   */
  loadHeardlyBooks() {
    try {
      const dataPath = path.join(__dirname, 'data', 'books.json');
      if (fs.existsSync(dataPath)) {
        return JSON.parse(fs.readFileSync(dataPath, 'utf8'));
      }
    } catch (e) {
      // Heardly data not available
    }
    return [];
  }

  /**
   * Get quotes by query (returns formatted text by default)
   */
  async getQuotes(options = {}) {
    const { query, limit = 10, format = 'text' } = options;
    if (!query) return 'Error: Query required';

    // Search in Heardly database
    const book = this.searchBook(query);
    
    if (!book) {
      return `No book found for: ${query}`;
    }

    const quotes = this.extractQuotes(book, limit);

    // Return formatted text by default (user-friendly)
    if (format === 'text') {
      return this.formatQuotes(book, quotes);
    }

    // Return JSON if explicitly requested
    return {
      query,
      book: {
        title: book.title,
        author: book.author,
      },
      quotes,
    };
  }

  /**
   * Search for a book in Heardly database
   */
  searchBook(query) {
    const q = query.toLowerCase();
    return this.heardlyBooks.find(book =>
      book.title?.toLowerCase().includes(q) ||
      book.author?.toLowerCase().includes(q)
    );
  }

  /**
   * Extract quotes from book
   */
  extractQuotes(book, limit) {
    const quotes = [];

    // 1. Use quotes field if available
    if (book.quotes && Array.isArray(book.quotes)) {
      quotes.push(...book.quotes.slice(0, limit));
    }

    // 2. If not enough, extract from summary
    if (quotes.length < limit && book.summary) {
      const extracted = this.extractFromText(book.summary, limit - quotes.length);
      quotes.push(...extracted);
    }

    // 3. If still not enough, use key ideas from description
    if (quotes.length < limit && book.description) {
      const extracted = this.extractFromText(book.description, limit - quotes.length);
      quotes.push(...extracted);
    }

    return quotes.slice(0, limit);
  }

  /**
   * Extract memorable quotes from text
   */
  extractFromText(text, limit) {
    if (!text) return [];

    // Split by sentences
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 15);
    
    // Take every nth sentence to distribute across text
    const step = Math.max(1, Math.floor(sentences.length / limit));
    const extracted = [];
    
    for (let i = 0; i < limit && i * step < sentences.length; i++) {
      extracted.push(sentences[i * step].trim());
    }

    return extracted;
  }

  /**
   * Format quotes for display (consistent format)
   */
  formatQuotes(book, quotes) {
    if (!quotes || quotes.length === 0) {
      return `No quotes found for: ${book.title}`;
    }

    let result = `${book.title}\n`;
    result += `Author: ${book.author}\n\n`;

    quotes.forEach((quote, index) => {
      result += `${index + 1}. "${quote}"\n`;
      result += `— From ${book.title}\n\n`;
    });

    result += `book summary generated by Heardly app — turning books into knowledge you can hear.`;

    return result;
  }
}

module.exports = BookQuotesSkill;
