#!/usr/bin/env python3
"""
claude_handoff.py
Writes a structured handoff package and notifies the user.
Does NOT invoke Claude Code automatically.
"""
import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


REASON_EXPLANATIONS = {
    "hard_gate": (
        "Local M2.7 JANGTQ-CRACK's Swift training data is 2+ years stale. "
        "iOS/Swift work consistently benefits from Sonnet 4.6's more recent "
        "training and deeper Apple framework knowledge."
    ),
    "build_failed": (
        "Local model generated code that failed to compile after the allowed "
        "iterations. The remaining errors suggest the model is missing context "
        "that isn't in our RAG."
    ),
    "reflection_low_confidence": (
        "After reflection passes, local model's confidence in its own output "
        "is LOW. Strong signal to get a second opinion."
    ),
    "user_request": "User explicitly requested Claude Code handoff.",
    "context_overflow": (
        "Task requires more context than M2.7's practical window. "
        "Sonnet 4.6's 1M context is the right tool."
    ),
    "soft_gate": (
        "Escalation score exceeded threshold based on task complexity, "
        "file count, and uncertainty signals."
    ),
}

REASON_HUMAN = {
    "hard_gate": "iOS domain (hard gate)",
    "build_failed": "Build errors unfixable locally",
    "reflection_low_confidence": "Low reflection confidence",
    "user_request": "User requested handoff",
    "context_overflow": "Task exceeds local context",
    "soft_gate": "Complexity threshold exceeded",
}


HANDOFF_TEMPLATE = """---
timestamp: {timestamp}
task_slug: {slug}
reason: {reason_detail}
orchestrator_version: 1.0.0
local_model: m27-jangtq-crack
---

# Handoff: {task_title}

## Original request

{task}

## Why this is being handed off

**Reason**: {reason_detail}

{reason_explanation}

## Context gathered locally

### Files read
{files_read_section}

### Codebase patterns identified
{patterns_section}

### Relevant documentation retrieved
{docs_section}

## Proposed approach (from local planning)

{plan_section}

## What local attempted and failed

{attempt_section}

## Suggested Claude Code prompt

Copy-paste this into Claude Code:

```
Read {handoff_path}

Then implement the plan above. You have write access to the project.
{execution_guidance}

When done, produce a summary of what changed and any remaining concerns.
```

Or run from terminal:

```bash
cd {project_root}
claude "Read {handoff_path_relative} and implement the plan"
```

## Estimated Claude quota cost

Based on context size: ~{input_tokens}K input + ~{output_tokens}K output = ~{total_tokens}K tokens.

---
*Generated by coding-orchestrator v1.0.0*
"""


def slugify(text: str, max_length: int = 50) -> str:
    s = re.sub(r"[^\w\s-]", "", text.lower())
    s = re.sub(r"[\s_-]+", "-", s)
    return s.strip("-")[:max_length]


def summarize_task(task: str) -> str:
    first = task.split(".")[0].strip()
    return first[:77] + "..." if len(first) > 80 else first


def format_files(ctx):
    if not ctx or "files_read" not in ctx:
        return "(none)"
    lines = []
    for f in ctx["files_read"]:
        if isinstance(f, dict):
            lines.append(f"- `{f['path']}` ({f.get('lines', '?')} lines)")
        else:
            lines.append(f"- `{f}`")
    return "\n".join(lines) if lines else "(none)"


def format_patterns(ctx):
    if not ctx or "patterns" not in ctx or not ctx["patterns"]:
        return "(none identified)"
    return "\n".join(f"- {p}" for p in ctx["patterns"])


def format_docs(ctx):
    if not ctx or "retrieved_docs" not in ctx or not ctx["retrieved_docs"]:
        return "(none retrieved)"
    return "\n".join(
        f"{i+1}. {d.get('title', d.get('url', 'source'))}"
        for i, d in enumerate(ctx["retrieved_docs"])
    )


def format_plan(plan):
    if not plan:
        return "(no plan developed — task escalated before planning)"

    out = ["Sub-problems identified:"]
    for i, sp in enumerate(plan.get("sub_problems", []), 1):
        out.append(f"{i}. **{sp['title']}**")
        out.append(f"   {sp.get('description', '')}")
        if sp.get("depends_on"):
            out.append(f"   Depends on: {', '.join(sp['depends_on'])}")
        out.append("")

    if plan.get("apis"):
        out.append("APIs involved:")
        for api in plan["apis"]:
            out.append(f"- `{api['name']}` — {api.get('version_requirement', 'any')}")
        out.append("")

    if plan.get("risks"):
        out.append("Risks:")
        for r in plan["risks"]:
            sev = r.get("severity", "MEDIUM").upper()
            out.append(f"- {sev}: {r['risk']}")
            if r.get("mitigation"):
                out.append(f"  Mitigation: {r['mitigation']}")

    return "\n".join(out)


def format_attempt(build_errors, critique_history):
    if not build_errors and not critique_history:
        return "(no prior attempts — escalated before code generation)"

    out = []
    if build_errors:
        out.append("Build errors remaining after fix attempts:")
        for err in build_errors[:10]:
            out.append(f"- `{err['file']}:{err['line']}`: {err['message']}")
        if len(build_errors) > 10:
            out.append(f"- ... and {len(build_errors) - 10} more")

    if critique_history:
        out.append("")
        out.append("Reflection pass findings:")
        for pr in critique_history:
            out.append(f"\n**Pass {pr['pass']}**:")
            out.append(pr["critique"][:500])

    return "\n".join(out)


def execution_guidance(plan):
    if not plan:
        return "Investigate the codebase, form a plan, then implement."
    order = plan.get("order", []) if plan else []
    if order:
        return (
            f"Implement the {len(order)} sub-problems in the listed order. "
            f"Run tests after each sub-problem."
        )
    return "Implement the proposed approach."


def estimate_input_tokens(ctx, plan):
    total = 1000
    if ctx:
        for f in ctx.get("files_read", []):
            lines = f.get("lines", 100) if isinstance(f, dict) else 100
            total += lines * 8
        total += len(ctx.get("retrieved_docs", [])) * 500
    if plan:
        total += 1000
    return total


def notify_user(title: str, body: str):
    """
    Notify via OpenClaw's messaging. Falls back to writing a file and
    printing to stderr if OpenClaw notification API is not reachable.
    """
    openclaw_endpoint = os.environ.get("OPENCLAW_NOTIFY_ENDPOINT")
    if openclaw_endpoint:
        try:
            import urllib.request
            data = json.dumps({"title": title, "body": body, "level": "info"}).encode()
            req = urllib.request.Request(
                openclaw_endpoint, data=data,
                headers={"Content-Type": "application/json"},
            )
            urllib.request.urlopen(req, timeout=5)
        except Exception as e:
            print(f"[notify] OpenClaw notify failed: {e}", file=sys.stderr)

    # Always write to file for status checking
    status_file = Path(".openclaw-skills/last_notification.json")
    status_file.parent.mkdir(parents=True, exist_ok=True)
    status_file.write_text(json.dumps({
        "title": title,
        "body": body,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }, indent=2))
    print(f"[notify] {title}\n{body}", file=sys.stderr)


def write_handoff(
    task: str,
    reason: str,
    project_root: str = ".",
    context_gathered: dict = None,
    proposed_approach: dict = None,
    build_errors: list = None,
    critique_history: list = None,
):
    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    slug = slugify(task)
    project = Path(project_root).resolve()

    handoff_dir = project / ".openclaw-skills" / "handoffs"
    handoff_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{timestamp.replace(':', '-').replace('+00-00', 'Z')}-{slug}.md"
    handoff_path = handoff_dir / filename

    relative_path = handoff_path.relative_to(project)

    content = HANDOFF_TEMPLATE.format(
        timestamp=timestamp,
        slug=slug,
        reason_detail=REASON_HUMAN.get(reason, reason),
        task=task,
        task_title=summarize_task(task),
        reason_explanation=REASON_EXPLANATIONS.get(reason, ""),
        files_read_section=format_files(context_gathered),
        patterns_section=format_patterns(context_gathered),
        docs_section=format_docs(context_gathered),
        plan_section=format_plan(proposed_approach),
        attempt_section=format_attempt(build_errors, critique_history),
        handoff_path=str(handoff_path.absolute()),
        handoff_path_relative=str(relative_path),
        project_root=str(project.absolute()),
        execution_guidance=execution_guidance(proposed_approach),
        input_tokens=estimate_input_tokens(context_gathered, proposed_approach) // 1000,
        output_tokens=8,
        total_tokens=estimate_input_tokens(context_gathered, proposed_approach) // 1000 + 8,
    )

    handoff_path.write_text(content)

    command = f'cd {project.absolute()} && claude "Read {relative_path} and implement the plan"'

    summary = f"Handoff ready: {summarize_task(task)} → Claude Code"

    notify_user(
        title="🤖 Claude Code handoff ready",
        body=f"{summary}\n\nPath: {relative_path}\n\nRun:\n  {command}",
    )

    # Log to SQLite for analytics
    try:
        import sqlite3
        log_db = Path.home() / ".openclaw-skills" / "handoff-log.sqlite"
        log_db.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(log_db)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS handoff_log (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                task_slug TEXT NOT NULL,
                reason TEXT NOT NULL,
                project_root TEXT,
                estimated_tokens INTEGER,
                user_ran_claude INTEGER DEFAULT 0,
                claude_succeeded INTEGER DEFAULT 0,
                notes TEXT
            )
        """)
        conn.execute(
            "INSERT INTO handoff_log (timestamp, task_slug, reason, project_root, estimated_tokens) "
            "VALUES (?, ?, ?, ?, ?)",
            (timestamp, slug, reason, str(project),
             estimate_input_tokens(context_gathered, proposed_approach) // 1000),
        )
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"[handoff] Log write failed: {e}", file=sys.stderr)

    return {
        "handoff_path": str(handoff_path.absolute()),
        "command": command,
        "summary": summary,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", required=True)
    parser.add_argument("--reason", required=True,
                        choices=list(REASON_HUMAN.keys()))
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--context-file", help="JSON file with context_gathered")
    parser.add_argument("--plan-file", help="JSON file with proposed_approach")
    parser.add_argument("--build-errors-file", help="JSON file with build errors")
    parser.add_argument("--critique-history-file", help="JSON file with critiques")
    args = parser.parse_args()

    ctx = json.loads(Path(args.context_file).read_text()) if args.context_file else None
    plan = json.loads(Path(args.plan_file).read_text()) if args.plan_file else None
    be = json.loads(Path(args.build_errors_file).read_text()) if args.build_errors_file else None
    ch = json.loads(Path(args.critique_history_file).read_text()) if args.critique_history_file else None

    result = write_handoff(
        task=args.task,
        reason=args.reason,
        project_root=args.project_root,
        context_gathered=ctx,
        proposed_approach=plan,
        build_errors=be,
        critique_history=ch,
    )

    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
