"""LunaClaw Brief — Core Data Models

Defines the canonical data structures flowing through the pipeline:
  Item → ScoredItem → ReportDraft → QualityResult

All models are immutable-friendly dataclasses with auto-computed fields.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Item:
    """Unified content item produced by every Source adapter.

    Attributes:
        title:        Headline / repo name / paper title.
        url:          Canonical link.
        source:       Source identifier ("github", "arxiv", "finnews", …).
        raw_text:     Abstract / description / summary (≤500 chars).
        published_at: ISO-8601 timestamp string (may be empty).
        meta:         Source-specific metadata (stars, points, alternatives…).
        item_id:      SHA-256 fingerprint for deduplication.
    """

    title: str
    url: str
    source: str
    raw_text: str
    published_at: Optional[str] = None
    meta: dict = field(default_factory=dict)
    item_id: str = ""

    def __post_init__(self):
        if not self.item_id:
            self.item_id = self._compute_id()

    def _compute_id(self) -> str:
        normalized = f"{self.title.lower().strip()}|{self.source}|{self.url}"
        return hashlib.sha256(normalized.encode()).hexdigest()[:16]


@dataclass
class ScoredItem:
    """Item after multi-dimensional scoring.

    Attributes:
        item:  The original Item.
        score: Composite score (higher = more relevant).
        tags:  Domain tags assigned by Scorer (e.g. ["CV", "OCR"]).
    """

    item: Item
    score: float
    tags: list = field(default_factory=list)


@dataclass
class ReportDraft:
    """Markdown draft generated by an Editor (LLM).

    Attributes:
        markdown:      Raw Markdown content.
        issue_number:  Auto-incremented issue number.
        word_count:    Character count (auto-computed).
        quality_score: Set after QualityChecker evaluation.
    """

    markdown: str
    issue_number: int
    word_count: int = 0
    quality_score: float = 0.0

    def __post_init__(self):
        self.word_count = len(self.markdown)


@dataclass
class QualityResult:
    """Result of QualityChecker validation.

    Attributes:
        passed: True if quality score ≥ threshold.
        score:  Normalized score in [0, 1].
        issues: Human-readable list of problems found.
    """

    passed: bool
    score: float
    issues: list = field(default_factory=list)


@dataclass
class PresetConfig:
    """Full configuration for a report type (preset).

    A preset defines everything the pipeline needs: which sources to fetch,
    how to score, which editor to invoke, quality thresholds, and template.

    Attributes:
        name:              Machine identifier ("ai_cv_weekly").
        display_name:      Human-readable title ("AI/CV Weekly").
        cycle:             "weekly" | "daily".
        editor_type:       Registry key for the Editor ("tech_weekly", "finance_daily", …).
        sources:           List of Source registry keys.
        time_range_days:   Lookback window for fetching.
        max_items:         Top-K items to select after scoring.
        domain_keywords:   Keyword → weight map for scoring.
        source_weights:    Source → weight map for scoring.
        low_value_keywords: Keywords that trigger zero-score filtering.
        sections:          Expected section names for quality checking.
        target_word_count: (min, max) character count target.
        tone:              "sharp" | "neutral".
        min_sections:      Minimum ## headings for quality pass.
        min_word_count:    Minimum character count for quality pass.
        dedup_window_days: Historical dedup window.
        template:          Jinja2 template name (without .html).
    """

    name: str
    display_name: str
    cycle: str
    editor_type: str

    # Data sources
    sources: list
    time_range_days: int
    max_items: int

    # Scoring weights
    domain_keywords: dict
    source_weights: dict
    low_value_keywords: list

    # Editor config
    sections: list
    target_word_count: tuple
    tone: str

    # Quality thresholds
    min_sections: int = 4
    min_word_count: int = 2000

    # Deduplication
    dedup_window_days: int = 30

    # Rendering
    template: str = "report"

    # Metadata
    description: str = ""
    show_disclaimer: bool = False
