export const editorPresets = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    filePath: '.claude/skills',
    type: 'directory' as const,
    defaultEnabled: true,
    isSkillType: true,
  },
  {
    id: 'hermes',
    name: 'Hermes',
    filePath: '.hermes/skills',
    type: 'directory' as const,
    defaultEnabled: true,
    isSkillType: true,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    filePath: '.cursorrules',
    type: 'file' as const,
    defaultEnabled: true,
    isSkillType: false,
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    filePath: '.windsurfrules',
    type: 'file' as const,
    defaultEnabled: true,
    isSkillType: false,
  },
  {
    id: 'cline',
    name: 'Cline',
    filePath: '.clinerules',
    type: 'file' as const,
    defaultEnabled: true,
    isSkillType: false,
  },
  {
    id: 'cursor-skills',
    name: 'Cursor Skills',
    filePath: '.cursor/skills',
    type: 'directory' as const,
    defaultEnabled: true,
    isSkillType: true,
  },
  {
    id: 'roo-cline',
    name: 'Roo-Cline',
    filePath: '.roorules',
    type: 'file' as const,
    defaultEnabled: true,
    isSkillType: false,
  },
  {
    id: 'antigravity',
    name: 'Antigravity',
    filePath: '.agents/skills',
    type: 'directory' as const,
    defaultEnabled: true,
    isSkillType: true,
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    filePath: '.github/skills',
    type: 'directory' as const,
    defaultEnabled: false,
    isSkillType: true,
  },
];
