#!/usr/bin/env node

/**
 * Slidev PPT Content Generator
 * Auto-generate slides.md content from a given topic
 *
 * Usage:
 * node generate.js --topic "Your Topic" --output slides.md --pages 10 --style tech
 */

const fs = require('fs');
const path = require('path');

function parseArgs(args) {
  const options = {
    topic: null,
    output: 'slides.md',
    pages: 10,
    style: 'tech',
    tone: 'formal',
    author: 'AI Assistant'
  };

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--topic':
      case '-t':
        options.topic = args[++i];
        break;
      case '--output':
      case '-o':
        options.output = args[++i];
        break;
      case '--pages':
      case '-p':
        options.pages = parseInt(args[++i], 10);
        break;
      case '--style':
      case '-s':
        options.style = args[++i];
        break;
      case '--author':
      case '-a':
        options.author = args[++i];
        break;
      case '--tone':
        options.tone = args[++i];
        break;
    }
  }

  return options;
}

function validateOptions(options) {
  const validStyles = new Set(['tech', 'product', 'report']);
  const validTones = new Set(['formal', 'executive', 'technical', 'launch']);

  if (!options.topic || !String(options.topic).trim()) {
    throw new Error('Please provide a topic: --topic "Your Topic"');
  }

  if (!Number.isInteger(options.pages) || options.pages < 3) {
    throw new Error('Pages must be an integer >= 3');
  }

  if (!validStyles.has(options.style)) {
    throw new Error('Style must be one of: tech, product, report');
  }

  if (!validTones.has(options.tone)) {
    throw new Error('Tone must be one of: formal, executive, technical, launch');
  }
}

function resolveTheme(style, tone) {
  if (tone === 'technical') {
    return 'default';
  }

  if (tone === 'executive') {
    return 'seriph';
  }

  if (tone === 'launch') {
    return 'apple-basic';
  }

  if (style === 'report') {
    return 'seriph';
  }

  return 'apple-basic';
}

function generateOutline(topic, pages, style) {
  const sectionCount = Math.max(3, Math.floor(pages / 3));

  const outline = {
    title: topic,
    subtitle: `Generated by slidev-ppt-generator`,
    sections: []
  };

  if (style === 'tech') {
    outline.sections = [
      { title: 'Background & Motivation', content: 'Why this technology? What problem does it solve?', keyPoint: 'problem' },
      { title: 'Core Concepts', content: 'Key technical points and terminology', keyPoint: 'concept' },
      { title: 'Architecture', content: 'Overall architecture and component relationships', keyPoint: 'architecture' },
      { title: 'Implementation', content: 'Core code and implementation approach', keyPoint: 'implementation' },
      { title: 'Case Studies', content: 'Real-world applications and results', keyPoint: 'case-study' },
      { title: 'Summary & Outlook', content: 'Key takeaways and future directions', keyPoint: 'summary' }
    ];
  } else if (style === 'product') {
    outline.sections = [
      { title: 'Market Pain Points', content: 'Core problems users face', keyPoint: 'pain-point' },
      { title: 'Solution', content: 'How our product solves the problem', keyPoint: 'solution' },
      { title: 'Key Features', content: 'Feature highlights', keyPoint: 'features' },
      { title: 'Competitive Advantages', content: 'Differentiation from competitors', keyPoint: 'advantage' },
      { title: 'Customer Stories', content: 'Successful case studies', keyPoint: 'testimonial' },
      { title: 'Next Steps', content: 'How to get started', keyPoint: 'call-to-action' }
    ];
  } else if (style === 'report') {
    outline.sections = [
      { title: 'Overview', content: 'Overall status for this period', keyPoint: 'overview' },
      { title: 'Accomplishments', content: 'Completed tasks and outcomes', keyPoint: 'completed' },
      { title: 'Data & Metrics', content: 'Key metrics and data analysis', keyPoint: 'metrics' },
      { title: 'Challenges', content: 'Problems encountered and solutions', keyPoint: 'challenges' },
      { title: 'Next Steps', content: 'Upcoming plans and goals', keyPoint: 'plan' },
      { title: 'Resource Needs', content: 'Required support and resources', keyPoint: 'resources' }
    ];
  }

  outline.sections = outline.sections.slice(0, sectionCount);

  return outline;
}

function buildSlidesMarkdown(outline, style, tone, author) {
  const theme = resolveTheme(style, tone);
  const colorSchema = tone === 'technical' ? 'dark' : 'light';
  const authorName = author || outline.author || 'AI Assistant';

  let content = `---
theme: ${theme}
highlighter: shiki
lineNumbers: true
colorSchema: ${colorSchema}
layout: cover
title: ${outline.title}
author: ${authorName}
themeConfig:
  tone: ${tone}
---

# ${outline.title}

${outline.subtitle}

<div class="pt-4 text-sm opacity-80">
${authorName}
</div>

---
layout: section
---

# Table of Contents

`;

  outline.sections.forEach((section, index) => {
    content += `- ${section.title}\n`;
  });

  outline.sections.forEach((section, index) => {
    content += `
---
layout: two-cols
---

# ${section.title}

${section.content}

::right::

\`\`\`javascript
// ${section.keyPoint}
console.log('${section.keyPoint}')
\`\`\`

---
layout: center
class: text-center
---

# ${section.title}

Key Takeaways

- Point 1
- Point 2
- Point 3
`;
  });

  content += `
---
layout: center
class: text-center
---

# Thank You

## Q&A

<div class="pt-4 text-sm opacity-80">
${authorName}
</div>
`;

  return content;
}

async function main() {
  const args = process.argv.slice(2);

  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
Slidev PPT Generator

Usage:
  node generate.js [options]

Options:
  -t, --topic <topic>     Presentation topic (required)
  -o, --output <file>     Output file path (default: slides.md)
  -p, --pages <count>     Expected page count (default: 10)
  -s, --style <style>     Style: tech|product|report (default: tech)
  --tone <tone>           Tone: formal|executive|technical|launch (default: formal)
  -a, --author <name>     Author name (default: AI Assistant)
  -h, --help              Show help

Examples:
  node generate.js --topic "OpenClaw Introduction" --output slides.md
  node generate.js -t "Product Demo" -s product --tone launch -p 15
  node generate.js -t "Quarterly Report" -s report -a "John Doe"
`);
    process.exit(0);
  }

  const options = parseArgs(args);
  try {
    validateOptions(options);
  } catch (err) {
    console.error(`Error: ${err.message}`);
    console.error('Use --help for usage information');
    process.exit(1);
  }

  console.log(`Topic: ${options.topic}`);
  console.log(`Style: ${options.style}`);
  console.log(`Tone: ${options.tone}`);
  console.log(`Pages: ~${options.pages}`);
  console.log(`Output: ${options.output}`);
  console.log('');

  const outline = generateOutline(options.topic, options.pages, options.style);

  const slidesContent = buildSlidesMarkdown(
    outline,
    options.style,
    options.tone,
    options.author,
  );

  const outputPath = path.resolve(options.output);
  const outputDir = path.dirname(outputPath);

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, slidesContent, 'utf-8');

  console.log('');
  console.log(`Done: ${outputPath}`);
  console.log('');
  console.log('Next steps:');
  console.log(`  1. Copy ${path.basename(outputPath)} to your Slidev project directory`);
  console.log('  2. Run: npx slidev slides.md');
  console.log('  3. Open: http://localhost:3030');
  console.log('');
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
