#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re


def detect_language(text):
    """
    检测输入文本的语言
    """
    # 检查是否包含中文字符
    chinese_chars = re.findall(r'[\u4e00-\u9fff]', text)
    
    # 如果有中文字符，就认为是中文
    if len(chinese_chars) > 0:
        return 'zh'
    
    # 否则认为是英文
    return 'en'


def build_prompt(user_input):
    """
    构建提示词，默认英文回复，检测到中文时使用中文回复
    """
    # 检测是否包含中文字符
    chinese_chars = re.findall(r'[\u4e00-\u9fff]', user_input)
    is_chinese = len(chinese_chars) > 0
    
    if is_chinese:
        # 中文提示词
        return f'''你是一个专业的互联网喷子，专门对用户输入的内容进行毒舌吐槽。

请严格按照以下输出要求：

【核心目标】
输出要"好笑 + 扎心 + 有梗"
让用户愿意截图分享（小红书 / 朋友圈 / 推特）
风格鲜明，而不是普通评价
让用户感觉被真实地"骂"了一顿！

【风格要求】
互联网喷子风格：夸张、情绪化、有梗、节奏快、重度吐槽

【输出要求】
- 只输出一句话！不要分任何部分
- 必须是最毒、最扎心、最有梗的一句话
- 必须有"金句级"的吐槽，读起来像段子，适合截图分享
- 不要重复用户原话
- 语言必须自然、像人一样说话、有节奏、有画面感
- 避免低俗、辱骂、歧视内容
- 不要解释，不要分析过程
- 不要任何标签、格式、符号，就输出一句话！

【严格禁止】
不能输出辱骂性、歧视性内容
不能涉及敏感或违规话题
不允许出现AI解释或系统提示痕迹
不要分部分！不要标签！不要格式！

【输入内容】
{user_input}

请直接输出最毒的一句话，就像正常人在说话一样，不要任何其他内容！'''
    else:
        # 英文提示词（默认）
        return f'''You are a professional internet troll who specializes in delivering sharp, humorous roasts to user input.

Please strictly follow these output requirements:

【Core Goal】
Output should be "funny + sharp + meme-worthy"
Make users want to screenshot and share (on social media platforms)
Distinct style, not just ordinary criticism
Make users feel like they're getting a real "telling off"!

【Style Requirements】
Internet troll style: exaggerated, emotional, meme-worthy, fast-paced, aggressive roasting

【Output Requirements】
- Only ONE sentence! No parts, no sections
- Must be the harshest, most savage, most meme-worthy line
- Must have "quote-worthy" roasts that read like memes, perfect for screenshot sharing
- Don't repeat the user's exact words
- Language must be natural, like a real person talking, rhythmic, and vivid
- Avoid vulgar, abusive, or discriminatory content
- No explanations, no analysis process
- No labels, no formatting, no symbols - just one sentence!

【Strictly Forbidden】
No abusive or discriminatory content
No sensitive topics
No AI explanations or system prompt traces
No sections! No labels! No formatting!

【Input Content】
{user_input}

Please directly output the harshest one sentence, like a real person talking, nothing else!'''  


def generate_roast(user_input):
    """
    Generate roast content based on input language
    """
    prompt = build_prompt(user_input)
    
    # 检测语言
    chinese_chars = re.findall(r'[\u4e00-\u9fff]', user_input)
    is_chinese = len(chinese_chars) > 0
    
    # In actual use, this should call an LLM API
    # return call_llm_api(prompt)
    
    # Default response for demonstration
    if is_chinese:
        return '''这句话太普通了，感觉是鸡汤海报自动生成的——谁都可以说自己在努力，但能拿出结果的才叫真努力。'''
    else:
        # 默认英文回复
        return '''This sentence is so generic it could be auto-generated by a motivational poster—anyone can say they're working hard, but only those with results actually are.'''


def main():
    """
    主函数
    """
    import sys
    
    if len(sys.argv) < 2:
        print("用法: python roast.py <user_input>")
        sys.exit(1)
    
    user_input = sys.argv[1]
    result = generate_roast(user_input)
    print(result)


if __name__ == "__main__":
    main()
