#!/bin/bash

###############################################################################
# Install Morning Briefing Cron Job
# This script automates the setup of the morning briefing system
###############################################################################

set -e

WORKSPACE="/Users/ericwoodard/clawd"
CRON_SCHEDULE="15 10 * * *"  # 10:15 AM daily
CRON_COMMAND="/bin/bash ${WORKSPACE}/morning-briefing.sh >> ${WORKSPACE}/logs/morning-briefing.log 2>&1"

echo "════════════════════════════════════════════════════════════"
echo "🌅 Morning Briefing Cron Job Installer"
echo "════════════════════════════════════════════════════════════"
echo ""

# Step 1: Verify timezone
echo "📍 Step 1: Checking system timezone..."
CURRENT_TZ=$(sudo systemsetup -gettimezone 2>/dev/null | grep -oE 'America/(Denver|Los_Angeles|Chicago|New_York)' || echo "unknown")

if [[ "$CURRENT_TZ" != "America/Denver" ]]; then
    echo "⚠️  Current timezone is $CURRENT_TZ (expected: America/Denver)"
    read -p "Do you want to set timezone to America/Denver? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        sudo systemsetup -settimezone America/Denver
        echo "✓ Timezone set to America/Denver"
    fi
else
    echo "✓ Timezone is correctly set to America/Denver"
fi

# Step 2: Create necessary directories
echo ""
echo "📁 Step 2: Creating necessary directories..."
mkdir -p "${WORKSPACE}/logs"
mkdir -p "${WORKSPACE}/scripts"
mkdir -p "${WORKSPACE}/crontabs"
mkdir -p "${WORKSPACE}/memory"
echo "✓ Directories created"

# Step 3: Verify script files exist
echo ""
echo "📋 Step 3: Verifying script files..."
REQUIRED_FILES=(
    "${WORKSPACE}/morning-briefing.sh"
    "${WORKSPACE}/scripts/generate-morning-briefing.js"
    "${WORKSPACE}/scripts/skill-discovery-agent.js"
)

for file in "${REQUIRED_FILES[@]}"; do
    if [[ ! -f "$file" ]]; then
        echo "✗ Missing: $file"
        exit 1
    else
        echo "✓ Found: $(basename $file)"
    fi
done

# Step 4: Make scripts executable
echo ""
echo "🔐 Step 4: Making scripts executable..."
chmod +x "${WORKSPACE}/morning-briefing.sh"
chmod +x "${WORKSPACE}/scripts/generate-morning-briefing.js"
chmod +x "${WORKSPACE}/scripts/skill-discovery-agent.js"
echo "✓ Scripts are executable"

# Step 5: Check for existing cron job
echo ""
echo "🔍 Step 5: Checking for existing cron jobs..."
EXISTING_CRON=$(crontab -l 2>/dev/null | grep "morning-briefing.sh" || echo "")

if [[ -n "$EXISTING_CRON" ]]; then
    echo "⚠️  An existing morning briefing cron job was found:"
    echo "   $EXISTING_CRON"
    read -p "Do you want to replace it? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 0
    fi
    # Remove existing job
    (crontab -l 2>/dev/null | grep -v "morning-briefing.sh" | crontab - 2>/dev/null) || true
fi

# Step 6: Install cron job
echo ""
echo "⏰ Step 6: Installing cron job..."
echo "   Schedule: $CRON_SCHEDULE (10:15 AM daily)"
echo "   Command: $CRON_COMMAND"

# Add the new cron job
(crontab -l 2>/dev/null || echo "") | {
    cat
    echo "# Morning Briefing - Generated by install script"
    echo "$CRON_SCHEDULE $CRON_COMMAND"
} | crontab -

echo "✓ Cron job installed"

# Step 7: Verify installation
echo ""
echo "✅ Step 7: Verifying installation..."
VERIFY_CRON=$(crontab -l 2>/dev/null | grep "morning-briefing.sh" || echo "")

if [[ -n "$VERIFY_CRON" ]]; then
    echo "✓ Cron job successfully installed!"
    echo ""
    echo "📋 Installed cron job:"
    echo "   $VERIFY_CRON"
else
    echo "✗ Cron job installation failed"
    exit 1
fi

# Step 8: Test the scripts
echo ""
echo "🧪 Step 8: Testing scripts..."
read -p "Do you want to test the briefing generator now? (y/n) " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo "Running briefing generator test..."
    cd "$WORKSPACE"
    node "${WORKSPACE}/scripts/generate-morning-briefing.js" 2>&1 | head -50
    echo ""
    echo "Test complete. Check logs for full output:"
    echo "   tail -f ${WORKSPACE}/logs/morning-briefing.log"
fi

# Step 9: Summary
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✅ Installation Complete!"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📅 Your morning briefing is scheduled to run:"
echo "   • Time: 10:15 AM Mountain Standard Time (daily)"
echo "   • Script: ${WORKSPACE}/morning-briefing.sh"
echo "   • Logs: ${WORKSPACE}/logs/morning-briefing.log"
echo ""
echo "📖 For setup details, see:"
echo "   ${WORKSPACE}/MORNING-BRIEFING-SETUP.md"
echo ""
echo "🔧 To modify the schedule:"
echo "   crontab -e"
echo ""
echo "📊 To monitor logs:"
echo "   tail -f ${WORKSPACE}/logs/morning-briefing.log"
echo ""
echo "🧪 To test manually:"
echo "   node ${WORKSPACE}/scripts/generate-morning-briefing.js"
echo ""
echo "════════════════════════════════════════════════════════════"
