#!/usr/bin/env node

/**
 * 技能自动创建引擎 - 将高自信模式转化为可复用技能
 * 
 * 功能：
 * 1. 扫描高自信模式（confidence > 0.7）
 * 2. 检查是否已有类似技能
 * 3. 自动创建新技能或更新现有技能
 * 4. 记录技能进化历史
 * 
 * 用法：
 *   node skill-creator.js [command]
 *   
 * 命令：
 *   scan        - 扫描可转化为技能的模式
 *   create <id> - 从指定模式创建技能
 *   auto        - 自动创建所有符合条件的技能
 */

const fs = require('fs');
const path = require('path');

// 工作空间根目录
const WORKSPACE = process.env.OPENCLAW_WORKSPACE || path.join(process.env.HOME, '.jvs/.openclaw/workspace');
const PATTERNS_PATH = path.join(WORKSPACE, 'instincts/patterns.jsonl');
const SKILLS_DIR = path.join(WORKSPACE, 'auto-skills');
const EVOLUTION_LOG = path.join(WORKSPACE, 'instincts/skill-evolution.jsonl');

/**
 * 加载所有模式
 */
function loadPatterns() {
  if (!fs.existsSync(PATTERNS_PATH)) {
    return [];
  }
  
  const content = fs.readFileSync(PATTERNS_PATH, 'utf-8');
  const lines = content.trim().split('\n').filter(line => line.trim());
  
  return lines.map(line => {
    try {
      return JSON.parse(line);
    } catch (error) {
      return null;
    }
  }).filter(p => p !== null);
}

/**
 * 扫描可转化为技能的模式
 */
function scanCreatablePatterns() {
  console.log('\n🔍 扫描可转化为技能的模式...\n');
  
  const patterns = loadPatterns();
  const creatable = [];
  
  patterns.forEach(pattern => {
    // 条件 1: 自信度高（> 0.7）
    if (pattern.confidence < 0.7) {
      return;
    }
    
    // 条件 2: 类型是成功模式
    if (pattern.type !== 'success_pattern') {
      return;
    }
    
    // 条件 3: 有明确的步骤
    if (!pattern.steps || pattern.steps.length < 3) {
      return;
    }
    
    // 条件 4: 尚未转化为技能
    if (pattern.convertedToSkill) {
      console.log(`⏭️  已转化：${pattern.id} → ${pattern.convertedToSkill}`);
      return;
    }
    
    creatable.push(pattern);
  });
  
  console.log(`📊 找到 ${creatable.length} 个可转化的模式:\n`);
  
  creatable.forEach((pattern, index) => {
    console.log(`${index + 1}. 🟢 ${pattern.id}`);
    console.log(`   标题：${pattern.title}`);
    console.log(`   自信度：${pattern.confidence.toFixed(3)}`);
    console.log(`   分类：${pattern.category}`);
    console.log('');
  });
  
  return creatable;
}

/**
 * 从模式创建技能
 */
function createSkillFromPattern(pattern) {
  console.log(`\n🛠️  开始从模式创建技能：${pattern.title}\n`);
  
  // 生成技能名称
  const skillName = generateSkillName(pattern);
  const skillDir = path.join(SKILLS_DIR, skillName);
  
  console.log(`   技能名称：${skillName}`);
  console.log(`   技能目录：${skillDir}`);
  
  // 创建目录
  if (!fs.existsSync(skillDir)) {
    fs.mkdirSync(skillDir, { recursive: true });
  }
  
  // 创建 SKILL.md
  const skillMd = generateSkillMd(pattern);
  fs.writeFileSync(path.join(skillDir, 'SKILL.md'), skillMd);
  
  // 创建 package.json（如果是 npm 技能）
  const packageJson = {
    name: `auto-${skillName}`,
    version: '1.0.0',
    description: pattern.description,
    keywords: pattern.tags || [],
    author: 'AIGC Autonomous Evolution System'
  };
  fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify(packageJson, null, 2));
  
  // 更新模式状态
  pattern.convertedToSkill = skillName;
  pattern.convertedAt = new Date().toISOString();
  savePatterns();
  
  // 记录进化日志
  logEvolution('skill_created', {
    patternId: pattern.id,
    skillName: skillName,
    confidence: pattern.confidence
  });
  
  console.log(`✅ 技能创建完成：${skillDir}`);
  console.log(`📝 文件：SKILL.md, package.json`);
  console.log('');
  
  return skillName;
}

/**
 * 生成技能名称
 */
function generateSkillName(pattern) {
  // 从标题生成 hyphen-case 名称
  const baseName = pattern.title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .substring(0, 50);
  
  // 添加分类前缀
  const prefix = pattern.category || 'general';
  return `${prefix}-${baseName}`;
}

/**
 * 生成 SKILL.md 内容
 */
function generateSkillMd(pattern) {
  const steps = pattern.steps.join('\n');
  const insights = pattern.keyInsights.join('\n');
  const tags = (pattern.tags || []).join(', ');
  
  return `---
name: ${generateSkillName(pattern)}
description: ${pattern.description}
category: ${pattern.category || 'general'}
autoGenerated: true
createdAt: ${new Date().toISOString()}
---

# ${pattern.title}

**自动生成时间**: ${new Date().toISOString()}  
**来源模式**: ${pattern.id}  
**自信度**: ${pattern.confidence.toFixed(3)}  
**分类**: ${pattern.category}  
**标签**: ${tags}

## 📋 适用场景

${pattern.description}

## 🚀 使用步骤

${steps}

## 💡 关键洞察

${insights}

## 📊 来源信息

- **原始任务**: ${pattern.sourceTask?.title || 'Unknown'}
- **任务 ID**: ${pattern.sourceTask?.id || 'Unknown'}
- **阶段**: ${pattern.sourceTask?.phase || 'Unknown'}
- **创建时间**: ${pattern.createdAt}

## 🔄 版本历史

- v1.0.0 (${new Date().toISOString().split('T')[0]}) - 初始版本（自动生成）

---

**注意**: 此技能由 AIGC 自主进化系统自动生成，基于高自信模式（confidence > 0.7）。
使用前请验证是否适合当前场景。
`;
}

/**
 * 保存模式
 */
function savePatterns() {
  const patterns = loadPatterns();
  const content = patterns.map(p => JSON.stringify(p) + '\n').join('');
  fs.writeFileSync(PATTERNS_PATH, content);
}

/**
 * 记录进化日志
 */
function logEvolution(eventType, data) {
  const logEntry = {
    timestamp: new Date().toISOString(),
    eventType,
    data
  };
  
  fs.appendFileSync(EVOLUTION_LOG, JSON.stringify(logEntry) + '\n');
}

/**
 * 自动创建所有符合条件的技能
 */
function autoCreateAll() {
  console.log('\n🚀 开始自动创建技能...\n');
  
  const creatable = scanCreatablePatterns();
  
  if (creatable.length === 0) {
    console.log('✅ 没有需要创建的技能\n');
    return;
  }
  
  let createdCount = 0;
  
  creatable.forEach(pattern => {
    try {
      createSkillFromPattern(pattern);
      createdCount++;
    } catch (error) {
      console.error(`❌ 创建失败 ${pattern.id}:`, error.message);
    }
  });
  
  console.log('═'.repeat(60));
  console.log(`✅ 成功创建 ${createdCount}/${creatable.length} 个技能`);
  console.log('═'.repeat(60));
  console.log('');
}

/**
 * 主函数
 */
async function main() {
  const args = process.argv.slice(2);
  const command = args[0] || 'scan';
  
  // 确保技能目录存在
  if (!fs.existsSync(SKILLS_DIR)) {
    fs.mkdirSync(SKILLS_DIR, { recursive: true });
    console.log(`📁 创建技能目录：${SKILLS_DIR}\n`);
  }
  
  switch (command) {
    case 'scan':
      scanCreatablePatterns();
      break;
    case 'create':
      if (!args[1]) {
        console.error('❌ 请提供模式 ID');
        console.log('用法：node skill-creator.js create <pattern-id>');
        process.exit(1);
      }
      const patterns = loadPatterns();
      const pattern = patterns.find(p => p.id === args[1]);
      if (!pattern) {
        console.error(`❌ 模式不存在：${args[1]}`);
        process.exit(1);
      }
      createSkillFromPattern(pattern);
      break;
    case 'auto':
      autoCreateAll();
      break;
    default:
      console.log('用法：node skill-creator.js [command]');
      console.log('\n命令:');
      console.log('  scan           - 扫描可转化为技能的模式');
      console.log('  create <id>    - 从指定模式创建技能');
      console.log('  auto           - 自动创建所有符合条件的技能');
  }
}

// 运行主函数
main().catch(error => {
  console.error('❌ 技能创建引擎错误:', error.message);
  console.error(error.stack);
  process.exit(1);
});
