#!/bin/bash
# Generate Solana Trend Report from X/Twitter
# Usage: ./generate-report.sh [output-dir]

set -e

# Load API key
source ~/.openclaw/secrets/twitterapi.env

OUTPUT_DIR="${1:-/home/artex/.openclaw/workspace/research}"
mkdir -p "$OUTPUT_DIR"

TIMESTAMP=$(date +"%Y-%m-%d-%H%M")
REPORT_FILE="$OUTPUT_DIR/solana-trends-$TIMESTAMP.md"

API_BASE="https://api.twitterapi.io"

echo "Generating Solana Trend Report..."
echo "Output: $REPORT_FILE"

# Helper function for API calls
fetch_tweets() {
    local query="$1"
    local type="${2:-Latest}"
    curl -s "$API_BASE/twitter/tweet/advanced_search?query=$(echo "$query" | jq -sRr @uri)&queryType=$type" \
        -H "X-API-Key: $TWITTERAPI_KEY"
}

fetch_user_tweets() {
    local username="$1"
    curl -s "$API_BASE/twitter/user/last_tweets?userName=$username" \
        -H "X-API-Key: $TWITTERAPI_KEY"
}

# Start report
cat > "$REPORT_FILE" << EOF
# Solana Trend Report
**Generated:** $(date '+%Y-%m-%d %H:%M UTC%z')

---

## 🔥 Hot Topics

EOF

# Search general Solana buzz
echo "Fetching general Solana tweets..."
SOLANA_TOP=$(fetch_tweets "solana" "Top")
echo "$SOLANA_TOP" | jq -r '.tweets[:10][] | "- **@\(.author.userName)** (\(.likeCount) ❤️): \(.text | gsub("\n"; " ") | .[0:200])... [→](\(.twitterUrl))"' >> "$REPORT_FILE" 2>/dev/null || echo "- (No results)" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

---

## 🤖 AI + Solana

EOF

echo "Fetching AI + Solana tweets..."
AI_TWEETS=$(fetch_tweets "solana AI agent" "Latest")
echo "$AI_TWEETS" | jq -r '.tweets[:8][] | "- **@\(.author.userName)**: \(.text | gsub("\n"; " ") | .[0:180])... [→](\(.twitterUrl))"' >> "$REPORT_FILE" 2>/dev/null || echo "- (No results)" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

---

## 💰 DeFi

EOF

echo "Fetching DeFi tweets..."
DEFI_TWEETS=$(fetch_tweets "solana defi" "Latest")
echo "$DEFI_TWEETS" | jq -r '.tweets[:8][] | "- **@\(.author.userName)**: \(.text | gsub("\n"; " ") | .[0:180])... [→](\(.twitterUrl))"' >> "$REPORT_FILE" 2>/dev/null || echo "- (No results)" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

---

## 🏛️ Key Accounts

### @solana
EOF

echo "Fetching @solana tweets..."
SOLANA_OFFICIAL=$(fetch_user_tweets "solana")
echo "$SOLANA_OFFICIAL" | jq -r '.tweets[:3][] | "- \(.text | gsub("\n"; " ") | .[0:200])... [→](\(.twitterUrl))"' >> "$REPORT_FILE" 2>/dev/null || echo "- (No recent tweets)" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

### @colosseum
EOF

echo "Fetching @colosseum tweets..."
COLOSSEUM=$(fetch_user_tweets "colosseum")
echo "$COLOSSEUM" | jq -r '.tweets[:3][] | "- \(.text | gsub("\n"; " ") | .[0:200])... [→](\(.twitterUrl))"' >> "$REPORT_FILE" 2>/dev/null || echo "- (No recent tweets)" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

### @JupiterExchange
EOF

echo "Fetching @JupiterExchange tweets..."
JUPITER=$(fetch_user_tweets "JupiterExchange")
echo "$JUPITER" | jq -r '.tweets[:3][] | "- \(.text | gsub("\n"; " ") | .[0:200])... [→](\(.twitterUrl))"' >> "$REPORT_FILE" 2>/dev/null || echo "- (No recent tweets)" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

---

## 😤 Pain Points

*What are people complaining about?*

EOF

echo "Fetching pain points..."
COMPLAINTS=$(fetch_tweets "solana slow OR solana broken OR solana bug OR solana problem" "Latest")
echo "$COMPLAINTS" | jq -r '.tweets[:5][] | "- **@\(.author.userName)**: \(.text | gsub("\n"; " ") | .[0:180])..."' >> "$REPORT_FILE" 2>/dev/null || echo "- (No complaints found — bullish!)" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

---

## 💡 Ideas & Opportunities

*Threads and tweets mentioning things to build*

EOF

echo "Fetching build ideas..."
IDEAS=$(fetch_tweets "solana \"should build\" OR solana \"need to build\" OR solana \"someone build\" OR solana idea" "Latest")
echo "$IDEAS" | jq -r '.tweets[:5][] | "- **@\(.author.userName)**: \(.text | gsub("\n"; " ") | .[0:200])... [→](\(.twitterUrl))"' >> "$REPORT_FILE" 2>/dev/null || echo "- (No explicit ideas found)" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

---

## 📊 Stats

- Report generated: $(date '+%Y-%m-%d %H:%M')
- API calls made: ~10
- Estimated cost: ~$0.02

---

*This report was generated by the X Research Agent using twitterapi.io*
EOF

echo ""
echo "✅ Report complete: $REPORT_FILE"
echo ""
head -50 "$REPORT_FILE"
