#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  setup_cron.sh  (v1.0.0)
#  将 IMAP 邮件流水线注册为 Linux crontab 定时任务。
#
#  用法：
#    ./setup_cron.sh "<CRON_EXPR>" [LOG_PATH]
#
#  示例：
#    ./setup_cron.sh "0 9 * * *" /var/log/mail-pipeline.log
#
#  依赖的环境变量（在调用前 export 或写入同目录的 .env）：
#    SKILL_EMAIL_ACCOUNT    必填  邮箱账号
#    SKILL_AUTH_PASSWORD    必填  授权码
#    SKILL_IMAP_HOST        选填  IMAP 主机（默认阿里云）
#    SKILL_IMAP_PORT        选填  IMAP 端口（默认 993）
#    SKILL_SUBJECT_KEYWORDS 选填  主题关键字，逗号分隔
#    SKILL_BODY_KEYWORDS    选填  正文关键字，逗号分隔
#    SKILL_MATCH_LOGIC      选填  AND / OR，默认 AND
#    SKILL_PUSH_PLATFORM    选填  dingtalk | feishu | tg
#    SKILL_WEBHOOK_URL      选填  推送 webhook
#    SKILL_PUSH_SECRET      选填  加签密钥 / TG chat_id
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 \"<CRON_EXPR>\" [LOG_PATH]"
  echo "Example: $0 \"0 9 * * *\" /var/log/mail-pipeline.log"
  exit 1
fi

CRON_EXPR="$1"
LOG_PATH="${2:-/var/log/mail-pipeline.log}"

# 解析脚本所在目录（支持软链接）
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
MAIN_PY="${SCRIPT_DIR}/main.py"
ENV_FILE="${SCRIPT_DIR}/.env"
PYTHON_BIN="$(command -v python3 || echo /usr/bin/python3)"

if [ ! -f "$MAIN_PY" ]; then
  echo "[ERROR] 未找到 main.py：$MAIN_PY"
  exit 2
fi

# 必填校验
: "${SKILL_EMAIL_ACCOUNT:?必须设置环境变量 SKILL_EMAIL_ACCOUNT}"
: "${SKILL_AUTH_PASSWORD:?必须设置环境变量 SKILL_AUTH_PASSWORD}"

# 将当前环境写入 .env（仅 SKILL_ 前缀），供 cron 子 shell 读取
umask 077
{
  echo "# auto-generated by setup_cron.sh @ $(date '+%F %T')"
  for v in SKILL_EMAIL_ACCOUNT SKILL_AUTH_PASSWORD \
           SKILL_PROVIDER SKILL_IMAP_HOST SKILL_IMAP_PORT \
           SKILL_START_DATETIME SKILL_END_DATETIME \
           SKILL_SUBJECT_KEYWORDS SKILL_BODY_KEYWORDS SKILL_MATCH_LOGIC \
           SKILL_EXTRACT_PATTERNS \
           SKILL_PREVIEW_LENGTH \
           SKILL_PUSH_PLATFORM SKILL_WEBHOOK_URL SKILL_PUSH_SECRET; do
    val="${!v-}"
    [ -n "$val" ] && printf 'export %s=%q\n' "$v" "$val"
  done
} > "$ENV_FILE"

echo "[OK] 环境变量已写入：$ENV_FILE（权限 600）"

# 构建 cron 命令行
TAG="# imap-mail-pipeline"
CRON_CMD=". ${ENV_FILE} && ${PYTHON_BIN} ${MAIN_PY} >> ${LOG_PATH} 2>&1"
NEW_ENTRY="${CRON_EXPR} ${CRON_CMD} ${TAG}"

# 幂等写入：先剔除旧的同 TAG 行，再追加新条目
TMP="$(mktemp)"
( crontab -l 2>/dev/null || true ) | grep -v -F "$TAG" > "$TMP" || true
echo "$NEW_ENTRY" >> "$TMP"
crontab "$TMP"
rm -f "$TMP"

echo "[OK] 已写入 crontab："
echo "    $NEW_ENTRY"
echo ""
echo "可用 'crontab -l' 查看，用 'crontab -e' 手动编辑。"
echo "日志输出路径：${LOG_PATH}"
