"""Weekly newsletter generation using Jinja2 templates."""

from datetime import datetime, timezone
from typing import Dict, List

from jinja2 import Template

from adapters.base import CodeAdapter, TicketAdapter
from core.branch_mapper import get_contributions
from core.jira_health import get_stale_epics, get_unassigned_tickets
from core.team_pulse import get_cycle_times, get_mr_trends

NEWSLETTER_TEMPLATE = """\
# Weekly Engineering Newsletter
_Week of {{ week_of }}_

## Team Activity
- **{{ total_merged }}** MRs merged this week
- **{{ total_opened }}** MRs opened
- **{{ active_engineers }}** engineers contributed

## Top Contributors
{% for author, count in top_contributors %}
- {{ author }}: {{ count }} MRs merged
{% endfor %}

## Cycle Time
- Average: **{{ avg_cycle_time }}h** ({{ cycle_direction }} from last week's {{ last_week_cycle }}h)

## MR Trends
{% for author, trend in trends.items() %}
- {{ author }}: {{ trend.current }} this week ({{ "+" if trend.change_pct >= 0 }}{{ trend.change_pct }}%)
{% endfor %}

{% if stale_epics %}
## Stale Epics ({{ stale_epics | length }})
{% for epic in stale_epics %}
- [{{ epic.key }}]({{ epic.url }}) {{ epic.title }} — {{ epic.days_since_update }}d stale
{% endfor %}
{% endif %}

{% if unassigned %}
## Unassigned Tickets ({{ unassigned | length }})
{% for ticket in unassigned[:10] %}
- [{{ ticket.key }}]({{ ticket.url }}) {{ ticket.title }}
{% endfor %}
{% if unassigned | length > 10 %}
_... and {{ unassigned | length - 10 }} more_
{% endif %}
{% endif %}

{% if contributions %}
## Branch → Ticket Map
{% for engineer, contribs in contributions.items() %}
### {{ engineer }}
{% for c in contribs %}
- {{ c.ticket_id }}: {{ c.ticket_title }} ({{ c.branch_name }}, {{ c.days_active }}d active)
{% endfor %}
{% endfor %}
{% endif %}

---
_Generated by em-intel on {{ generated_at }}_
"""


def generate_newsletter(
    code_adapter: CodeAdapter,
    ticket_adapter: TicketAdapter,
    project_keys: List[str],
    days: int = 7,
) -> str:
    """Generate a weekly newsletter from all data sources.

    Returns:
        Rendered markdown string.
    """
    mrs = code_adapter.get_merge_requests(days=days)
    tickets = ticket_adapter.get_tickets(project_keys)
    epics = ticket_adapter.get_epics(project_keys)

    now = datetime.now(timezone.utc)
    merged = [m for m in mrs if m.state == "merged"]
    opened = [m for m in mrs if m.state in ("opened", "open")]

    # Top contributors by merged MR count
    author_counts: Dict[str, int] = {}
    for mr in merged:
        author_counts[mr.author] = author_counts.get(mr.author, 0) + 1
    top = sorted(author_counts.items(), key=lambda x: x[1], reverse=True)[:10]

    # Cycle times
    cycle_times = get_cycle_times(mrs)
    all_times = list(cycle_times.values())
    avg_ct = round(sum(all_times) / len(all_times), 1) if all_times else 0.0

    # Last week for comparison
    last_week_mrs = code_adapter.get_merge_requests(days=days + 7)
    last_week_ct = get_cycle_times(last_week_mrs)
    lw_times = list(last_week_ct.values())
    lw_avg = round(sum(lw_times) / len(lw_times), 1) if lw_times else 0.0
    direction = "down" if avg_ct < lw_avg else ("up" if avg_ct > lw_avg else "flat")

    # Trends
    trends = get_mr_trends(mrs)

    # Health
    stale_days = 14
    stale = get_stale_epics(epics, days=stale_days)
    unassigned = get_unassigned_tickets(tickets)

    # Contributions
    contribs = get_contributions(code_adapter, ticket_adapter, project_keys, days=days)

    template = Template(NEWSLETTER_TEMPLATE)
    return template.render(
        week_of=now.strftime("%Y-%m-%d"),
        total_merged=len(merged),
        total_opened=len(opened),
        active_engineers=len(set(m.author for m in mrs)),
        top_contributors=top,
        avg_cycle_time=avg_ct,
        last_week_cycle=lw_avg,
        cycle_direction=direction,
        trends=trends,
        stale_epics=stale,
        unassigned=unassigned,
        contributions=contribs,
        generated_at=now.strftime("%Y-%m-%d %H:%M UTC"),
    )
