#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DATA_DIR="${SCRIPT_DIR}/../data"
MEMORY_FILE="${DATA_DIR}/emotional_memory.json"
STATE_FILE="${DATA_DIR}/emotional_state.json"

mkdir -p "$DATA_DIR"

ACTION="${1:-weekly}"
shift || true

generate_report() {
  local PERIOD="$1"
  python3 - "$PERIOD" "$MEMORY_FILE" "$STATE_FILE" <<'PYEOF'
import json, sys
from datetime import datetime, timedelta
from collections import Counter

period = sys.argv[1]
memory_file = sys.argv[2]
state_file = sys.argv[3]

# Load data
try:
    with open(memory_file, 'r') as f:
        memory = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    memory = {"patterns": [], "growth": [], "preferences": []}

try:
    with open(state_file, 'r') as f:
        states = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    states = {"sessions": []}

patterns = memory.get("patterns", [])
sessions = states.get("sessions", [])

now = datetime.utcnow()
if period == "weekly":
    since = now - timedelta(days=7)
    label = f"{(now - timedelta(days=7)).strftime('%b %d')} - {now.strftime('%b %d, %Y')}"
elif period == "monthly":
    since = now - timedelta(days=30)
    label = f"{(now - timedelta(days=30)).strftime('%b %d')} - {now.strftime('%b %d, %Y')}"
else:
    since = now - timedelta(days=7)
    label = "Custom period"

since_str = since.strftime('%Y-%m-%d')

# Filter recent patterns
recent = [p for p in patterns if p.get("timestamp", "") >= since_str]

# Count anchor tags
anchors = ["grounding", "softness", "connection", "release", "courage"]
anchor_counts = Counter()
for p in recent:
    for tag in p.get("tags", []):
        if tag.lower() in anchors:
            anchor_counts[tag.lower()] += 1

total_anchor = sum(anchor_counts.values()) or 1

# Count importance
imp_counts = Counter(p.get("importance", "medium") for p in recent)

# Build report
print(f"# 🫀 Emotional Wellness Report")
print(f"**{label}**\n")

print("## Anchor Distribution")
for a in anchors:
    count = anchor_counts.get(a, 0)
    pct = int(count / total_anchor * 100) if total_anchor > 0 else 0
    bar = "█" * (pct // 5) + "░" * (20 - pct // 5)
    dominant = " ← Dominant" if count == max(anchor_counts.values(), default=0) and count > 0 else ""
    print(f"{a.capitalize():12s} {bar} {pct:3d}%{dominant}")

print(f"\n## Summary")
print(f"- Total patterns recorded: {len(recent)}")
print(f"- High importance: {imp_counts.get('high', 0)}")
print(f"- Medium importance: {imp_counts.get('medium', 0)}")
print(f"- Low importance: {imp_counts.get('low', 0)}")

if recent:
    print(f"\n## Recent Observations")
    for p in recent[-5:]:
        print(f"- [{p.get('timestamp','')}] {p.get('observation','')[:100]}")

# Growth indicators
growth = memory.get("growth", [])
recent_growth = [g for g in growth if g.get("timestamp", "") >= since_str]
if recent_growth:
    print(f"\n## Growth Indicators")
    for g in recent_growth[-5:]:
        print(f"- {g.get('observation', '')}")

print(f"\n---")
print(f"_Generated by emotional-persona • All data local_")
PYEOF
}

case "$ACTION" in
  weekly)
    generate_report "weekly"
    ;;
  monthly)
    generate_report "monthly"
    ;;
  anchors)
    SINCE=""
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --since) SINCE="$2"; shift 2 ;;
        *)       shift ;;
      esac
    done
    python3 -c "
import json
from collections import Counter
with open('$MEMORY_FILE', 'r') as f:
    data = json.load(f)
anchors = ['grounding','softness','connection','release','courage']
counts = Counter()
for p in data.get('patterns',[]):
    ts = p.get('timestamp','')
    if '$SINCE' and ts < '$SINCE':
        continue
    for t in p.get('tags',[]):
        if t.lower() in anchors:
            counts[t.lower()] += 1
total = sum(counts.values()) or 1
print('Anchor Distribution (all time):')
for a in anchors:
    c = counts.get(a,0)
    pct = int(c/total*100)
    bar = '█' * (pct//5) + '░' * (20-pct//5)
    print(f'  {a.capitalize():12s} {bar} {pct:3d}% ({c})')
"
    ;;
  growth)
    python3 -c "
import json
with open('$MEMORY_FILE', 'r') as f:
    data = json.load(f)
growth = data.get('growth',[])
if not growth:
    print('No growth indicators recorded yet.')
else:
    print('Growth Timeline:')
    for g in growth[-15:]:
        print(f\"  [{g.get('timestamp','')}] {g.get('observation','')}\")
"
    ;;
  help|*)
    cat <<EOF
emotional-persona: Emotion Report Generator

Usage:
  emotion_report.sh weekly              Weekly wellness report
  emotion_report.sh monthly             Monthly wellness report
  emotion_report.sh anchors [--since]   Anchor distribution over time
  emotion_report.sh growth              Growth tracking timeline
EOF
    ;;
esac
