"""
Builds the HTML digest page.
"""

from datetime import datetime


# ── HTML helpers ──────────────────────────────────────────────────────────────

def _reel_html(reel: dict) -> str:
    caption = reel.get("caption", "").strip()
    caption_line = f"<p style='color:#555;font-size:13px;margin:4px 0'><em>{caption[:200]}…</em></p>" if caption else ""
    transcript_summary = reel.get("transcript_summary", "")
    summary_block = f"""
      <div style='margin-top:10px;padding:10px;background:#f0f7ff;border-radius:6px;border-left:3px solid #0095f6'>
        <div style='font-size:11px;color:#888;margin-bottom:4px;text-transform:uppercase;letter-spacing:0.5px'>Audio Summary</div>
        <div style='font-size:14px;line-height:1.6;color:#333'>{transcript_summary}</div>
      </div>
    """ if transcript_summary else ""
    return f"""
    <div style='border:1px solid #e0e0e0;border-radius:8px;padding:14px;margin:10px 0;background:#fafafa'>
      <div style='font-size:12px;color:#888;margin-bottom:4px'>
        Reel · {reel.get('date','')} · {reel.get('likes',0):,} likes
      </div>
      {summary_block}
      {caption_line}
      <a href='{reel.get("url","")}' style='font-size:12px;color:#0095f6'>View on Instagram</a>
    </div>
    """


def _account_section(username: str, data: dict) -> str:
    reels = data.get("reels", [])

    if not reels:
        return f"""
        <div style='margin:20px 0'>
          <h2 style='margin:0 0 4px'>@{username}</h2>
          <p style='color:#aaa;font-size:13px'>No new reels in the lookback window.</p>
        </div>
        <hr style='border:none;border-top:1px solid #eee'>
        """

    reels_html = "".join(_reel_html(r) for r in reels)

    return f"""
    <div style='margin:20px 0'>
      <h2 style='margin:0 0 8px'>
        <a href='https://www.instagram.com/{username}/' style='color:#0095f6;text-decoration:none'>@{username}</a>
      </h2>
      <h3 style='margin:12px 0 6px;color:#333'>Reels ({len(reels)})</h3>
      {reels_html}
    </div>
    <hr style='border:none;border-top:1px solid #eee'>
    """


def build_html(results: dict) -> str:
    date_str    = datetime.now().strftime("%A, %B %#d, %Y")
    accounts    = "".join(_account_section(u, d) for u, d in results.items())
    total_reels = sum(len(d["reels"]) for d in results.values())

    return f"""
    <!DOCTYPE html>
    <html>
    <body style='font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
                 max-width:680px;margin:0 auto;padding:20px;color:#222'>
      <div style='background:linear-gradient(135deg,#f09433,#e6683c,#dc2743,#cc2366,#bc1888);
                  border-radius:12px;padding:20px;margin-bottom:24px;text-align:center'>
        <h1 style='color:white;margin:0;font-size:24px'>Instagram Daily Digest</h1>
        <p style='color:rgba(255,255,255,0.9);margin:6px 0 0;font-size:14px'>{date_str}</p>
        <p style='color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:13px'>
          {len(results)} accounts · {total_reels} reels
        </p>
      </div>

      {accounts}

      <p style='font-size:11px;color:#bbb;text-align:center;margin-top:30px'>
        Generated by Instagram Daily Digest · Powered by Claude
      </p>
    </body>
    </html>
    """
