#!/usr/bin/env python3
"""Generate traceable dreaming summary."""
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional

import sys
sys.path.insert(0, str(Path(__file__).parent.parent / "lib"))

from config_loader import load_config
from log_utils import get_logger

logger = get_logger("dreaming-optimizer.summary")


def generate_markdown_summary(data: dict) -> str:
    """Generate human-readable markdown summary.
    
    Args:
        data: Summary data dict
        
    Returns:
        str: Markdown formatted summary
    """
    lines = [
        "# 🌙 Dreaming Summary",
        "",
        f"**Generated:** {data.get('ts', 'unknown')}",
        f"**Version:** {data.get('dreaming_version', '1.0.0')}",
        "",
        "## Consolidation Results",
        "",
        f"- **Scored:** {data.get('scored', 0)} entries",
        f"- **Passed:** {data.get('passed', 0)} entries (committed)",
        f"- **Archived:** {data.get('archived', 0)} entries",
        f"- **Merged:** {data.get('merged', 0)} entries (deduplication)",
        f"- **Discarded:** {data.get('discarded', 0)} entries",
        "",
        "## Tag Distribution",
        "",
    ]
    
    tags = data.get("tags", {})
    for tag_name, count in sorted(tags.items(), key=lambda x: -x[1]):
        lines.append(f"- **{tag_name}:** {count}")
    
    lines.append("")
    
    if data.get("recommendations"):
        lines.append("## Recommendations")
        lines.append("")
        for rec in data["recommendations"]:
            lines.append(f"- {rec}")
        lines.append("")
    
    lines.append("---")
    lines.append(f"*Generated by dreaming-optimizer v{data.get('dreaming_version', '1.0.0')}*")
    
    return "\n".join(lines)


def generate_summary(
    scored: int = 0,
    passed: int = 0,
    archived: int = 0,
    merged: int = 0,
    committed: int = 0,
    discarded: int = 0,
    tag_counts: dict[str, int] = None,
    recommendations: list[str] = None,
    output_dir: Path = None,
    format: str = "json",
) -> dict:
    """Generate traceable dreaming summary.
    
    Args:
        scored: Total entries scored
        passed: Entries passing threshold
        archived: Entries archived (35 <= score < 70)
        merged: Entries merged via dedup
        committed: Entries written to B-layer
        discarded: Entries discarded (score < 35)
        tag_counts: {"fact": n, "opinion": n, ...}
        recommendations: Optional list of recommendation strings
        output_dir: Directory for summary files
        format: "json" (default) or "markdown"
        
    Returns:
        dict: Summary data (also written to file)
    """
    if tag_counts is None:
        tag_counts = {"fact": 0, "opinion": 0, "preference": 0, "learning": 0, "context": 0}
    if recommendations is None:
        recommendations = []
    
    if output_dir is None:
        output_dir = Path.home() / ".openclaw" / "workspace" / "memory" / "dreaming-summaries"
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    summary = {
        "ts": datetime.now(tz=timezone.utc).isoformat(),
        "scored": scored,
        "passed": passed,
        "archived": archived,
        "merged": merged,
        "committed": committed,
        "discarded": discarded,
        "tags": tag_counts,
        "recommendations": recommendations,
        "dreaming_version": "1.0.0",
    }
    
    date_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    
    # Write JSON summary
    json_file = output_dir / f"dreaming-summary-{date_str}.json"
    json_file.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.info(f"Written JSON summary to {json_file}")
    
    # Write Markdown summary
    md_file = output_dir / f"dreaming-summary-{date_str}.md"
    md_file.write_text(generate_markdown_summary(summary), encoding="utf-8")
    logger.info(f"Written Markdown summary to {md_file}")
    
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate dreaming summary")
    parser.add_argument("--scored", type=int, default=0)
    parser.add_argument("--passed", type=int, default=0)
    parser.add_argument("--archived", type=int, default=0)
    parser.add_argument("--merged", type=int, default=0)
    parser.add_argument("--committed", type=int, default=0)
    parser.add_argument("--discarded", type=int, default=0)
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--format", choices=["json", "markdown"], default="json")
    args = parser.parse_args()
    
    result = generate_summary(
        scored=args.scored,
        passed=args.passed,
        archived=args.archived,
        merged=args.merged,
        committed=args.committed,
        discarded=args.discarded,
        output_dir=args.output_dir,
        format=args.format,
    )
    
    print(json.dumps(result, indent=2, ensure_ascii=False))
