#!/usr/bin/env bash
# Generate SEO audit reports
set -euo pipefail

SITE=""
TYPE="full"

while [[ $# -gt 0 ]]; do
  case $1 in
    --site) SITE="$2"; shift 2 ;;
    --type) TYPE="$2"; shift 2 ;;
    *) shift ;;
  esac
done

[ -z "$SITE" ] && { echo "Usage: generate-report.sh --site <domain> --type <full|summary|geo|monthly>"; exit 1; }

BASE_DIR="${SEO_AUDIT_DIR:-$HOME/.openclaw/workspace/seo-audit}"
SITE_DIR="$BASE_DIR/sites/$SITE/audits"
REPORTS_DIR="$BASE_DIR/reports"
mkdir -p "$REPORTS_DIR"

[ ! -d "$SITE_DIR" ] && { echo "❌ No audits found for $SITE. Run an audit first."; exit 1; }

TIMESTAMP=$(date +%Y%m%d)
REPORT_FILE="$REPORTS_DIR/$SITE-$TYPE-$TIMESTAMP.md"

python3 << PYEOF
import json, glob, os
from datetime import datetime

site = "$SITE"
report_type = "$TYPE"
site_dir = "$SITE_DIR"
report_file = "$REPORT_FILE"

# Gather latest audits
audits = {}
for audit_type in ["onpage", "technical", "geo"]:
    files = sorted(glob.glob(f"{site_dir}/{audit_type}-*.json"), reverse=True)
    if files:
        with open(files[0]) as f:
            audits[audit_type] = json.load(f)

if not audits:
    print(f"❌ No audit data found for {site}")
    exit(1)

# Build report
report = f"# SEO Audit Report — {site}\n"
report += f"**Generated:** {datetime.now().strftime('%B %d, %Y')}\n"
report += f"**Report Type:** {report_type.title()}\n\n"

# Overall scores
report += "## Overall Scores\n\n"
report += "| Audit Type | Score | Grade |\n"
report += "|-----------|-------|-------|\n"

total_score = 0
count = 0
for atype, data in audits.items():
    score = data.get("overall_score", data.get("geo_score", 0))
    grade = data.get("grade", "N/A")
    report += f"| {atype.title()} | {score:.0f}/100 | {grade} |\n"
    total_score += score
    count += 1

if count > 0:
    combined = total_score / count
    combined_grade = "A" if combined >= 90 else "B" if combined >= 80 else "C" if combined >= 70 else "D" if combined >= 60 else "F"
    report += f"| **Combined** | **{combined:.0f}/100** | **{combined_grade}** |\n"

report += "\n"

# Issues summary
all_issues = []
for data in audits.values():
    all_issues.extend(data.get("issues", []))

criticals = [i for i in all_issues if i.get("severity") == "critical"]
warnings = [i for i in all_issues if i.get("severity") == "warning"]

if criticals:
    report += "## 🔴 Critical Issues\n\n"
    for i in criticals:
        report += f"- **{i['check']}:** {i['message']}\n"
    report += "\n"

if warnings:
    report += "## 🟡 Warnings\n\n"
    for i in warnings:
        report += f"- **{i['check']}:** {i['message']}\n"
    report += "\n"

# GEO recommendations
if "geo" in audits:
    recs = audits["geo"].get("recommendations", [])
    if recs:
        report += "## 💡 GEO Optimization Recommendations\n\n"
        for r in recs:
            report += f"1. {r}\n"
        report += "\n"

# Detailed scores
report += "## Detailed Scores\n\n"
for atype, data in audits.items():
    report += f"### {atype.title()}\n\n"
    scores = data.get("scores", {})
    for check, score in sorted(scores.items(), key=lambda x: x[1]):
        emoji = "🟢" if score >= 80 else "🟡" if score >= 60 else "🔴"
        report += f"- {emoji} {check}: {score:.0f}/100\n"
    report += "\n"

report += "---\n*Generated by Reighlan SEO Audit Suite*\n"

with open(report_file, "w") as f:
    f.write(report)

print(f"📄 Report generated: {report_file}")
print(f"   Type: {report_type}")
print(f"   Combined score: {combined:.0f}/100 ({combined_grade})" if count > 0 else "")
PYEOF
