// cn-lexicon.js
// 中国大陆客户调查分析的预缓存汉字词典。
// Purpose: avoid MiniMax / small-context models token-level typos in `\uXXXX`
// escape sequences when pptxgenjs slide code is generated.
// Usage (from slide-NN.js):
//   const L = require('../../skills/cn-client-investigation/references/cn-lexicon.js');
//   slide.addText(L.company.cambricon.cn_full, { fontSize: 26, fontFace: "Microsoft YaHei" });
//
// Rule: when you need a Chinese term in slide code, PREFER `require` this file
// and reference its constants. Do NOT inline-type long Chinese strings or
// encode as `\uXXXX` — both routes are typo-prone on MiniMax-M2.7.
//
// Add new entries by editing this file (UTF-8, no BOM) and committing. Do not
// emit entries via agent tool-call JSON; write them via `edit` or `write` on
// this file directly.

'use strict';

const LEXICON = {
  // ---- 业务常用 section headers ----
  sections: {
    executive_summary: '执行摘要',
    company_overview: '公司概览',
    company_positioning: '公司定位',
    management: '管理层',
    shareholder_structure: '股权结构',
    product_matrix: '产品矩阵',
    tech_architecture: '技术架构',
    timeline: '发展时间线',
    market: '市场分析',
    tam_sam_som: '市场规模与国产替代',
    competition: '竞争格局',
    financial: '财务分析',
    financials_history: '财务历史',
    valuation: '估值分析',
    comps: '可比估值',
    risk: '风险分析',
    risk_matrix: '风险矩阵',
    catalysts: '催化剂清单',
    investment_thesis: '投资逻辑',
    investment_highlights: '投资亮点',
    investment_conclusion: '投资结论',
    appendix: '附录',
    disclaimer: '免责声明',
    data_sources: '数据来源',
  },

  // ---- 财务 line items（尤其易错字）----
  finance: {
    revenue: '营业收入',
    gross_profit: '毛利',
    gross_margin: '毛利率',
    operating_profit: '营业利润',
    operating_margin: '营业利润率',
    net_income_attributable: '归属于母公司股东的净利润',
    net_income_nonrecurring_adj: '扣除非经常性损益的净利润',
    net_margin: '净利率',
    ebitda: 'EBITDA',
    rd_expense: '研发费用',
    rd_intensity: '研发费用率',
    selling_expense: '销售费用',
    admin_expense: '管理费用',
    operating_cashflow: '经营活动现金流净额',
    free_cashflow: '自由现金流',
    capex: '资本开支',
    cash_and_equivalents: '货币资金',
    total_assets: '总资产',
    total_liabilities: '总负债',
    equity: '所有者权益',
    debt: '有息负债',
    net_debt: '净有息负债',
    market_cap: '总市值',
    ev: '企业价值',
    ps_ratio: '市销率',
    pe_ratio: '市盈率',
    pb_ratio: '市净率',
    ev_revenue: 'EV/Revenue',
    ev_ebitda: 'EV/EBITDA',
    loss: '亏损',
    deficit: '赤字',
    impairment: '减值',
    amortization: '摊销',
    depreciation: '折旧',
  },

  // ---- 投资建议 & 评级 ----
  rating: {
    overweight: '增持',
    neutral: '中性',
    underweight: '减持',
    buy: '买入',
    sell: '卖出',
    hold: '持有',
    aggressive_coverage: '积极关注',
    initiate_coverage: '首次覆盖',
    maintain_coverage: '维持评级',
    target_price: '目标价',
    target_price_range: '目标价区间',
  },

  // ---- 中国市场 / 监管常用术语 ----
  cn_market: {
    a_share: 'A股',
    star_market: '科创板',
    chinext: '创业板',
    bj_exchange: '北交所',
    main_board: '主板',
    hk_main: '港股主板',
    hk_h_share: 'H股',
    zhongcai_gai: '中概股',
    ipo_cninfo: '招股书',
    annual_report: '年报',
    quarterly_report: '季报',
    prospectus: '招股说明书',
    sse: '上海证券交易所',
    szse: '深圳证券交易所',
    hkex: '香港交易所',
    csrc: '中国证监会',
    entity_list: '美国实体清单',
    export_control: '美国出口管制',
    controlling_shareholder: '实际控制人',
    strategic_investor: '战略投资人',
    state_capital: '国资背景',
    esop: '员工持股计划',
    lock_up_period: '解禁期',
    guochan_tihuan: '国产替代',
    shibazhanlue: '"十四五"规划',
    xinjijianshe: '新基建',
    zhuanjing_tixin: '专精特新',
    smart_compute_center: '智算中心',
    ai_accelerator: 'AI加速卡',
    cuda_compat: 'CUDA兼容',
    self_research: '自研',
  },

  // ---- 目标公司 / 典型 peer（中英 ticker 对齐）----
  // 添加新公司时填齐 cn_full / cn_short / en_full / en_short / ticker / exchange
  company: {
    cambricon: {
      cn_full: '中科寒武纪科技股份有限公司',
      cn_short: '寒武纪',
      en_full: 'Cambricon Technologies Corporation Limited',
      en_short: 'Cambricon',
      ticker: '688256.SH',
      exchange: '上海证券交易所科创板',
    },
    hygon: {
      cn_full: '海光信息技术股份有限公司',
      cn_short: '海光信息',
      en_full: 'Hygon Information Technology',
      en_short: 'Hygon',
      ticker: '688041.SH',
      exchange: '上海证券交易所科创板',
    },
    moore_threads: {
      cn_full: '摩尔线程智能科技（北京）有限责任公司',
      cn_short: '摩尔线程',
      en_full: 'Moore Threads Intelligent Technology',
      en_short: 'Moore Threads',
      ticker: 'N/A',
      exchange: '港交所递表中（2024-11）',
    },
    huawei_hisilicon: {
      cn_full: '华为海思半导体有限公司',
      cn_short: '海思',
      en_full: 'HiSilicon (Huawei)',
      en_short: 'HiSilicon',
      ticker: 'N/A（华为未上市）',
      exchange: '未上市',
    },
    biren: {
      cn_full: '壁仞科技（上海）有限公司',
      cn_short: '壁仞科技',
      en_full: 'Biren Technology',
      en_short: 'Biren',
      ticker: 'N/A',
      exchange: '未上市',
    },
    enflame: {
      cn_full: '上海燧原科技有限公司',
      cn_short: '燧原科技',
      en_full: 'Enflame Technology',
      en_short: 'Enflame',
      ticker: 'N/A',
      exchange: '未上市',
    },
    // —— 加新公司请在这里往下追加 ——
  },

  // ---- Red-Zone keywords — 2026-04-18 实测 MiniMax \uXXXX drift 对应的正确字面 ----
  // 用法：agent 在 slide JS 里需要打这些词时，直接 require LEXICON.red_zone.<key>，
  // 绝对不要让模型自己逐字符生成。scanner 的 RED_FLAG_DYADS 与此对齐。
  red_zone: {
    cambricon_short: '寒武纪',
    cambricon_full: '寒武纪科技',
    core_chip: '核心芯片',
    accelerator: '加速器',
    accelerator_card: '加速卡',
    accelerator_chip: '加速芯片',
    net_profit_loss: '净利润/亏损',
    net_profit: '净利润',
    financial_loss: '财务亏损',
    revenue_and_net: '营收与净利',
    catalyst_list: '催化剂清单',
    catalyst: '催化剂',
    core_isa: '核心指令集',
    core_technology: '核心技术',
    software_conversion: '软件转化',
    aimedia_research: '艾瑞咨询',
    aimedia_consulting: '艾媒咨询',
    flagship_product: '旗舰产品',
    debugging_loop: '调试循环',
    enterprise_customer: '企业客户',
    customer_one_is: '企业客户是',
  },

  // ---- Industry-specific 术语词典 ----
  industry_terms: {
    // AI 芯片 / 半导体
    ai_chip: {
      ai_accelerator: 'AI加速卡',
      gpu: '图形处理器',
      dsa: '领域专用架构',
      npu: '神经网络处理器',
      soc: '片上系统',
      hbm: '高带宽内存',
      chiplet: '芯粒',
      advanced_packaging: '先进封装',
      cowos: 'CoWoS先进封装',
      eda_software: 'EDA工具',
      foundry: '晶圆代工',
      wafer: '晶圆',
      process_node: '制程节点',
      seven_nm: '7纳米',
      five_nm: '5纳米',
      fabless: '无晶圆厂设计',
      smart_compute_center: '智算中心',
      compute_power: '算力',
      training_chip: '训练芯片',
      inference_chip: '推理芯片',
      self_research_isa: '自研指令集架构',
      cuda_compat: 'CUDA兼容',
      entity_list: '美国实体清单',
    },
    // 新能源车
    nev: {
      battery: '动力电池',
      cell: '电芯',
      nmc: '三元锂',
      lfp: '磷酸铁锂',
      sodium_ion: '钠离子电池',
      solid_state: '固态电池',
      energy_density: '能量密度',
      bms: '电池管理系统',
      charging_pile: '充电桩',
      fast_charge: '快充',
      supply_chain_vertical: '垂直一体化',
      range_km: '续航里程',
      vehicle_platform: '整车平台',
      skateboard_chassis: '滑板底盘',
      auto_driving_l2: '辅助驾驶L2',
      auto_driving_l3: '辅助驾驶L3',
      auto_driving_l4: '高阶自动驾驶L4',
      lidar: '激光雷达',
      lidar_solid_state: '固态激光雷达',
      ota_upgrade: 'OTA升级',
    },
    // 创新药 / 生物医药
    biotech: {
      innovative_drug: '创新药',
      biologic: '生物药',
      small_molecule: '小分子',
      monoclonal_antibody: '单克隆抗体',
      adc: '抗体偶联药物',
      car_t: 'CAR-T细胞治疗',
      gene_therapy: '基因治疗',
      mrna: 'mRNA疫苗',
      clinical_phase_1: '临床一期',
      clinical_phase_2: '临床二期',
      clinical_phase_3: '临床三期',
      ind_approval: 'IND批准',
      nda_submission: 'NDA申报',
      fda_approval: 'FDA获批',
      nmpa_approval: '国家药监局获批',
      license_out: '对外授权',
      milestone_payment: '里程碑付款',
      royalty: '销售分成',
      patent_cliff: '专利悬崖',
      orphan_drug: '孤儿药',
      medical_insurance: '医保谈判',
    },
    // SaaS / 企业软件
    saas: {
      arr: '年度经常性收入',
      mrr: '月度经常性收入',
      nrr: '净收入留存率',
      grr: '总收入留存率',
      churn_rate: '客户流失率',
      cac: '客户获取成本',
      ltv: '客户终身价值',
      payback_period: '回收期',
      rule_of_40: '40 法则',
      magic_number: '销售效率比',
      logo_count: '付费客户数',
      arpu: '单客户平均收入',
      land_and_expand: '拓客再增购',
      acv: '平均合同金额',
      tcv: '合同总金额',
      seat_license: '席位订阅',
      per_seat_pricing: '按人计费',
      multi_tenant: '多租户架构',
      private_cloud: '私有云',
      hybrid_deployment: '混合部署',
    },
    // 消费品 / 品牌消费龙头（白酒 / 调味品 / 乳品 / 家电 / 化妆品 / 服饰）
    consumer_brand: {
      // 白酒
      kweichow_moutai: '贵州茅台',
      wuliangye: '五粮液',
      luzhou_laojiao: '泸州老窖',
      yanghe: '洋河股份',
      shede: '舍得酒业',
      fenjiu: '山西汾酒',
      gujing: '古井贡酒',
      high_end_baijiu: '高端白酒',
      baijiu_premium: '超高端白酒',
      baijiu_mid_range: '次高端白酒',
      daqu: '大曲',
      sauce_aroma: '酱香型',
      strong_aroma: '浓香型',
      light_aroma: '清香型',
      aging: '年份酒',
      volume_volume: '吨位',
      price_band: '价格带',
      // 调味品 / 乳品 / 食品
      haitian_flavor: '海天味业',
      yili: '伊利股份',
      mengniu: '蒙牛乳业',
      nongfu_spring: '农夫山泉',
      yuanqi_forest: '元气森林',
      // 家电 / 白电
      midea: '美的集团',
      gree: '格力电器',
      haier: '海尔智家',
      // 服饰 / 化妆品 / 免税
      anta: '安踏体育',
      li_ning: '李宁',
      chn_duty_free: '中国中免',
      proya: '珀莱雅',
      // 消费通用
      ex_factory_price: '出厂价',
      suggested_retail: '指导价',
      channel_inventory: '渠道库存',
      distributor: '经销商',
      direct_sales: '直营',
      dealer_network: '经销商网络',
      brand_moat: '品牌护城河',
      premium_positioning: '高端定位',
      consumer_upgrade: '消费升级',
    },

    // 消费电子 / 硬件
    consumer_hw: {
      wearable: '可穿戴设备',
      smart_home: '智能家居',
      iot_module: '物联网模组',
      ar_glasses: 'AR 眼镜',
      vr_headset: 'VR 头显',
      bom_cost: '物料成本',
      yield_rate: '良率',
      asp: '平均售价',
      dealer_inventory: '经销商库存',
      flagship_launch: '旗舰新品发布',
      global_shipment: '全球出货量',
      quarterly_ship: '季度出货',
      design_win: '设计中标',
      tier1_customer: 'Tier 1 客户',
      hw_margin: '硬件毛利',
      subscription_attach: '订阅捆绑',
      modem_chip: '基带芯片',
      fingerprint_sensor: '指纹传感器',
      imaging_sensor: '图像传感器',
      haptics: '触觉反馈',
    },
  },

  // ---- 数据源 ----
  data_sources: {
    tushare: 'Tushare Pro',
    cninfo: '巨潮资讯网 cninfo.com.cn',
    sse_official: '上交所官网 sse.com.cn',
    szse_official: '深交所官网 szse.cn',
    hkex_official: '港交所官网 hkex.com.hk',
    tianyancha: '天眼查',
    qichacha: '企查查',
    wind: 'Wind 资讯',
    ths: '同花顺',
    eastmoney: '东方财富',
    caixin: '财新网',
    cls: '财联社',
  },
};

module.exports = LEXICON;
