#!/usr/bin/env python3
"""
API Client Generator and Tester
Create API clients and test endpoints.

Usage:
    python api_client.py --action test --url https://api.example.com/users --method GET
    python api_client.py --action create-client --name myapi --base-url https://api.example.com
"""

import argparse
import json
import requests
import sys
import time
from datetime import datetime
from pathlib import Path

class APIClient:
    def __init__(self, base_url=None, auth_type=None, token=None):
        self.base_url = base_url or ""
        self.auth_type = auth_type or "none"
        self.token = token
        self.session = requests.Session()
        self.logs = []
        
    def log(self, message):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        log_entry = f"[{timestamp}] {message}"
        self.logs.append(log_entry)
        print(log_entry)
    
    def set_auth(self, auth_type, **kwargs):
        """Configure authentication."""
        self.auth_type = auth_type
        
        if auth_type == "bearer":
            self.session.headers.update({
                "Authorization": f"Bearer {kwargs.get('token', '')}"
            })
        elif auth_type == "basic":
            import base64
            credentials = f"{kwargs.get('username', '')}:{kwargs.get('password', '')}"
            encoded = base64.b64encode(credentials.encode()).decode()
            self.session.headers.update({
                "Authorization": f"Basic {encoded}"
            })
        elif auth_type == "api_key":
            self.session.headers.update({
                "X-API-Key": kwargs.get('api_key', '')
            })
        
        self.log(f"Authentication configured: {auth_type}")
    
    def request(self, method, url, **kwargs):
        """Make HTTP request with error handling."""
        full_url = f"{self.base_url}{url}" if url.startswith('/') else url
        
        self.log(f"{method} {full_url}")
        
        try:
            response = self.session.request(
                method,
                full_url,
                timeout=30,
                **kwargs
            )
            
            self.log(f"Status: {response.status_code}")
            
            # Handle rate limiting
            if response.status_code == 429:
                retry_after = int(response.headers.get('Retry-After', 60))
                self.log(f"Rate limited. Waiting {retry_after}s...")
                time.sleep(retry_after)
                return self.request(method, url, **kwargs)  # Retry
            
            response.raise_for_status()
            
            try:
                return response.json()
            except json.JSONDecodeError:
                return {"text": response.text}
                
        except requests.exceptions.RequestException as e:
            self.log(f"Error: {str(e)}")
            return {"error": str(e)}
    
    def test_endpoint(self, url, method="GET", headers=None, body=None):
        """Test an API endpoint."""
        self.log(f"Testing endpoint: {url}")
        
        if headers:
            self.session.headers.update(headers)
        
        kwargs = {}
        if body and method in ["POST", "PUT", "PATCH"]:
            kwargs["json"] = body if isinstance(body, dict) else json.loads(body)
        
        result = self.request(method, url, **kwargs)
        
        self.log(f"Response: {json.dumps(result, indent=2)[:500]}")
        
        return result
    
    def generate_client(self, name, base_url, auth_type="bearer", language="python"):
        """Generate API client code."""
        self.log(f"Generating {language} client for {name}")
        
        if language == "python":
            code = f'''#!/usr/bin/env python3
"""
{name} API Client
Auto-generated by api-integrator skill
"""

import requests
from typing import Optional, Dict, Any

class {name.replace("-", "_").title().replace("_", "")}Client:
    def __init__(self, api_key: str, base_url: str = "{base_url}"):
        self.base_url = base_url
        self.session = requests.Session()
        self.session.headers.update({{
            "Authorization": f"Bearer {{api_key}}",
            "Content-Type": "application/json"
        }})
    
    def _request(self, method: str, endpoint: str, **kwargs) -> Dict[str, Any]:
        """Make API request."""
        url = f"{{self.base_url}}{{endpoint}}"
        response = self.session.request(method, url, **kwargs)
        response.raise_for_status()
        return response.json()
    
    def get(self, endpoint: str, params: Optional[Dict] = None) -> Dict[str, Any]:
        """GET request."""
        return self._request("GET", endpoint, params=params)
    
    def post(self, endpoint: str, data: Dict[str, Any]) -> Dict[str, Any]:
        """POST request."""
        return self._request("POST", endpoint, json=data)
    
    def put(self, endpoint: str, data: Dict[str, Any]) -> Dict[str, Any]:
        """PUT request."""
        return self._request("PUT", endpoint, json=data)
    
    def delete(self, endpoint: str) -> Dict[str, Any]:
        """DELETE request."""
        return self._request("DELETE", endpoint)

# Usage example:
if __name__ == "__main__":
    client = {name.replace("-", "_").title().replace("_", "")}Client(api_key="YOUR_API_KEY")
    # response = client.get("/users")
    # print(response)
'''
        elif language == "javascript":
            code = f'''// {name} API Client
// Auto-generated by api-integrator skill

class {name.replace("-", "_").title().replace("_", "")}Client {{
  constructor(apiKey, baseUrl = "{base_url}") {{
    this.baseUrl = baseUrl;
    this.apiKey = apiKey;
  }}

  async _request(method, endpoint, options = {{}}) {{
    const url = `${{this.baseUrl}}${{endpoint}}`;
    const response = await fetch(url, {{
      method,
      headers: {{
        'Authorization': `Bearer ${{this.apiKey}}`,
        'Content-Type': 'application/json',
        ...options.headers
      }},
      ...options
    }});
    
    if (!response.ok) {{
      throw new Error(`HTTP error! status: ${{response.status}}`);
    }}
    
    return response.json();
  }}

  async get(endpoint, params) {{
    return this._request('GET', endpoint);
  }}

  async post(endpoint, data) {{
    return this._request('POST', endpoint, {{ body: JSON.stringify(data) }});
  }}

  async put(endpoint, data) {{
    return this._request('PUT', endpoint, {{ body: JSON.stringify(data) }});
  }}

  async delete(endpoint) {{
    return this._request('DELETE', endpoint);
  }}
}}

// Usage:
// const client = new {name.replace("-", "_").title().replace("_", "")}Client('YOUR_API_KEY');
// const response = await client.get('/users');
'''
        else:
            return {"error": f"Unsupported language: {language}"}
        
        return {"code": code, "language": language}

def main():
    parser = argparse.ArgumentParser(description='API Client Tool')
    parser.add_argument('--action', required=True,
                        choices=['test', 'create-client', 'webhook-test'],
                        help='Action to perform')
    parser.add_argument('--url', help='API endpoint URL')
    parser.add_argument('--method', default='GET',
                        choices=['GET', 'POST', 'PUT', 'DELETE', 'PATCH'],
                        help='HTTP method')
    parser.add_argument('--base-url', help='Base URL for API client')
    parser.add_argument('--name', help='Client name')
    parser.add_argument('--auth', default='bearer',
                        choices=['none', 'bearer', 'basic', 'api_key'],
                        help='Authentication type')
    parser.add_argument('--token', help='Auth token/API key')
    parser.add_argument('--username', help='Username for basic auth')
    parser.add_argument('--password', help='Password for basic auth')
    parser.add_argument('--headers', help='Custom headers (JSON)')
    parser.add_argument('--body', help='Request body (JSON)')
    parser.add_argument('--language', default='python',
                        choices=['python', 'javascript'],
                        help='Output language for client generation')
    parser.add_argument('--output', help='Output file path')
    args = parser.parse_args()
    
    client = APIClient(args.base_url, args.auth, args.token)
    
    # Setup auth if needed
    if args.auth == "bearer" and args.token:
        client.set_auth("bearer", token=args.token)
    elif args.auth == "basic" and args.username and args.password:
        client.set_auth("basic", username=args.username, password=args.password)
    elif args.auth == "api_key" and args.token:
        client.set_auth("api_key", api_key=args.token)
    
    if args.action == 'test':
        if not args.url:
            print("Error: --url required for test action")
            return 1
        
        headers = json.loads(args.headers) if args.headers else None
        body = json.loads(args.body) if args.body else None
        
        result = client.test_endpoint(args.url, args.method, headers, body)
    
    elif args.action == 'create-client':
        if not args.name or not args.base_url:
            print("Error: --name and --base-url required for create-client")
            return 1
        
        result = client.generate_client(args.name, args.base_url, args.auth, args.language)
        
        if args.output and "code" in result:
            output_path = Path(args.output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(result["code"])
            print(f"Client code saved to: {output_path}")
    
    elif args.action == 'webhook-test':
        result = {"message": "Webhook test endpoint - configure your webhook receiver"}
    
    else:
        result = {"error": "Unknown action"}
    
    print(f"\nResult: {json.dumps(result, indent=2, ensure_ascii=False)[:1000]}")
    return 0 if "error" not in result else 1

if __name__ == '__main__':
    sys.exit(main())
