#!/usr/bin/env bash
set -euo pipefail

# Interactive env setup for telethon-session skill.
# Writes a local .env file (gitignored) that can be sourced to populate env vars.
#
# Why: a child process cannot permanently set env vars for your current shell.
# This script therefore writes .env and tells you how to load it.

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$SKILL_DIR/.env"
EXAMPLE_FILE="$SKILL_DIR/.env.example"

say() { printf "%s\n" "$*"; }

prompt() {
  local label="$1"
  local default="${2:-}"
  local value=""

  if [ -n "$default" ]; then
    read -r -p "$label [$default]: " value || true
    value="${value:-$default}"
  else
    read -r -p "$label: " value || true
  fi

  printf "%s" "$value"
}

prompt_secret() {
  local label="$1"
  local value=""

  # -s: silent, -r: raw
  read -r -s -p "$label: " value || true
  printf "\n" >&2
  printf "%s" "$value"
}

normalize_phone() {
  # remove spaces
  echo "$1" | tr -d ' '
}

mask() {
  local s="$1"
  local n=${#s}
  if [ "$n" -le 6 ]; then
    printf "%s" "***"
  else
    printf "%s" "${s:0:2}***${s:n-2:2}"
  fi
}

say "telethon-session env setup"
say "Directory: $SKILL_DIR"
say

if [ -f "$EXAMPLE_FILE" ] && [ ! -f "$ENV_FILE" ]; then
  say "Tip: there is a template at: $EXAMPLE_FILE"
fi

# Defaults
default_api_id=""
default_session="telegram_session"

# If an existing .env exists, try to load a few defaults (without leaking to stdout)
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  set +u
  source "$ENV_FILE" || true
  set -u
  default_api_id="${TELEGRAM_API_ID:-}"
  default_session="${TELETHON_SESSION:-$default_session}"
  say "Found existing .env; will overwrite it after confirmation."
  say
fi

api_id="$(prompt "TELEGRAM_API_ID (from https://my.telegram.org)" "$default_api_id")"
api_hash="$(prompt_secret "TELEGRAM_API_HASH (sensitive, hidden input)")"
phone_raw="$(prompt "TELEGRAM_PHONE (e.g. +8613..., spaces OK)" "${TELEGRAM_PHONE:-}")"
phone="$(normalize_phone "$phone_raw")"
session="$(prompt "TELETHON_SESSION (session name, no .session extension)" "$default_session")"

say
say "Summary (masked):"
say "  TELEGRAM_API_ID=$api_id"
say "  TELEGRAM_API_HASH=$(mask "$api_hash")"
say "  TELEGRAM_PHONE=$(mask "$phone")"
say "  TELETHON_SESSION=$session"
say

confirm="$(prompt "Write these to $ENV_FILE? (yes/no)" "no")"
if [ "$confirm" != "yes" ]; then
  say "Aborted. No changes made."
  exit 1
fi

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup_env.sh
# Keep this file secret. Do NOT commit it.
TELEGRAM_API_ID=$api_id
TELEGRAM_API_HASH=$api_hash
TELEGRAM_PHONE=$phone
TELETHON_SESSION=$session
EOF
chmod 600 "$ENV_FILE" || true

say
say "Wrote: $ENV_FILE (mode 600)"
say
say "To load these env vars into your CURRENT shell, run:"
say "  cd $SKILL_DIR"
say "  set -a && source .env && set +a"
say
say "To make them permanent, add the export lines to your shell profile (e.g. ~/.bashrc)"
say "or keep using .env + source as needed."
