#!/usr/bin/env python3
"""
generate_report.py — Generate or update the Skill Growth Dashboard

Usage:
    python3 generate_report.py                    # Full dashboard update
    python3 generate_report.py --skill <name>     # Single skill report
    python3 generate_report.py --output json       # Output as JSON instead of markdown
"""

import argparse
import json
import re
from datetime import datetime, timedelta
from pathlib import Path
from batch_analyze import evaluate_skill, get_installed_skills, read_usage_log

WORKSPACE = Path.home() / ".openclaw" / "workspace"
SKILLS_DIR = WORKSPACE / "skills"
GROWER_DIR = SKILLS_DIR / "skill-garden"
DASHBOARD_PATH = GROWER_DIR / "references" / "dashboard.md"


def get_all_evaluations() -> list:
    """Evaluate all skills and return sorted list."""
    skills = get_installed_skills()
    results = []
    for skill in skills:
        eval_result = evaluate_skill(skill)
        results.append(eval_result)
    return sorted(results, key=lambda x: -x["overall"])


def get_status_emoji(score: float) -> str:
    if score >= 70:
        return "🟢"
    elif score >= 50:
        return "🟡"
    else:
        return "🔴"


def outcome_summary(skill: str, days: int = 7) -> dict:
    """Get outcome distribution for a skill in last N days."""
    entries = read_usage_log(skill, days)
    if not entries:
        return {"total": 0, "OK": 0, "PARTIAL": 0, "FAIL": 0, "SLOW": 0, "SKIP": 0}

    summary = {"total": len(entries), "OK": 0, "PARTIAL": 0, "FAIL": 0, "SLOW": 0, "SKIP": 0}
    for e in entries:
        outcome = e.get("outcome", "OK")
        if outcome in summary:
            summary[outcome] += 1
    return summary


def build_dashboard(evaluations: list) -> str:
    """Build the full dashboard markdown."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Count statuses
    total = len(evaluations)
    healthy = sum(1 for e in evaluations if e["overall"] >= 70)
    attention = sum(1 for e in evaluations if 50 <= e["overall"] < 70)
    critical = sum(1 for e in evaluations if e["overall"] < 50)

    # Build health bar
    def bar(count, total, width=16):
        filled = int((count / total) * width) if total > 0 else 0
        return "█" * filled + "░" * (width - filled)

    lines = []
    lines.append(f"# Skill Growth Dashboard\n")
    lines.append(f"> Last updated: {now} (auto-generated by Skill Garden)\n")
    lines.append("---\n")
    lines.append("## 📊 Overall Health\n")
    lines.append(f"```\nTotal Skills Tracked:     {total}\n")
    lines.append(f"Skills \"Healthy\":         {healthy}  {bar(healthy, total)}\n")
    lines.append(f"Skills \"Needs Attention\": {attention}  {bar(attention, total)}\n")
    lines.append(f"Skills \"Critical\":        {critical}  {bar(critical, total)}\n```\n")
    lines.append("**Health Definitions:**\n")
    lines.append("- Healthy: All dimensions ≥ 70%\n")
    lines.append("- Needs Attention: Any dimension 50–69%\n")
    lines.append("- Critical: Any dimension < 50% OR ≥ 3 fails in 7 days\n")
    lines.append("---\n")
    lines.append("## 🌱 Per-Skill Breakdown\n")

    for ev in evaluations:
        skill = ev["skill"]
        status = "🟢 Healthy" if ev["overall"] >= 70 else "🟡 Attention" if ev["overall"] >= 50 else "🔴 Critical"
        entries_7d = read_usage_log(skill, 7)
        last_used = max([e.get("date", "") for e in entries_7d], default="Never")
        recent_signals = [e.get("signal", "") for e in entries_7d[-3:]]
        recent_flags = []
        for e in entries_7d:
            recent_flags.extend(e.get("flags", []))
        flag_counts = ", ".join(f"[{f}]" for f in set(recent_flags)) if recent_flags else "None"

        lines.append(f"### {skill}\n")
        lines.append(f"**Status:** {status}\n")
        lines.append(f"**Last Used:** {last_used}\n")
        lines.append(f"**Uses This Week:** {len(entries_7d)}\n")
        lines.append(f"**Overall Score:** {ev['overall']}%\n")
        lines.append("\n| Dimension | Score | Status |\n")
        lines.append("|-----------|-------|--------|\n")
        for dim, label in [
            ("coverage", "Coverage"),
            ("completeness", "Completeness"),
            ("clarity", "Clarity"),
            ("currency", "Currency"),
            ("efficiency", "Efficiency"),
        ]:
            score = ev[dim]
            emoji = get_status_emoji(score)
            lines.append(f"| {label} | {score}% | {emoji} |\n")

        lines.append("\n**Recent Signals:**\n")
        for s in recent_signals[:3]:
            lines.append(f"- {last_used}: {s}\n")
        lines.append(f"\n**Flags This Week:** {flag_counts}\n")
        lines.append("---\n")

    # Weekly trends
    lines.append("## 📈 Weekly Trends\n")
    lines.append("### Outcome Distribution (this week)\n")

    total_ok = total_partial = total_fail = total_slow = 0
    for ev in evaluations:
        summary = outcome_summary(ev["skill"], 7)
        total_ok += summary["OK"]
        total_partial += summary["PARTIAL"]
        total_fail += summary["FAIL"]
        total_slow += summary["SLOW"]

    total = total_ok + total_partial + total_fail + total_slow
    if total > 0:
        def pct_bar(count, total, width=40):
            filled = int((count / total) * width) if total > 0 else 0
            return "█" * filled + "░" * (width - filled)

        lines.append("```\n")
        lines.append(f"OK:       {total_ok:3d}  {pct_bar(total_ok, total)}  {int((total_ok/total)*100)}%\n")
        lines.append(f"PARTIAL:  {total_partial:3d}  {pct_bar(total_partial, total)}  {int((total_partial/total)*100)}%\n")
        lines.append(f"FAIL:     {total_fail:3d}  {pct_bar(total_fail, total)}  {int((total_fail/total)*100)}%\n")
        lines.append(f"SLOW:     {total_slow:3d}  {pct_bar(total_slow, total)}  {int((total_slow/total)*100)}%\n")
        lines.append("```\n")
    else:
        lines.append("*No usage data this week.*\n")

    lines.append("### Most-Used Skills (this week)\n")
    by_usage = sorted(evaluations, key=lambda x: -len(read_usage_log(x["skill"], 7)))
    for ev in by_usage[:5]:
        count = len(read_usage_log(ev["skill"], 7))
        emoji = get_status_emoji(ev["overall"])
        lines.append(f"{count}. **{ev['skill']}** — {count} uses — {emoji}\n")

    lines.append("---\n")
    lines.append("## 🎯 Pending Proposals\n")
    proposals_path = GROWER_DIR / "references" / "improvement_proposals.md"
    if proposals_path.exists():
        content = proposals_path.read_text()
        # Extract proposals with confidence
        lines.append("> See `references/improvement_proposals.md` for full details.\n")
        # Just show summary from proposals file
        proposal_blocks = re.split(r"\n## ", content)
        for block in proposal_blocks[1:6]:  # Show top 5
            if block.strip():
                lines.append(f"- {block.strip()[:100]}\n")
    else:
        lines.append("*No proposals yet.*\n")

    lines.append("---\n")
    lines.append(f"\n*Dashboard auto-generated by Skill Garden. Do not edit manually.*\n")

    return "".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate Skill Growth Dashboard")
    parser.add_argument("--skill", help="Generate report for a specific skill only")
    parser.add_argument("--output", default="markdown", choices=["markdown", "json"])
    parser.add_argument("--path", default=None, help="Output path (default: dashboard.md)")
    args = parser.parse_args()

    if args.skill:
        ev = evaluate_skill(args.skill)
        print(json.dumps(ev, indent=2, default=str))
        return

    evaluations = get_all_evaluations()

    if args.output == "json":
        print(json.dumps(evaluations, indent=2, default=str))
        return

    dashboard = build_dashboard(evaluations)

    if args.path:
        Path(args.path).write_text(dashboard)
        print(f"[OK] Dashboard written to: {args.path}")
    else:
        DASHBOARD_PATH.parent.mkdir(parents=True, exist_ok=True)
        DASHBOARD_PATH.write_text(dashboard)
        print(f"[OK] Dashboard written to: {DASHBOARD_PATH}")


if __name__ == "__main__":
    main()
