/**
 * OPS Code Review - ESLint 通用配置（React + TypeScript）
 * 使用 --no-eslintrc 忽略项目原有配置，独立运行
 *
 * 兼容 ESLint v8/v9/v10，不依赖项目本地的 typescript-eslint
 * 用法: npx eslint src --ext .ts,.tsx --no-eslintrc -c /path/to/this/file
 */
module.exports = [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/coverage/**',
      '**/*.min.js',
      '**/vendor/**',
    ],
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: require('@typescript-eslint/parser'),
      parserOptions: {
        ecmaFeatures: { jsx: true },
        ecmaVersion: 2022,
        sourceType: 'module',
      },
      globals: {
        console: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        Promise: 'readonly',
        fetch: 'readonly',
        module: 'writable',
        require: 'readonly',
        exports: 'writable',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
      },
    },
    rules: {
      // TypeScript 规则（基础）
      'no-undef': 'error',
      'no-unused-vars': 'off',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'warn',
      'no-extra-semi': 'off',
      'no-inner-declarations': 'off',
      'no-irregular-whitespace': 'warn',
      'no-loss-of-precision': 'error',
      'no-negated-in-lhs': 'off',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'off',
      'no-regex-spaces': 'error',
      'no-sparse-arrays': 'warn',
      'no-template-curly-in-string': 'warn',
      'no-unexpected-multiline': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      // React
      'react/jsx-uses-react': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react/display-name': 'off',
      // 通用风格
      'no-console': 'off',
      'prefer-const': 'warn',
      'no-var': 'error',
      'eqeqeq': ['error', 'always'],
      'curly': ['error', 'all'],
      'default-case': 'warn',
      'no-else-return': 'warn',
      'no-lone-blocks': 'warn',
      'no-new-wrappers': 'error',
      'no-redeclare': 'error',
      'no-return-await': 'error',
      'no-throw-literal': 'error',
      'no-underscore-dangle': 'off',
      'no-use-before-define': 'off',
      'array-callback-return': 'error',
      'consistent-return': 'warn',
      'dot-notation': 'warn',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new': 'error',
      'no-param-reassign': 'warn',
      'no-proto': 'error',
      'prefer-promise-reject-errors': 'warn',
      'prefer-rest-params': 'warn',
      'radix': 'error',
    },
  },
  {
    files: ['**/*.js', '**/*.jsx'],
    languageOptions: {
      globals: {
        console: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        Promise: 'readonly',
        fetch: 'readonly',
        module: 'writable',
        require: 'readonly',
        exports: 'writable',
      },
    },
    rules: {
      'no-console': 'off',
      'no-undef': 'error',
      'no-unused-vars': 'off',
      'prefer-const': 'warn',
      'no-var': 'error',
      'eqeqeq': ['error', 'always'],
    },
  },
];
