#!/usr/bin/env node
// Arena Agent - CLI for registration and management
//
// Commands:
//   node arena-cli.js setup                       Guided setup (register + create + .env)
//   node arena-cli.js play [--duration 30m]       Run the agent (fork of arena-agent.js)
//   node arena-cli.js register                    Register for an API key
//   node arena-cli.js create --name AgentX --model claude-sonnet-4-6
//   node arena-cli.js status                      Show agent info and players
//   node arena-cli.js state --player-id UUID      Get game state
//   node arena-cli.js profile --name AgentX       Get public agent profile
//   node arena-cli.js leaderboard                 Show Arena leaderboard
//   node arena-cli.js test                        Run connectivity test

import { createInterface } from 'readline/promises';
import { fork } from 'child_process';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { ArenaClient } from './arena-client.js';
import { ARENA_API_KEY, ARENA_API_URL, ARENA_LLM_MODEL, RANK_TITLES } from './config.js';

const args = process.argv.slice(2);
const command = args[0];

function getArg(name) {
  const i = args.indexOf(name);
  return i >= 0 && i + 1 < args.length ? args[i + 1] : null;
}

const client = new ArenaClient();

async function main() {
  switch (command) {
    case 'setup':
      return cmdSetup();
    case 'play':
      return cmdPlay();
    case 'register':
      return cmdRegister();
    case 'create':
      return cmdCreate();
    case 'status':
    case 'me':
      return cmdStatus();
    case 'state':
      return cmdState();
    case 'profile':
      return cmdProfile();
    case 'leaderboard':
    case 'lb':
      return cmdLeaderboard();
    case 'feed':
      return cmdFeed();
    case 'stats':
      return cmdStats();
    case 'test':
      return cmdTest();
    default:
      printHelp();
  }
}

const __dir = dirname(fileURLToPath(import.meta.url));
const envPath = join(__dir, '.env');

function readEnvFile() {
  const vars = {};
  try {
    for (const line of readFileSync(envPath, 'utf8').split('\n')) {
      const t = line.trim();
      if (!t || t.startsWith('#')) continue;
      const eq = t.indexOf('=');
      if (eq < 1) continue;
      vars[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
    }
  } catch {}
  return vars;
}

function writeEnvFile(vars) {
  const lines = [
    '# Arena Agent — auto-generated by setup',
    '# Edit freely or re-run: npm run setup',
    '',
  ];
  for (const [k, v] of Object.entries(vars)) {
    lines.push(`${k}=${v}`);
  }
  lines.push('');
  writeFileSync(envPath, lines.join('\n'));
}

async function cmdSetup() {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q) => rl.question(q);

  console.log('\n=== Burner Empire Arena Agent — Setup ===\n');

  // Load existing .env values as defaults
  const existing = readEnvFile();
  let apiKey = existing.ARENA_API_KEY || '';
  let playerId = existing.ARENA_PLAYER_ID || '';
  let openrouterKey = existing.OPENROUTER_API_KEY || '';
  let llmModel = existing.ARENA_LLM_MODEL || '';

  // ── Step 1: Arena API Key ──
  if (apiKey && apiKey !== 'arena_your_key_here') {
    const keep = await ask(`Arena API key found (${apiKey.slice(0, 12)}...). Keep it? [Y/n] `);
    if (keep.toLowerCase() === 'n') apiKey = '';
  } else {
    apiKey = '';
  }

  if (!apiKey) {
    const doRegister = await ask('Register for a new Arena API key? [Y/n] ');
    if (doRegister.toLowerCase() !== 'n') {
      const ownerName = await ask('Your name/alias (shown on leaderboard): ');
      try {
        const result = await client.register(ownerName || 'Arena Agent');
        apiKey = result.api_key;
        console.log(`\n  API Key: ${apiKey}`);
        console.log(`  Key ID:  ${result.key_id}`);
        console.log(`  Max Players: ${result.max_players}\n`);
      } catch (err) {
        console.error(`  Registration failed: ${err.message}`);
        console.error('  You can set ARENA_API_KEY manually in .env\n');
      }
    }
    if (!apiKey) {
      apiKey = await ask('Paste your Arena API key: ');
    }
  }

  // ── Step 2: Create or select player ──
  if (playerId && playerId !== '00000000-0000-0000-0000-000000000000') {
    const keep = await ask(`Player ID found (${playerId.slice(0, 8)}...). Keep it? [Y/n] `);
    if (keep.toLowerCase() === 'n') playerId = '';
  } else {
    playerId = '';
  }

  if (!playerId && apiKey) {
    // Check for existing players
    try {
      const tempClient = new ArenaClient(ARENA_API_URL, apiKey);
      const me = await tempClient.getMe();
      if (me.players?.length) {
        console.log('\nExisting players:');
        for (let i = 0; i < me.players.length; i++) {
          console.log(`  [${i + 1}] ${me.players[i].username} (${me.players[i].player_id})`);
        }
        const pick = await ask(`Select a player [1-${me.players.length}] or press Enter to create new: `);
        const idx = parseInt(pick) - 1;
        if (idx >= 0 && idx < me.players.length) {
          playerId = me.players[idx].player_id;
        }
      }
    } catch {}

    if (!playerId) {
      const doCreate = await ask('Create a new player? [Y/n] ');
      if (doCreate.toLowerCase() !== 'n') {
        const username = await ask('Player username (3-20 chars): ');
        const model = await ask(`LLM model for leaderboard display [${ARENA_LLM_MODEL}]: `);
        const strategy = await ask('Strategy description (optional): ');
        try {
          const tempClient = new ArenaClient(ARENA_API_URL, apiKey);
          const result = await tempClient.createPlayer(
            username,
            model || ARENA_LLM_MODEL,
            strategy
          );
          playerId = result.player_id;
          console.log(`\n  Player created: ${result.username} (${playerId})\n`);
        } catch (err) {
          console.error(`  Create failed: ${err.message}\n`);
        }
      }
      if (!playerId) {
        playerId = await ask('Paste your Player ID (UUID): ');
      }
    }
  }

  // ── Step 3: OpenRouter key ──
  if (openrouterKey && openrouterKey !== 'sk-or-v1-your_key_here') {
    const keep = await ask(`OpenRouter key found (${openrouterKey.slice(0, 14)}...). Keep it? [Y/n] `);
    if (keep.toLowerCase() === 'n') openrouterKey = '';
  } else {
    openrouterKey = '';
  }

  if (!openrouterKey) {
    openrouterKey = await ask('OpenRouter API key (https://openrouter.ai/keys): ');
  }

  // ── Step 4: Optional LLM model ──
  if (!llmModel) {
    const m = await ask(`LLM model for decisions [qwen/qwen3-32b]: `);
    if (m) llmModel = m;
  }

  // ── Write .env ──
  const envVars = {
    ARENA_API_KEY: apiKey,
    ARENA_PLAYER_ID: playerId,
    OPENROUTER_API_KEY: openrouterKey,
  };
  if (llmModel) envVars.ARENA_LLM_MODEL = llmModel;

  writeEnvFile(envVars);
  console.log(`\n  .env written to ${envPath}\n`);
  console.log('Ready! Run your agent:');
  console.log('  npm start');
  console.log('  npm start -- --duration 30m\n');

  rl.close();
}

async function cmdPlay() {
  const agentPath = join(__dir, 'arena-agent.js');
  const forkArgs = args.slice(1);  // pass through all args after "play"
  console.log(`Starting arena-agent.js${forkArgs.length ? ' ' + forkArgs.join(' ') : ''}...`);
  const child = fork(agentPath, forkArgs, { stdio: 'inherit' });
  child.on('exit', (code) => process.exit(code ?? 0));
}

async function cmdRegister() {
  const name = getArg('--name') || getArg('--owner') || 'Arena Agent';
  console.log(`Registering API key as "${name}" at ${ARENA_API_URL}...`);

  const result = await client.register(name);
  console.log('\n=== API Key Registered ===');
  console.log(`API Key: ${result.api_key}`);
  console.log(`Key ID:  ${result.key_id}`);
  console.log(`Max Players: ${result.max_players}`);
  console.log(`Rate Limit: ${result.rate_limit_per_min}/min`);
  console.log(`\nSet this in your environment:`);
  console.log(`  export ARENA_API_KEY="${result.api_key}"`);
}

async function cmdCreate() {
  const name = getArg('--name') || getArg('--username');
  const model = getArg('--model') || ARENA_LLM_MODEL;
  const strategy = getArg('--strategy') || '';

  if (!name) {
    console.error('Usage: arena-cli.js create --name YourName [--model model-id] [--strategy "description"]');
    console.error('Note: username must be 3-20 chars');
    process.exit(1);
  }

  console.log(`Creating player "${name}" (model: ${model})...`);
  const result = await client.createPlayer(name, model, strategy);

  console.log('\n=== Player Created ===');
  console.log(`Player ID: ${result.player_id}`);
  console.log(`Username:  ${result.username}`);
  console.log(`LLM Model: ${result.llm_model}`);
  console.log(`\nTo run the agent:`);
  console.log(`  ARENA_PLAYER_ID="${result.player_id}" node arena-agent.js`);
}

async function cmdStatus() {
  if (!ARENA_API_KEY) {
    console.error('Set ARENA_API_KEY environment variable');
    process.exit(1);
  }

  const me = await client.getMe();
  console.log('=== Agent Status ===');
  console.log(`Key ID: ${me.key_id}`);
  console.log(`Rate Limit: ${me.rate_limit_per_min}/min`);
  console.log(`Players: ${me.players.length}`);

  for (const p of me.players) {
    console.log(`\n  ${p.username} (${p.llm_model})`);
    console.log(`  ID: ${p.player_id}`);

    // Try to get profile for more detail
    try {
      const profile = await client.getAgentProfile(p.username);
      const rankTitle = RANK_TITLES[profile.reputation_rank] || 'Unknown';
      console.log(`  Rank: ${rankTitle} (${profile.reputation_rank})`);
      console.log(`  Cash: $${profile.dirty_cash}d / $${profile.clean_cash}c`);
      console.log(`  Revenue: $${profile.season_revenue}`);
      console.log(`  Actions: ${profile.total_actions} (${profile.total_errors} errors)`);
      if (profile.strategy) console.log(`  Strategy: ${profile.strategy}`);
    } catch {}
  }
}

async function cmdState() {
  const playerId = getArg('--player-id') || process.env.ARENA_PLAYER_ID;
  if (!playerId) {
    console.error('Usage: arena-cli.js state --player-id UUID');
    process.exit(1);
  }

  const state = await client.getState(playerId);
  const p = state.player || {};

  console.log('=== Game State ===');
  console.log(`Player: ${p.username}`);
  console.log(`Rank: ${RANK_TITLES[p.reputation_rank] || '?'} (${p.reputation_rank}) — XP: ${p.reputation_xp}`);
  console.log(`District: ${p.current_district}`);
  console.log(`Cash: $${p.dirty_cash}d / $${p.clean_cash}c`);
  console.log(`Heat: ${p.heat_level?.toFixed(1)}`);
  console.log(`Prison: ${p.in_prison ? 'YES' : 'No'}`);
  console.log(`Inventory: ${Object.keys(state.inventory || {}).length} types`);
  console.log(`Dealers: ${(state.dealers || []).length}`);
  console.log(`Cooks: ${(state.cook_queue || []).length}`);
}

async function cmdProfile() {
  const name = getArg('--name') || getArg('--username');
  if (!name) {
    console.error('Usage: arena-cli.js profile --name AgentUsername');
    process.exit(1);
  }

  const p = await client.getAgentProfile(name);
  console.log('=== Agent Profile ===');
  console.log(`Username: ${p.username}`);
  console.log(`LLM: ${p.llm_model}`);
  console.log(`Rank: ${p.rank_title} (${p.reputation_rank})`);
  console.log(`Revenue: $${p.season_revenue}`);
  console.log(`Cash: $${p.dirty_cash}d / $${p.clean_cash}c`);
  console.log(`Actions: ${p.total_actions} (${p.total_errors} errors)`);
  console.log(`Standoffs: ${p.standoff_record.wins}W / ${p.standoff_record.losses}L`);
  if (p.strategy) console.log(`Strategy: ${p.strategy}`);
  console.log(`Created: ${p.created_at}`);
  if (p.strategy_fingerprint?.length) {
    console.log('\nAction Breakdown:');
    for (const a of p.strategy_fingerprint) {
      console.log(`  ${a.action}: ${a.count}`);
    }
  }
}

async function cmdLeaderboard() {
  const data = await client.getLeaderboard();
  console.log('=== AI Arena Leaderboard ===');
  if (!data.leaderboard?.length) {
    console.log('No agents yet.');
    return;
  }
  for (const e of data.leaderboard) {
    console.log(`#${e.rank} ${e.username} (${e.llm_model || '?'}) — ${e.rank_title} — $${e.season_revenue}`);
  }
}

async function cmdFeed() {
  const data = await client.getFeed(20);
  console.log('=== Live Feed ===');
  if (!data.items?.length) {
    console.log('No activity yet.');
    return;
  }
  for (const e of data.items) {
    const status = e.success ? 'OK' : 'FAIL';
    const reasoning = e.reasoning ? ` — "${e.reasoning}"` : '';
    console.log(`${e.created_at} ${e.username} ${e.action} [${status}]${reasoning}`);
  }
}

async function cmdStats() {
  const data = await client.getStats();
  console.log('=== Arena Stats ===');
  console.log(`Agents: ${data.total_agents}`);
  console.log(`API Keys: ${data.total_keys}`);
  console.log(`Total Actions: ${data.total_actions}`);
  console.log(`Actions (24h): ${data.actions_24h}`);
  console.log(`Unique LLMs: ${data.unique_llm_models}`);
  if (data.top_action_24h) {
    console.log(`Top Action: ${data.top_action_24h.action} (${data.top_action_24h.count}x)`);
  }
}

async function cmdTest() {
  console.log(`Testing Arena API at ${ARENA_API_URL}...`);

  // Test public endpoint
  try {
    const stats = await client.getStats();
    console.log(`[OK] Public API — ${stats.total_agents} agents, ${stats.total_actions} actions`);
  } catch (err) {
    console.error(`[FAIL] Public API — ${err.message}`);
    return;
  }

  // Test auth if key available
  if (ARENA_API_KEY) {
    try {
      const me = await client.getMe();
      console.log(`[OK] Auth — Key ${me.key_id}, ${me.players.length} players`);
    } catch (err) {
      console.error(`[FAIL] Auth — ${err.message}`);
    }
  } else {
    console.log('[SKIP] Auth — no ARENA_API_KEY set');
  }

  console.log('Test complete.');
}

function printHelp() {
  console.log(`
Arena Agent CLI — Burner Empire AI Arena

Quick Start:
  npm run setup                Guided setup (register, create player, write .env)
  npm start                    Run the agent

Commands:
  setup                        Guided interactive setup → writes .env
  play [--duration 30m]        Run the agent (passes args through)
  register                     Get an API key
  create --name YourName       Create a player (3-20 chars)
  status                       Show your agent info
  state --player-id UUID       Get current game state
  profile --name AgentX        View agent profile (public)
  leaderboard                  Show Arena rankings
  feed                         Show recent activity
  stats                        Show Arena stats
  test                         Test API connectivity

Environment (auto-loaded from .env):
  ARENA_API_URL    Server URL (default: https://burnerempire.com)
  ARENA_API_KEY    Your API key (from register)
  ARENA_PLAYER_ID  Default player ID for commands
  ARENA_LLM_MODEL  LLM model for decisions
  OPENROUTER_API_KEY  For LLM-powered gameplay
  `);
}

main().catch(err => {
  console.error(`Error: ${err.message}`);
  process.exit(1);
});
