"""Phase 5: Streak badges (~4 badges).

Runs today's streak actions and generates a reusable daily script:
  - 7-Day Login Streak
  - 30-Day Login Streak
  - Submission Streak (7 days)
  - Super Submission Streak (30 days)

The script is generated for the user to schedule themselves if desired.
No cron jobs or launchd plists are installed automatically.
"""

import platform
import stat
import subprocess
from pathlib import Path

from badge_tracker import set_status, should_attempt
from utils import REPO_ROOT, TEMPLATES_DIR, get_kaggle_cli


DAILY_SCRIPT_PATH = REPO_ROOT / "skills" / "badge-collector" / "scripts" / "daily_streak.sh"


def _create_daily_script() -> Path:
    """Create the daily streak script (no credentials embedded)."""
    kaggle_cli = get_kaggle_cli()
    submission_file = TEMPLATES_DIR / "submission_titanic.csv"

    script = f"""#!/usr/bin/env bash
# Daily Kaggle streak script — auto-generated by badge-collector
# Makes an API call (counts as login) and submits to Titanic
# Credentials are read from ~/.kaggle/kaggle.json or env vars at runtime.

set -euo pipefail

KAGGLE="{kaggle_cli}"

# 1. API activity = login
$KAGGLE datasets list --page-size 1 > /dev/null 2>&1 || true

# 2. Daily Titanic submission (if submission file exists)
SUBMISSION="{submission_file}"
if [ -f "$SUBMISSION" ]; then
    $KAGGLE competitions submit \\
        -c titanic \\
        -f "$SUBMISSION" \\
        -m "Daily streak submission $(date +%Y-%m-%d)" \\
        > /dev/null 2>&1 || true
fi

echo "[$(date)] Streak script completed"
"""
    DAILY_SCRIPT_PATH.write_text(script)
    # Owner-only read/write/execute (no group or world access)
    DAILY_SCRIPT_PATH.chmod(stat.S_IRWXU)
    return DAILY_SCRIPT_PATH


def _run_today(kaggle_cli: str) -> bool:
    """Run today's streak actions inline (API call + Titanic submission)."""
    print("  Running today's streak actions...")

    # 1. API activity (counts as login)
    result = subprocess.run(
        [kaggle_cli, "datasets", "list", "--page-size", "1"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print("    API login activity: OK")
    else:
        print(f"    API login activity: FAILED ({result.stderr.strip()})")

    # 2. Titanic submission
    submission_file = TEMPLATES_DIR / "submission_titanic.csv"
    if submission_file.exists():
        result = subprocess.run(
            [kaggle_cli, "competitions", "submit",
             "-c", "titanic",
             "-f", str(submission_file),
             "-m", "Daily streak submission"],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            print("    Titanic submission: OK")
        else:
            print(f"    Titanic submission: FAILED ({result.stderr.strip()})")
    else:
        print(f"    Titanic submission: SKIPPED (no {submission_file})")

    return True


def _print_scheduling_instructions(script_path: Path) -> None:
    """Print instructions for the user to set up their own daily scheduling."""
    system = platform.system()

    print("\n  --- Manual scheduling instructions ---")
    print(f"  Daily script created at: {script_path}")
    print()

    if system == "Darwin":
        print("  To schedule on macOS (launchd):")
        print(f"    1. Create a plist at ~/Library/LaunchAgents/com.kaggle.streak.plist")
        print(f"       with ProgramArguments pointing to: /bin/bash {script_path}")
        print(f"    2. Load it: launchctl load ~/Library/LaunchAgents/com.kaggle.streak.plist")
        print()
        print("  Or use cron:")
        print(f"    crontab -e   # then add:")
        print(f"    0 10 * * * {script_path}")
    else:
        print("  To schedule on Linux (cron):")
        print(f"    crontab -e   # then add:")
        print(f"    0 10 * * * {script_path}")

    print()
    print("  Credentials are read from ~/.kaggle/kaggle.json or")
    print("  KAGGLE_USERNAME + KAGGLE_KEY env vars at runtime.")
    print("  Badges will be earned after 7/30 days of daily execution.")


def run(username: str) -> tuple[int, int]:
    """Run today's streak actions and generate reusable script.

    Returns (attempted, succeeded).
    """
    badge_ids = [
        "seven_day_login_streak",
        "thirty_day_login_streak",
        "submission_streak",
        "super_submission_streak",
    ]

    actionable = [b for b in badge_ids if should_attempt(b)]
    if not actionable:
        print("  All streak badges already earned/skipped")
        return 0, 0

    print("\n  --- Phase 5: Streak badges ---")

    kaggle_cli = get_kaggle_cli()

    # Run today's actions immediately
    _run_today(kaggle_cli)

    # Generate the reusable daily script
    script_path = _create_daily_script()

    # Print instructions for manual scheduling
    _print_scheduling_instructions(script_path)

    for bid in actionable:
        set_status(bid, "attempting", "today's actions done — schedule daily script for full streaks")

    return len(actionable), len(actionable)
