#!/usr/bin/env python3
"""
VASP Input File Generator

Generates INCAR, KPOINTS, and POSCAR template files for VASP calculations.

Usage:
    python generate_vasp_inputs.py --type <calculation_type> [options]

Calculation Types:
    relaxation  - Structural optimization (default)
    static      - Single-point energy calculation
    md          - Molecular dynamics simulation
    band        - Band structure calculation
    dos         - Density of states calculation
"""

import argparse
import os
import sys
from pathlib import Path
from datetime import datetime


# Default INCAR parameters by calculation type
INCAR_TEMPLATES = {
    "relaxation": {
        "ENCUT": 500,
        "EDIFF": 1e-5,
        "EDIFFG": -1e-3,
        "NSW": 200,
        "IBRION": 2,
        "ISIF": 3,
        "POTIM": 0.5,
        "ISMEAR": 0,
        "SIGMA": 0.05,
        "LREAL": "Auto",
        "LWAVE": False,
        "LCHARG": False,
        "NELM": 60,
        "ALGO": "Normal",
        "ISPIN": 1,
        "NPAR": 4,
        "LPLANE": True,
    },
    "static": {
        "ENCUT": 500,
        "EDIFF": 1e-6,
        "NSW": 1,
        "ISMEAR": 0,
        "SIGMA": 0.05,
        "LREAL": "Auto",
        "LWAVE": False,
        "LCHARG": True,
        "NELM": 100,
        "ALGO": "Normal",
        "ISPIN": 1,
        "NPAR": 4,
        "LPLANE": True,
    },
    "md": {
        "ENCUT": 500,
        "EDIFF": 1e-5,
        "NSW": 1000,
        "IBRION": 0,
        "POTIM": 1.0,
        "TEBEG": 300,
        "TEEND": 300,
        "ISMEAR": 1,
        "SIGMA": 0.2,
        "LREAL": "Auto",
        "LWAVE": False,
        "LCHARG": False,
        "NELM": 60,
        "ALGO": "Fast",
        "ISPIN": 1,
        "MDALGO": 2,
        "SMASS": -3.0,
    },
    "band": {
        "ENCUT": 500,
        "EDIFF": 1e-6,
        "NSW": 1,
        "ISMEAR": 0,
        "SIGMA": 0.05,
        "LREAL": "Auto",
        "LWAVE": True,
        "LCHARG": True,
        "NELM": 100,
        "ALGO": "Normal",
        "ISPIN": 1,
        "ICHARG": 11,
    },
    "dos": {
        "ENCUT": 500,
        "EDIFF": 1e-6,
        "NSW": 1,
        "ISMEAR": -5,  # Tetrahedron method
        "LREAL": "Auto",
        "LWAVE": False,
        "LCHARG": False,
        "NELM": 100,
        "ALGO": "Normal",
        "ISPIN": 1,
        "ICHARG": 11,
        "LORBIT": 11,
    },
}

# KPOINTS templates
KPOINTS_TEMPLATES = {
    "relaxation": "automatic",
    "static": "automatic",
    "md": "automatic",
    "band": "line-mode",
    "dos": "automatic",
}


def generate_incar(calc_type: str, custom_params: dict = None) -> str:
    """Generate INCAR file content."""
    params = INCAR_TEMPLATES.get(calc_type, INCAR_TEMPLATES["relaxation"]).copy()
    
    if custom_params:
        params.update(custom_params)
    
    lines = [
        "# VASP INCAR - Generated by vasp-input-generator",
        f"# Calculation Type: {calc_type.upper()}",
        f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "# === Electronic Minimization ===",
        f"ENCUT = {params.get('ENCUT', 500)}",
        f"EDIFF = {params.get('EDIFF', 1e-5):.1e}",
        f"NELM = {params.get('NELM', 60)}",
        f"ALGO = {params.get('ALGO', 'Normal')}",
        "",
        "# === Ionic Minimization ===",
    ]
    
    if "EDIFFG" in params:
        lines.append(f"EDIFFG = {params['EDIFFG']:.1e}")
    
    if "NSW" in params:
        lines.append(f"NSW = {params['NSW']}")
    
    if "IBRION" in params:
        lines.append(f"IBRION = {params['IBRION']}")
    
    if "ISIF" in params:
        lines.append(f"ISIF = {params['ISIF']}")
    
    if "POTIM" in params:
        lines.append(f"POTIM = {params['POTIM']}")
    
    lines.extend([
        "",
        "# === Smearing ===",
        f"ISMEAR = {params.get('ISMEAR', 0)}",
        f"SIGMA = {params.get('SIGMA', 0.05)}",
        "",
        "# === Output Control ===",
        f"LREAL = {params.get('LREAL', 'Auto')}",
        f"LWAVE = {'.TRUE.' if params.get('LWAVE', False) else '.FALSE.'}",
        f"LCHARG = {'.TRUE.' if params.get('LCHARG', False) else '.FALSE.'}",
        "",
        "# === Parallelization ===",
        f"NPAR = {params.get('NPAR', 4)}",
        f"LPLANE = {'.TRUE.' if params.get('LPLANE', True) else '.FALSE.'}",
        "",
        "# === Spin ===",
        f"ISPIN = {params.get('ISPIN', 1)}",
    ])
    
    # Add MD-specific parameters
    if calc_type == "md":
        lines.extend([
            "",
            "# === MD Settings ===",
            f"TEBEG = {params.get('TEBEG', 300)}",
            f"TEEND = {params.get('TEEND', 300)}",
            f"MDALGO = {params.get('MDALGO', 2)}",
            f"SMASS = {params.get('SMASS', -3.0)}",
        ])
    
    # Add band/DOS-specific parameters
    if calc_type in ["band", "dos"]:
        lines.extend([
            "",
            "# === Non-self-consistent ===",
            f"ICHARG = {params.get('ICHARG', 11)}",
        ])
    
    if "LORBIT" in params:
        lines.append(f"LORBIT = {params['LORBIT']}")
    
    lines.append("")
    return "\n".join(lines)


def generate_kpoints(calc_type: str, structure: str = None, kspacing: float = 0.5) -> str:
    """Generate KPOINTS file content."""
    template = KPOINTS_TEMPLATES.get(calc_type, "automatic")
    
    if template == "automatic":
        if structure and os.path.exists(structure):
            # Could parse structure to estimate k-points
            # For now, use default
            kpoints = 0
            line = "Automatic"
        else:
            kpoints = 0
            line = "Automatic"
        
        content = f"""# VASP KPOINTS - Generated by vasp-input-generator
# Calculation Type: {calc_type.upper()}
# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# K-point spacing: {kspacing} A^-1

{line}
0
Gamma
{int(1/kspacing)} {int(1/kspacing)} {int(1/kspacing)}
0 0 0
"""
    else:  # line-mode for band structure
        content = f"""# VASP KPOINTS - Band Structure Line Mode
# Calculation Type: {calc_type.upper()}
# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# 
# Replace with high-symmetry k-path for your structure
# Example for FCC: Γ-X-W-K-Γ-L-U-W-L-K | U-X

Line-mode
reciprocal
40

# Gamma point
0.0 0.0 0.0
0.5 0.0 0.5

# X point
0.5 0.0 0.5
0.625 0.25 0.625

# W point
0.625 0.25 0.625
0.375 0.375 0.75

# K point
0.375 0.375 0.75
0.0 0.0 0.0
"""
    
    return content


def generate_poscar_template() -> str:
    """Generate a POSCAR template file."""
    content = """# VASP POSCAR Template
# Replace with your structure
# Generated by vasp-input-generator

Element1 Element2
1.0
    4.0    0.0    0.0
    0.0    4.0    0.0
    0.0    0.0    4.0
Element1
Element2
1
1
Direct
0.0  0.0  0.0
0.5  0.5  0.5
"""
    return content


def main():
    parser = argparse.ArgumentParser(
        description="Generate VASP input files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    
    parser.add_argument(
        "--type", "-t",
        type=str,
        default="relaxation",
        choices=["relaxation", "static", "md", "band", "dos"],
        help="Calculation type (default: relaxation)",
    )
    
    parser.add_argument(
        "--output", "-o",
        type=str,
        default=".",
        help="Output directory (default: current directory)",
    )
    
    parser.add_argument(
        "--structure", "-s",
        type=str,
        default=None,
        help="Existing POSCAR file for k-point estimation",
    )
    
    parser.add_argument(
        "--kspacing", "-k",
        type=float,
        default=0.5,
        help="K-point spacing in Å⁻¹ (default: 0.5)",
    )
    
    parser.add_argument(
        "--encut", "-e",
        type=int,
        default=None,
        help="Override ENCUT value",
    )
    
    parser.add_argument(
        "--ispin",
        type=int,
        default=None,
        choices=[1, 2],
        help="Override ISPIN (1=non-spin-polarized, 2=spin-polarized)",
    )
    
    args = parser.parse_args()
    
    # Create output directory if needed
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Custom parameters
    custom_params = {}
    if args.encut:
        custom_params["ENCUT"] = args.encut
    if args.ispin:
        custom_params["ISPIN"] = args.ispin
    
    # Generate INCAR
    incar_content = generate_incar(args.type, custom_params)
    incar_path = output_dir / "INCAR"
    with open(incar_path, "w", encoding="utf-8") as f:
        f.write(incar_content)
    print(f"[OK] Generated: {incar_path}")
    
    # Generate KPOINTS
    kpoints_content = generate_kpoints(args.type, args.structure, args.kspacing)
    kpoints_path = output_dir / "KPOINTS"
    with open(kpoints_path, "w", encoding="utf-8") as f:
        f.write(kpoints_content)
    print(f"[OK] Generated: {kpoints_path}")
    
    # Generate POSCAR template if no existing structure
    if not args.structure or not os.path.exists(args.structure):
        poscar_content = generate_poscar_template()
        poscar_path = output_dir / "POSCAR.template"
        with open(poscar_path, "w", encoding="utf-8") as f:
            f.write(poscar_content)
        print(f"[OK] Generated: {poscar_path} (template - edit with your structure)")
    else:
        print(f"[INFO] Using existing structure: {args.structure}")
    
    print(f"\n[INFO] Calculation type: {args.type.upper()}")
    print(f"[INFO] Remember to generate POTCAR by concatenating pseudopotential files")
    print(f"[INFO] Example: cat POTCAR_* > POTCAR")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
