[build]
  command = "echo 'No build needed'"
  publish = "."
  functions = "functions"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/price"
  to = "/.netlify/functions/verify"
  status = 200