#!/usr/bin/env python3
"""Generate a starter DOSBox/DOSBox-X config file."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

from resolve_dosbox import find_binaries


def quote_autoexec_path(path: Path) -> str:
    return str(path.resolve()).replace('\\', '/')


def choose_binary() -> str | None:
    binaries = find_binaries()
    if not binaries:
        return None
    return next((b for b in binaries if 'dosbox-x' in b.lower()), binaries[0])


def build_conf(game_path: Path, iso_path: Path | None, exe: str | None, fullscreen: bool, output: str, cycles: str, binary: str | None) -> str:
    autoexec = [
        f"mount c \"{quote_autoexec_path(game_path)}\"",
    ]
    if iso_path:
        autoexec.append(f"imgmount d \"{quote_autoexec_path(iso_path)}\" -t iso")
    autoexec.append("c:")
    autoexec.append("dir")
    if exe:
        autoexec.append(exe)

    full = "true" if fullscreen else "false"
    binary_comment = binary or "NOT FOUND"

    return f"""# Generated by make_dosbox_conf.py
# Preferred emulator: {binary_comment}

[sdl]
fullscreen={full}
output={output}

[render]
aspect=true
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles={cycles}
cycleup=500
cycledown=500

[mixer]
rate=44100
blocksize=1024
prebuffer=20

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
mixer=true
oplmode=auto
oplemu=default
oplrate=44100

[autoexec]
{"\n".join(autoexec)}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a starter DOSBox config file.")
    parser.add_argument("--game-path", required=True, help="Folder to mount as C:")
    parser.add_argument("--iso", help="Optional ISO to mount as D:")
    parser.add_argument("--exe", help="Optional executable or batch file to auto-run")
    parser.add_argument("--conf", required=True, help="Output config path")
    parser.add_argument("--fullscreen", action="store_true", help="Start in fullscreen mode")
    parser.add_argument("--output", default="opengl", help="Output mode: opengl, texture, ddraw, surface")
    parser.add_argument("--cycles", default="auto", help="CPU cycles value")
    args = parser.parse_args()

    game_path = Path(args.game_path)
    if not game_path.exists() or not game_path.is_dir():
        print(f"Game path not found or not a directory: {game_path}", file=sys.stderr)
        return 1

    iso_path = Path(args.iso) if args.iso else None
    if iso_path and not iso_path.exists():
        print(f"ISO path not found: {iso_path}", file=sys.stderr)
        return 1

    conf_path = Path(args.conf)
    conf_path.parent.mkdir(parents=True, exist_ok=True)

    binary = choose_binary()
    conf_text = build_conf(
        game_path=game_path,
        iso_path=iso_path,
        exe=args.exe,
        fullscreen=args.fullscreen,
        output=args.output,
        cycles=args.cycles,
        binary=binary,
    )
    conf_path.write_text(conf_text, encoding="utf-8")
    print(f"Wrote config: {conf_path.resolve()}")
    if binary:
        print(f"Preferred emulator: {binary}")
        print(f'Launch example: "{binary}" -conf "{conf_path.resolve()}"')
    else:
        print("Preferred emulator: not found")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
