import { ISPConfigError } from "./errors";
import { ISPConfigPluginConfig } from "./types";

export const WRITE_TOOLS = new Set<string>([
  "isp_client_add",
  "isp_site_add",
  "isp_domain_add",
  "isp_dns_zone_add",
  "isp_dns_record_add",
  "isp_dns_record_delete",
  "isp_mail_domain_add",
  "isp_mail_user_add",
  "isp_mail_user_delete",
  "isp_db_add",
  "isp_db_user_add",
  "isp_shell_user_add",
  "isp_ftp_user_add",
  "isp_cron_add",
  "isp_provision_site",
  // v0.5.0 — Phase 1 write tools
  "isp_client_change_password",
  "isp_client_delete_everything",
  "isp_client_template_add",
  "isp_client_template_delete",
  "isp_server_ip_add",
  "isp_server_ip_update",
  "isp_server_ip_delete",
  "isp_server_config_set",
  "isp_site_backup",
  "isp_site_set_status",
  // v0.6.0 — Phase 2 write tools
  "isp_dns_alias_add",
  "isp_dns_alias_update",
  "isp_dns_alias_delete",
  "isp_dns_dname_add",
  "isp_dns_dname_update",
  "isp_dns_dname_delete",
  "isp_dns_ds_add",
  "isp_dns_ds_update",
  "isp_dns_ds_delete",
  "isp_dns_hinfo_add",
  "isp_dns_hinfo_update",
  "isp_dns_hinfo_delete",
  "isp_dns_loc_add",
  "isp_dns_loc_update",
  "isp_dns_loc_delete",
  "isp_dns_naptr_add",
  "isp_dns_naptr_update",
  "isp_dns_naptr_delete",
  "isp_dns_rp_add",
  "isp_dns_rp_update",
  "isp_dns_rp_delete",
  "isp_dns_sshfp_add",
  "isp_dns_sshfp_update",
  "isp_dns_sshfp_delete",
  "isp_dns_tlsa_add",
  "isp_dns_tlsa_update",
  "isp_dns_tlsa_delete",
  "isp_dns_slave_add",
  "isp_dns_slave_update",
  "isp_dns_slave_delete",
  "isp_dns_templatezone_add",
  "isp_dns_zone_set_status",
  "isp_dns_zone_set_dnssec",
  // v0.7.0 — Phase 3 write tools
  "isp_mail_aliasdomain_add",
  "isp_mail_aliasdomain_update",
  "isp_mail_aliasdomain_delete",
  "isp_mail_catchall_add",
  "isp_mail_catchall_update",
  "isp_mail_catchall_delete",
  "isp_mail_mailinglist_add",
  "isp_mail_mailinglist_update",
  "isp_mail_mailinglist_delete",
  "isp_mail_user_filter_add",
  "isp_mail_user_filter_update",
  "isp_mail_user_filter_delete",
  "isp_mail_user_backup",
  "isp_mail_domain_set_status",
  "isp_mail_fetchmail_add",
  "isp_mail_fetchmail_update",
  "isp_mail_fetchmail_delete",
  "isp_mail_transport_add",
  "isp_mail_transport_update",
  "isp_mail_transport_delete",
  "isp_mail_relay_recipient_add",
  "isp_mail_relay_recipient_update",
  "isp_mail_relay_recipient_delete",
  "isp_mail_relay_domain_add",
  "isp_mail_relay_domain_update",
  "isp_mail_relay_domain_delete",
  "isp_mail_spamfilter_whitelist_add",
  "isp_mail_spamfilter_whitelist_update",
  "isp_mail_spamfilter_whitelist_delete",
  "isp_mail_spamfilter_blacklist_add",
  "isp_mail_spamfilter_blacklist_update",
  "isp_mail_spamfilter_blacklist_delete",
  "isp_mail_spamfilter_user_add",
  "isp_mail_spamfilter_user_update",
  "isp_mail_spamfilter_user_delete",
  "isp_mail_policy_add",
  "isp_mail_policy_update",
  "isp_mail_policy_delete",
  "isp_mail_whitelist_add",
  "isp_mail_whitelist_update",
  "isp_mail_whitelist_delete",
  "isp_mail_blacklist_add",
  "isp_mail_blacklist_update",
  "isp_mail_blacklist_delete",
  "isp_mail_filter_add",
  "isp_mail_filter_update",
  "isp_mail_filter_delete",
  // v0.8.0 — Phase 4 write tools
  "isp_vhost_aliasdomain_add",
  "isp_vhost_aliasdomain_update",
  "isp_vhost_aliasdomain_delete",
  "isp_vhost_subdomain_add",
  "isp_vhost_subdomain_update",
  "isp_vhost_subdomain_delete",
  "isp_web_aliasdomain_add",
  "isp_web_aliasdomain_update",
  "isp_web_aliasdomain_delete",
  "isp_web_subdomain_add",
  "isp_web_subdomain_update",
  "isp_web_subdomain_delete",
  "isp_web_folder_add",
  "isp_web_folder_update",
  "isp_web_folder_delete",
  "isp_web_folder_user_add",
  "isp_web_folder_user_update",
  "isp_web_folder_user_delete",
  "isp_webdav_user_add",
  "isp_webdav_user_update",
  "isp_webdav_user_delete",
  // v0.9.0 — Phase 5 write tools
  "isp_system_config_set",
  "isp_config_value_add",
  "isp_config_value_update",
  "isp_config_value_replace",
  "isp_config_value_delete",
  "isp_aps_update_packages",
  "isp_aps_change_status",
  "isp_aps_install",
  "isp_aps_instance_delete",
  "isp_domain_registry_add",
  "isp_domain_registry_update",
  "isp_domain_registry_delete",
  "isp_update_record_permissions",
  // v1.0.0 — Phase 6 write tools
  "isp_openvz_ostemplate_add",
  "isp_openvz_ostemplate_update",
  "isp_openvz_ostemplate_delete",
  "isp_openvz_template_add",
  "isp_openvz_template_update",
  "isp_openvz_template_delete",
  "isp_openvz_ip_add",
  "isp_openvz_ip_update",
  "isp_openvz_ip_delete",
  "isp_openvz_vm_add",
  "isp_openvz_vm_add_from_template",
  "isp_openvz_vm_update",
  "isp_openvz_vm_delete",
  "isp_openvz_vm_start",
  "isp_openvz_vm_stop",
  "isp_openvz_vm_restart",
]);

export function assertToolAllowed(config: ISPConfigPluginConfig, toolName: string): void {
  const allowed = config.allowedOperations ?? [];
  if (allowed.length > 0 && !allowed.includes(toolName)) {
    throw new ISPConfigError("permission_denied",
      `Tool ${toolName} is blocked by allowedOperations policy`,
      { statusCode: 403 },
    );
  }

  if ((config.readOnly ?? false) && WRITE_TOOLS.has(toolName)) {
    throw new ISPConfigError("permission_denied",
      `Tool ${toolName} is blocked because readOnly=true`,
      { statusCode: 403 },
    );
  }
}
