import { CursorAdapter } from './cursor-adapter.js';
import type { SkillMeta } from '../../types/index.js';

export class ClineAdapter extends CursorAdapter {
  override generateHeaderContent(skills: SkillMeta[]): string {
    return `# Cline Rules\n\n> Generated by open-skills for ${skills.length} skill(s)\n\n`;
  }
}
