import * as path from 'node:path';
import { pathExists as pathExistsFn, readFile, ensureDir, writeFile } from '../../core/fs-utils.js';
import { BaseAdapter } from './base-adapter.js';
import type { InstallScope, SkillMeta, InstallResult } from '../../types/index.js';
import { createFileMarker, createSourceMarker, createRuleMarker, parseExistingFile } from '../marker-system.js';

export class CursorAdapter extends BaseAdapter {
  generateHeaderContent(skills: SkillMeta[]): string {
    return `# Cursor Rules\n\n> Generated by open-skills for ${skills.length} skill(s)\n\n`;
  }

  transformSkillContent(content: string): string {
    return content;
  }

  shouldGenerateIndex(): boolean {
    return false;
  }

  shouldCopySkillDirectory(): boolean {
    return false;
  }

  async generateOutput(
    scope: InstallScope,
    skills: SkillMeta[],
    skillContents: Map<string, string>
  ): Promise<InstallResult[]> {
    const targetPath = this.getTargetPath(scope);
    const results: InstallResult[] = [];

    let existingBlocks = await this.loadExistingBlocks(targetPath);
    const isManaged = existingBlocks.length > 0;

    const newBlocks = skills.map((skill) => {
      const content = skillContents.get(skill.name) || '';
      const lines = content.split('\n');
      const ruleBlocks = lines.map((line, idx) =>
        createRuleMarker({
          source: skill.name,
          id: `${skill.name}-line-${idx}`,
          priority: 'medium',
          content: line,
        })
      );

      return createSourceMarker({
        source: skill.name,
        count: lines.length,
        content: ruleBlocks.map((b) => b.raw).join('\n'),
      });
    });

    const header = this.generateHeaderContent(skills);
    const fileBlock = createFileMarker({
      editor: this.id,
      version: '2.0.0',
      content: header + newBlocks.map((b) => b.raw).join('\n'),
    });

    if (!isManaged) {
      const exists = await pathExistsFn(targetPath);
      if (exists) {
        results.push({
          skill: skills[0],
          success: false,
          message: `Refusing to overwrite unmanaged file: ${targetPath}. Please backup and remove it first.`,
          targetPath,
        });
        for (let i = 1; i < skills.length; i++) {
          results.push({
            skill: skills[i],
            success: false,
            message: 'Skipped due to unmanaged target file',
            targetPath,
          });
        }
        return results;
      }
    }

    const output = fileBlock.raw;
    await ensureDir(path.dirname(targetPath));
    await writeFile(targetPath, output, 'utf-8');

    for (const skill of skills) {
      results.push({
        skill,
        success: true,
        message: `Synced to ${targetPath}`,
        targetPath,
      });
    }

    return results;
  }

  private async loadExistingBlocks(targetPath: string) {
    if (!(await pathExistsFn(targetPath))) return [];
    const content = await readFile(targetPath, 'utf-8');
    return parseExistingFile(content);
  }
}
