#!/usr/bin/env python3
"""
FlowClaw Workflow Executor v1.1.3

HTTP service (Port 8765) that receives workflow execution requests from n8n,
runs YAML-defined workflows step-by-step with proper error handling,
and reports results back via Discord + Notion.

Architecture:
  n8n (Notion trigger) → HTTP POST /workflow/execute → this service
  Each workflow is a YAML file with ordered, composable steps.
  Steps share data via a flat variable store (_vars).

Platform Support:
  macOS ✅  Linux ✅  Windows ❌
  Requires Gunicorn (Unix/macOS only) and bash startup scripts.
  See README.md § Platform Support for details.

v1.0.0 (2026-03-29):
  - MONITORING: Prometheus /metrics endpoint with counters, histograms, gauges
  - LOGGING: Structured JSON logging (replaces basicConfig text format)
  - VALIDATION: JSON Schema validation on workflow YAML load
  - PARALLELISM: DAG-based parallel step execution via depends_on
  - DASHBOARD: /dashboard HTML page for operational visibility
"""

import concurrent.futures
import hmac
import json
import logging
import os
import re
import shutil
import sqlite3
import subprocess
import sys
import time
import uuid
from collections import deque
from contextlib import contextmanager
from datetime import datetime, timezone
from functools import wraps
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

import requests
import yaml
from flask import Flask, jsonify, request, Response

# ---------------------------------------------------------------------------
# Optional dependencies (Prometheus + jsonschema — graceful degradation)
# ---------------------------------------------------------------------------

try:
    from prometheus_client import (
        Counter, Histogram, Gauge,
        generate_latest, CONTENT_TYPE_LATEST,
        REGISTRY,
    )
    PROMETHEUS_AVAILABLE = True
except ImportError:
    PROMETHEUS_AVAILABLE = False

try:
    from jsonschema import validate as jsonschema_validate, ValidationError as JsonSchemaValidationError
    JSONSCHEMA_AVAILABLE = True
except ImportError:
    JSONSCHEMA_AVAILABLE = False

# ---------------------------------------------------------------------------
# Paths & Configuration
# ---------------------------------------------------------------------------

WORKSPACE = Path.home() / ".openclaw" / "workspace"
FLOWCLAW_DIR = WORKSPACE / "flowclaw"
WORKFLOWS_DIR = FLOWCLAW_DIR / "workflows"
LOGS_DIR = FLOWCLAW_DIR / "logs" / "workflow-runs"
DATA_DIR = FLOWCLAW_DIR / "data"
DB_PATH = DATA_DIR / "workflow-runs.db"
PENDING_APPROVALS_DIR = DATA_DIR / "pending-approvals"
OPENCLAW_CONFIG = Path.home() / ".openclaw" / "openclaw.json"
# Schema resolution: prefer the bundled schema in src/ (shipped with the repo),
# fall back to the runtime workflows dir for deployments that copy it there.
_SRC_SCHEMA_PATH = Path(__file__).parent / "workflow-schema.json"
_RUNTIME_SCHEMA_PATH = WORKFLOWS_DIR / "workflow-schema.json"
WORKFLOW_SCHEMA_PATH = _SRC_SCHEMA_PATH if _SRC_SCHEMA_PATH.exists() else _RUNTIME_SCHEMA_PATH

VERSION = "1.1.3"

# Request timeouts (seconds)
NOTION_TIMEOUT = 15
HTTP_TIMEOUT = 30

# Total attempts for transient failures and 429 rate limits
MAX_RETRIES = 3

# Discord enforces a 2000-char message limit
DISCORD_MAX_LEN = 2000

# Idempotency: consider a task_id "already processed" if run within this window
DEDUP_WINDOW_HOURS = 24

# C4: kept for pending-approval metadata
APPROVAL_TIMEOUT_DEFAULT = 3600  # 1 hour

# Valid workflow name: alphanumeric, hyphens, underscores (no path traversal)
_VALID_NAME_RE = re.compile(r"^[a-zA-Z0-9_-]{1,64}$")

# Detect unresolved {variable} placeholders after template resolution
_UNRESOLVED_RE = re.compile(r"\{[a-zA-Z_][a-zA-Z0-9_]*\}")

# Valid Notion page ID: 32 hex chars (UUID format, with or without hyphens)
_VALID_NOTION_ID_RE = re.compile(
    r"^[0-9a-f]{8}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{12}$",
    re.IGNORECASE,
)

# Valid run_id: timestamp + hex suffix generated by this service
_VALID_RUN_ID_RE = re.compile(r"^[0-9]{8}-[0-9]{6}-[0-9a-f]{6}$")

# Valid ISO 8601 date for Notion date fields
_VALID_ISO_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

# Allowlisted Notion status values accepted by this service
_VALID_NOTION_STATUSES: frozenset = frozenset({
    "Not Started", "In Progress", "Conception Review", "QA",
    "Staging Review", "Done", "Blocked", "Cancelled",
    "pending_approval",
})

# Maximum input lengths (bytes/chars) — defence against oversized payloads
_MAX_TASK_ID_LEN = 64
_MAX_RUN_ID_LEN = 32
_MAX_APPROVED_BY_LEN = 128
_MAX_NOTES_LEN = 1000
_MAX_TASK_TEXT_LEN = 50_000
_MAX_NAME_LEN = 512
_MAX_STATUS_LEN = 64

NOTION_VERSION = "2022-06-28"
NOTION_API = "https://api.notion.com/v1"
DISCORD_API = "https://discord.com/api/v10"

# Discord channel IDs — must be configured via environment variables.
# Set DISCORD_CHANNEL_PROJECT_UPDATES, DISCORD_CHANNEL_PROJECT_CALLS,
# DISCORD_CHANNEL_CHATTERIA in your .env file.
# Channels with empty string IDs are treated as disabled (notifications skipped).
# The allowlist in /notify/discord ONLY permits channels defined here.
def _build_discord_channels() -> Dict[str, str]:
    return {
        "project_updates": os.environ.get("DISCORD_CHANNEL_PROJECT_UPDATES", ""),
        "project_calls": os.environ.get("DISCORD_CHANNEL_PROJECT_CALLS", ""),
        "chatteria": os.environ.get("DISCORD_CHANNEL_CHATTERIA", ""),
    }

# ---------------------------------------------------------------------------
# Structured JSON Logging
# ---------------------------------------------------------------------------


class StructuredLogger:
    """JSON-structured logger — every record is a single JSON line to stderr."""

    def __init__(self, name: str) -> None:
        self.name = name

    def _log(self, level: str, msg: str, extra: Dict) -> None:
        record = {
            "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "level": level,
            "logger": self.name,
            "message": msg,
            **extra,
        }
        print(json.dumps(record, default=str), file=sys.stderr, flush=True)

    def info(self, msg: str, **kwargs) -> None:
        self._log("INFO", msg, kwargs)

    def warning(self, msg: str, **kwargs) -> None:
        self._log("WARNING", msg, kwargs)

    def error(self, msg: str, **kwargs) -> None:
        self._log("ERROR", msg, kwargs)

    def debug(self, msg: str, **kwargs) -> None:
        self._log("DEBUG", msg, kwargs)

    def exception(self, msg: str, **kwargs) -> None:
        import traceback
        kwargs["traceback"] = traceback.format_exc()
        self._log("ERROR", msg, kwargs)

    # --- Compatibility shims for old %-style format calls ---
    def _format_msg(self, msg: str, args) -> str:
        try:
            return msg % args if args else msg
        except Exception as exc:  # noqa: BLE001
            import sys
            print(f"WARNING: _format_msg failed: {exc}", file=sys.stderr)
            return f"{msg} {args}"

    def _compat(self, level: str, msg: str, *args, **kwargs) -> None:
        formatted = self._format_msg(msg, args)
        extra = {k: v for k, v in kwargs.items() if k not in ("exc_info", "stack_info")}
        self._log(level, formatted, extra)


# Root structured logger
log = StructuredLogger("executor")

# Suppress noisy Flask/Werkzeug text logs — we use structured output
logging.getLogger("werkzeug").setLevel(logging.ERROR)
logging.getLogger("gunicorn").setLevel(logging.WARNING)


# ---------------------------------------------------------------------------
# Prometheus Metrics (graceful degradation if not installed)
# ---------------------------------------------------------------------------

if PROMETHEUS_AVAILABLE:
    workflow_executions = Counter(
        "workflow_executions_total",
        "Total workflow executions",
        ["workflow_name", "status"],
    )
    workflow_duration = Histogram(
        "workflow_duration_seconds",
        "Workflow execution time in seconds",
        ["workflow_name"],
        buckets=(5, 15, 30, 60, 120, 300, 600, 1800, float("inf")),
    )
    workflow_step_duration = Histogram(
        "workflow_step_duration_seconds",
        "Individual step execution time in seconds",
        ["workflow_name", "step"],
        buckets=(0.1, 0.5, 1, 5, 15, 30, 60, 300, float("inf")),
    )
    workflow_errors = Counter(
        "workflow_errors_total",
        "Workflow errors by type",
        ["workflow_name", "error_type"],
    )
    active_workflows = Gauge(
        "active_workflows",
        "Number of currently running workflows",
    )
    schema_validation_failures = Counter(
        "workflow_schema_validation_failures_total",
        "Schema validation failures",
        ["workflow_name"],
    )
else:
    # No-op stubs so the rest of the code runs unchanged
    class _NoopMetric:
        def labels(self, **kw): return self
        def inc(self, *a, **kw): pass
        def dec(self, *a, **kw): pass
        def observe(self, *a, **kw): pass
        def set(self, *a, **kw): pass
        @contextmanager
        def time(self): yield

    workflow_executions = _NoopMetric()
    workflow_duration = _NoopMetric()
    workflow_step_duration = _NoopMetric()
    workflow_errors = _NoopMetric()
    active_workflows = _NoopMetric()
    schema_validation_failures = _NoopMetric()


# ---------------------------------------------------------------------------
# In-memory run history (for /dashboard — bounded ring buffer)
# ---------------------------------------------------------------------------

_RUN_HISTORY: deque = deque(maxlen=100)   # last 100 runs
_ACTIVE_RUNS: Dict[str, Dict] = {}        # run_id → metadata (currently running)
_ERROR_LOG: deque = deque(maxlen=50)      # last 50 errors


def _track_run_start(run_id: str, workflow_name: str) -> None:
    _ACTIVE_RUNS[run_id] = {
        "run_id": run_id,
        "workflow_name": workflow_name,
        "started_at": time.time(),
    }
    active_workflows.inc()


def _track_run_end(run_id: str, workflow_name: str, status: str, duration_s: float, error: Optional[str] = None) -> None:
    _ACTIVE_RUNS.pop(run_id, None)
    active_workflows.dec()
    record = {
        "run_id": run_id,
        "workflow_name": workflow_name,
        "status": status,
        "duration_s": round(duration_s, 2),
        "finished_at": time.time(),
        "error": error,
    }
    _RUN_HISTORY.append(record)
    if error:
        _ERROR_LOG.append({**record, "error": error})


# ---------------------------------------------------------------------------
# Env loading
# ---------------------------------------------------------------------------


def _load_env_from_openclaw() -> None:
    """Load API keys from openclaw.json env block — OPT-IN ONLY.

    Set FLOWCLAW_LOAD_OPENCLAW_CONFIG=true to enable.
    By default, FlowClaw only reads credentials from environment variables or .env files.
    """
    opt_in = os.environ.get("FLOWCLAW_LOAD_OPENCLAW_CONFIG", "").lower().strip()
    if opt_in != "true":
        return

    if not OPENCLAW_CONFIG.exists():
        return

    log.warning(
        "Loading credentials from openclaw.json — this is opt-in behavior. "
        "Set credentials via .env or environment variables for tighter isolation.",
        config_path=str(OPENCLAW_CONFIG),
    )

    try:
        config = json.loads(OPENCLAW_CONFIG.read_text())
        env_block = config.get("env", {})
        loaded_keys = []
        for key in [
            "NOTION_API_KEY", "DISCORD_BOT_TOKEN", "N8N_API_KEY",
            "OPENCLAW_GATEWAY_URL", "OPENCLAW_GATEWAY_TOKEN",
            "WORKFLOW_EXECUTOR_API_KEY",
        ]:
            if key not in os.environ and key in env_block:
                os.environ[key] = env_block[key]
                loaded_keys.append(key)
        if loaded_keys:
            log.info(
                "Loaded credentials from openclaw.json",
                keys=loaded_keys,
                count=len(loaded_keys),
            )
    except Exception as exc:
        log.warning("Failed to load env from openclaw.json", error=str(exc))


_load_env_from_openclaw()

NOTION_API_KEY = os.environ.get("NOTION_API_KEY", "")
DISCORD_BOT_TOKEN = os.environ.get("DISCORD_BOT_TOKEN", "")
OPENCLAW_GATEWAY_URL = os.environ.get("OPENCLAW_GATEWAY_URL", "")
OPENCLAW_GATEWAY_TOKEN = os.environ.get("OPENCLAW_GATEWAY_TOKEN", "")

if not OPENCLAW_GATEWAY_URL and os.environ.get("FLOWCLAW_LOAD_OPENCLAW_CONFIG", "").lower().strip() == "true":
    if OPENCLAW_CONFIG.exists():
        try:
            config = json.loads(OPENCLAW_CONFIG.read_text())
            gateway = config.get("gateway", {})
            if gateway.get("bind", "loopback") == "loopback":
                OPENCLAW_GATEWAY_URL = "http://127.0.0.1:18789"
            if not OPENCLAW_GATEWAY_TOKEN:
                OPENCLAW_GATEWAY_TOKEN = config.get("gateway", {}).get("auth", {}).get("token", "")
        except Exception as exc:  # noqa: BLE001
            import sys
            print(f"WARNING: Failed to load OpenClaw config: {exc}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Path safety helper
# ---------------------------------------------------------------------------


def _safe_path(base: Path, relative: str) -> Path:
    """Resolve *relative* under *base*, raising ValueError on path traversal."""
    resolved = (base / relative).resolve()
    try:
        resolved.relative_to(base.resolve())
    except ValueError:
        raise ValueError(f"Path traversal detected: {relative!r} must stay under {base}")
    return resolved


# ---------------------------------------------------------------------------
# SQLite — Idempotency + Approvals + Workflow State DB
# ---------------------------------------------------------------------------


@contextmanager
def _db():
    """Context manager for SQLite connections (thread-safe WAL mode)."""
    conn = sqlite3.connect(str(DB_PATH), check_same_thread=False)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    except Exception as exc:  # noqa: BLE001
        log.warning("Database transaction rolled back", error=str(exc))
        conn.rollback()
        raise
    finally:
        conn.close()


def _init_db() -> None:
    """Create SQLite schema if it doesn't exist."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    PENDING_APPROVALS_DIR.mkdir(parents=True, exist_ok=True)

    with _db() as conn:
        conn.executescript("""
            CREATE TABLE IF NOT EXISTS processed_tasks (
                task_id        TEXT PRIMARY KEY,
                run_id         TEXT NOT NULL,
                processed_at   INTEGER NOT NULL,
                workflow_name  TEXT NOT NULL,
                status         TEXT NOT NULL DEFAULT 'running'
            );

            CREATE TABLE IF NOT EXISTS approvals (
                run_id       TEXT PRIMARY KEY,
                approved_by  TEXT NOT NULL,
                approved_at  INTEGER NOT NULL,
                notes        TEXT
            );

            CREATE TABLE IF NOT EXISTS workflow_states (
                run_id        TEXT PRIMARY KEY,
                task_id       TEXT,
                workflow_name TEXT NOT NULL,
                vars_json     TEXT NOT NULL,
                resume_step   INTEGER NOT NULL DEFAULT 0,
                created_at    INTEGER NOT NULL,
                expires_at    INTEGER NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_processed_at
                ON processed_tasks (processed_at);

            CREATE INDEX IF NOT EXISTS idx_workflow_states_task
                ON workflow_states (task_id);
        """)

        try:
            conn.execute("ALTER TABLE processed_tasks ADD COLUMN status TEXT NOT NULL DEFAULT 'running'")
            conn.commit()
            log.info("DB migration: added 'status' column to processed_tasks")
        except sqlite3.OperationalError:
            pass

    log.info("DB initialized", path=str(DB_PATH))


def _record_task(task_id: str, run_id: str, workflow_name: str) -> bool:
    """Atomically record a new task. Returns True if recorded, False if duplicate."""
    try:
        with _db() as conn:
            cursor = conn.execute(
                "INSERT INTO processed_tasks (task_id, run_id, processed_at, workflow_name, status) "
                "VALUES (?, ?, ?, ?, 'running')",
                (task_id, run_id, int(time.time()), workflow_name),
            )
            conn.commit()
            return cursor.rowcount > 0
    except sqlite3.IntegrityError:
        return False


def _update_task_status(task_id: str, status: str) -> None:
    with _db() as conn:
        conn.execute("UPDATE processed_tasks SET status = ? WHERE task_id = ?", (status, task_id))


def _get_task_by_run_id(run_id: str) -> Optional[Dict]:
    with _db() as conn:
        row = conn.execute(
            "SELECT task_id, run_id, processed_at, workflow_name, status "
            "FROM processed_tasks WHERE run_id = ?",
            (run_id,),
        ).fetchone()
    return dict(row) if row else None


def _check_duplicate(task_id: str) -> Optional[Dict]:
    cutoff = int(time.time()) - DEDUP_WINDOW_HOURS * 3600
    with _db() as conn:
        row = conn.execute(
            "SELECT run_id, processed_at, workflow_name, status FROM processed_tasks "
            "WHERE task_id = ? AND processed_at > ?",
            (task_id, cutoff),
        ).fetchone()
    if row:
        return {
            "run_id": row["run_id"],
            "processed_at": row["processed_at"],
            "workflow_name": row["workflow_name"],
            "status": row["status"],
        }
    return None


def _record_approval(run_id: str, approved_by: str, notes: str = "") -> None:
    with _db() as conn:
        conn.execute(
            "INSERT OR REPLACE INTO approvals (run_id, approved_by, approved_at, notes) VALUES (?, ?, ?, ?)",
            (run_id, approved_by, int(time.time()), notes),
        )


def _check_approval(run_id: str) -> Optional[Dict]:
    with _db() as conn:
        row = conn.execute(
            "SELECT approved_by, approved_at, notes FROM approvals WHERE run_id = ?",
            (run_id,),
        ).fetchone()
    return dict(row) if row else None


def _get_task_history(task_id: str) -> List[Dict]:
    with _db() as conn:
        rows = conn.execute(
            "SELECT run_id, processed_at, workflow_name, status FROM processed_tasks "
            "WHERE task_id = ? ORDER BY processed_at DESC",
            (task_id,),
        ).fetchall()
    return [dict(r) for r in rows]


def _save_workflow_state(
    run_id: str, task_id: Optional[str], workflow_name: str,
    vars_dict: Dict, resume_step: int, timeout_s: int = APPROVAL_TIMEOUT_DEFAULT,
) -> None:
    with _db() as conn:
        conn.execute(
            "INSERT OR REPLACE INTO workflow_states "
            "(run_id, task_id, workflow_name, vars_json, resume_step, created_at, expires_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (run_id, task_id, workflow_name, json.dumps(vars_dict), resume_step,
             int(time.time()), int(time.time()) + timeout_s),
        )


def _load_workflow_state(run_id: str) -> Optional[Dict]:
    with _db() as conn:
        row = conn.execute(
            "SELECT run_id, task_id, workflow_name, vars_json, resume_step, created_at, expires_at "
            "FROM workflow_states WHERE run_id = ?",
            (run_id,),
        ).fetchone()
    if not row:
        return None
    return {
        "run_id": row["run_id"],
        "task_id": row["task_id"],
        "workflow_name": row["workflow_name"],
        "vars": json.loads(row["vars_json"]),
        "resume_step": row["resume_step"],
        "created_at": row["created_at"],
        "expires_at": row["expires_at"],
    }


def _delete_workflow_state(run_id: str) -> None:
    with _db() as conn:
        conn.execute("DELETE FROM workflow_states WHERE run_id = ?", (run_id,))


# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------


def require_auth(f):
    """Decorator: enforce Bearer or X-API-Key authentication."""
    @wraps(f)
    def decorated(*args, **kwargs):
        expected = os.environ.get("WORKFLOW_EXECUTOR_API_KEY")
        if not expected:
            log.error("WORKFLOW_EXECUTOR_API_KEY not set — rejecting request")
            return jsonify({"error": "service_misconfigured", "message": "Authentication not configured"}), 503

        auth_header = request.headers.get("Authorization", "")
        api_key_header = request.headers.get("X-API-Key", "")
        provided = api_key_header or auth_header.removeprefix("Bearer ").strip()

        if provided and hmac.compare_digest(provided, expected):
            return f(*args, **kwargs)

        log.warning("Unauthorized request", path=request.path, remote_addr=request.remote_addr)
        return jsonify({"error": "unauthorized"}), 401

    return decorated


# ---------------------------------------------------------------------------
# Notion Client
# ---------------------------------------------------------------------------


class NotionClient:
    def __init__(self, api_key: str) -> None:
        if not api_key:
            raise ValueError("NOTION_API_KEY environment variable is required")
        self._headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "Notion-Version": NOTION_VERSION,
        }

    def _request(self, method: str, path: str, **kwargs: Any) -> Dict:
        url = f"{NOTION_API}/{path}"
        last_error: Optional[Exception] = None

        for attempt in range(1, MAX_RETRIES + 1):
            try:
                r = requests.request(method, url, headers=self._headers, timeout=NOTION_TIMEOUT, **kwargs)
                if r.status_code == 429:
                    wait = min(float(r.headers.get("Retry-After", "1")), 60.0)
                    log.warning("Notion 429 rate limit", path=path, retry_after=wait, attempt=attempt)
                    time.sleep(wait)
                    continue
                r.raise_for_status()
                return r.json()
            except (requests.exceptions.Timeout, requests.exceptions.ConnectionError) as exc:
                last_error = exc
                if attempt < MAX_RETRIES:
                    time.sleep(0.5 * attempt)
                continue
            except requests.exceptions.HTTPError:
                log.error("Notion HTTP error", path=path, status=r.status_code)
                raise

        raise last_error or RuntimeError(f"Request to {path} failed after {MAX_RETRIES} attempts")

    def get_task(self, page_id: str) -> Dict:
        page = self._request("GET", f"pages/{page_id}")
        props = page.get("properties", {})

        def _title(p): return (p.get("title") or [{}])[0].get("text", {}).get("content", "")
        def _rich_text(p): return (p.get("rich_text") or [{}])[0].get("text", {}).get("content", "")
        def _select(p): s = p.get("select"); return s["name"] if s else None
        def _number(p): return p.get("number")
        def _checkbox(p): return p.get("checkbox", False)

        return {
            "id": page["id"], "url": page.get("url", ""),
            "name": _title(props.get("Name", {})),
            "type": _select(props.get("Type", {})),
            "status": _select(props.get("Status", {})),
            "phase": _select(props.get("Phase", {})),
            "budget_estimated": _number(props.get("Budget Estimated", {})),
            "pages_affected": _number(props.get("Pages Affected", {})),
            "gdpr_impact": _checkbox(props.get("GDPR Impact", {})),
            "pre_approved": _checkbox(props.get("Pre-Approved", {})),
            "assigned_to": _rich_text(props.get("Assigned To", {})),
            "description": _rich_text(props.get("Description", {})) if "Description" in props else "",
        }

    def get_page_raw(self, page_id: str) -> Dict:
        return self._request("GET", f"pages/{page_id}")

    def set_status(self, page_id: str, status: str) -> Dict:
        return self._request("PATCH", f"pages/{page_id}",
                             json={"properties": {"Status": {"select": {"name": status}}}})

    def set_health_check(self, page_id: str, result: str) -> Dict:
        return self._request("PATCH", f"pages/{page_id}",
                             json={"properties": {"Health Check": {"select": {"name": result}}}})


# ---------------------------------------------------------------------------
# Agent Selector
# ---------------------------------------------------------------------------


class AgentSelector:
    _ARCHITECT = {"concept", "requirements", "architecture", "planning", "design doc", "technical spec", "system design", "blueprint"}
    _DESIGNER = {"design", "ui design", "ux", "mockup", "wireframe", "prototype", "figma", "sketch", "visual"}
    _FRONTEND = {"frontend", "ui", "website", "landing", "hero", "css", "html", "styling", "tailwind", "react", "nextjs"}
    _BACKEND = {"backend", "api", "database", "server", "endpoint", "migration", "schema", "python", "flask", "django"}
    _QA = {"qa", "test", "testing", "quality", "validation", "verification", "bug", "regression"}
    _DEVOPS = {"deploy", "deployment", "devops", "infrastructure", "ci/cd", "pipeline", "docker", "kubernetes", "aws"}

    @classmethod
    def select(cls, description: str, tech_stack: Optional[List[str]] = None, phase: Optional[str] = None) -> Dict[str, str]:
        words = set(description.lower().split())
        if phase:
            phase_lower = phase.lower()
            if phase_lower in {"concept", "requirements", "architecture"}:
                return {"agentId": "backend", "runtime": "subagent", "reason": f"Phase: {phase}"}
            if phase_lower == "design":
                return {"agentId": "creative", "runtime": "subagent", "reason": f"Phase: {phase}"}
            if phase_lower == "qa":
                return {"agentId": "quality", "runtime": "subagent", "reason": f"Phase: {phase}"}
            if phase_lower == "deploy":
                return {"agentId": "devops", "runtime": "subagent", "reason": f"Phase: {phase}"}

        scores = {
            "architect": len(words & cls._ARCHITECT),
            "designer": len(words & cls._DESIGNER),
            "frontend": len(words & cls._FRONTEND),
            "backend": len(words & cls._BACKEND),
            "qa": len(words & cls._QA),
            "devops": len(words & cls._DEVOPS),
        }
        if tech_stack:
            stack = {s.lower() for s in tech_stack}
            if stack & {"typescript", "react", "nextjs", "tailwind"}:
                scores["frontend"] += 5
            if stack & {"python", "flask", "django", "fastapi"}:
                scores["backend"] += 5

        winner = max(scores, key=scores.get)
        mapping = {
            "architect": ("backend", "Architect keywords"),
            "designer": ("creative", "Designer keywords"),
            "qa": ("quality", "QA keywords"),
            "devops": ("devops", "DevOps keywords"),
            "frontend": ("frontend", "Frontend keywords"),
            "backend": ("backend", "Backend keywords"),
        }
        if scores[winner] > 0 and winner in mapping:
            agent_id, reason = mapping[winner]
            return {"agentId": agent_id, "runtime": "subagent", "reason": f"{reason} ({scores[winner]})"}

        return {"agentId": "frontend", "runtime": "subagent", "reason": "Default (frontend)"}


# ---------------------------------------------------------------------------
# Workflow Executor
# ---------------------------------------------------------------------------


class WorkflowExecutor:
    """Load and execute YAML workflows with proper step orchestration."""

    def __init__(self) -> None:
        self.notion = NotionClient(NOTION_API_KEY) if NOTION_API_KEY else None
        self.run_id = (
            datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S") + "-" + uuid.uuid4().hex[:6]
        )
        self.run_log: List[Dict] = []
        self._vars: Dict[str, str] = {}
        self._spawned_agents: Dict[str, Dict] = {}
        self._workflow_name: str = "unknown"

    # -- structured logging per run ----------------------------------------

    def _log(self, step: str, status: str, data: Any = None) -> None:
        entry: Dict[str, Any] = {
            "ts": datetime.now(timezone.utc).isoformat() + "Z",
            "run_id": self.run_id,
            "workflow": self._workflow_name,
            "step": step,
            "status": status,
        }
        if data is not None:
            entry["data"] = data
        self.run_log.append(entry)
        log.info("Step event", run_id=self.run_id, workflow=self._workflow_name,
                 step=step, status=status)

    # -- main entry --------------------------------------------------------

    def execute(self, workflow_name: str, context: Dict, resume_from_step: int = 0) -> Dict:
        """Execute all steps in order; stop on first failure."""
        self._workflow_name = workflow_name
        self._vars.update({k: str(v) for k, v in context.items() if v is not None})
        self._log("workflow", "started", {"context_keys": list(context.keys()), "resume_from": resume_from_step})

        _track_run_start(self.run_id, workflow_name)
        wf_start = time.time()

        try:
            wf = self._load(workflow_name)
        except (FileNotFoundError, ValueError, yaml.YAMLError) as exc:
            duration = time.time() - wf_start
            self._log("workflow", "load_failed", {"error": str(exc)})
            workflow_executions.labels(workflow_name=workflow_name, status="failed").inc()
            workflow_errors.labels(workflow_name=workflow_name, error_type="load_error").inc()
            _track_run_end(self.run_id, workflow_name, "failed", duration, error=str(exc))
            return self._result("failed", error=str(exc))

        steps = wf.get("steps", [])
        if not steps:
            self._log("workflow", "no_steps", {})
            workflow_executions.labels(workflow_name=workflow_name, status="failed").inc()
            _track_run_end(self.run_id, workflow_name, "failed", time.time() - wf_start, error="No steps")
            return self._result("failed", error="No steps defined in workflow")

        self._log("workflow", "loaded", {"steps": len(steps)})

        # Check for DAG mode (any step has depends_on)
        has_dag = any(
            (list(s.values())[0] or {}).get("depends_on") is not None
            for s in steps if isinstance(s, dict) and len(s) == 1
        )

        if has_dag and resume_from_step == 0:
            result = self._execute_dag(steps, workflow_name)
        else:
            result = self._execute_sequential(steps, workflow_name, resume_from_step)

        duration = time.time() - wf_start
        workflow_duration.labels(workflow_name=workflow_name).observe(duration)

        final_status = result.get("status", "failed")
        if final_status not in ("pending_approval",):
            metric_status = "success" if final_status == "success" else "failed"
            workflow_executions.labels(workflow_name=workflow_name, status=metric_status).inc()
            _track_run_end(self.run_id, workflow_name, final_status, duration,
                           error=result.get("error") if final_status != "success" else None)
        else:
            _track_run_end(self.run_id, workflow_name, "pending_approval", duration)

        return result

    def _execute_sequential(self, steps: List[Dict], workflow_name: str, resume_from_step: int = 0) -> Dict:
        """Classic sequential step execution (original behaviour)."""
        for step_idx, step_def in enumerate(steps):
            if step_idx < resume_from_step:
                self._log(f"step_{step_idx}", "skipped_resume", {})
                continue

            if not isinstance(step_def, dict) or len(step_def) != 1:
                log.warning("Invalid step definition", step_idx=step_idx, step=step_def)
                continue

            name, config = next(iter(step_def.items()))
            config = config or {}

            self._log(name, "started")
            step_start = time.time()
            result = self._run_step(name, config, step_idx=step_idx)
            step_dur = time.time() - step_start
            workflow_step_duration.labels(workflow_name=workflow_name, step=name).observe(step_dur)

            if result.get("status") == "pending_approval":
                self._log("workflow", "pending_approval", {"paused_at_step": step_idx})
                return self._result("pending_approval", run_id=self.run_id, paused_at_step=step_idx,
                                    message="Workflow paused — awaiting human approval.")

            if result.get("status") != "failed":
                for k, v in result.items():
                    if k != "status" and isinstance(v, (str, int, float, bool)):
                        self._vars[k] = str(v)

            self._log(name, "done", {"duration_s": round(step_dur, 2), "status": result.get("status")})

            if result.get("status") == "failed":
                self._log("workflow", "failed", {"failed_step": name, "error": result.get("error")})
                workflow_errors.labels(workflow_name=workflow_name, error_type="step_failed").inc()
                return self._result("failed", error=result.get("error", ""), failed_step=name)

        self._log("workflow", "completed")
        return self._result("success")

    def _execute_dag(self, steps: List[Dict], workflow_name: str) -> Dict:
        """Execute steps using a DAG (dependency graph) for parallel execution.

        Steps with no depends_on default to depending on the previous step
        (preserving existing sequential semantics). Steps that declare
        depends_on: [] run as soon as their explicit deps complete.

        Parallelism: up to 4 concurrent threads for independent steps.
        Note: OpenClaw agent *spawning* still happens serially (CLI limitation),
        but wait/IO-bound steps benefit from true parallelism.
        """
        # Build dependency map: step_name → set of step names it depends on
        step_names = []
        step_configs: Dict[str, Dict] = {}
        step_indices: Dict[str, int] = {}

        for idx, step_def in enumerate(steps):
            if not isinstance(step_def, dict) or len(step_def) != 1:
                continue
            name, config = next(iter(step_def.items()))
            config = config or {}
            step_names.append(name)
            step_configs[name] = config
            step_indices[name] = idx

        dag: Dict[str, Set[str]] = {}
        for i, name in enumerate(step_names):
            config = step_configs[name]
            if "depends_on" in config:
                deps = config["depends_on"]
                if deps is None:
                    deps = []
                dag[name] = set(deps)
            else:
                # Default: depend on previous step
                dag[name] = {step_names[i - 1]} if i > 0 else set()

        completed: Set[str] = set()
        results: Dict[str, Dict] = {}

        log.info("DAG execution mode", workflow=workflow_name, steps=len(step_names),
                 run_id=self.run_id)

        while len(completed) < len(step_names):
            # Find all steps ready to run
            ready = [
                n for n in step_names
                if n not in completed and dag[n].issubset(completed)
                and n not in results  # not already in-flight
            ]

            if not ready:
                remaining = [n for n in step_names if n not in completed]
                log.error("DAG deadlock", remaining=remaining, completed=list(completed))
                return self._result("failed", error=f"DAG deadlock — circular dependency among: {remaining}")

            if len(ready) == 1:
                # Run single step inline (no thread overhead)
                name = ready[0]
                config = self._resolve(step_configs[name])
                self._log(name, "started")
                step_start = time.time()
                result = self._run_step(name, config, step_idx=step_indices[name])
                step_dur = time.time() - step_start
                workflow_step_duration.labels(workflow_name=workflow_name, step=name).observe(step_dur)

                results[name] = result
                completed.add(name)

                if result.get("status") == "pending_approval":
                    self._log("workflow", "pending_approval", {"paused_at_step": step_indices[name]})
                    return self._result("pending_approval", run_id=self.run_id,
                                        paused_at_step=step_indices[name],
                                        message="Workflow paused — awaiting human approval.")

                if result.get("status") != "failed":
                    for k, v in result.items():
                        if k != "status" and isinstance(v, (str, int, float, bool)):
                            self._vars[k] = str(v)

                self._log(name, "done", {"duration_s": round(step_dur, 2)})

                if result.get("status") == "failed":
                    self._log("workflow", "failed", {"failed_step": name, "error": result.get("error")})
                    workflow_errors.labels(workflow_name=workflow_name, error_type="step_failed").inc()
                    return self._result("failed", error=result.get("error", ""), failed_step=name)

            else:
                # Multiple independent steps — run in parallel
                log.info("Parallel step batch", steps=ready, run_id=self.run_id)
                self._log("dag_parallel", "started", {"steps": ready})

                def _run_parallel_step(step_name: str) -> tuple:
                    cfg = self._resolve(step_configs[step_name])
                    self._log(step_name, "started")
                    t0 = time.time()
                    res = self._run_step(step_name, cfg, step_idx=step_indices[step_name])
                    dur = time.time() - t0
                    workflow_step_duration.labels(workflow_name=workflow_name, step=step_name).observe(dur)
                    self._log(step_name, "done", {"duration_s": round(dur, 2)})
                    return step_name, res, dur

                with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
                    futures = {executor.submit(_run_parallel_step, n): n for n in ready}
                    for future in concurrent.futures.as_completed(futures):
                        try:
                            step_name, result, dur = future.result()
                        except Exception as exc:
                            step_name = futures[future]
                            log.error("Parallel step exception", step=step_name, error=str(exc))
                            return self._result("failed", error=str(exc), failed_step=step_name)

                        results[step_name] = result
                        completed.add(step_name)

                        if result.get("status") != "failed":
                            for k, v in result.items():
                                if k != "status" and isinstance(v, (str, int, float, bool)):
                                    self._vars[k] = str(v)

                        if result.get("status") == "failed":
                            workflow_errors.labels(workflow_name=workflow_name, error_type="step_failed").inc()
                            return self._result("failed", error=result.get("error", ""), failed_step=step_name)

        self._log("workflow", "completed")
        return self._result("success")

    # -- helpers -----------------------------------------------------------

    def _result(self, status: str, **extra: Any) -> Dict:
        return {"status": status, "run_id": self.run_id, **extra, "log": self.run_log}

    @staticmethod
    def _load(name: str) -> Dict:
        """Load and validate workflow YAML against JSON schema."""
        if not _VALID_NAME_RE.match(name):
            raise ValueError(f"Invalid workflow name: {name!r} (alphanumeric, hyphens, underscores only)")

        path = WORKFLOWS_DIR / f"{name}.yaml"
        if not path.exists():
            raise FileNotFoundError(f"Workflow not found: {path}")

        try:
            data = yaml.safe_load(path.read_text())
        except yaml.YAMLError as exc:
            raise yaml.YAMLError(f"YAML parse error in {name}.yaml: {exc}") from exc

        if not isinstance(data, dict):
            raise ValueError(f"Workflow {name!r} is empty or not a YAML mapping")

        # Schema validation (if jsonschema available and schema file exists)
        if JSONSCHEMA_AVAILABLE and WORKFLOW_SCHEMA_PATH.exists():
            try:
                schema = json.loads(WORKFLOW_SCHEMA_PATH.read_text())
                jsonschema_validate(instance=data, schema=schema)
            except JsonSchemaValidationError as e:
                schema_validation_failures.labels(workflow_name=name).inc()
                log.error("Workflow schema validation failed",
                          workflow=name, error=e.message, path=str(list(e.absolute_path)))
                raise ValueError(f"Invalid workflow schema: {e.message}") from e
            except Exception as exc:
                log.warning("Schema validation skipped due to error", error=str(exc))
        elif not JSONSCHEMA_AVAILABLE:
            log.debug("jsonschema not installed — schema validation skipped")

        return data

    def _resolve(self, obj: Any) -> Any:
        if isinstance(obj, str):
            result = obj
            for key, val in self._vars.items():
                result = result.replace(f"{{{key}}}", str(val))
            unresolved = _UNRESOLVED_RE.findall(result)
            if unresolved:
                log.warning("Unresolved template variables", variables=unresolved, run_id=self.run_id)
            return result
        if isinstance(obj, dict):
            return {k: self._resolve(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [self._resolve(i) for i in obj]
        return obj

    def _run_step(self, name: str, config: Dict, step_idx: int = 0) -> Dict:
        config = self._resolve(config)
        handler = getattr(self, f"_step_{name}", None)

        if handler is None:
            return {"status": "failed", "error": f"Unknown step: {name!r}"}

        try:
            if name == "wait_approval":
                result = handler(config, step_idx=step_idx)
            else:
                result = handler(config)
            if not isinstance(result, dict):
                return {"status": "failed", "error": f"Step {name!r} returned invalid result type"}
            return result
        except Exception as exc:
            log.exception("Step raised exception", step=name, run_id=self.run_id, error=str(exc))
            return {"status": "failed", "error": str(exc)}

    # -----------------------------------------------------------------------
    # Step Implementations
    # -----------------------------------------------------------------------

    def _step_mock_task(self, cfg: Dict) -> Dict:
        name = cfg.get("taskName", "Test Task")
        self._vars["task_name"] = name
        return {"status": "success", "task_name": name}

    def _step_read_notion_task(self, cfg: Dict) -> Dict:
        task_id = cfg.get("taskId") or self._vars.get("taskId")
        if not task_id:
            return {"status": "failed", "error": "No taskId provided"}
        if not self.notion:
            return {"status": "failed", "error": "NOTION_API_KEY not configured"}

        try:
            task = self.notion.get_task(task_id)
        except Exception as exc:
            return {"status": "failed", "error": f"Failed to read Notion task: {exc}"}

        if not task.get("name"):
            return {"status": "failed", "error": "Task has no name in Notion"}

        self._vars["task_name"] = task["name"]
        self._vars["task_type"] = task["type"] or "Unknown"
        self._vars["description"] = task["description"]
        self._vars["notion_url"] = task["url"]
        if task.get("phase"):
            self._vars["phase"] = task["phase"]

        output = cfg.get("output")
        if output:
            try:
                out_path = _safe_path(FLOWCLAW_DIR, output)
                out_path.parent.mkdir(parents=True, exist_ok=True)
                briefing = (
                    f"# Task Briefing\n\n"
                    f"**Task:** {task['name']}\n**Type:** {task['type'] or '(no type)'}\n"
                    f"**Notion:** {task['url']}\n\n## Description\n\n{task['description'] or '(no description)'}\n\n"
                    f"## Instructions\n\n- Follow existing code style\n- Test changes locally before committing\n- Commit with a clear message\n"
                )
                out_path.write_text(briefing)
                self._vars["briefing_file"] = str(out_path)
            except Exception as exc:
                log.warning("Failed to write briefing", error=str(exc), run_id=self.run_id)

        return {"status": "success", "task_name": task["name"], "task_type": task["type"] or "Unknown"}

    def _step_create_briefing(self, cfg: Dict) -> Dict:
        output = cfg.get("output")
        content = cfg.get("content", "")
        if not output:
            return {"status": "failed", "error": "No output path specified"}
        try:
            out_path = _safe_path(FLOWCLAW_DIR, output)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content)
            self._vars["briefing_file"] = str(out_path)
            return {"status": "success", "briefing_file": str(out_path)}
        except ValueError as exc:
            return {"status": "failed", "error": f"Invalid output path: {exc}"}
        except Exception as exc:
            return {"status": "failed", "error": f"Failed to create briefing: {exc}"}

    def _step_select_agent(self, cfg: Dict) -> Dict:
        desc = cfg.get("task_description") or self._vars.get("description", "")
        stack = cfg.get("tech_stack")
        phase = cfg.get("phase") or self._vars.get("phase")
        if isinstance(stack, str):
            stack = [s.strip() for s in stack.split(",") if s.strip()]
        result = AgentSelector.select(desc, stack, phase)
        self._vars["agentId"] = result["agentId"]
        return {"status": "success", **result}

    def _step_spawn_agent(self, cfg: Dict) -> Dict:
        agent_id = cfg.get("agentId") or self._vars.get("agentId", "frontend")
        task_text = cfg.get("task", "")
        # Safe int coercion — YAML config may supply a float or string
        try:
            timeout_s = int(cfg.get("timeout", 600))
        except (TypeError, ValueError):
            timeout_s = 600

        if task_text.startswith("file:"):
            try:
                p = _safe_path(FLOWCLAW_DIR, task_text[5:])
                task_text = p.read_text() if p.exists() else task_text
            except ValueError as exc:
                return {"status": "failed", "error": f"Invalid task file path: {exc}"}

        if not isinstance(task_text, str):
            task_text = str(task_text)
        if not task_text.strip():
            return {"status": "failed", "error": "No task text provided"}
        if len(task_text) > _MAX_TASK_TEXT_LEN:
            return {"status": "failed", "error": f"Task text exceeds maximum length ({_MAX_TASK_TEXT_LEN} chars)"}

        openclaw_bin = shutil.which("openclaw")
        if not openclaw_bin:
            # Candidate paths for common Unix/macOS install locations.
            # Windows is not supported (see Platform Support in README).
            for candidate in [
                Path.home() / ".local/share/fnm/node-versions/v24.14.0/installation/bin/openclaw",
                Path("/usr/local/bin/openclaw"),
                Path("/opt/homebrew/bin/openclaw"),
            ]:
                if candidate.exists():
                    openclaw_bin = str(candidate)
                    break

        if not openclaw_bin:
            return {"status": "failed", "error": "openclaw CLI not found in PATH"}

        ALLOWED_AGENTS = {"frontend", "backend", "creative", "quality", "devops", "main"}
        if agent_id not in ALLOWED_AGENTS:
            return {"status": "failed", "error": f"Unknown agent: {agent_id!r}. Allowed: {sorted(ALLOWED_AGENTS)}"}

        session_id = f"wf-{self.run_id}-{agent_id}"
        cmd = [openclaw_bin, "agent", "--agent", agent_id, "--message", task_text,
               "--session-id", session_id, "--timeout", str(timeout_s), "--json"]

        log.info("Spawning agent", agent_id=agent_id, session_id=session_id,
                 task_preview=task_text[:100], run_id=self.run_id)

        try:
            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        except Exception as exc:
            return {"status": "failed", "error": f"Failed to launch openclaw agent: {exc}"}

        self._spawned_agents[session_id] = {
            "proc": proc, "agent_id": agent_id, "session_id": session_id,
            "started_at": time.time(), "timeout_s": timeout_s,
        }
        return {"status": "success", "session_id": session_id, "agent_id": agent_id}

    def _step_wait_completion(self, cfg: Dict) -> Dict:
        session_id = cfg.get("sessionId") or self._vars.get("session_id")
        store_as = cfg.get("store_as", "agent_result")

        if not session_id:
            return {"status": "failed", "error": "No session_id to wait for"}

        entry = self._spawned_agents.get(session_id)
        if not entry:
            return {"status": "failed", "error": f"No spawned agent found for session_id={session_id!r}"}

        proc: subprocess.Popen = entry["proc"]
        try:
            timeout_s = int(cfg.get("timeout", entry.get("timeout_s", 600)))
        except (TypeError, ValueError):
            timeout_s = 600
        remaining = max(1, timeout_s - (time.time() - entry["started_at"]))

        log.info("Waiting for agent", agent_id=entry["agent_id"], session_id=session_id,
                 timeout=remaining, run_id=self.run_id)

        try:
            stdout, stderr = proc.communicate(timeout=remaining)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.communicate()
            return {"status": "failed", "error": f"Agent timed out after {timeout_s}s", "session_id": session_id}
        except Exception as exc:
            return {"status": "failed", "error": f"Error waiting for agent: {exc}"}
        finally:
            self._spawned_agents.pop(session_id, None)

        wall_time = round(time.time() - entry["started_at"], 1)

        if proc.returncode != 0:
            err_snippet = (stderr or "")[:500].strip()
            log.error("Agent exited with error", agent_id=entry["agent_id"],
                      returncode=proc.returncode, run_id=self.run_id)
            return {"status": "failed", "error": f"Agent exited with code {proc.returncode}",
                    "stderr": err_snippet, "session_id": session_id, "wall_time_s": wall_time}

        try:
            result_json = json.loads(stdout)
        except json.JSONDecodeError:
            result_text = stdout.strip()
            self._vars[store_as] = result_text
            return {"status": "success", "session_id": session_id, "agent_id": entry["agent_id"],
                    store_as: result_text, "wall_time_s": wall_time, "raw": True}

        api_status = result_json.get("status", "")
        if api_status not in ("ok", "completed"):
            err = result_json.get("error") or result_json.get("summary") or f"status={api_status}"
            return {"status": "failed", "error": f"Agent returned error: {err}", "session_id": session_id}

        payloads = result_json.get("result", {}).get("payloads", [])
        reply_text = " ".join(p["text"] for p in payloads if isinstance(p, dict) and p.get("text")).strip()
        meta = result_json.get("result", {}).get("meta", {})
        agent_meta = meta.get("agentMeta", {})
        run_id_openclaw = result_json.get("runId", "")

        log.info("Agent completed", agent_id=entry["agent_id"], wall_time=wall_time,
                 run_id_openclaw=run_id_openclaw, run_id=self.run_id)

        self._vars[store_as] = reply_text
        return {
            "status": "success", "session_id": session_id, "agent_id": entry["agent_id"],
            store_as: reply_text, "wall_time_s": wall_time, "run_id_openclaw": run_id_openclaw,
            "model": agent_meta.get("model", ""),
            "tokens_total": agent_meta.get("usage", {}).get("total", 0),
            "aborted": meta.get("aborted", False),
        }

    def _step_wait_approval(self, cfg: Dict, step_idx: int = 0) -> Dict:
        """C4 FIX: Non-blocking two-phase approval gate."""
        run_id = self.run_id
        try:
            timeout_s = int(cfg.get("timeout", APPROVAL_TIMEOUT_DEFAULT))
        except (TypeError, ValueError):
            timeout_s = APPROVAL_TIMEOUT_DEFAULT
        channel_key = cfg.get("channel", "project_updates")
        if not isinstance(channel_key, str):
            channel_key = "project_updates"
        task_name = self._vars.get("task_name", "Unknown Task")
        task_id = self._vars.get("taskId") or self._vars.get("task_id")
        workflow_name = self._vars.get("_workflow_name", "unknown")

        default_msg = (
            f"🔔 **Approval Required**\n\nWorkflow run `{run_id}` is ready for deployment.\n"
            f"Task: **{task_name}**\n\n"
            f"To approve: `POST /workflow/approve` with `{{\"run_id\": \"{run_id}\", \"approved_by\": \"owner\"}}`\n"
            f"Timeout: {timeout_s // 60} minutes."
        )
        message = cfg.get("message", default_msg)
        self._step_notify_discord({"channel": channel_key, "message": message})

        pending_file = PENDING_APPROVALS_DIR / f"{run_id}.json"
        try:
            pending_file.write_text(json.dumps({
                "run_id": run_id, "task_name": task_name, "task_id": task_id,
                "workflow_name": workflow_name, "requested_at": int(time.time()),
                "timeout_at": int(time.time()) + timeout_s, "resume_step": step_idx + 1,
            }, indent=2))
        except Exception as exc:
            log.warning("Failed to write pending approval file", error=str(exc), run_id=run_id)

        try:
            _save_workflow_state(run_id=run_id, task_id=task_id, workflow_name=workflow_name,
                                 vars_dict=dict(self._vars), resume_step=step_idx + 1, timeout_s=timeout_s)
            log.info("Workflow state saved — awaiting approval", run_id=run_id, step_idx=step_idx)
        except Exception as exc:
            log.error("Failed to save workflow state", error=str(exc), run_id=run_id)

        if task_id:
            try:
                _update_task_status(task_id, "pending_approval")
            except Exception as exc:
                log.warning("Failed to update task status", error=str(exc), run_id=run_id)

        return {
            "status": "pending_approval", "run_id": run_id, "task_name": task_name,
            "paused_at_step": step_idx, "resume_step": step_idx + 1,
            "message": "Workflow paused — awaiting approval. POST /workflow/approve to continue.",
        }

    def _step_qa_check(self, cfg: Dict) -> Dict:
        script = cfg.get("script")
        url = cfg.get("stagingUrl") or self._vars.get("deploy_url")

        if not script:
            return {"status": "success", "qa_passed": "true", "note": "No QA script configured"}
        if not url:
            return {"status": "success", "qa_passed": "true", "note": "No staging URL (simulated deploy)"}

        # Enforce script must be a .py file — prevents execution of shell scripts or binaries
        if not isinstance(script, str) or not script.endswith(".py"):
            return {"status": "failed", "error": "QA script must be a .py file"}

        # Validate URL format to prevent argument injection into the script
        if not isinstance(url, str) or not (url.startswith("http://") or url.startswith("https://")):
            return {"status": "failed", "error": "stagingUrl must be an http:// or https:// URL"}

        try:
            script_path = _safe_path(FLOWCLAW_DIR, script)
        except ValueError as exc:
            return {"status": "failed", "error": f"Invalid script path: {exc}"}

        if not script_path.exists():
            return {"status": "failed", "error": f"QA script not found: {script_path}"}

        try:
            proc = subprocess.run(["python3", str(script_path), url],
                                  capture_output=True, text=True, timeout=60)
            try:
                qa = json.loads(proc.stdout)
            except json.JSONDecodeError:
                qa = {"passed": proc.returncode == 0, "raw": proc.stdout[:500]}
            passed = qa.get("passed", False)
            self._vars["qa_passed"] = "true" if passed else "false"
            return {"status": "success", "qa_passed": "true" if passed else "false", "detail": qa}
        except subprocess.TimeoutExpired:
            return {"status": "failed", "error": "QA script timed out (>60s)"}
        except Exception as exc:
            return {"status": "failed", "error": f"QA check failed: {exc}"}

    def _step_deploy(self, cfg: Dict) -> Dict:
        project = cfg.get("project") or self._vars.get("project_name")
        cwd = cfg.get("cwd")
        prod_raw = cfg.get("prod", True)

        # Safely coerce prod to bool — YAML may give "false" (string) or False (bool)
        if isinstance(prod_raw, bool):
            prod = prod_raw
        elif isinstance(prod_raw, str):
            prod = prod_raw.lower() not in ("false", "0", "no", "off")
        else:
            prod = bool(prod_raw)

        if not project:
            return {"status": "failed", "error": "No project specified for deploy"}

        # Validate project name to prevent path traversal via project name
        if not isinstance(project, str) or not _VALID_NAME_RE.match(project):
            return {"status": "failed", "error": "Invalid project name (alphanumeric, hyphens, underscores only)"}

        if cwd:
            try:
                work_dir = _safe_path(WORKSPACE, cwd)
            except ValueError as exc:
                return {"status": "failed", "error": f"Invalid cwd: {exc}"}
        else:
            try:
                work_dir = _safe_path(WORKSPACE, project)
            except ValueError as exc:
                return {"status": "failed", "error": f"Invalid project path: {exc}"}

        if not work_dir.exists():
            deploy_url = f"https://{project}"
            self._vars["deploy_url"] = deploy_url
            return {"status": "success", "deploy_url": deploy_url, "note": "Simulated (project dir not found)"}

        cmd = ["vercel"] + (["--prod"] if prod else []) + ["--yes"]
        try:
            proc = subprocess.run(cmd, cwd=work_dir, capture_output=True, text=True, timeout=300)
            if proc.returncode != 0:
                return {"status": "failed", "error": f"vercel exited {proc.returncode}", "stderr": proc.stderr[:500]}
            lines = [l.strip() for l in proc.stdout.strip().split("\n") if l.strip()]
            deploy_url = next((l for l in reversed(lines) if l.startswith("http")), f"https://{project}.vercel.app")
            self._vars["deploy_url"] = deploy_url
            return {"status": "success", "deploy_url": deploy_url}
        except subprocess.TimeoutExpired:
            return {"status": "failed", "error": "Deploy timed out (>300s)"}
        except FileNotFoundError:
            deploy_url = f"https://{project}"
            self._vars["deploy_url"] = deploy_url
            return {"status": "success", "deploy_url": deploy_url, "note": "Simulated (vercel CLI not installed)"}
        except Exception as exc:
            return {"status": "failed", "error": f"Deploy failed: {exc}"}

    def _step_update_notion(self, cfg: Dict) -> Dict:
        task_id = cfg.get("taskId") or self._vars.get("taskId")
        status = cfg.get("status", "Done")
        if not task_id:
            return {"status": "failed", "error": "No taskId for Notion update"}
        if not self.notion:
            return {"status": "failed", "error": "NOTION_API_KEY not configured"}
        try:
            self.notion.set_status(task_id, status)
            qa = self._vars.get("qa_passed")
            if qa:
                self.notion.set_health_check(task_id, "Passed" if qa == "true" else "Failed")
            return {"status": "success", "task_id": task_id, "new_status": status}
        except Exception as exc:
            return {"status": "failed", "error": f"Failed to update Notion: {exc}"}

    def _step_notify_discord(self, cfg: Dict) -> Dict:
        """Send message to Discord channel (best-effort)."""
        channel_key = cfg.get("channel", "project_updates")
        if not isinstance(channel_key, str):
            channel_key = "project_updates"
        message = cfg.get("message", "Workflow step completed.")
        if not isinstance(message, str):
            message = str(message)

        if len(message) > DISCORD_MAX_LEN:
            message = message[:DISCORD_MAX_LEN - 3] + "..."

        channels = _build_discord_channels()
        channel_id = channels.get(channel_key)
        if not channel_id:
            log.warning("Discord channel not configured or unknown key",
                        channel_key=channel_key, run_id=self.run_id)
            return {"status": "success", "skipped": True, "note": f"Channel not configured: {channel_key}"}

        if not DISCORD_BOT_TOKEN:
            return {"status": "success", "simulated": True, "note": "DISCORD_BOT_TOKEN not set"}

        try:
            r = requests.post(
                f"{DISCORD_API}/channels/{channel_id}/messages",
                headers={"Authorization": f"Bot {DISCORD_BOT_TOKEN}", "Content-Type": "application/json"},
                json={"content": message},
                timeout=HTTP_TIMEOUT,
            )
            r.raise_for_status()
            return {"status": "success", "channel": channel_key, "message_id": r.json().get("id", "")}
        except Exception as exc:
            log.warning("Discord notification failed (best-effort)", error=str(exc), run_id=self.run_id)
            return {"status": "success", "skipped": True, "note": f"Discord error (best-effort): {exc}"}


# ---------------------------------------------------------------------------
# Flask App
# ---------------------------------------------------------------------------

app = Flask(__name__)


@app.route("/health", methods=["GET"])
def health():
    wf_count = len(list(WORKFLOWS_DIR.glob("*.yaml"))) if WORKFLOWS_DIR.exists() else 0
    return jsonify({
        "status": "healthy",
        "version": VERSION,
        "workflows": wf_count,
        "auth": bool(os.environ.get("WORKFLOW_EXECUTOR_API_KEY")),
        "db": str(DB_PATH),
        "prometheus": PROMETHEUS_AVAILABLE,
        "jsonschema": JSONSCHEMA_AVAILABLE,
        "active_workflows": len(_ACTIVE_RUNS),
    })


@app.route("/metrics", methods=["GET"])
def metrics():
    """Prometheus metrics endpoint."""
    if not PROMETHEUS_AVAILABLE:
        return Response(
            "# prometheus_client not installed\n# pip install prometheus_client\n",
            status=503,
            content_type="text/plain",
        )
    return Response(generate_latest(), status=200, content_type=CONTENT_TYPE_LATEST)


@app.route("/dashboard", methods=["GET"])
def dashboard():
    """Operational health dashboard (single-file SPA)."""
    recent = list(reversed(list(_RUN_HISTORY)))[:20]
    active = list(_ACTIVE_RUNS.values())
    errors = list(reversed(list(_ERROR_LOG)))[:10]

    # Compute success rate from last 100
    last_100 = list(_RUN_HISTORY)
    success_count = sum(1 for r in last_100 if r["status"] == "success")
    success_rate = round(success_count / max(len(last_100), 1) * 100, 1)

    # Avg duration by workflow
    by_wf: Dict[str, List[float]] = {}
    for r in last_100:
        by_wf.setdefault(r["workflow_name"], []).append(r["duration_s"])
    avg_durations = {wf: round(sum(durs) / len(durs), 1) for wf, durs in by_wf.items()}

    def _row_class(status):
        return {"success": "success", "failed": "danger", "pending_approval": "warning"}.get(status, "secondary")

    def _fmt_ts(ts):
        return datetime.fromtimestamp(ts).strftime("%H:%M:%S") if ts else "—"

    def _fmt_dur(s):
        return f"{s:.1f}s" if s < 60 else f"{s/60:.1f}m"

    recent_rows = "\n".join(
        f'<tr class="table-{_row_class(r["status"])}"><td>{_fmt_ts(r["finished_at"])}</td>'
        f'<td><code>{r["run_id"][-12:]}</code></td>'
        f'<td>{r["workflow_name"]}</td>'
        f'<td><span class="badge bg-{_row_class(r["status"])}">{r["status"]}</span></td>'
        f'<td>{_fmt_dur(r["duration_s"])}</td>'
        f'<td>{(r.get("error") or "")[:60]}</td></tr>'
        for r in recent
    )

    active_rows = "\n".join(
        f'<tr><td>{_fmt_ts(r["started_at"])}</td>'
        f'<td><code>{r["run_id"][-12:]}</code></td>'
        f'<td>{r["workflow_name"]}</td>'
        f'<td>{_fmt_dur(time.time() - r["started_at"])}</td></tr>'
        for r in active
    )

    avg_rows = "\n".join(
        f"<tr><td>{wf}</td><td>{_fmt_dur(avg)}</td></tr>"
        for wf, avg in sorted(avg_durations.items())
    )

    error_rows = "\n".join(
        f'<tr><td>{_fmt_ts(e["finished_at"])}</td>'
        f'<td>{e["workflow_name"]}</td>'
        f'<td class="text-danger">{(e.get("error") or "")[:100]}</td></tr>'
        for e in errors
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Workflow Executor Dashboard — v{VERSION}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
<meta http-equiv="refresh" content="30">
<style>
  body {{ background: #0d1117; color: #e6edf3; }}
  .card {{ background: #161b22; border-color: #30363d; }}
  .card-header {{ border-color: #30363d; }}
  table {{ font-size: 0.875rem; }}
  .badge {{ font-size: 0.75rem; }}
</style>
</head>
<body>
<div class="container-fluid py-4">
  <h1 class="mb-4">🦊 Workflow Executor <small class="text-muted fs-6">v{VERSION}</small>
    <span class="badge bg-{'success' if not active else 'warning'} ms-2 fs-6">
      {'Idle' if not active else f'{len(active)} Active'}
    </span>
  </h1>

  <!-- Stats row -->
  <div class="row g-3 mb-4">
    <div class="col-sm-3">
      <div class="card text-center">
        <div class="card-body">
          <div class="fs-2 fw-bold text-info">{len(active)}</div>
          <div class="text-muted">Active Workflows</div>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="card text-center">
        <div class="card-body">
          <div class="fs-2 fw-bold {'text-success' if success_rate >= 80 else 'text-warning'}">{success_rate}%</div>
          <div class="text-muted">Success Rate (last {len(last_100)})</div>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="card text-center">
        <div class="card-body">
          <div class="fs-2 fw-bold">{len(last_100)}</div>
          <div class="text-muted">Total Runs (memory)</div>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="card text-center">
        <div class="card-body">
          <div class="fs-2 fw-bold text-{'danger' if errors else 'success'}">{len(errors)}</div>
          <div class="text-muted">Recent Errors</div>
        </div>
      </div>
    </div>
  </div>

  <!-- Active workflows -->
  <div class="card mb-4">
    <div class="card-header"><strong>⚡ Active Workflows ({len(active)})</strong></div>
    <div class="card-body p-0">
      <table class="table table-dark table-striped mb-0">
        <thead><tr><th>Started</th><th>Run ID</th><th>Workflow</th><th>Elapsed</th></tr></thead>
        <tbody>{'<tr><td colspan="4" class="text-center text-muted py-3">No active workflows</td></tr>' if not active else active_rows}</tbody>
      </table>
    </div>
  </div>

  <!-- Recent runs -->
  <div class="card mb-4">
    <div class="card-header"><strong>📋 Recent Runs (last 20)</strong></div>
    <div class="card-body p-0">
      <table class="table table-dark table-striped mb-0">
        <thead><tr><th>Finished</th><th>Run ID</th><th>Workflow</th><th>Status</th><th>Duration</th><th>Error</th></tr></thead>
        <tbody>{'<tr><td colspan="6" class="text-center text-muted py-3">No runs yet</td></tr>' if not recent else recent_rows}</tbody>
      </table>
    </div>
  </div>

  <div class="row g-3">
    <!-- Avg duration -->
    <div class="col-md-6">
      <div class="card">
        <div class="card-header"><strong>⏱ Avg Duration by Workflow</strong></div>
        <div class="card-body p-0">
          <table class="table table-dark table-striped mb-0">
            <thead><tr><th>Workflow</th><th>Avg</th></tr></thead>
            <tbody>{'<tr><td colspan="2" class="text-center text-muted py-3">No data yet</td></tr>' if not avg_rows else avg_rows}</tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Error log -->
    <div class="col-md-6">
      <div class="card">
        <div class="card-header"><strong>🔴 Error Log (last 10)</strong></div>
        <div class="card-body p-0">
          <table class="table table-dark table-striped mb-0">
            <thead><tr><th>Time</th><th>Workflow</th><th>Error</th></tr></thead>
            <tbody>{'<tr><td colspan="3" class="text-center text-muted py-3">No errors 🎉</td></tr>' if not errors else error_rows}</tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="text-muted text-center mt-4 small">Auto-refresh every 30s · Prometheus: {'✅' if PROMETHEUS_AVAILABLE else '❌ (pip install prometheus_client)'} · Schema validation: {'✅' if JSONSCHEMA_AVAILABLE else '❌ (pip install jsonschema)'}</div>
</div>
</body>
</html>"""
    return Response(html, content_type="text/html")


@app.route("/workflow/execute", methods=["POST"])
@require_auth
def execute():
    if not request.is_json:
        return jsonify({"status": "error", "error": "Content-Type must be application/json"}), 415
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({"status": "error", "error": "Request body must be a JSON object"}), 400

    wf_name = data.get("workflowName", "")
    if not isinstance(wf_name, str):
        return jsonify({"status": "error", "error": "workflowName must be a string"}), 400
    wf_name = wf_name.strip()

    context = data.get("context", {})
    if not isinstance(context, dict):
        return jsonify({"status": "error", "error": "context must be a JSON object"}), 400

    if "task_id" in data and "taskId" not in context:
        context["taskId"] = data["task_id"]
    if "taskId" in data and "taskId" not in context:
        context["taskId"] = data["taskId"]

    if not wf_name:
        return jsonify({"status": "error", "error": "Missing workflowName"}), 400
    if not _VALID_NAME_RE.match(wf_name):
        return jsonify({"status": "error", "error": "Invalid workflowName format (alphanumeric, hyphens, underscores, 1-64 chars)"}), 400

    task_id = context.get("taskId") or data.get("task_id")
    if task_id is not None:
        if not isinstance(task_id, str):
            return jsonify({"status": "error", "error": "taskId must be a string"}), 400
        task_id = task_id.strip()
        if len(task_id) > _MAX_TASK_ID_LEN:
            return jsonify({"status": "error", "error": f"taskId too long (max {_MAX_TASK_ID_LEN} chars)"}), 400
        if not task_id:
            task_id = None

    if task_id:
        run_id = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S") + "-" + uuid.uuid4().hex[:6]
        recorded = _record_task(task_id, run_id, wf_name)
        if not recorded:
            existing = _check_duplicate(task_id)
            if existing:
                log.info("Duplicate task rejected", task_id=task_id, original_run_id=existing["run_id"])
                return jsonify({
                    "status": "duplicate",
                    "task_id": task_id,
                    "original_run_id": existing["run_id"],
                    "original_workflow": existing["workflow_name"],
                    "original_status": existing.get("status", "unknown"),
                    "processed_at": existing["processed_at"],
                    "message": "Task already processed within 24h. Use /workflow/history to query.",
                }), 200
            else:
                log.warning("IntegrityError but no recent record — allowing through", task_id=task_id)
    else:
        run_id = None

    executor = WorkflowExecutor()
    if run_id:
        executor.run_id = run_id

    context["_workflow_name"] = wf_name
    result = executor.execute(wf_name, context)

    if task_id:
        final_status = result.get("status", "failed")
        if final_status not in ("pending_approval",):
            db_status = "completed" if final_status == "success" else "failed"
            try:
                _update_task_status(task_id, db_status)
            except Exception as exc:
                log.warning("Failed to update task status", error=str(exc))

    try:
        LOGS_DIR.mkdir(parents=True, exist_ok=True)
        log_file = LOGS_DIR / f"{executor.run_id}-{wf_name}.json"
        log_file.write_text(json.dumps(result, indent=2, default=str))
    except Exception as exc:
        log.warning("Failed to write log file", error=str(exc))

    result_status = result.get("status")
    status_code = 200 if result_status == "success" else (202 if result_status == "pending_approval" else 500)
    return jsonify(result), status_code


@app.route("/workflow/approve", methods=["POST"])
@require_auth
def approve_workflow():
    """Approve a pending workflow run and trigger resumption."""
    if not request.is_json:
        return jsonify({"status": "error", "error": "Content-Type must be application/json"}), 415
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({"status": "error", "error": "Request body must be a JSON object"}), 400

    run_id = data.get("run_id", "")
    approved_by = data.get("approved_by", "")

    if not isinstance(run_id, str):
        return jsonify({"status": "error", "error": "run_id must be a string"}), 400
    if not isinstance(approved_by, str):
        return jsonify({"status": "error", "error": "approved_by must be a string"}), 400

    run_id = run_id.strip()
    approved_by = approved_by.strip()

    if not run_id:
        return jsonify({"status": "error", "error": "Missing run_id"}), 400
    if not _VALID_RUN_ID_RE.match(run_id):
        return jsonify({"status": "error", "error": "Invalid run_id format"}), 400
    if not approved_by:
        return jsonify({"status": "error", "error": "Missing approved_by"}), 400
    if len(approved_by) > _MAX_APPROVED_BY_LEN:
        return jsonify({"status": "error", "error": f"approved_by too long (max {_MAX_APPROVED_BY_LEN} chars)"}), 400

    notes = data.get("notes", "")
    if not isinstance(notes, str):
        notes = ""
    notes = notes[:_MAX_NOTES_LEN]  # Truncate silently — it's a non-critical annotation

    try:
        _record_approval(run_id, approved_by, notes)
    except Exception as exc:
        return jsonify({"status": "error", "error": f"DB error: {exc}"}), 500

    log.info("Workflow approved", run_id=run_id, approved_by=approved_by)

    pending_file = PENDING_APPROVALS_DIR / f"{run_id}.json"
    try:
        pending_file.unlink(missing_ok=True)
    except Exception as exc:  # noqa: BLE001
        log.warning("Failed to remove pending approval file", path=str(pending_file), error=str(exc))

    resume_result = _resume_workflow(run_id, approved_by)
    return jsonify({
        "status": "success", "run_id": run_id, "approved_by": approved_by,
        "approved_at": int(time.time()), "resume_result": resume_result,
    })


@app.route("/workflow/resume", methods=["POST"])
@require_auth
def resume_workflow_endpoint():
    """Resume a paused workflow by run_id."""
    if not request.is_json:
        return jsonify({"status": "error", "error": "Content-Type must be application/json"}), 415
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({"status": "error", "error": "Request body must be a JSON object"}), 400

    run_id = data.get("run_id", "")
    approved_by = data.get("approved_by", "system")

    if not isinstance(run_id, str):
        return jsonify({"status": "error", "error": "run_id must be a string"}), 400
    if not isinstance(approved_by, str):
        approved_by = "system"

    run_id = run_id.strip()
    approved_by = approved_by.strip() or "system"

    if not run_id:
        return jsonify({"status": "error", "error": "Missing run_id"}), 400
    if not _VALID_RUN_ID_RE.match(run_id):
        return jsonify({"status": "error", "error": "Invalid run_id format"}), 400
    if len(approved_by) > _MAX_APPROVED_BY_LEN:
        approved_by = approved_by[:_MAX_APPROVED_BY_LEN]

    result = _resume_workflow(run_id, approved_by)
    return jsonify(result), (200 if result.get("status") == "success" else 400)


def _resume_workflow(run_id: str, approved_by: str) -> Dict:
    """Internal: load saved workflow state and continue execution from saved step."""
    state = _load_workflow_state(run_id)
    if not state:
        log.warning("No saved state for resume", run_id=run_id)
        return {"status": "error", "error": f"No saved state found for run_id={run_id}."}

    if int(time.time()) > state["expires_at"]:
        _delete_workflow_state(run_id)
        return {"status": "error", "error": f"Workflow state for run_id={run_id} has expired."}

    workflow_name = state["workflow_name"]
    resume_step = state["resume_step"]
    saved_vars = state["vars"]
    task_id = state.get("task_id")

    log.info("Resuming workflow", workflow=workflow_name, run_id=run_id,
             resume_step=resume_step, approved_by=approved_by)

    executor = WorkflowExecutor()
    executor.run_id = run_id
    executor._vars = dict(saved_vars)
    executor._vars["approved_by"] = approved_by
    _delete_workflow_state(run_id)

    result = executor.execute(workflow_name, {}, resume_from_step=resume_step)

    if task_id:
        final_status = result.get("status", "failed")
        if final_status not in ("pending_approval",):
            db_status = "completed" if final_status == "success" else "failed"
            try:
                _update_task_status(task_id, db_status)
            except Exception as exc:
                log.warning("Failed to update task status after resume", error=str(exc))

    try:
        LOGS_DIR.mkdir(parents=True, exist_ok=True)
        (LOGS_DIR / f"{run_id}-{workflow_name}-resumed.json").write_text(
            json.dumps(result, indent=2, default=str)
        )
    except Exception as exc:
        log.warning("Failed to write resumed log file", error=str(exc))

    return result


@app.route("/workflow/history", methods=["GET"])
@require_auth
def workflow_history():
    task_id = request.args.get("task_id", "").strip()
    if not task_id:
        return jsonify({"status": "error", "error": "Missing task_id query parameter"}), 400
    if len(task_id) > _MAX_TASK_ID_LEN:
        return jsonify({"status": "error", "error": f"task_id too long (max {_MAX_TASK_ID_LEN} chars)"}), 400
    try:
        runs = _get_task_history(task_id)
    except Exception as exc:
        return jsonify({"status": "error", "error": f"DB error: {exc}"}), 500
    return jsonify({"task_id": task_id, "runs": runs, "count": len(runs)})


@app.route("/workflow/pending-approvals", methods=["GET"])
@require_auth
def pending_approvals():
    pending = []
    try:
        for f in sorted(PENDING_APPROVALS_DIR.glob("*.json")):
            try:
                pending.append(json.loads(f.read_text()))
            except Exception as exc:  # noqa: BLE001
                log.warning("Failed to parse pending approval file", path=str(f), error=str(exc))
                pending.append({"run_id": f.stem, "error": "parse error"})
    except Exception as exc:
        return jsonify({"status": "error", "error": str(exc)}), 500
    return jsonify({"pending": pending, "count": len(pending)})


@app.route("/notify/discord", methods=["POST"])
@require_auth
def notify_discord():
    """Send a Discord message with channel allowlist enforcement."""
    if not request.is_json:
        return jsonify({"status": "error", "error": "Content-Type must be application/json"}), 415
    data = request.get_json(silent=True) or {}
    if not isinstance(data, dict):
        return jsonify({"status": "error", "error": "Request body must be a JSON object"}), 400

    channel_key = data.get("channel")
    channel_id = data.get("channelId")
    message = data.get("message", "")

    if not isinstance(message, str) or not message.strip():
        return jsonify({"status": "error", "error": "Missing or empty message"}), 400

    if len(message) > DISCORD_MAX_LEN:
        message = message[:DISCORD_MAX_LEN - 3] + "..."

    channels = _build_discord_channels()
    # Allowlist: only non-empty channel IDs that are configured
    allowed_ids = {v for v in channels.values() if v}

    if channel_id:
        if not isinstance(channel_id, str):
            return jsonify({"status": "error", "error": "channelId must be a string"}), 400
        if channel_id not in allowed_ids:
            log.warning("Rejected unauthorized Discord channel", channel_id=channel_id,
                        remote_addr=request.remote_addr)
            return jsonify({"error": "unauthorized_channel",
                            "message": "Channel ID not in allowlist."}), 403
    elif channel_key:
        if not isinstance(channel_key, str):
            return jsonify({"status": "error", "error": "channel must be a string"}), 400
        channel_id = channels.get(channel_key)
        if not channel_id:
            known = [k for k, v in channels.items() if v]
            return jsonify({"status": "error",
                            "error": f"Unknown or unconfigured channel: {channel_key!r}. Configured: {known}"}), 400
    else:
        return jsonify({"status": "error", "error": "Missing channel or channelId"}), 400

    if not DISCORD_BOT_TOKEN:
        return jsonify({"status": "error", "error": "DISCORD_BOT_TOKEN not configured"}), 500

    if len(message) > DISCORD_MAX_LEN:
        message = message[:DISCORD_MAX_LEN - 3] + "..."

    try:
        r = requests.post(
            f"{DISCORD_API}/channels/{channel_id}/messages",
            headers={"Authorization": f"Bot {DISCORD_BOT_TOKEN}", "Content-Type": "application/json"},
            json={"content": message},
            timeout=HTTP_TIMEOUT,
        )
        r.raise_for_status()
        return jsonify({"status": "success", "message_id": r.json().get("id", "")})
    except Exception as exc:
        return jsonify({"status": "error", "error": str(exc)}), 500


@app.route("/notion/update", methods=["POST"])
@require_auth
def notion_update():
    if not request.is_json:
        return jsonify({"status": "error", "error": "Content-Type must be application/json"}), 415
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({"status": "error", "error": "Request body must be a JSON object"}), 400

    page_id = data.get("pageId", "")
    status = data.get("status", "Done")

    if not isinstance(page_id, str) or not page_id.strip():
        return jsonify({"status": "error", "error": "Missing or invalid pageId"}), 400
    page_id = page_id.strip()
    if not _VALID_NOTION_ID_RE.match(page_id):
        return jsonify({"status": "error", "error": "pageId must be a valid Notion UUID"}), 400

    if not isinstance(status, str):
        return jsonify({"status": "error", "error": "status must be a string"}), 400
    status = status.strip()
    if status not in _VALID_NOTION_STATUSES:
        return jsonify({
            "status": "error",
            "error": f"Invalid status value. Allowed: {sorted(_VALID_NOTION_STATUSES)}",
        }), 400

    executor = WorkflowExecutor()
    if not executor.notion:
        return jsonify({"status": "error", "error": "NOTION_API_KEY not configured"}), 500
    try:
        executor.notion.set_status(page_id, status)
        return jsonify({"status": "success", "pageId": page_id, "newStatus": status})
    except Exception as exc:
        return jsonify({"status": "error", "error": str(exc)}), 500


@app.route("/notion/create-subtask", methods=["POST"])
@require_auth
def notion_create_subtask():
    if not request.is_json:
        return jsonify({"status": "error", "error": "Content-Type must be application/json"}), 415
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({"status": "error", "error": "Request body must be a JSON object"}), 400

    name = data.get("name", "")
    if not isinstance(name, str):
        return jsonify({"status": "error", "error": "name must be a string"}), 400
    name = name.strip()
    if not name:
        return jsonify({"status": "skipped", "reason": "empty name"}), 200
    if len(name) > _MAX_NAME_LEN:
        return jsonify({"status": "error", "error": f"name too long (max {_MAX_NAME_LEN} chars)"}), 400

    executor = WorkflowExecutor()
    if not executor.notion:
        return jsonify({"status": "error", "error": "NOTION_API_KEY not configured"}), 500

    phase_map = {
        "Requirements": "P1", "Conception": "P2", "Development": "P3",
        "QA": "P4", "Staging": "P5", "Deploy": "P6",
        "Concept": "P2", "Architecture Review": "P2", "Design": "P2",
        "Frontend": "P3", "Backend": "P3",
    }
    role_map = {
        "frontend": ["Dev"], "backend": ["Dev"], "creative": ["Design"],
        "quality": ["QA"], "devops": ["Ops"], "product": ["PM"],
        "legal": ["Legal"], "finance": ["Finance"], "growth": ["Strategy"], "main": ["PM"],
    }
    # Allowlisted assigned_to values — only known agent IDs are accepted
    allowed_assigned_to = set(role_map.keys()) | {""}

    assigned_to = data.get("assignedTo", "")
    if not isinstance(assigned_to, str):
        assigned_to = ""
    assigned_to = assigned_to.strip()
    if assigned_to and assigned_to not in allowed_assigned_to:
        return jsonify({"status": "error",
                        "error": f"Invalid assignedTo value. Allowed: {sorted(allowed_assigned_to - {''})}"}), 400

    properties = {
        "Name": {"title": [{"text": {"content": name}}]},
        "Status": {"select": {"name": "Not Started"}},
        "Assigned To": {"rich_text": [{"text": {"content": assigned_to or "Unassigned"}}]},
    }

    roles = role_map.get(assigned_to, [])
    if roles:
        properties["Role"] = {"multi_select": [{"name": r} for r in roles]}

    phase_raw = data.get("phase", "")
    if not isinstance(phase_raw, str):
        phase_raw = ""
    phase = phase_map.get(phase_raw.strip())
    if phase:
        properties["Phase"] = {"select": {"name": phase}}

    due_date = data.get("dueDate")
    if due_date is not None:
        if not isinstance(due_date, str) or not _VALID_ISO_DATE_RE.match(due_date.strip()):
            return jsonify({"status": "error", "error": "dueDate must be a valid ISO 8601 date (YYYY-MM-DD)"}), 400
        properties["Due Date"] = {"date": {"start": due_date.strip()}}

    if data.get("isFastlane"):
        properties["Type"] = {"select": {"name": "Fastlane"}}
        properties["Pre-Approved"] = {"checkbox": True}

    db_id = os.environ.get("NOTION_TASKS_DATABASE_ID", "").strip()
    if not db_id:
        return jsonify({
            "status": "error",
            "error": "NOTION_TASKS_DATABASE_ID environment variable is not configured",
        }), 500
    if not _VALID_NOTION_ID_RE.match(db_id):
        return jsonify({
            "status": "error",
            "error": "NOTION_TASKS_DATABASE_ID is not a valid Notion UUID",
        }), 500

    try:
        result = executor.notion._request("POST", "pages",
                                          json={"parent": {"database_id": db_id}, "properties": properties})
        return jsonify({"status": "success", "pageId": result["id"], "url": result.get("url", "")})
    except Exception as exc:
        return jsonify({"status": "error", "error": str(exc)}), 500


@app.route("/workflows/list", methods=["GET"])
@require_auth
def list_workflows():
    workflows = [f.stem for f in WORKFLOWS_DIR.glob("*.yaml")]
    return jsonify({"workflows": sorted(workflows), "count": len(workflows)})


# ---------------------------------------------------------------------------
# Startup & Entry Points
# ---------------------------------------------------------------------------

def _on_startup() -> None:
    """Called once per gunicorn worker on startup."""
    log.info("Workflow Executor worker started", version=VERSION, pid=os.getpid())
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    PENDING_APPROVALS_DIR.mkdir(parents=True, exist_ok=True)
    _init_db()

    if not PROMETHEUS_AVAILABLE:
        log.warning("prometheus_client not installed — /metrics will return 503. Run: pip install prometheus_client")
    if not JSONSCHEMA_AVAILABLE:
        log.warning("jsonschema not installed — schema validation disabled. Run: pip install jsonschema")


def main() -> None:
    """Dev-mode Flask runner with threading."""
    log.info("Starting Workflow Executor (dev mode)", version=VERSION)
    _on_startup()
    app.run(host="127.0.0.1", port=8765, debug=False, threaded=True)


if __name__ == "__main__":
    main()
else:
    # Gunicorn imports this module directly (not via __main__).
    # _on_startup() is NOT called inside main() for gunicorn — call it here.
    # When running via `python3 workflow-executor.py`, main() calls _on_startup() instead.
    _on_startup()
