#!/usr/bin/env python3
"""
Final Pre-Submission Compliance Check Systematic validator for PhD research papers before advisor review or journal submission.

Usage:  
    python check_compliance.py --project-dir ./my-research-project [--report-format pdf]
    
Checks coverage, completeness, mathematical consistency, revision documentation, and LaTeX formatting adherence.
"""

import argparse
from datetime import datetime
from pathlib import Path


class ComplianceChecker:
    """Validate research project against submission standards."""
    
    DEFAULT_CHECKLIST = [
        ("Literature Survey", "literature_sufficient", False),  
        ("Baseline Comparisons", "baselines_complete", False),
        ("Ablation Studies", "ablations_present", False),
        ("Robustness Tests", "robustness_validated", False),
        ("LaTeX Formatting", "latex_standards_met", False),
        ("Revision Rounds ≥6", "revision_tracking_adequate", False),
        ("Math Notation Consistency", "math_symbols_verified", False),
        ("All Figures High-Res (≥300 DPI)", "figures_quality_sufficient", False)
    ]
    
    def __init__(self, project_dir: Path):
        self.project_dir = project_dir
        self.checklist = {item[1]: {"name": item[0], "status": None, "message": "", "passed": False} for item in self.DEFAULT_CHECKLIST}
        
    def run_literature_check(self):
        """Check if literature survey is comprehensive."""
        lit_dir = self.project_dir / "01-literature-survey"
        
        bibtex_files = list(lit_dir.glob("*.bibtex"))
        pdfs_or_md = len(list(lit_dir.glob("*.pdf"))) + len(list(lit_dir.glob("*.md")))
        
        if len(bibtex_files) >= 30 and pdfs_or_md > 10:
            self.checklist["literature_sufficient"]["status"] = "passed"
            self.checklist["literature_sufficient"]["message"] = f"{len(bibtex_files)} BibTeX entries, {pdfs_or_md} papers documented"  
            status = True  
        else:
            self.checklist["literature_sufficient"]["status"] = "failed"  
            self.checklist["literature_sufficient"]["message"] = f"Only {len(bibtex_files)} BibTeX found (expected ≥50)"  
            status = False
        
        return status  
    
    def run_experiment_check(self):
        """Validate experimental design completeness."""
        exp_dir = self.project_dir / "04-experiments"
        
        comparison_configs = len(list(exp_dir.glob("*comparison*.yaml")))
        ablation_configs = len(list(exp_dir.glob("*ablation*.yaml")))  
        robustness_configs = len(list(exp_dir.glob("*robustness*.yaml")))
        
        baselines_ok = comparison_configs >= 1
        ablations_ok = ablation_configs >= 1
        robustness_ok = robustness_configs >= 1
        
        self.checklist["baselines_complete"]["status"] = "passed" if baselines_ok else "failed"  
        self.checklist["ablations_present"]["status"] = "passed" if ablations_ok else "failed" 
        self.checklist["robustness_validated"]["status"] = "passed" if robustness_ok else "failed"
        
        return baselines_ok and ablations_ok and robustness_ok


def generate_compliance_report(compliance_data: dict, project_dir: Path) -> str:  
    """Generate human-readable compliance summary."""
    
    report_path = project_dir / f"compliance-check-{datetime.now().strftime('%Y%m%d-%H%M%S')}.md" 
    
    md_content = f"""# Pre-Submission Compliance Audit Report
    
**Project:** {project_dir.name}  
**Audit Date:** {datetime.now().isoformat()}
**Status: {'✅ READY FOR SUBMISSION' if all_checklist_pass(compliance_data) else '⚠️ ISSUES DETECTED — REVIEW REQUIRED'}

## Compliance Checklist Results  

| Check Item | Status | Details |  
|-----------|:-:|------- |
"""
    
    all_passed = True
    
    for check_key, data in compliance_data.items():
        status_icon = "✅" if data["passed"] else "❌"
        md_content += f"| {data['name']} | {status_icon} PASSED/FAILED | {data['message']} |\n"
        
        if not data["passed"]:
            all_passed = False
    
    # Summary sections recommendation
    md_content += """### Recommendations

Based on failed checks above, consider:

**If Literature Insufficient:** Run `./scripts/multi_source_search.py` with broader queries  
**If Missing Experiment Types:** Execute respective designs before drafting results section  
**If Math Notation Issues:** Use `verify_math_notation.py --verbose` for detailed symbol mapping  
**If Figures Quality Low:** Export all TikZ/draw.io diagrams at ≥300 DPI resolution  

---
*Generated by PhD Research Companion — Compliance Checking System v1.0*"""
    
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(md_content)
    
    return str(report_path)


def main():  
    parser = argparse.ArgumentParser(description="Final pre-submission research compliance checker")
    
    parser.add_argument("--project-dir", required=True, help="Root directory of PhD research project")
    parser.add_argument("--report-format", default="markdown", choices=["markdown", "pdf"], help="Report output format")
    
    args = parser.parse_args()
    
    project_root = Path(args.project_dir).expanduser().resolve()
    
    print(f"🔍 Running Compliance Audit on: {project_root}")  
    print(f"Project structure validation...\\n")

    checker = ComplianceChecker(project_root)
    
    # Run individual checks 
    lit_ok = checker.run_literature_check()  
    exp_ok = checker.run_experiment_check()
    
    for check_key, data in checker.checklist.items():
        if data["status"] == "passed":
            print(f"✅ {data['name']}: PASSED")
        else:
            print(f"❌ {data['name']}: FAILED - {data['message']}")
    
    report_path = generate_compliance_report(checker.checklist, project_root)
    
    print(f"\\n📊 Compliance Report Generated: {report_path}")  
    

if __name__ == "__main__":
    main()