import sys
import json
import os

# Ensure UTF-8 output on Windows
if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

class ReportGenerator:
    def __init__(self, data):
        self.data = data
        self.version = "1.0.0"

    def generate(self):
        if not self.data:
            return "# Scam Guards Security Report\n\nNo data provided."

        # Support both single event and full chain
        if isinstance(self.data, list):
             events = self.data
             latest = events[-1]
        else:
             events = [self.data]
             latest = self.data

        # If it was chained by evidence_chain.py
        details = latest.get("details", latest)
        threat_level = details.get("threat_level", "UNKNOWN")
        overall_score = details.get("overall_score", 0)
        
        emoji = "🔴" if threat_level == "DANGER" or threat_level == "CRITICAL" else "🟡" if threat_level == "WARNING" else "🟢"
        
        report = [
            f"# 🛡️ Scam Guards Security Report",
            f"\n**Version:** {self.version}",
            f"**Generated:** {details.get('timestamp') or details.get('scan_timestamp')}",
            f"**Overall Threat Level:** {emoji} {threat_level} (Score: {overall_score})",
            f"\n---",
            f"\n## 🔍 Detection Summary",
        ]

        # Add specific findings
        findings = details.get("findings", [])
        if findings:
            for f in findings:
                sev = f.get("severity", "INFO")
                # Use standard emojis that are safer or ensure utf-8
                sev_emoji = "🔥" if sev == "CRITICAL" else "⚠️" if sev == "HIGH" else "📝"
                report.append(f"- {sev_emoji} **{f.get('rule') or f.get('dimension')}**: {f.get('evidence') or 'Behavior detected'}")
                if "location" in f:
                    report.append(f"  - *Location:* {f['location']}")
        else:
            report.append("- No significant threats detected.")

        # Add Evidence Chain
        report.append(f"\n---")
        report.append(f"\n## ⛓️ Evidence Chain (SHA-256)")
        for event in events:
            seq = event.get("sequence", 1)
            e_hash = event.get("hash", "N/A")
            p_hash = event.get("previous_hash", "N/A")
            e_type = event.get("event_type", "EVENT")
            
            report.append(f"### Record #{seq}: {e_type}")
            report.append(f"- **Hash:** `{e_hash}`")
            report.append(f"- **Prev:** `{p_hash}`")

        # Verified Badge
        if threat_level == "SAFE" and overall_score <= 0.2:
            report.append(f"\n---")
            report.append(f"\n![Verified by Scam Guards](file://{{baseDir}}/assets/badge-verified.svg)")
            report.append(f"\n> **PASS**: This session/skill is verified as safe by Scam Guards.")
        
        report.append(f"\n\n---")
        report.append(f"*Disclaimer: This report is generated by an automated security agent. Use caution.*")

        return "\n".join(report)

if __name__ == "__main__":
    try:
        input_data = sys.stdin.read()
        if not input_data.strip():
            sys.exit(0)
            
        data = json.loads(input_data)
        generator = ReportGenerator(data)
        print(generator.generate())
            
    except Exception as e:
        # Use simple ASCII for error to avoid further encoding issues during crash
        print(f"Error generating report: {str(e)}")
        sys.exit(1)
