#!/usr/bin/env python3
"""
BeastXA Memory Pro — MEMORY.md Smart Splitter

Reads a large MEMORY.md file and splits it into topic files based on ## headers.
Generates an index file pointing to each topic.

Usage:
    python3 split_memory.py
    python3 split_memory.py --input /path/to/MEMORY.md --output /path/to/topics/
    python3 split_memory.py --dry-run   # Preview without writing
"""

import argparse
import os
import re
import sys
from pathlib import Path
from datetime import datetime


def slugify(text: str) -> str:
    """Convert a header to a safe filename."""
    # Remove markdown formatting and special chars
    text = re.sub(r'[#*`\[\](){}|]', '', text).strip()
    # Replace spaces and special chars with hyphens
    text = re.sub(r'[\s/\\:]+', '-', text)
    # Remove leading/trailing hyphens
    text = text.strip('-')
    # Lowercase for consistency
    return text.lower() if text else 'misc'


def detect_topics(content: str) -> list:
    """Split content by ## headers into topic chunks."""
    lines = content.split('\n')
    topics = []
    current_title = None
    current_lines = []
    
    for line in lines:
        # Match ## headers (but not ### or deeper)
        match = re.match(r'^##\s+(.+)$', line)
        if match:
            # Save previous topic
            if current_title is not None:
                body = '\n'.join(current_lines).strip()
                if body:  # Only save non-empty topics
                    topics.append({
                        'title': current_title,
                        'slug': slugify(current_title),
                        'body': body
                    })
            current_title = match.group(1).strip()
            current_lines = []
        else:
            current_lines.append(line)
    
    # Don't forget the last topic
    if current_title is not None:
        body = '\n'.join(current_lines).strip()
        if body:
            topics.append({
                'title': current_title,
                'slug': slugify(current_title),
                'body': body
            })
    
    # Handle content before first ## header
    if topics and lines:
        pre_header = []
        for line in lines:
            if re.match(r'^##\s+', line):
                break
            pre_header.append(line)
        pre_content = '\n'.join(pre_header).strip()
        if pre_content and not pre_content.startswith('# MEMORY'):
            topics.insert(0, {
                'title': 'General',
                'slug': 'general',
                'body': pre_content
            })
    
    return topics


def merge_duplicate_slugs(topics: list) -> list:
    """Merge topics with the same slug."""
    merged = {}
    order = []
    for t in topics:
        slug = t['slug']
        if slug in merged:
            merged[slug]['body'] += '\n\n' + t['body']
        else:
            merged[slug] = t.copy()
            order.append(slug)
    return [merged[s] for s in order]


def generate_index(topics: list, output_dir: str) -> str:
    """Generate MEMORY-INDEX.md content."""
    lines = [
        '# Memory Index',
        f'_Auto-generated by BeastXA Memory Pro on {datetime.now().strftime("%Y-%m-%d %H:%M")}_',
        f'_Source: MEMORY.md → {len(topics)} topic files_',
        '',
        '| Topic | File | Lines |',
        '|-------|------|-------|',
    ]
    for t in topics:
        filepath = f'topics/{t["slug"]}.md'
        line_count = t['body'].count('\n') + 1
        lines.append(f'| {t["title"]} | `{filepath}` | {line_count} |')
    
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description='Split MEMORY.md into topic files')
    parser.add_argument('--input', '-i', default='MEMORY.md',
                        help='Path to MEMORY.md (default: ./MEMORY.md)')
    parser.add_argument('--output', '-o', default='memory/topics',
                        help='Output directory for topic files (default: memory/topics/)')
    parser.add_argument('--index', default='memory/MEMORY-INDEX.md',
                        help='Path for index file (default: memory/MEMORY-INDEX.md)')
    parser.add_argument('--dry-run', '-n', action='store_true',
                        help='Preview split without writing files')
    parser.add_argument('--force', '-f', action='store_true',
                        help='Overwrite existing topic files')
    args = parser.parse_args()
    
    # Read input
    input_path = Path(args.input)
    if not input_path.exists():
        print(f'❌ File not found: {input_path}')
        print(f'   Make sure MEMORY.md exists in your workspace')
        sys.exit(1)
    
    content = input_path.read_text(encoding='utf-8')
    original_lines = content.count('\n') + 1
    print(f'📖 Reading {input_path} ({original_lines} lines)')
    
    # Detect and merge topics
    topics = detect_topics(content)
    topics = merge_duplicate_slugs(topics)
    
    if not topics:
        print('⚠️  No ## headers found in MEMORY.md. Nothing to split.')
        sys.exit(0)
    
    total_lines = sum(t['body'].count('\n') + 1 for t in topics)
    print(f'🔍 Found {len(topics)} topics ({total_lines} lines of content)')
    
    # Preview
    print('\n📋 Topics:')
    for i, t in enumerate(topics, 1):
        lines = t['body'].count('\n') + 1
        print(f'   {i}. {t["title"]} → topics/{t["slug"]}.md ({lines} lines)')
    
    if args.dry_run:
        print('\n🏁 Dry run complete. No files written.')
        return
    
    # Create output directory
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Write topic files
    written = 0
    skipped = 0
    for t in topics:
        filepath = output_dir / f'{t["slug"]}.md'
        if filepath.exists() and not args.force:
            print(f'   ⏭️  Skipping {filepath} (exists, use --force to overwrite)')
            skipped += 1
            continue
        
        file_content = f'## {t["title"]}\n{t["body"]}\n'
        filepath.write_text(file_content, encoding='utf-8')
        written += 1
    
    # Write index
    index_path = Path(args.index)
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_content = generate_index(topics, str(output_dir))
    index_path.write_text(index_content, encoding='utf-8')
    
    print(f'\n✅ Split complete!')
    print(f'   📁 {written} topic files written to {output_dir}/')
    if skipped:
        print(f'   ⏭️  {skipped} files skipped (already exist)')
    print(f'   📑 Index written to {index_path}')
    print(f'   📖 Original MEMORY.md untouched')


if __name__ == '__main__':
    main()
