/**
 * Memoria — Auto Skill Creation (Layer 23)
 *
 * When a procedure reaches maturity (repeated successes, high quality),
 * automatically generates a reusable skill document (.md) in the workspace.
 *
 * Inspired by Hermes' "auto skill creation from experience" concept.
 *
 * Lifecycle:
 * 1. Procedure is captured via after_tool_call (existing Layer 1b)
 * 2. Procedure accumulates successes + quality improvements
 * 3. When maturity threshold is reached → auto-generate skill .md
 * 4. Skill is written to workspace/.skills/ (or .learnings/skills/)
 * 5. Agent can reference these skills in future sessions
 */

import fs from "fs";
import path from "path";
import type { ProceduralMemory, Procedure } from "./procedural.js";

export interface AutoSkillConfig {
  /** Minimum success count before promoting to skill (default: 3) */
  minSuccesses: number;
  /** Minimum quality.overall before promoting (default: 0.6) */
  minQuality: number;
  /** Directory to write skill files (relative to workspace) */
  skillDir: string;
  /** Maximum number of auto-skills to create per session (default: 2) */
  maxPerSession: number;
}

const DEFAULT_CONFIG: AutoSkillConfig = {
  minSuccesses: 3,
  minQuality: 0.6,
  skillDir: ".skills",
  maxPerSession: 2,
};

export class AutoSkillCreator {
  private cfg: AutoSkillConfig;
  private proceduralMem: ProceduralMemory;
  private workspacePath: string;
  private createdThisSession: Set<string> = new Set();
  private promotedIds: Set<string> = new Set();

  constructor(
    proceduralMem: ProceduralMemory,
    workspacePath: string,
    config?: Partial<AutoSkillConfig>
  ) {
    this.proceduralMem = proceduralMem;
    this.workspacePath = workspacePath;
    this.cfg = { ...DEFAULT_CONFIG, ...config };

    // Load already-promoted procedure IDs from existing skill files
    this.loadPromotedIds();
  }

  private loadPromotedIds(): void {
    const skillDir = path.join(this.workspacePath, this.cfg.skillDir);
    if (!fs.existsSync(skillDir)) return;

    try {
      const files = fs.readdirSync(skillDir).filter(f => f.endsWith(".md"));
      for (const file of files) {
        const content = fs.readFileSync(path.join(skillDir, file), "utf-8");
        const match = content.match(/procedure_id:\s*(\S+)/);
        if (match) this.promotedIds.add(match[1]);
      }
    } catch {
      // Ignore read errors
    }
  }

  /**
   * Check all mature procedures and create skills for eligible ones.
   * Called periodically (e.g., on agent_end or after successful tool sequences).
   * Returns the number of new skills created.
   */
  checkAndPromote(): number {
    if (this.createdThisSession.size >= this.cfg.maxPerSession) return 0;

    const candidates = this.findMatureProcedures();
    let created = 0;

    for (const proc of candidates) {
      if (this.createdThisSession.size >= this.cfg.maxPerSession) break;
      if (this.promotedIds.has(proc.id)) continue;

      try {
        this.createSkillFile(proc);
        this.promotedIds.add(proc.id);
        this.createdThisSession.add(proc.id);
        created++;
      } catch {
        // Non-blocking
      }
    }

    return created;
  }

  /**
   * Find procedures that have reached maturity threshold.
   */
  private findMatureProcedures(): Procedure[] {
    const all = this.proceduralMem.getAllProcedures();
    return all.filter(proc =>
      proc.success_count >= this.cfg.minSuccesses &&
      proc.quality.overall >= this.cfg.minQuality &&
      !this.promotedIds.has(proc.id) &&
      proc.degradation_score < 0.5 // Not degraded
    ).sort((a, b) => {
      // Prioritize: highest quality × most successes
      const scoreA = a.quality.overall * Math.log2(a.success_count + 1);
      const scoreB = b.quality.overall * Math.log2(b.success_count + 1);
      return scoreB - scoreA;
    });
  }

  /**
   * Generate a skill .md file from a mature procedure.
   */
  private createSkillFile(proc: Procedure): void {
    const skillDir = path.join(this.workspacePath, this.cfg.skillDir);
    if (!fs.existsSync(skillDir)) {
      fs.mkdirSync(skillDir, { recursive: true });
    }

    // Generate a clean filename
    const slug = proc.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60);
    const filename = `${slug}.md`;
    const filepath = path.join(skillDir, filename);

    // Don't overwrite existing files
    if (fs.existsSync(filepath)) return;

    const successRate = Math.round(
      (proc.success_count / Math.max(proc.success_count + proc.failure_count, 1)) * 100
    );

    const content = `# ${proc.name}

> Auto-generated by Memoria from ${proc.success_count} successful executions.
> procedure_id: ${proc.id}
> quality: ${Math.round(proc.quality.overall * 100)}% | success_rate: ${successRate}%
> version: ${proc.version} | last_success: ${proc.last_success_at ? new Date(proc.last_success_at).toISOString().slice(0, 10) : "unknown"}

## Goal

${proc.goal}

## Steps

${proc.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

${proc.gotchas ? `## Gotchas

${proc.gotchas.split(" | ").map(g => `- ⚠️ ${g}`).join("\n")}` : ""}

${proc.improvements && proc.improvements.length > 0 ? `## Evolution

${proc.improvements.slice(-3).map(imp => `- ${imp.change}`).join("\n")}` : ""}

${proc.context ? `## Trigger Patterns

Keywords: ${proc.context}` : ""}

---
*This skill was automatically created by Memoria when the procedure reached maturity.*
*Edit freely — your improvements will be preserved.*
`;

    fs.writeFileSync(filepath, content, "utf-8");
  }

  /**
   * Get stats about auto-skill creation.
   */
  stats(): { totalPromoted: number; createdThisSession: number; candidates: number } {
    return {
      totalPromoted: this.promotedIds.size,
      createdThisSession: this.createdThisSession.size,
      candidates: this.findMatureProcedures().length,
    };
  }
}
