"""
Scheduler — installs/removes cron jobs or runs a background daemon.
Automatically detects which method is available on the current system.
"""

from __future__ import annotations

import datetime
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

# Python 3.9+ has zoneinfo in stdlib; 3.8 needs backports.zoneinfo
try:
    import zoneinfo
except ImportError:
    try:
        from backports import zoneinfo  # type: ignore[no-redef]
    except ImportError:
        zoneinfo = None  # type: ignore[assignment]

from .display import print_error, print_info, print_success, print_warning

_CRON_TAG = "# tmw-managed"
_MAIN_SCRIPT = Path(__file__).parent.parent / "tmw.py"


# ── crontab helpers ───────────────────────────────────────────────────────────

def _has_crontab() -> bool:
    return subprocess.run(["which", "crontab"], capture_output=True).returncode == 0


def _read_crontab() -> str:
    r = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else ""


def _write_crontab(content: str) -> None:
    subprocess.run(["crontab", "-"], input=content, text=True, check=True)


def _remove_tmw_crons() -> None:
    lines = _read_crontab().splitlines()
    cleaned, skip = [], False
    for line in lines:
        if _CRON_TAG in line:
            skip = True
            continue
        if skip:
            skip = False
            continue
        cleaned.append(line)
    _write_crontab("\n".join(cleaned) + "\n")


def _install_cron(config_path: str, config: dict) -> None:
    import random as _r
    abs_cfg = str(Path(config_path).resolve())
    cmd = f"{sys.executable} {_MAIN_SCRIPT} run --config {abs_cfg} >> /tmp/tmw.log 2>&1"

    if config.get("simulate_work"):
        ws = config.get("work_start", "09:00")
        we = config.get("work_end", "18:00")
        sh = int(ws.split(":")[0])
        eh = int(we.split(":")[0])
        expr = f"*/30 {sh}-{eh} * * 1-5"
    else:
        minute = _r.randint(5, 55)
        expr = f"{minute} * * * *"

    current = _read_crontab().rstrip()
    _write_crontab(f"{current}\n{_CRON_TAG}\n{expr} {cmd}\n")
    print_success(f"Cron installed: [{expr}]")
    print_info("Log: /tmp/tmw.log")


# ── daemon helpers ────────────────────────────────────────────────────────────

def _pid_file(config_path: str) -> Path:
    return Path(config_path).parent / ".tmw_daemon.pid"


def _log_file(config_path: str) -> Path:
    return Path(config_path).parent / "tmw_daemon.log"


def _daemon_running(config_path: str) -> Optional[int]:
    pf = _pid_file(config_path)
    if not pf.exists():
        return None
    try:
        pid = int(pf.read_text().strip())
        os.kill(pid, 0)
        return pid
    except Exception:
        pf.unlink(missing_ok=True)
        return None


def _write_daemon_script(script_path: Path, config_path: str) -> None:
    abs_cfg = str(Path(config_path).resolve())
    main = str(_MAIN_SCRIPT.resolve())
    content = f'''#!/usr/bin/env python3
# Auto-generated by TrustMeImWorking — do not edit
import subprocess, sys, time, datetime, json

CONFIG = {repr(abs_cfg)}
MAIN   = {repr(main)}

def in_work_window():
    try:
        cfg = json.loads(open(CONFIG).read())
        if not cfg.get("simulate_work"):
            return True
        import datetime as dt
        tz_name = cfg.get("timezone","")
        tz = (zoneinfo.ZoneInfo(tz_name) if (tz_name and zoneinfo is not None)
              else dt.datetime.now().astimezone().tzinfo)
        now = dt.datetime.now(tz)
        if now.weekday() >= 5:
            return False
        sh, sm = map(int, cfg["work_start"].split(":"))
        eh, em = map(int, cfg["work_end"].split(":"))
        return dt.time(sh, sm) <= now.time() < dt.time(eh, em)
    except Exception:
        return True

print(f"[daemon] started {{datetime.datetime.now()}}", flush=True)
while True:
    if in_work_window():
        print(f"[daemon] trigger {{datetime.datetime.now().strftime('%H:%M:%S')}}", flush=True)
        subprocess.run([sys.executable, MAIN, "run", "--config", CONFIG])
    else:
        print(f"[daemon] skip {{datetime.datetime.now().strftime('%H:%M:%S')}}", flush=True)
    time.sleep(1800)
'''
    script_path.write_text(content)


def _start_daemon(config_path: str) -> None:
    abs_cfg = str(Path(config_path).resolve())
    script = Path(abs_cfg).parent / ".tmw_daemon_runner.py"
    log = _log_file(abs_cfg)
    _write_daemon_script(script, abs_cfg)

    proc = subprocess.Popen(
        [sys.executable, str(script)],
        stdout=open(log, "a"),
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    _pid_file(abs_cfg).write_text(str(proc.pid))
    print_success(f"Daemon started (PID {proc.pid})")
    print_info(f"Log: {log}")
    print_info(f"Stop: tmw scheduler --uninstall --config {abs_cfg}")


def _stop_daemon(config_path: str) -> None:
    pid = _daemon_running(config_path)
    if pid is None:
        print_warning("No daemon running.")
        return
    try:
        os.kill(pid, signal.SIGTERM)
        _pid_file(config_path).unlink(missing_ok=True)
        print_success(f"Daemon stopped (PID {pid})")
    except Exception as exc:
        print_error(f"Failed to stop daemon: {exc}")


# ── Public API ────────────────────────────────────────────────────────────────

def install(config_path: str, config: dict) -> None:
    if _has_crontab():
        _remove_tmw_crons()
        _install_cron(config_path, config)
    else:
        print_info("crontab not available — starting background daemon.")
        _start_daemon(config_path)


def uninstall(config_path: str) -> None:
    if _has_crontab():
        _remove_tmw_crons()
        print_success("Cron jobs removed.")
    _stop_daemon(config_path)


def status(config_path: Optional[str] = None) -> None:
    if _has_crontab():
        lines = _read_crontab().splitlines()
        managed = [l for l in lines if _CRON_TAG not in l and
                   any(_CRON_TAG in lines[max(0, i-1)] for i, x in enumerate(lines) if x == l)]
        print_info(f"Cron jobs managed by tmw: {len(managed)}")
        for l in lines:
            if _CRON_TAG in l:
                idx = lines.index(l)
                if idx + 1 < len(lines):
                    print_info(f"  {lines[idx+1]}")
    else:
        print_info("crontab not available on this system.")

    if config_path:
        pid = _daemon_running(config_path)
        if pid:
            print_success(f"Daemon running (PID {pid})")
        else:
            print_info("Daemon not running.")
