#!/usr/bin/env python3
"""
室内设计全案方案自动生成器
按照隐室空间设计标准规范生成
"""

import sys
import os

TEMPLATE = """# {project_name} 设计方案

## 一、项目信息
- **项目地址**: {address}
- **建筑面积**: {area} ㎡
- **套内面积**: {area_net} ㎡
- **风格定位**: {style}
- **客户需求**: {requirements}

---

## 二、户型诊断

### 结构分析
{structure_analysis}

### 采光分析
{lighting_analysis}

### 动线分析
{traffic_analysis}

### 主要问题点优化建议
{problems}

---

## 三、风格定位

### 色彩方案
| 区域 | 主色调 | 辅色调 | 点缀色 |
|------|--------|--------|--------|
| 客餐厅 | {color_living_primary} | {color_living_secondary} | {color_living_accent} |
| 卧室 | {color_bed_primary} | {color_bed_secondary} | {color_bed_accent} |

### 材质组合
{material_list}

### 避坑提示
{pitfalls}

---

## 四、平面布局方案（文字逻辑）

### 客餐厅
- 沙发尺寸建议：根据开间选择，深度 ≥ 900mm
- 餐桌位：距墙过道预留 ≥ 900mm 过人空间
- 动线宽度：客餐厅主通道 ≥ 1200mm，次通道 ≥ 900mm
- 收纳：
  - 玄关柜：深度 ≥ 350mm（挂衣区）
  - 电视柜：深度 ≤ 350mm，节省空间
- 核心关系：客餐厅一体化设计，保证互动性

{living_layout}

### 卧室
- 床：1.8m 床建议开间 ≥ 3600mm，预留两边过道 ≥ 600mm
- 衣柜：深度 ≥ 600mm（挂衣区），长度按储物需求计算
- 过道：床侧预留 ≥ 600mm 通行
- 梳妆台：靠窗采光好的位置优先

{bedding_layout}

### 厨房
- 动线顺序：**洗 → 切 → 炒**，不可反向
- 台面宽度： ≥ 600mm
- 冰箱位置：靠近门，拿取食材不用穿过操作区
- 吊柜：底距台面 ≥ 1500mm，不撞头
- 收纳：地柜+吊柜充分利用墙面

{kitchen_layout}

### 卫生间
- 优先做干湿分离，干区洗手台，湿区淋浴+马桶
- 马桶中心距墙 ≥ 400mm，两侧预留 ≥ 150mm
- 淋浴区最小尺寸： ≥ 900mm × 900mm
- 防水：淋浴区墙面做到 1800mm，干区做到 300mm

{bathroom_layout}

### 收纳系统总体规划
{storage}

---

## 五、灯光系统设计

### 色温建议
| 空间 | 色温 |
|------|------|
| 客厅 | 3500K（暖白光，舒适不发黄） |
| 卧室 | 3000K（暖光，氛围温馨） |
| 厨房/卫生间 | 4000K（中性白光，看清细节） |

### 灯具配置建议
- **客餐厅**：{light_living}
- **卧室**：{light_bed}
- **厨房**：{light_kitchen}
- **卫生间**：{light_bath}

### 设计要点
{light_notes}

---

## 六、材料清单（可落地版）

| 空间 | 部位 | 材料建议 | 规格 |
|------|------|----------|------|
{materials}

---

## 七、预算拆分（行业通用比例，按套内面积计算）

| 项目 | 比例 | 估算价格（{total} ㎡） | 说明 |
|------|------|------------------------|------|
| 设计费 | 5% | {cost_design} | 方案+效果图+施工图+工地对接 |
| 基础装修 | 25% | {cost_base} | 水电+瓦工+木工+油漆+人工辅材 |
| 主材 | 25% | {cost_material} | 瓷砖/地板/木门/橱柜/洁具 |
| 全屋定制 | 20% | {cost_custom} | 衣柜/鞋柜/电视柜/储物柜 |
| 软装家具 | 20% | {cost_soft} | 沙发/床/餐桌椅/窗帘/灯具 |
| 管理费&杂费 | 5% | {cost_other} | 搬运+清理+管理 |
| **总计** | 100% | **{total_cost}** | |

*注：按 ￥{unit_price}/㎡ 套内面积估算，可根据实际调整单位价格*

---

## 八、设计说明

> {design_idea}

---

## 九、施工注意要点

1. **水电**：  
   插座数量：客厅每面墙不少于2个，卧室床头两边各1个，厨房台面上方不少于3个  
   走顶不走地，方便后期维修

2. **防水**：  
   淋浴区墙面做到 1800mm 高，干区墙面 300mm 高  
   闭水试验不少于 48 小时，检查楼下顶面

3. **吊顶**：  
   石膏板拼缝留 V 型槽，贴牛皮纸防开裂  
   龙骨间距 ≤ 400mm，保证牢固

4. **墙面**：  
   墙面找平误差 ≤ 3mm，否则乳胶漆会有色差  
   阴阳角要顺直，用靠尺校正

5. **定制收口**：  
   橱柜与墙面打玻璃胶，衣柜与顶/墙面收缝美观  
   石材台面留伸缩缝，防止热胀冷缩

{extra_construction}

---

*Generated by 隐室空间设计 AI 助手*
"""

STYLE_PRESETS = {
    "现代简约": {
        "colors": {
            "living": ("浅灰乳胶漆", "浅原木色", "黑色/深色")
        },
        "materials": [
            ("地面", "客餐厅", "瓷砖/强化复合地板", "750×1500mm"),
            ("墙面", "全屋", "乳胶漆", "-"),
            ("柜体", "全屋定制", "颗粒板/多层板", "-"),
            ("厨卫", "墙面", "墙砖", "300×600mm/400×800mm"),
        ],
        "pitfalls": "避免过多造型堆砌，简约≠廉价，材质质感比造型重要",
        "lights": {
            "living": "磁吸轨道灯+射灯，无主灯设计，简洁干净",
            "bed": "主吸顶灯+床头壁灯/台灯",
        }
    },
    "轻美式": {
        "colors": {
            "living": ("奶咖乳胶漆", "原木色橡木", "深咖点缀")
        },
        "materials": [
            ("地面", "客餐厅卧室", "实木复合地板/仿古砖", "150×900mm"),
            ("墙面", "全屋", "乳胶漆+部分实木线条", "-"),
            ("柜体", "全屋定制", "实木贴皮/多层板", "-"),
            ("厨卫", "墙面", "墙砖", "300×600mm"),
        ],
        "pitfalls": "避免深色过多导致空间压抑，原木色+浅墙是松弛感关键",
        "lights": {
            "living": "主吊灯+筒灯，保留美式氛围感，不要太暗",
            "bed": "主吊灯+床头台灯",
        }
    },
    "宋式美学": {
        "colors": {
            "living": ("大白墙/浅灰", "黑胡桃木/橡木", "宣纸色留白")
        },
        "materials": [
            ("地面", "客餐厅", "哑光砖/实木地板", "自然面"),
            ("墙面", "全屋", "艺术涂料/乳胶漆", "留白多"),
            ("柜体", "实木", "黑胡桃/榆木", "榫卯结构"),
            ("门窗", "松木框+玻璃", "-"),
        ],
        "pitfalls": "少就是多，留白比满墙装饰重要，尊重材质本身纹理",
        "lights": {
            "living": "吸顶灯+落地灯+灯带，低照度营造安静氛围",
            "bed": "壁灯+吸顶灯，简洁不抢空间",
        }
    },
    "工业风": {
        "colors": {
            "living": ("水泥灰/乳胶漆", "黑色钢结构", "红砖/木色点缀")
        },
        "materials": [
            ("地面", "整体空间", "水泥砖/金刚砂地面", "-"),
            ("墙面", "部分", "水泥漆/文化砖", "-"),
            ("顶面", "保留原顶刷漆", "黑色", "-"),
            ("柜体", "金属框架+实木层板", "-"),
        ],
        "pitfalls":  "裸露结构要干净，不要乱糟糟堆元素，控制深色比例在30%以内",
        "lights": {
            "living": "工业风吊灯+轨道射灯，突出材质质感",
            "bed": "黑色工矿灯/筒灯",
        }
    },
}

def interactive_input():
    print("🏠 室内设计全案方案自动生成器")
    print("-" * 50)
    project = input("项目名称: ").strip()
    address = input("项目地址: ").strip()
    area = float(input("建筑面积(㎡): ").strip())
    area_net = input("套内面积(㎡) [留空=建筑面积*0.75]: ").strip()
    if not area_net:
        area_net = area * 0.75
    else:
        area_net = float(area_net)
    
    print("\n常见风格选项：现代简约 / 轻美式 / 宋式美学 / 工业风")
    style = input("风格定位: ").strip()
    requirements = input("客户核心需求（换行结束）:\n")
    unit_price = float(input("单位造价估算（元/㎡套内，一般1500-3000）: ").strip())
    
    print("\n开始生成方案...\n")
    
    # 填充默认值根据风格
    preset = STYLE_PRESETS.get(style, None)
    
    if preset:
        cp_living_pr, cp_living_sec, cp_living_ac = preset["colors"]["living"]
        cp_bed_pr, cp_bed_sec, cp_bed_ac = cp_living_pr, cp_living_sec, cp_living_ac
        materials = preset["materials"]
        pitfalls = preset["pitfalls"]
        ll = preset["lights"]["living"]
        lb = preset["lights"]["bed"]
    else:
        cp_living_pr = input("客餐厅主色调: ").strip() or "浅灰"
        cp_living_sec = input("客餐厅辅色调: ").strip() or "原木色"
        cp_living_ac = input("客餐厅点缀色: ").strip() or "黑色"
        cp_bed_pr = cp_living_pr
        cp_bed_sec = cp_living_sec
        cp_bed_ac = cp_living_ac
        materials = [
            ("地面", "客餐厅", "瓷砖", "750×1500mm"),
            ("墙面", "全屋", "乳胶漆", "-"),
            ("柜体", "全屋定制", "颗粒板", "-"),
        ]
        pitfalls = ""
        ll = "无主灯磁吸轨道"
        lb = "吸顶灯+台灯"
    
    # 格式化材料表格
    material_str = ""
    for row in materials:
        space, part, mat, spec = row
        material_str += f"| {space} | {part} | {mat} | {spec} |\n"
    
    # 预算计算
    total_area = float(area_net)
    total_cost = total_area * unit_price
    cost_design = total_cost * 0.05
    cost_base = total_cost * 0.25
    cost_material = total_cost * 0.25
    cost_custom = total_cost * 0.20
    cost_soft = total_cost * 0.20
    cost_other = total_cost * 0.05
    
    # 生成内容
    content = TEMPLATE.format(
        project_name=project,
        address=address,
        area=area,
        area_net=area_net,
        style=style,
        requirements=requirements,
        # 户型诊断 - 默认空让用户填
        structure_analysis="\n",
        lighting_analysis="\n",
        traffic_analysis="\n",
        problems="\n",
        # 颜色
        color_living_primary=cp_living_pr,
        color_living_secondary=cp_living_sec,
        color_living_accent=cp_living_ac,
        color_bed_primary=cp_bed_pr,
        color_bed_secondary=cp_bed_sec,
        color_bed_accent=cp_bed_ac,
        # 材质
        material_list="",
        material_list_formatted=material_str,
        pitfalls=pitfalls,
        # 布局 - 默认空
        living_layout="",
        bedding_layout="",
        kitchen_layout="",
        bathroom_layout="",
        storage="",
        # 灯光
        light_living=ll,
        light_bed=lb,
        light_kitchen="铝扣板集成吊顶带灯+台面灯带",
        light_bath="集成吊顶灯+镜前灯",
        light_notes="- 优先防眩光射灯，避免眩光刺眼\n- 无主灯设计注意分层照明，不要只装一层",
        # 材料表
        materials=material_str,
        # 预算
        total=area_net,
        unit_price=unit_price,
        cost_design=f"{cost_design:.0f}",
        cost_base=f"{cost_base:.0f}",
        cost_material=f"{cost_material:.0f}",
        cost_custom=f"{cost_custom:.0f}",
        cost_soft=f"{cost_soft:.0f}",
        cost_other=f"{cost_other:.0f}",
        total_cost=f"{total_cost:.0f}",
        # 设计说明
        design_idea=requirements,
        # 施工
        extra_construction="",
    )
    
    output_path = os.path.join(os.path.expanduser("~/Desktop"), f"{project}_全案方案.md")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"✓ 全案方案已生成: {output_path}")
    print("你可以直接编辑填充具体信息，或者导出到PPT/方案册")

if __name__ == "__main__":
    interactive_input()
