import pytest
from ghostclaw.cli.formatters import MarkdownFormatter
from typing import Dict, Any

@pytest.fixture
def mock_report() -> Dict[str, Any]:
    return {
        "vibe_score": 85,
        "stack": "Python",
        "files_analyzed": 10,
        "total_lines": 500,
        "metadata": {"timestamp": "2023-10-27T10:00:00Z"},
        "issues": ["Issue 1"],
        "architectural_ghosts": ["Ghost 1"],
        "red_flags": ["Flag 1"],
        "ai_reasoning": "This is good code.",
        "ai_synthesis": "Overall looks fine.",
        "coupling_metrics": {"avg_ccn": 2.5, "avg_nd": 1.5}
    }

def test_markdown_formatter(mock_report):
    formatter = MarkdownFormatter()
    result = formatter.format(mock_report)

    assert "Architecture Report — 2023-10-27T10:00:00Z" in result
    assert "🟢 Vibe Score: 85/100" in result
    assert "Stack**: Python" in result
    assert "Avg CCN**: 2.5" in result
    assert "Avg Nesting Depth**: 1.5" in result
    assert "Issue 1" in result
    assert "Ghost 1" in result
    assert "Flag 1" in result
    assert "This is good code." in result
    assert "Overall looks fine." in result
    assert "*Generated by Ghostclaw Architectural Assistant*" in result
