#!/usr/bin/env python3
"""Example: Compile a Typst document to PDF."""

import requests
import base64
import sys

API_URL = "https://studio-intrinsic--typetex-compile-app.modal.run/public/compile/typst"


def compile_typst(content: str, output_path: str = "output.pdf") -> bool:
    """
    Compile Typst content to PDF.

    Args:
        content: Typst source code
        output_path: Path to save the output PDF

    Returns:
        True if successful, False otherwise
    """
    response = requests.post(
        API_URL,
        json={
            "content": content,
            "main_filename": "main.typ",
        },
        timeout=120,
    )

    result = response.json()

    if result["success"]:
        pdf_bytes = base64.b64decode(result["pdf_base64"])
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)
        print(f"PDF saved to {output_path} ({len(pdf_bytes)} bytes)")
        return True
    else:
        print(f"Compilation failed: {result['error']}")
        return False


# Example Typst document
EXAMPLE_DOCUMENT = r"""
#set page(paper: "a4", margin: 2cm)
#set text(font: "New Computer Modern", size: 11pt)
#set heading(numbering: "1.")

#align(center)[
  #text(size: 24pt, weight: "bold")[
    Sample Document
  ]

  #v(1em)

  _Generated by TypeTex Compile API_
]

#v(2em)

= Introduction

This document demonstrates the Typst compilation API. Typst is a modern
typesetting system that combines the power of LaTeX with a friendlier syntax.

= Features

== Math Support

Typst supports beautiful mathematics:

$ integral_0^infinity e^(-x^2) dif x = sqrt(pi) / 2 $

== Lists

- First item
- Second item
  - Nested item
  - Another nested item
- Third item

== Tables

#table(
  columns: 3,
  [*Name*], [*Type*], [*Description*],
  [Typst], [Markup], [Modern typesetting],
  [LaTeX], [Markup], [Classic typesetting],
  [Word], [WYSIWYG], [Office suite],
)

== Code

```python
def hello():
    print("Hello, World!")
```

= Conclusion

This PDF was compiled using the TypeTex public API.
"""

if __name__ == "__main__":
    if len(sys.argv) > 1:
        # Compile a file passed as argument
        with open(sys.argv[1], "r") as f:
            content = f.read()
        output = sys.argv[2] if len(sys.argv) > 2 else "output.pdf"
    else:
        # Use example document
        content = EXAMPLE_DOCUMENT
        output = "example.pdf"

    compile_typst(content, output)
