#!/usr/bin/env python3
"""
generate_html.py - Generate self-contained mindmap HTML from mindmap_data.json.
"""
import json

def main():
    with open("mindmap_data.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    workspace_title = data.get("t", "Notion Mind Map")
    json_str = json.dumps(data, ensure_ascii=False, separators=(',', ':'))

    # Build HTML using string concatenation to avoid f-string brace escaping issues
    html = (
        '<!DOCTYPE html>\n'
        '<html lang="zh-CN">\n'
        '<head>\n'
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        '<title>' + workspace_title + ' - 思维导图</title>\n'
        '<style>\n'
        '* { margin:0; padding:0; box-sizing:border-box; }\n'
        'html,body { width:100%; height:100%; overflow:hidden; font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif; background:#1a1a2e; color:#e0e0e0; }\n'
        '#toolbar { position:fixed; top:0; left:0; right:0; height:48px; background:#16213e; border-bottom:1px solid #2a2a4a; display:flex; align-items:center; padding:0 16px; gap:10px; z-index:1000; user-select:none; }\n'
        '#toolbar .btn { padding:6px 14px; background:#2a2a4a; color:#c0c0d0; border:1px solid #3a3a5a; border-radius:6px; cursor:pointer; font-size:12px; white-space:nowrap; transition:background .15s; }\n'
        '#toolbar .btn:hover { background:#3a3a5a; color:#fff; }\n'
        '#toolbar .sep { width:1px; height:24px; background:#2a2a4a; }\n'
        '#search-box { padding:5px 10px; background:#0f0f23; border:1px solid #3a3a5a; border-radius:6px; color:#e0e0e0; font-size:12px; width:200px; outline:none; }\n'
        '#search-box:focus { border-color:#667eea; }\n'
        '#search-box::placeholder { color:#555; }\n'
        '#stats { font-size:11px; color:#888; margin-left:auto; white-space:nowrap; }\n'
        '#canvas-wrap { position:absolute; top:48px; left:0; right:0; bottom:0; overflow:hidden; cursor:grab; }\n'
        '#canvas-wrap.grabbing { cursor:grabbing; }\n'
        'canvas { display:block; }\n'
        '#zoom-indicator { position:fixed; bottom:16px; right:16px; background:#16213e; border:1px solid #2a2a4a; border-radius:6px; padding:4px 10px; font-size:11px; color:#888; z-index:1000; user-select:none; }\n'
        '#ctx-menu { position:fixed; display:none; background:#1e1e3a; border:1px solid #3a3a5a; border-radius:8px; padding:4px 0; min-width:180px; box-shadow:0 8px 32px rgba(0,0,0,.6); z-index:2000; font-size:13px; }\n'
        '.ctx-item { padding:8px 16px; cursor:pointer; color:#d0d0e0; transition:background .1s; }\n'
        '.ctx-item:hover { background:#2a2a4a; }\n'
        '#tooltip { position:fixed; display:none; background:#1e1e3a; border:1px solid #3a3a5a; border-radius:6px; padding:4px 10px; font-size:11px; color:#aaa; z-index:1500; pointer-events:none; white-space:nowrap; }\n'
        '#footer { position:fixed; bottom:12px; left:16px; font-size:11px; color:#555; z-index:1000; user-select:none; }\n'
        '#footer a { color:#555; text-decoration:none; transition:color .15s; }\n'
        '#footer a:hover { color:#667eea; }\n'
        '</style>\n'
        '</head>\n'
        '<body>\n'
        '<div id="toolbar">\n'
        '  <div class="btn" id="btn-reset">重置</div>\n'
        '  <div class="btn" id="btn-fit">适应屏幕</div>\n'
        '  <div class="btn" id="btn-expand">展开全部</div>\n'
        '  <div class="btn" id="btn-collapse">折叠全部</div>\n'
        '  <div class="sep"></div>\n'
        '  <input type="text" id="search-box" placeholder="搜索页面... (Ctrl+F)">\n'
        '  <div id="stats"></div>\n'
        '</div>\n'
        '<div id="canvas-wrap"><canvas id="cv"></canvas></div>\n'
        '<div id="zoom-indicator">100%</div>\n'
        '<div id="ctx-menu">\n'
        '  <div class="ctx-item" id="ctx-copy">复制 Notion 链接</div>\n'
        '  <div class="ctx-item" id="ctx-focus">聚焦此页面</div>\n'
        '</div>\n'
        '<div id="tooltip"></div>\n'
        '<script>\n'
        '"use strict";\n'
        'const RAW = ' + json_str + ';\n'
    ) + (
        'const NODE_H = 28;\n'
        'const NODE_PAD_X = 14;\n'
        'const NODE_GAP_Y = 4;\n'
        'const LEVEL_GAP_X = 220;\n'
        'const FONT = \'13px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif\';\n'
        'const FONT_BOLD = \'bold 13px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif\';\n'
        'const BRANCH_COLORS = [\n'
        '  "#667eea","#43b581","#faa61a","#f47b67","#b967ff",\n'
        '  "#2ee4d6","#ff6b9d","#c4e538","#6c9eff","#ff9f43",\n'
        '  "#a29bfe","#fd79a8","#00cec9","#fdcb6e","#e17055"\n'
        '];\n'
        '\n'
        'let nodes = [];\n'
        'let rootNode = null;\n'
        '\n'
        'function buildTree(raw, parent, depth) {\n'
        '  const n = {\n'
        '    id: raw.id,\n'
        '    title: raw.t,\n'
        '    link: raw.l,\n'
        '    depth: depth,\n'
        '    parent: parent,\n'
        '    children: [],\n'
        '    _children: null,\n'
        '    expanded: depth < 2,\n'
        '    x: 0, y: 0,\n'
        '    w: 0,\n'
        '    branchColor: null,\n'
        '    subtreeH: 0,\n'
        '    descendantCount: 0\n'
        '  };\n'
        '  nodes.push(n);\n'
        '  if (raw.c) {\n'
        '    for (const ch of raw.c) {\n'
        '      const child = buildTree(ch, n, depth + 1);\n'
        '      n.children.push(child);\n'
        '    }\n'
        '  }\n'
        '  n.descendantCount = countDesc(n);\n'
        '  if (depth >= 2 && n.children.length > 0) {\n'
        '    n._children = n.children;\n'
        '    n.children = [];\n'
        '    n.expanded = false;\n'
        '  }\n'
        '  return n;\n'
        '}\n'
        '\n'
        'function countDesc(n) {\n'
        '  let c = 0;\n'
        '  const ch = n._children || n.children;\n'
        '  for (const x of ch) { c += 1 + countDesc(x); }\n'
        '  return c;\n'
        '}\n'
        '\n'
        'function hasAnyChildren(n) {\n'
        '  return (n.children && n.children.length > 0) || (n._children && n._children.length > 0);\n'
        '}\n'
        '\n'
        'function assignColors(root) {\n'
        '  root.branchColor = "#e0e0e0";\n'
        '  const L1 = root._children || root.children;\n'
        '  for (let i = 0; i < L1.length; i++) {\n'
        '    L1[i].branchColor = BRANCH_COLORS[i % BRANCH_COLORS.length];\n'
        '    assignChildColors(L1[i]);\n'
        '  }\n'
        '}\n'
        '\n'
        'function assignChildColors(n) {\n'
        '  const ch = n._children || n.children;\n'
        '  if (n.depth === 1) {\n'
        '    for (let i = 0; i < ch.length; i++) {\n'
        '      ch[i].branchColor = varyColor(n.branchColor, i, ch.length);\n'
        '      assignChildColors(ch[i]);\n'
        '    }\n'
        '  } else {\n'
        '    for (const c of ch) {\n'
        '      c.branchColor = n.branchColor;\n'
        '      assignChildColors(c);\n'
        '    }\n'
        '  }\n'
        '}\n'
        '\n'
        'function varyColor(hex, idx, total) {\n'
        '  let r = parseInt(hex.slice(1,3),16);\n'
        '  let g = parseInt(hex.slice(3,5),16);\n'
        '  let b = parseInt(hex.slice(5,7),16);\n'
        '  const factor = 0.7 + 0.6 * (idx / Math.max(total, 1));\n'
        '  r = Math.min(255, Math.round(r * factor));\n'
        '  g = Math.min(255, Math.round(g * factor));\n'
        '  b = Math.min(255, Math.round(b * factor));\n'
        '  const toHex = v => v.toString(16).padStart(2,"0");\n'
        '  return "#" + toHex(r) + toHex(g) + toHex(b);\n'
        '}\n'
        '\n'
        'let mCtx;\n'
        'function measureText(text) {\n'
        '  mCtx.font = FONT;\n'
        '  return mCtx.measureText(text).width;\n'
        '}\n'
        '\n'
        'function layout(root) {\n'
        '  computeWidths(root);\n'
        '  computeSubtreeHeight(root);\n'
        '  positionNode(root, 60, 0);\n'
        '}\n'
        '\n'
        'function computeWidths(n) {\n'
        '  n.w = measureText(n.title) + NODE_PAD_X * 2 + (hasAnyChildren(n) ? 20 : 0);\n'
        '  for (const c of n.children) computeWidths(c);\n'
        '}\n'
        '\n'
        'function computeSubtreeHeight(n) {\n'
        '  if (n.children.length === 0) { n.subtreeH = NODE_H; return NODE_H; }\n'
        '  let total = 0;\n'
        '  for (const c of n.children) { total += computeSubtreeHeight(c); }\n'
        '  total += (n.children.length - 1) * NODE_GAP_Y;\n'
        '  n.subtreeH = Math.max(NODE_H, total);\n'
        '  return n.subtreeH;\n'
        '}\n'
        '\n'
        'function positionNode(n, x, yCenter) {\n'
        '  n.x = x; n.y = yCenter;\n'
        '  if (n.children.length === 0) return;\n'
        '  const childX = x + LEVEL_GAP_X;\n'
        '  let startY = yCenter - n.subtreeH / 2;\n'
        '  for (const c of n.children) {\n'
        '    computeSubtreeHeight(c);\n'
        '    positionNode(c, childX, startY + c.subtreeH / 2);\n'
        '    startY += c.subtreeH + NODE_GAP_Y;\n'
        '  }\n'
        '}\n'
        '\n'
        'function toggleNode(n) {\n'
        '  if (n._children) { n.children = n._children; n._children = null; n.expanded = true; }\n'
        '  else if (n.children.length > 0) { n._children = n.children; n.children = []; n.expanded = false; }\n'
        '  layout(rootNode);\n'
        '  render();\n'
        '}\n'
        '\n'
        'function expandAll(n) {\n'
        '  if (n._children) { n.children = n._children; n._children = null; n.expanded = true; }\n'
        '  for (const c of n.children) expandAll(c);\n'
        '}\n'
        '\n'
        'function collapseToLevel(n, maxLevel) {\n'
        '  const allCh = n._children || n.children;\n'
        '  if (n.depth < maxLevel) {\n'
        '    n.children = allCh; n._children = null; n.expanded = true;\n'
        '    for (const c of n.children) collapseToLevel(c, maxLevel);\n'
        '  } else {\n'
        '    if (allCh.length > 0) {\n'
        '      for (const c of allCh) collapseToLevel(c, maxLevel);\n'
        '      n._children = allCh; n.children = []; n.expanded = false;\n'
        '    }\n'
        '  }\n'
        '}\n'
        '\n'
        'let camX = 0, camY = 0, zoom = 1.0;\n'
        'let cvs, ctx;\n'
        'let W, H;\n'
        '\n'
        'function render() {\n'
        '  const dpr = window.devicePixelRatio || 1;\n'
        '  ctx.setTransform(1, 0, 0, 1, 0, 0);\n'
        '  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);\n'
        '  ctx.clearRect(0, 0, W, H);\n'
        '  ctx.save();\n'
        '  ctx.translate(W/2, H/2);\n'
        '  ctx.scale(zoom, zoom);\n'
        '  ctx.translate(-camX, -camY);\n'
        '  drawLinks(rootNode);\n'
        '  drawNodes(rootNode);\n'
        '  drawSearchHighlights();\n'
        '  ctx.restore();\n'
        '  document.getElementById("zoom-indicator").textContent = Math.round(zoom * 100) + "%";\n'
        '}\n'
        '\n'
        'function drawLinks(n) {\n'
        '  for (const c of n.children) {\n'
        '    const x1 = n.x + n.w, y1 = n.y;\n'
        '    const x2 = c.x, y2 = c.y;\n'
        '    const cpx = (x1 + x2) / 2;\n'
        '    ctx.beginPath();\n'
        '    ctx.moveTo(x1, y1);\n'
        '    ctx.bezierCurveTo(cpx, y1, cpx, y2, x2, y2);\n'
        '    ctx.strokeStyle = c.branchColor || "#555";\n'
        '    ctx.globalAlpha = 0.5;\n'
        '    ctx.lineWidth = Math.max(1, 2.5 - n.depth * 0.3);\n'
        '    ctx.stroke();\n'
        '    ctx.globalAlpha = 1;\n'
        '    drawLinks(c);\n'
        '  }\n'
        '}\n'
        '\n'
        'function drawNodes(n) {\n'
        '  const isLeaf = !hasAnyChildren(n);\n'
        '  const nh = NODE_H, nx = n.x, ny = n.y - nh / 2;\n'
        '  if (!isLeaf) {\n'
        '    ctx.beginPath();\n'
        '    roundRect(ctx, nx, ny, n.w, nh, 6);\n'
        '    ctx.fillStyle = n.branchColor || "#667eea";\n'
        '    ctx.globalAlpha = n.depth === 0 ? 0.3 : 0.15;\n'
        '    ctx.fill();\n'
        '    ctx.globalAlpha = 1;\n'
        '    ctx.strokeStyle = n.branchColor || "#667eea";\n'
        '    ctx.lineWidth = 1;\n'
        '    ctx.globalAlpha = 0.6;\n'
        '    ctx.stroke();\n'
        '    ctx.globalAlpha = 1;\n'
        '  } else {\n'
        '    ctx.beginPath();\n'
        '    ctx.moveTo(nx, n.y + nh/2 - 1);\n'
        '    ctx.lineTo(nx + n.w, n.y + nh/2 - 1);\n'
        '    ctx.strokeStyle = n.branchColor || "#555";\n'
        '    ctx.globalAlpha = 0.25;\n'
        '    ctx.lineWidth = 1;\n'
        '    ctx.stroke();\n'
        '    ctx.globalAlpha = 1;\n'
        '  }\n'
        '  ctx.font = n.depth <= 1 ? FONT_BOLD : FONT;\n'
        '  ctx.fillStyle = n.branchColor || "#e0e0e0";\n'
        '  ctx.globalAlpha = isLeaf ? 0.85 : 1;\n'
        '  ctx.textBaseline = "middle";\n'
        '  ctx.fillText(n.title, nx + NODE_PAD_X, n.y);\n'
        '  ctx.globalAlpha = 1;\n'
        '  if (hasAnyChildren(n)) {\n'
        '    ctx.font = "10px sans-serif";\n'
        '    ctx.fillStyle = n.branchColor || "#888";\n'
        '    ctx.globalAlpha = 0.7;\n'
        '    ctx.fillText(n.expanded ? "\\u25C0" : "\\u25B6", nx + n.w - 16, n.y);\n'
        '    ctx.globalAlpha = 1;\n'
        '  }\n'
        '  for (const c of n.children) drawNodes(c);\n'
        '}\n'
        '\n'
        'function roundRect(ctx, x, y, w, h, r) {\n'
        '  ctx.moveTo(x + r, y);\n'
        '  ctx.arcTo(x + w, y, x + w, y + h, r);\n'
        '  ctx.arcTo(x + w, y + h, x, y + h, r);\n'
        '  ctx.arcTo(x, y + h, x, y, r);\n'
        '  ctx.arcTo(x, y, x + w, y, r);\n'
        '  ctx.closePath();\n'
        '}\n'
        '\n'
        'let searchResults = [];\n'
        'let searchIdx = -1;\n'
        '\n'
        'function doSearch(query) {\n'
        '  searchResults = []; searchIdx = -1;\n'
        '  if (!query) { render(); return; }\n'
        '  const q = query.toLowerCase();\n'
        '  for (const n of nodes) { if (n.title.toLowerCase().includes(q)) searchResults.push(n); }\n'
        '  if (searchResults.length > 0) {\n'
        '    searchIdx = 0;\n'
        '    collapseAllExceptPaths(searchResults);\n'
        '    for (const r of searchResults) { expandPathTo(r); }\n'
        '    layout(rootNode);\n'
        '    focusOnNode(searchResults[0]);\n'
        '  }\n'
        '  render();\n'
        '}\n'
        '\n'
        'function collapseAllExceptPaths(results) {\n'
        '  const pathNodes = new Set();\n'
        '  for (const r of results) {\n'
        '    let cur = r.parent;\n'
        '    while (cur) { pathNodes.add(cur); cur = cur.parent; }\n'
        '    pathNodes.add(r);\n'
        '  }\n'
        '  function walk(n) {\n'
        '    if (!pathNodes.has(n)) {\n'
        '      const allCh = n._children || n.children;\n'
        '      if (allCh.length > 0 && n.children.length > 0) {\n'
        '        n._children = n.children; n.children = []; n.expanded = false;\n'
        '      }\n'
        '    }\n'
        '    const ch = n._children || n.children;\n'
        '    for (const c of ch) walk(c);\n'
        '  }\n'
        '  walk(rootNode);\n'
        '}\n'
        '\n'
        'function expandPathTo(n) {\n'
        '  const path = [];\n'
        '  let cur = n.parent;\n'
        '  while (cur) { path.unshift(cur); cur = cur.parent; }\n'
        '  for (const p of path) { if (p._children) { p.children = p._children; p._children = null; p.expanded = true; } }\n'
        '}\n'
        '\n'
        'function drawSearchHighlights() {\n'
        '  for (let i = 0; i < searchResults.length; i++) {\n'
        '    const n = searchResults[i];\n'
        '    ctx.beginPath();\n'
        '    roundRect(ctx, n.x - 2, n.y - NODE_H/2 - 2, n.w + 4, NODE_H + 4, 8);\n'
        '    ctx.strokeStyle = i === searchIdx ? "#ffd700" : "#ffa500";\n'
        '    ctx.lineWidth = i === searchIdx ? 3 : 1.5;\n'
        '    ctx.globalAlpha = i === searchIdx ? 1 : 0.6;\n'
        '    ctx.stroke();\n'
        '    ctx.globalAlpha = 1;\n'
        '  }\n'
        '}\n'
        '\n'
        'function nextSearchResult() {\n'
        '  if (searchResults.length === 0) return;\n'
        '  searchIdx = (searchIdx + 1) % searchResults.length;\n'
        '  collapseAllExceptPaths(searchResults);\n'
        '  for (const r of searchResults) { expandPathTo(r); }\n'
        '  layout(rootNode);\n'
        '  focusOnNode(searchResults[searchIdx]);\n'
        '  render();\n'
        '}\n'
        '\n'
        'let dragging = false;\n'
        'let dragStartX, dragStartY, camStartX, camStartY;\n'
        'let hoveredNode = null;\n'
        'let ctxTarget = null;\n'
        '\n'
        'function hitTest(sx, sy) {\n'
        '  const wx = (sx - W/2) / zoom + camX;\n'
        '  const wy = (sy - H/2) / zoom + camY;\n'
        '  return hitTestNode(rootNode, wx, wy);\n'
        '}\n'
        '\n'
        'function hitTestNode(n, wx, wy) {\n'
        '  const nh = NODE_H;\n'
        '  if (wx >= n.x && wx <= n.x + n.w && wy >= n.y - nh/2 && wy <= n.y + nh/2) return n;\n'
        '  for (const c of n.children) { const r = hitTestNode(c, wx, wy); if (r) return r; }\n'
        '  return null;\n'
        '}\n'
        '\n'
        'function focusOnNode(n) {\n'
        '  camX = n.x + n.w / 2;\n'
        '  camY = n.y;\n'
        '  zoom = 1.0;\n'
        '  render();\n'
        '}\n'
        '\n'
        'function fitScreen() {\n'
        '  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;\n'
        '  function walk(n) {\n'
        '    minX = Math.min(minX, n.x); maxX = Math.max(maxX, n.x + n.w);\n'
        '    minY = Math.min(minY, n.y - NODE_H/2); maxY = Math.max(maxY, n.y + NODE_H/2);\n'
        '    for (const c of n.children) walk(c);\n'
        '  }\n'
        '  walk(rootNode);\n'
        '  const tw = maxX - minX, th = maxY - minY;\n'
        '  if (tw <= 0 || th <= 0) return;\n'
        '  zoom = Math.min((W - 80) / tw, (H - 80) / th, 2);\n'
        '  camX = minX + tw / 2;\n'
        '  camY = minY + th / 2;\n'
        '  render();\n'
        '}\n'
        '\n'
        'const tooltip = document.getElementById("tooltip");\n'
        'function showTooltip(n, sx, sy) {\n'
        '  if (!hasAnyChildren(n)) { tooltip.style.display = "none"; return; }\n'
        '  const allCh = n._children || n.children;\n'
        '  tooltip.textContent = n.depth === 0 ? allCh.length + " 个一级页面" : countDesc(n) + " 个子页面";\n'
        '  tooltip.style.display = "block";\n'
        '  tooltip.style.left = (sx + 12) + "px";\n'
        '  tooltip.style.top = (sy - 28) + "px";\n'
        '}\n'
        '\n'
        'function init() {\n'
        '  cvs = document.getElementById("cv");\n'
        '  ctx = cvs.getContext("2d");\n'
        '  mCtx = document.createElement("canvas").getContext("2d");\n'
        '  resize();\n'
        '  window.addEventListener("resize", () => { resize(); layout(rootNode); render(); });\n'
        '  rootNode = buildTree(RAW, null, 0);\n'
        '  assignColors(rootNode);\n'
        '  layout(rootNode);\n'
        '  updateStats();\n'
        '  camX = rootNode.x + rootNode.w / 2 + 200;\n'
        '  camY = rootNode.y;\n'
        '  zoom = 1.0;\n'
        '  render();\n'
        '\n'
        '  const wrap = document.getElementById("canvas-wrap");\n'
        '  wrap.addEventListener("mousedown", (e) => {\n'
        '    if (e.button === 0) {\n'
        '      dragging = true;\n'
        '      dragStartX = e.clientX; dragStartY = e.clientY;\n'
        '      camStartX = camX; camStartY = camY;\n'
        '      wrap.classList.add("grabbing");\n'
        '    }\n'
        '  });\n'
        '  window.addEventListener("mousemove", (e) => {\n'
        '    if (dragging) {\n'
        '      camX = camStartX - (e.clientX - dragStartX) / zoom;\n'
        '      camY = camStartY - (e.clientY - dragStartY) / zoom;\n'
        '      render();\n'
        '    } else {\n'
        '      const rect = cvs.getBoundingClientRect();\n'
        '      const sx = e.clientX - rect.left, sy = e.clientY - rect.top;\n'
        '      const n = hitTest(sx, sy);\n'
        '      if (n !== hoveredNode) {\n'
        '        hoveredNode = n;\n'
        '        cvs.style.cursor = n ? "pointer" : "";\n'
        '        if (n) showTooltip(n, e.clientX, e.clientY);\n'
        '        else tooltip.style.display = "none";\n'
        '        render();\n'
        '      } else if (n) {\n'
        '        tooltip.style.left = (e.clientX + 12) + "px";\n'
        '        tooltip.style.top = (e.clientY - 28) + "px";\n'
        '      }\n'
        '    }\n'
        '  });\n'
        '  window.addEventListener("mouseup", (e) => {\n'
        '    if (!dragging) return;\n'
        '    dragging = false;\n'
        '    wrap.classList.remove("grabbing");\n'
        '    const moved = Math.abs(e.clientX - dragStartX) + Math.abs(e.clientY - dragStartY);\n'
        '    if (moved < 4 && e.button === 0) {\n'
        '      const rect = cvs.getBoundingClientRect();\n'
        '      const n = hitTest(e.clientX - rect.left, e.clientY - rect.top);\n'
        '      if (n) {\n'
        '        if (e.ctrlKey || e.metaKey) { if (n.link) window.open(n.link, "_blank"); }\n'
        '        else { const ox = n.x, oy = n.y; toggleNode(n); camX += n.x - ox; camY += n.y - oy; render(); }\n'
        '      }\n'
        '    }\n'
        '  });\n'
        '  wrap.addEventListener("wheel", (e) => {\n'
        '    e.preventDefault();\n'
        '    const rect = cvs.getBoundingClientRect();\n'
        '    const mx = e.clientX - rect.left, my = e.clientY - rect.top;\n'
        '    const wx = (mx - W/2) / zoom + camX, wy = (my - H/2) / zoom + camY;\n'
        '    const newZoom = Math.max(0.05, Math.min(4, zoom + (e.deltaY > 0 ? -0.05 : 0.05)));\n'
        '    camX = wx - (mx - W/2) / newZoom;\n'
        '    camY = wy - (my - H/2) / newZoom;\n'
        '    zoom = newZoom;\n'
        '    render();\n'
        '  }, { passive: false });\n'
        '  wrap.addEventListener("contextmenu", (e) => {\n'
        '    e.preventDefault();\n'
        '    const rect = cvs.getBoundingClientRect();\n'
        '    const n = hitTest(e.clientX - rect.left, e.clientY - rect.top);\n'
        '    if (n) {\n'
        '      ctxTarget = n;\n'
        '      const menu = document.getElementById("ctx-menu");\n'
        '      document.getElementById("ctx-copy").style.display = n.link ? "" : "none";\n'
        '      menu.style.display = "block";\n'
        '      menu.style.left = e.clientX + "px";\n'
        '      menu.style.top = e.clientY + "px";\n'
        '      const mr = menu.getBoundingClientRect();\n'
        '      if (mr.right > window.innerWidth) menu.style.left = (e.clientX - mr.width) + "px";\n'
        '      if (mr.bottom > window.innerHeight) menu.style.top = (e.clientY - mr.height) + "px";\n'
        '    }\n'
        '  });\n'
        '  document.addEventListener("click", () => { document.getElementById("ctx-menu").style.display = "none"; });\n'
        '  document.getElementById("ctx-copy").addEventListener("click", () => {\n'
        '    if (ctxTarget && ctxTarget.link) navigator.clipboard.writeText(ctxTarget.link).catch(() => prompt("Copy:", ctxTarget.link));\n'
        '  });\n'
        '  document.getElementById("ctx-focus").addEventListener("click", () => { if (ctxTarget) focusOnNode(ctxTarget); });\n'
        '  document.getElementById("btn-reset").addEventListener("click", () => {\n'
        '    collapseToLevel(rootNode, 2);\n'
        '    layout(rootNode);\n'
        '    camX = rootNode.x + rootNode.w / 2 + 200;\n'
        '    camY = rootNode.y;\n'
        '    zoom = 1.0;\n'
        '    render();\n'
        '  });\n'
        '  document.getElementById("btn-fit").addEventListener("click", fitScreen);\n'
        '  document.getElementById("btn-expand").addEventListener("click", () => { expandAll(rootNode); layout(rootNode); fitScreen(); });\n'
        '  document.getElementById("btn-collapse").addEventListener("click", () => { collapseToLevel(rootNode, 1); layout(rootNode); fitScreen(); });\n'
        '  const searchBox = document.getElementById("search-box");\n'
        '  searchBox.addEventListener("input", () => doSearch(searchBox.value));\n'
        '  searchBox.addEventListener("keydown", (e) => {\n'
        '    if (e.key === "Enter") nextSearchResult();\n'
        '    if (e.key === "Escape") { searchBox.value = ""; searchResults = []; searchIdx = -1; searchBox.blur(); render(); }\n'
        '  });\n'
        '  document.addEventListener("keydown", (e) => {\n'
        '    if ((e.ctrlKey || e.metaKey) && e.key === "f") { e.preventDefault(); searchBox.focus(); searchBox.select(); }\n'
        '  });\n'
        '}\n'
        '\n'
        'function resize() {\n'
        '  const dpr = window.devicePixelRatio || 1;\n'
        '  W = window.innerWidth;\n'
        '  H = window.innerHeight - 48;\n'
        '  cvs.width = W * dpr;\n'
        '  cvs.height = H * dpr;\n'
        '  cvs.style.width = W + "px";\n'
        '  cvs.style.height = H + "px";\n'
        '  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);\n'
        '}\n'
        '\n'
        'function updateStats() {\n'
        '  let maxD = 0;\n'
        '  for (const n of nodes) if (n.depth > maxD) maxD = n.depth;\n'
        '  document.getElementById("stats").textContent = nodes.length + " 个页面 | 最大 " + maxD + " 层";\n'
        '}\n'
        '\n'
        'window.addEventListener("DOMContentLoaded", init);\n'
        '</script>\n'
        '<div id="footer"><a href="https://github.com/infniu/notion-to-mindmap" target="_blank">Powered by infniu with Ai</a></div>\n'
        '</body>\n'
        '</html>'
    )

    with open("mindmap.html", 'w', encoding='utf-8') as f:
        f.write(html)
    print("Generated: mindmap.html", flush=True)

if __name__ == "__main__":
    main()
