#!/usr/bin/env bash
set -euo pipefail

CMD="${1:-help}"
shift 2>/dev/null || true

case "$CMD" in

standard)
  NAME="${1:-myproject}"
  python3 << 'PYEOF'
import sys
name = sys.argv[1] if len(sys.argv) > 1 else "myproject"

print("# {}".format(name))
print("")
print("> Short description of what {} does and why it exists.".format(name))
print("")
print("## Features")
print("")
print("- Feature one")
print("- Feature two")
print("- Feature three")
print("")
print("## Installation")
print("")
print("```bash")
print("npm install {}".format(name))
print("# or")
print("pip install {}".format(name))
print("```")
print("")
print("## Quick Start")
print("")
print("```bash")
print("{} --help".format(name))
print("```")
print("")
print("## Usage")
print("")
print("```python")
print("from {} import main".format(name.replace("-", "_")))
print("main()")
print("```")
print("")
print("## Configuration")
print("")
print("| Option | Default | Description |")
print("|--------|---------|-------------|")
print("| `--verbose` | `false` | Enable verbose output |")
print("| `--config` | `~/.{}.yml` | Config file path |".format(name))
print("")
print("## Contributing")
print("")
print("Pull requests are welcome. See [CONTRIBUTING.md](CONTRIBUTING.md) for guidelines.")
print("")
print("## License")
print("")
print("MIT - see [LICENSE](LICENSE)")
print("")
print("Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
  ;;

awesome)
  TOPIC="${1:-Resources}"
  python3 << 'PYEOF'
import sys
topic = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Resources"

print("# Awesome {}".format(topic))
print("")
print("[![Awesome](https://awesome.re/badge.svg)](https://awesome.re)")
print("")
print("> A curated list of awesome {} resources, tools, and libraries.".format(topic.lower()))
print("")
print("## Contents")
print("")
print("- [Libraries](#libraries)")
print("- [Tools](#tools)")
print("- [Articles](#articles)")
print("- [Videos](#videos)")
print("- [Community](#community)")
print("")
print("## Libraries")
print("")
print("- [Library Name](https://example.com) - Short description of what it does.")
print("- [Another Library](https://example.com) - Another description.")
print("")
print("## Tools")
print("")
print("- [Tool Name](https://example.com) - What this tool does.")
print("- [Another Tool](https://example.com) - Another tool description.")
print("")
print("## Articles")
print("")
print("- [Article Title](https://example.com) - Brief summary.")
print("")
print("## Videos")
print("")
print("- [Video Title](https://youtube.com) - Brief summary.")
print("")
print("## Community")
print("")
print("- [Discord](https://discord.gg/example)")
print("- [Subreddit](https://reddit.com/r/example)")
print("")
print("## Contributing")
print("")
print("Contributions welcome! Read the [contribution guidelines](CONTRIBUTING.md) first.")
print("")
print("## License")
print("")
print("CC0 1.0 Universal")
print("")
print("Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
  ;;

minimal)
  NAME="${1:-mytool}"
  python3 << 'PYEOF'
import sys
name = sys.argv[1] if len(sys.argv) > 1 else "mytool"

print("# {}".format(name))
print("")
print("One-line description of {}.".format(name))
print("")
print("## Install")
print("")
print("```bash")
print("npm install -g {}".format(name))
print("```")
print("")
print("## Usage")
print("")
print("```bash")
print("{} <input> [options]".format(name))
print("```")
print("")
print("## License")
print("")
print("MIT")
print("")
print("Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
  ;;

detailed)
  NAME="${1:-myproject}"
  python3 << 'PYEOF'
import sys
name = sys.argv[1] if len(sys.argv) > 1 else "myproject"

print("# {}".format(name))
print("")
print("[![Build Status](https://img.shields.io/github/actions/workflow/status/user/{}/ci.yml)](https://github.com/user/{}/actions)".format(name, name))
print("[![Version](https://img.shields.io/npm/v/{})](https://npmjs.com/package/{})".format(name, name))
print("[![License](https://img.shields.io/github/license/user/{})](LICENSE)".format(name))
print("")
print("> Detailed description of {} — what problem it solves and for whom.".format(name))
print("")
print("## Table of Contents")
print("")
print("- [Features](#features)")
print("- [Prerequisites](#prerequisites)")
print("- [Installation](#installation)")
print("- [Quick Start](#quick-start)")
print("- [Configuration](#configuration)")
print("- [API Reference](#api-reference)")
print("- [Architecture](#architecture)")
print("- [Testing](#testing)")
print("- [Deployment](#deployment)")
print("- [Roadmap](#roadmap)")
print("- [Contributing](#contributing)")
print("- [License](#license)")
print("")
print("## Features")
print("")
print("- **Feature 1** — Description of the first key feature")
print("- **Feature 2** — Description of the second key feature")
print("- **Feature 3** — Description of the third key feature")
print("")
print("## Prerequisites")
print("")
print("- Node.js >= 18 (or Python >= 3.8)")
print("- npm >= 9 (or pip)")
print("- Docker (optional)")
print("")
print("## Installation")
print("")
print("```bash")
print("git clone https://github.com/user/{}.git".format(name))
print("cd {}".format(name))
print("npm install")
print("```")
print("")
print("## Quick Start")
print("")
print("```bash")
print("cp .env.example .env")
print("npm run dev")
print("```")
print("")
print("## Configuration")
print("")
print("| Variable | Default | Description |")
print("|----------|---------|-------------|")
print("| `PORT` | `3000` | Server port |")
print("| `LOG_LEVEL` | `info` | Logging level |")
print("| `DB_URL` | - | Database connection string |")
print("")
print("## API Reference")
print("")
print("See [docs/API.md](docs/API.md) for complete API documentation.")
print("")
print("## Architecture")
print("")
print("```")
print("src/")
print("  controllers/   # Request handlers")
print("  services/      # Business logic")
print("  models/        # Data models")
print("  middleware/    # Middleware")
print("  utils/         # Utilities")
print("```")
print("")
print("## Testing")
print("")
print("```bash")
print("npm test              # Run all tests")
print("npm run test:coverage # With coverage report")
print("```")
print("")
print("## Deployment")
print("")
print("```bash")
print("docker build -t {} .".format(name))
print("docker run -p 3000:3000 {}".format(name))
print("```")
print("")
print("## Roadmap")
print("")
print("- [ ] Feature A")
print("- [ ] Feature B")
print("- [ ] Performance improvements")
print("")
print("## Contributing")
print("")
print("See [CONTRIBUTING.md](CONTRIBUTING.md)")
print("")
print("## License")
print("")
print("MIT - see [LICENSE](LICENSE)")
print("")
print("Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
  ;;

library)
  NAME="${1:-mylib}"
  python3 << 'PYEOF'
import sys
name = sys.argv[1] if len(sys.argv) > 1 else "mylib"

print("# {}".format(name))
print("")
print("[![npm](https://img.shields.io/npm/v/{})](https://npmjs.com/package/{})".format(name, name))
print("[![Downloads](https://img.shields.io/npm/dm/{})](https://npmjs.com/package/{})".format(name, name))
print("[![Bundle Size](https://img.shields.io/bundlephobia/minzip/{})](https://bundlephobia.com/package/{})".format(name, name))
print("")
print("> A lightweight library for [purpose].")
print("")
print("## Install")
print("")
print("```bash")
print("npm install {}".format(name))
print("# or")
print("yarn add {}".format(name))
print("```")
print("")
print("## API")
print("")
print("### `functionName(param1, param2)`")
print("")
print("Description of the function.")
print("")
print("**Parameters:**")
print("")
print("| Name | Type | Default | Description |")
print("|------|------|---------|-------------|")
print("| `param1` | `string` | Required | Description |")
print("| `param2` | `object` | `{}` | Options |")
print("")
print("**Returns:** `Promise<Result>`")
print("")
print("**Example:**")
print("")
print("```javascript")
print("import {{ functionName }} from '{}';".format(name))
print("")
print("const result = await functionName('hello', { option: true });")
print("console.log(result);")
print("```")
print("")
print("## Browser Support")
print("")
print("| Chrome | Firefox | Safari | Edge |")
print("|--------|---------|--------|------|")
print("| 90+ | 88+ | 14+ | 90+ |")
print("")
print("## License")
print("")
print("MIT")
print("")
print("Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
  ;;

app)
  NAME="${1:-myapp}"
  python3 << 'PYEOF'
import sys
name = sys.argv[1] if len(sys.argv) > 1 else "myapp"

print("# {}".format(name))
print("")
print("![Screenshot](docs/screenshot.png)")
print("")
print("> A brief tagline for {}.".format(name))
print("")
print("## Download")
print("")
print("| Platform | Link |")
print("|----------|------|")
print("| macOS | [Download](releases) |")
print("| Windows | [Download](releases) |")
print("| Linux | [Download](releases) |")
print("")
print("## Features")
print("")
print("- **Feature 1** — What it does for the user")
print("- **Feature 2** — What it does for the user")
print("- **Feature 3** — What it does for the user")
print("")
print("## Getting Started")
print("")
print("1. Download the latest release")
print("2. Install and open the application")
print("3. Follow the onboarding wizard")
print("")
print("## Development Setup")
print("")
print("```bash")
print("git clone https://github.com/user/{}.git".format(name))
print("cd {}".format(name))
print("npm install")
print("npm run dev")
print("```")
print("")
print("## Tech Stack")
print("")
print("- Frontend: React / Vue / Electron")
print("- Backend: Node.js / Python")
print("- Database: PostgreSQL / SQLite")
print("")
print("## Feedback & Support")
print("")
print("- Bug reports: [GitHub Issues](issues)")
print("- Feature requests: [Discussions](discussions)")
print("- Email: support@example.com")
print("")
print("## License")
print("")
print("MIT")
print("")
print("Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
  ;;

api)
  NAME="${1:-myapi}"
  python3 << 'PYEOF'
import sys
name = sys.argv[1] if len(sys.argv) > 1 else "myapi"

print("# {} API".format(name))
print("")
print("> RESTful API for [purpose].")
print("")
print("**Base URL:** `https://api.example.com/v1`")
print("")
print("## Authentication")
print("")
print("```")
print("Authorization: Bearer <your-api-key>")
print("```")
print("")
print("Get your API key at [dashboard.example.com](https://dashboard.example.com)")
print("")
print("## Endpoints")
print("")
print("### Resources")
print("")
print("| Method | Endpoint | Description |")
print("|--------|----------|-------------|")
print("| GET | `/resources` | List all resources |")
print("| GET | `/resources/:id` | Get a resource |")
print("| POST | `/resources` | Create a resource |")
print("| PUT | `/resources/:id` | Update a resource |")
print("| DELETE | `/resources/:id` | Delete a resource |")
print("")
print("### Example Request")
print("")
print("```bash")
print('curl -X GET "https://api.example.com/v1/resources" \\')
print('  -H "Authorization: Bearer YOUR_KEY" \\')
print('  -H "Content-Type: application/json"')
print("```")
print("")
print("### Example Response")
print("")
print("```json")
print("{")
print('  "data": [')
print('    { "id": 1, "name": "example" }')
print("  ],")
print('  "meta": { "total": 1, "page": 1 }')
print("}")
print("```")
print("")
print("## Error Codes")
print("")
print("| Code | Meaning |")
print("|------|---------|")
print("| 400 | Bad Request |")
print("| 401 | Unauthorized |")
print("| 404 | Not Found |")
print("| 429 | Rate Limited |")
print("| 500 | Server Error |")
print("")
print("## Rate Limits")
print("")
print("- 100 requests/minute per API key")
print("- Check `X-RateLimit-Remaining` header")
print("")
print("## SDKs")
print("")
print("- Python: `pip install {}-sdk`".format(name))
print("- Node.js: `npm install {}-sdk`".format(name))
print("")
print("## License")
print("")
print("MIT")
print("")
print("Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
  ;;

badges)
  NAME="${1:-myproject}"
  PLATFORM="${2:-npm}"
  python3 << 'PYEOF'
import sys
name = sys.argv[1] if len(sys.argv) > 1 else "myproject"
platform = sys.argv[2] if len(sys.argv) > 2 else "npm"

print("=" * 60)
print("  Badge Generator: {} ({})".format(name, platform))
print("=" * 60)
print("")
print("Copy-paste these badges into your README:")
print("")

if platform == "npm":
    print("[![npm version](https://img.shields.io/npm/v/{}.svg)](https://npmjs.com/package/{})".format(name, name))
    print("[![downloads](https://img.shields.io/npm/dm/{}.svg)](https://npmjs.com/package/{})".format(name, name))
    print("[![bundle size](https://img.shields.io/bundlephobia/minzip/{})](https://bundlephobia.com/package/{})".format(name, name))
elif platform == "pip":
    print("[![PyPI](https://img.shields.io/pypi/v/{})](https://pypi.org/project/{})".format(name, name))
    print("[![Downloads](https://img.shields.io/pypi/dm/{})](https://pypi.org/project/{})".format(name, name))
    print("[![Python](https://img.shields.io/pypi/pyversions/{})](https://pypi.org/project/{})".format(name, name))

print("[![license](https://img.shields.io/github/license/user/{})](LICENSE)".format(name))
print("[![build](https://img.shields.io/github/actions/workflow/status/user/{}/ci.yml)](https://github.com/user/{}/actions)".format(name, name))
print("[![stars](https://img.shields.io/github/stars/user/{})](https://github.com/user/{})".format(name, name))
print("[![issues](https://img.shields.io/github/issues/user/{})](https://github.com/user/{}/issues)".format(name, name))
print("[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](CONTRIBUTING.md)")
print("")
print("Custom badges (shields.io):")
print("[![custom](https://img.shields.io/badge/label-message-color)]")
print("")
print("Color options: brightgreen, green, yellow, orange, red, blue,")
print("  lightgrey, blueviolet, ff69b4, success, important, critical")
print("")
print("Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
  ;;

*)
  echo "README Template - Professional README Generator"
  echo ""
  echo "Usage: bash readme-template.sh <command> [args]"
  echo ""
  echo "Commands:"
  echo "  standard <name>          Standard README template"
  echo "  awesome <topic>          Awesome-list format"
  echo "  minimal <name>           Minimal README"
  echo "  detailed <name>          Detailed/comprehensive README"
  echo "  library <name>           Open-source library README"
  echo "  app <name>               Application README"
  echo "  api <name>               API project README"
  echo "  badges <name> <platform> Badge generator (npm/pip)"
  echo ""
  echo "Powered by BytesAgain | bytesagain.com | hello@bytesagain.com"
  ;;

esac
