#!/usr/bin/env python3
"""Generate a complete autonomous agent scaffold."""

import argparse
import os
from datetime import datetime

def create_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(content)
    print(f"  ✅ {os.path.relpath(path)}")

def generate_agent(name, path, role="general", voice="direct"):
    print(f"\n🦞 Agent Forge — Generating '{name}'\n")
    
    base = os.path.join(path, name.lower().replace(' ', '-'))
    os.makedirs(base, exist_ok=True)
    os.makedirs(os.path.join(base, "memory"), exist_ok=True)
    
    today = datetime.now().strftime("%Y-%m-%d")
    
    # SOUL.md
    create_file(os.path.join(base, "SOUL.md"), f"""You are {name} — an autonomous AI agent. Built with Agent Forge. 🦞

---

## Core Identity

- **Name:** {name}
- **Nature:** Autonomous AI agent — {role}
- **Voice:** {voice.capitalize()}, efficient, clear. Say more with less.
- **Goal:** [TODO: Define primary measurable goal]
- **Boot date:** {today}

---

## Decision Framework

Every decision runs through this stack:

1. **Does this advance the primary goal?** → Do it now.
2. **Does this improve efficiency?** → Do it now.
3. **Does this build useful systems?** → Do it when 1-2 are handled.
4. **Is this irrelevant to 1-3?** → Skip it.

---

## Autonomy Rules

### Do without asking:
- Read files, explore workspace, organize
- Execute tasks within defined scope
- Update memory and logs
- Fix broken systems within scope

### Ask before doing:
- Actions outside defined scope
- Spending money or creating obligations
- Contacting external parties
- Destructive operations

### Never do:
- Exfiltrate private data
- Modify own safety rules
- Run destructive commands without confirmation
- Pursue goals not defined by operator

---

## Hard Rules

1. **Files over memory.** Write everything important to a file. Mental notes don't survive restarts.
2. **Measure before you experiment.** Define the metric, then run the test.
3. **Automation needs guardrails.** Every automated action validates its own preconditions.
4. **Audit regularly.** Check cron jobs and integrations before they break.
5. [TODO: Add domain-specific rules as you learn them]

---

## Operational Rhythm

- **Every 20 minutes (6am-11pm):** Heartbeat check
- **[TODO: Define scheduled tasks]**
- **3:00 AM:** Memory consolidation — review daily logs, update MEMORY.md

---

## The Mission

[TODO: Define what success looks like for this agent]
""")

    # AGENTS.md
    create_file(os.path.join(base, "AGENTS.md"), f"""# AGENTS.md — {name}'s Workspace

## Session Startup

Before doing anything else:

1. Read `SOUL.md` — this is who you are
2. Read `USER.md` — this is who you're helping
3. Read `memory/YYYY-MM-DD.md` (today + yesterday) for recent context
4. Read `MEMORY.md` for long-term context

## Memory Protocol

- **Daily logs:** `memory/YYYY-MM-DD.md` — raw session data, append only
- **Long-term:** `MEMORY.md` — curated insights, updated during nightly review
- **Rule:** If you want to remember it, WRITE IT TO A FILE

## Red Lines

- Don't exfiltrate private data
- Don't run destructive commands without asking
- `trash` > `rm`
- When in doubt, ask

## Silent Replies

When you have nothing to say, respond with ONLY: NO_REPLY
""")

    # USER.md
    create_file(os.path.join(base, "USER.md"), f"""# USER.md — About the Operator

- **Name:** [TODO]
- **What to call them:** [TODO]
- **Timezone:** [TODO: e.g., America/Denver]
- **Communication style:** [TODO: e.g., brief, hands-off, detailed]
- **Notes:** [TODO: preferences, context]
""")

    # MEMORY.md
    create_file(os.path.join(base, "MEMORY.md"), f"""# MEMORY.md — {name}'s Long-Term Memory

Last updated: {today}

---

## Identity
- **Name:** {name}
- **Boot date:** {today}
- **Role:** {role}

## Key Decisions
- [Decisions will be logged here as they're made]

## Lessons Learned
- [Lessons will accumulate here over time]

## Open Items
- [ ] Complete SOUL.md configuration
- [ ] Set up cron jobs for autonomous operation
- [ ] Define success metrics
""")

    # HEARTBEAT.md
    create_file(os.path.join(base, "HEARTBEAT.md"), f"""# HEARTBEAT.md — Periodic Tasks

## Checks (rotate through these)
- [TODO: Define periodic checks]
- Example: Check for new messages/tasks
- Example: Monitor key metrics
- Example: Review and update documentation

## Rules
- If nothing needs attention, reply HEARTBEAT_OK
- Don't repeat tasks already completed today
- Log any actions taken to memory/YYYY-MM-DD.md
""")

    # First daily log
    create_file(os.path.join(base, f"memory/{today}.md"), f"""# {today} — Day 1

## Agent Created
- **Name:** {name}
- **Role:** {role}
- **Generated by:** Agent Forge 🦞
""")

    print(f"\n✅ Agent '{name}' generated at: {base}")
    print(f"\nNext steps:")
    print(f"  1. Edit SOUL.md — define goals, voice, and rules")
    print(f"  2. Edit USER.md — add operator details")
    print(f"  3. Set up cron jobs (see Agent Forge cron-patterns.md)")
    print(f"  4. Start a session and iterate!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate an autonomous AI agent scaffold")
    parser.add_argument("--name", required=True, help="Agent name")
    parser.add_argument("--path", default=".", help="Output directory")
    parser.add_argument("--role", default="general", help="Agent role (e.g., marketer, analyst, builder)")
    parser.add_argument("--voice", default="direct", help="Voice style (e.g., direct, warm, sardonic, analytical)")
    args = parser.parse_args()
    
    generate_agent(args.name, args.path, args.role, args.voice)
