#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup-nginx.sh — Install and configure nginx as reverse proxy
#
# nginx listens on port 18789 and routes:
#   /lark/*     → lark-openclaw-bridge (localhost:18787)
#   /arouter/*  → arouter              (localhost:18785)
#
# Usage:  bash setup-nginx.sh
# Re-run: idempotent — overwrites nginx config and reloads
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${BLUE}[INFO]${RESET} $*"; }
success() { echo -e "${GREEN}[ OK ]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET} $*"; }
error()   { echo -e "${RED}[ERR ]${RESET} $*" >&2; }
die()     { error "$*"; exit 1; }

# ── Must be root ──────────────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
  die "This script must be run as root (or via sudo)"
fi

# ── Detect package manager ────────────────────────────────────────────────────
if command -v apt-get &>/dev/null; then
  PKG_MGR="apt"
elif command -v yum &>/dev/null; then
  PKG_MGR="yum"
elif command -v dnf &>/dev/null; then
  PKG_MGR="dnf"
else
  die "No supported package manager found (apt/yum/dnf)"
fi
info "Package manager: $PKG_MGR"

# ── Install nginx ─────────────────────────────────────────────────────────────
if command -v nginx &>/dev/null; then
  success "nginx already installed: $(nginx -v 2>&1 | awk -F/ '{print $2}')"
else
  info "Installing nginx..."
  case "$PKG_MGR" in
    apt) apt-get update -qq && apt-get install -y -qq nginx ;;
    yum) yum install -y -q epel-release && yum install -y -q nginx ;;
    dnf) dnf install -y -q nginx ;;
  esac
  success "nginx installed"
fi

# ── Write nginx config ───────────────────────────────────────────────────────
NGINX_CONF="/etc/nginx/conf.d/oc-atomecorp.conf"

info "Writing nginx config to $NGINX_CONF"

cat > "$NGINX_CONF" << 'NGINX_EOF'
# oc.atomecorp.net reverse proxy
# Generated by setup-nginx.sh — safe to re-run

# WebSocket upgrade map
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream lark_bridge {
    server 127.0.0.1:18787;
    keepalive 16;
}

upstream arouter {
    server 127.0.0.1:18785;
    keepalive 16;
}

server {
    listen 18789;
    server_name oc.atomecorp.net;

    # --- Logging ---
    access_log /var/log/nginx/oc-atomecorp-access.log;
    error_log  /var/log/nginx/oc-atomecorp-error.log;

    # --- Shared proxy settings ---
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # --- /lark/ → lark-openclaw-bridge (strip prefix) ---
    #
    # /lark/deploy_key      → static file (deploy key for install.sh fallback)
    # /lark/webhook/:appId  → bridge /webhook/:appId
    # /lark/bridge          → bridge /bridge (WebSocket)
    # /lark/health          → bridge /health
    # /lark/logs            → bridge /logs (SSE)
    # /lark/status          → bridge /status
    # /lark/install.sh      → bridge /install.sh
    # /lark/openclaw-config → bridge /openclaw-config

    location = /lark/deploy_key {
        alias /var/www/lark-static/deploy_key;
        default_type application/octet-stream;
    }

    location /lark/ {
        proxy_pass http://lark_bridge/;

        # WebSocket support (for /lark/bridge)
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        # SSE support (for /lark/logs)
        proxy_buffering off;
        proxy_cache off;

        # Long-lived connections (WebSocket + SSE)
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # --- /arouter/ → arouter (strip prefix) ---
    #
    # /arouter/v1/*         → arouter /v1/*
    # /arouter/admin/*      → arouter /admin/*
    # /arouter/metrics      → arouter /metrics

    location /arouter/ {
        proxy_pass http://arouter/;

        # Streaming support for SSE chat completions
        proxy_buffering off;
        proxy_cache off;

        # LLM requests can be slow
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;

        # Allow large request bodies (for long prompts)
        client_max_body_size 10m;
    }

    # --- Root: return 404 for unmatched paths ---
    location / {
        return 404 '{"error":"not found","hint":"use /lark/ or /arouter/ prefix"}';
        add_header Content-Type application/json;
    }
}
NGINX_EOF

success "nginx config written"

# ── Remove default site if it conflicts ───────────────────────────────────────
if [ -f /etc/nginx/sites-enabled/default ]; then
  info "Removing default nginx site to avoid port conflicts"
  rm -f /etc/nginx/sites-enabled/default
fi

# ── Test nginx config ─────────────────────────────────────────────────────────
info "Testing nginx config..."
if ! nginx -t 2>&1; then
  die "nginx config test failed — please check $NGINX_CONF"
fi
success "nginx config test passed"

# ── Enable and start/reload nginx ─────────────────────────────────────────────
if systemctl is-active --quiet nginx; then
  info "Reloading nginx..."
  systemctl reload nginx
  success "nginx reloaded"
else
  info "Starting nginx..."
  systemctl enable nginx
  systemctl start nginx
  success "nginx started and enabled"
fi

# ── Verify ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}nginx is now running on port 18789${RESET}"
echo ""
echo "  Routing:"
echo "    /lark/*     → 127.0.0.1:18787  (lark-openclaw-bridge)"
echo "    /arouter/*  → 127.0.0.1:18785  (arouter)"
echo ""
echo "  Config:  $NGINX_CONF"
echo "  Logs:    /var/log/nginx/oc-atomecorp-{access,error}.log"
echo ""
echo -e "${YELLOW}Make sure the backend services are running:${RESET}"
echo "  - lark-openclaw-bridge on port 18787"
echo "  - arouter on port 18785"
echo ""
